### ISSUE TITLE
Crosshair leaves pixels behind if drawn over wide Status Bar

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1025]
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/4836654377)._

See for yourself, towards the bottom right corner:
![woof0001](https://user-images.githubusercontent.com/73968015/235288679-f3fc8b25-128e-4aa9-8555-c714e06c5551.png)

Seems like fixing it is just a matter of redrawing those extra parts, whether they're rock background or a proper wide Status Bar graphic.

**Comment by fabiangreffrath** [comment]
I think we should take the crosshair patch height and width into consideration before applying the new screen coordinates here:

https://github.com/fabiangreffrath/woof/blob/ab708171f3e25b030bd260f28a49927dc71a35a3/src/hu_stuff.c#L1307-L1311
