### ISSUE TITLE
[Requests] Allow user defined translation tables / option for dumping auto-generated tables

### ISSUE THREAD

**Issue by ManxLoaghtan** [fabiangreffrath/woof#1033]
Hello, 
The last release (11.0.0) added the feature of auto-generating the boom color translation tables, but this creates a problem where they override PWAD provided translation tables (Like those in AAliens or DOTB) and consequently make the menu/HUD text look slightly different. Would it be possible to prioritise user provided tables?
As a separate request:
Would it also be possible to add a command line option to dump the auto-generated lumps for a provided palette, stuff like translation tables and translucency tables, so they can be packaged with WADs for engines that don't automatically generate them?

**Comment by kraflab** [comment]
Not that this should influence the decision in woof, but the next dsda-doom drops manual translation tables in favor of autogenerated ones as well. Speaking of aaliens, I used this as one of my test cases and consulted skillsaw on the results before making the change.

**Comment by kraflab** [comment]
I also made a thread on dw and no one seemed to care 🤷

**Comment by fabiangreffrath** [comment]
> Would it be possible to prioritise user provided tables? 

They actually are. To provide some background: A color translation table only actually translates a color if the value at index `i` is not equal index `i` (`cr[i] != i`). In Woof, we catch these cases and keep them unchanged. That is, we merely *extend* the color translation tables to all other colors, but we do not override the ranges that are already translated by the original table.

Thus, I am surprised to read that certain graphics look differently than before. Could you probably provide some comparison screenshots, please?

> As a separate request: Would it also be possible to add a command line option to dump the auto-generated lumps for a provided palette, stuff like translation tables and translucency tables, so they can be packaged with WADs for engines that don't automatically generate them?

Sure, we could port over Crispy's `-lumpdump` feature.

**Comment by fabiangreffrath** [comment]
Actually, the former only applies if you pass the `-tranmap` parameter. If you don't, then the PWAD's own translation tables are used unchanged.

**Comment by ManxLoaghtan** [comment]
> Thus, I am surprised to read that certain graphics look differently than before. Could you probably provide some comparison screenshots, please?

It appears I made a mistake. I was comparing Woof's translation to Prboom+ under the assumption that it was more accurate but it seems the later one was actually altering things. The inside of the "0" character on the left is darker in Prboom+ for instance. This has also been carried over to dsda-doom, but I guess it doesn't matter now since it'll be changed soon (I'm fine with that). It was fun forcing AAliens to run in dos.
![aalienscolortranslation](https://user-images.githubusercontent.com/124502884/236412310-13395bda-441c-4b3d-8094-b40b7a318e6a.png)

**Comment by fabiangreffrath** [comment]
> It appears I made a mistake.

No problem, thanks for the discussion anyway!

Please note how the `0%` in the Armor widget is now actually translated to red (because it is supposed to be that color). Formerly, in Boom and MBF, the "red" translation table actually meant "no color translation at all", because Doom's original IWAD graphics were all red already. 😉
