### ISSUE TITLE
Coordinates display isn't always properly updated

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1036]
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/4900775217)._

Simply put: if the Automap Follow Mode is disabled, the coordinates display _outside_ of the Automap won't be updated at all.

With the Automap on, the coordinates display reports the position of the Automap crosshair. With Follow Mode on, it of course is the player's position, so the values reported by the coordinates display also apply for when the Automap is off. With Follow Mode off, however, the coordinates display will still report the position of the crosshair, which will remain static regardless of the player's position.

**Comment by rfomin** [comment]
Check "Coords follow pointer" automap menu option.

**Comment by MrAlaux** [comment]
Right, I missed that.

Still, is there any use to knowing the pointer's position if the Automap is off? Personally, I think the coords display should always report the player's position if the Automap is off - as long as the coords display is also enabled outside of the Automap, of course.

**Comment by fabiangreffrath** [comment]
I guess there should be an additional check for `automap_on` in `am_map.c:AM_Coordinates()`.

**Comment by fabiangreffrath** [comment]
With "Coords follow Player" enabled, the coords jump back and forth when toggling follow mode, although the palayer doesn't actually move at all. 🤷

**Comment by rfomin** [comment]
> With "Coords follow Player" enabled

Do you mean "Coords follow _Pointer_"? Hmm, works fine for me.

**Comment by fabiangreffrath** [comment]
Does this work for you?
```patch
--- a/src/am_map.c
+++ b/src/am_map.c
@@ -1101,7 +1101,7 @@ int map_point_coordinates;

 void AM_Coordinates(const mobj_t *mo, fixed_t *x, fixed_t *y, fixed_t *z)
 {
-  *z = followplayer || !map_point_coordinates ? *x = mo->x, *y = mo->y, mo->z :
+  *z = followplayer || !map_point_coordinates || !automapactive ? *x = mo->x, *y = mo->y, mo->z :
     R_PointInSubsector(*x = m_x+m_w/2, *y = m_y+m_h/2)->sector->floorheight;
 }

```

**Comment by MrAlaux** [comment]
Yep, seems to be working.

Somewhat related: when trying out your fix (applied to the latest master) I noticed that, with _Coords Follow Pointer_ enabled, the displayed coordinates change when I toggle Follow Mode, even if the pointer remains in the same spot. Not sure what that's about, but I thought I could mention it.

**Comment by fabiangreffrath** [comment]
Yep, that's what I've seen yesterday https://github.com/fabiangreffrath/woof/issues/1036#issuecomment-1537469496

No idea what's happening here, though.

**Comment by MrAlaux** [comment]
Oh, I missed that comment, sorry.

**Comment by fabiangreffrath** [comment]
I think I'll just rewrite this short function for it to become readable.

**Comment by fabiangreffrath** [comment]
Wait, I think that's a `FRACBITS` vs. `MAPBITS` thing here.

**Comment by fabiangreffrath** [comment]
Cannot check right now, but this may help:

```patch
--- a/src/am_map.c
+++ b/src/am_map.c
@@ -1101,8 +1101,8 @@ int map_point_coordinates;

 void AM_Coordinates(const mobj_t *mo, fixed_t *x, fixed_t *y, fixed_t *z)
 {
-  *z = followplayer || !map_point_coordinates ? *x = mo->x, *y = mo->y, mo->z :
-    R_PointInSubsector(*x = m_x+m_w/2, *y = m_y+m_h/2)->sector->floorheight;
+  *z = followplayer || !map_point_coordinates || !automapactive ? *x = mo->x, *y = mo->y, mo->z :
+    R_PointInSubsector(*x = (m_x+m_w/2) << FRACTOMAPBITS, *y = (m_y+m_h/2) << FRACTOMAPBITS)->sector->floorheight;
 }

 //
```

**Comment by MrAlaux** [comment]
I can't test it right now either, sorry.
