### ISSUE TITLE
Integer scaling doesn't work properly at 1080p

### ISSUE THREAD

**Issue by GabrielCARangel** [fabiangreffrath/woof#1038]
I don't know if this was reported or not, but the integer scaling option doesn't seem to work correctly at 1080p.
Here's an example on the HUD, notice how the bars have different pixel sizes:
![integer_problem_2](https://user-images.githubusercontent.com/22735373/236648099-7a847ef7-553c-4c2e-aebb-f9a8f8c768fa.png)

**Comment by rfomin** [comment]
These are non-square pixel artifacts, if I understand correctly. Try to disable `correct_aspect_ratio` in config, you should get perfect square pixels with integer scaling.

**Comment by mikeday0** [comment]
Internal vertical resolution is either 200 pixels (original) or 400 pixels (hi-res). It's not possible to integer scale either of those to 1080. Smooth Pixel Scaling should help here, correct?

**Comment by GabrielCARangel** [comment]
Disabling the aspect ration correction does fix it, but Doom's pixels need to be stretched to look right, so it's not a complete solution.
Would it be possible to have the resolution scale to 1280x1000 instead? The pixel size wouldn't be 5x6, but 4x5 looks close to maintain the stretched look needed.

**Comment by fabiangreffrath** [comment]
I'm afraid I don't understand exactly what's requested here. Doom's correct pixel aspect ratio is 1.2. By which means should we decide that it's now right to scale by 1.25 instead? (Apart from the fact that it's just not the right aspect ratio)

**Comment by liPillON** [comment]
In my experience as a user: when terminology like "pixel perfect scaling" starts being used in a project, a lot of subjectivity comes into play... 

I would always try to keep things simple by using only unambiguous concepts like:
- integer scaling: enlarge/reduce by applying an integer factor to multiply/divide both vertical and horizontal resolution
- even VS uneven scaling: apply the same factor (either integer or not) to both axis VS apply different factors to each axis
- accurate aspect ratio correction: can only be achieved with uneven integer scaling applied to specific scenarios (eg: 5x horizontally and 6x vertically to transform a 16:10 image with square physical pixels to a 4:3 image with non-square logical pixels)
- approximate aspect ratio correction: traditionally obtained by duplicating every fifth row of pixels from the original image, leading to image distortion

In dosbox staging, "pixel perfect" means "avoiding pixels distortions takes priority over appropriate aspect ratio correction" and so they end up with such an unusual 1.25 non-square pixel aspect ratio.
This to me has no sense: you'll end up with perfectly sharp pixels sure but you'll also have to deal with an image aspect ratio potentially not suited for the art assets made by the game developer.

As I see it, the best compromise between accurate aspect ratio correction, integer scaling, modern screen resolutions and minimal pixel distortion would be:
1) determine the display's (or window's when not in fullscreen mode) vertical resolution (eg: 1080p)
2) check if the user wants to a.r. correction to be performed
3a) if yes, always apply a 6x/12x/18x scaling factor for the vertical resolution and 5x/10x/15x factor for the horizonal resolution
3b) if no, determine the minimum integer scale factor necessary to exceed the display res (eg: 200x6=1200 or 400x3=1200) and apply it to both axis (resulting in a 1920x1200 image)
4) now downscale using bilinear filtering

**Comment by liPillON** [comment]
I've summarized some typical scenarios in the following tables:


![Screenshot 2023-05-07 224652](https://user-images.githubusercontent.com/48625273/236701886-d6600913-ab5c-4d9e-a81d-cce256fd43f5.png)

**Comment by GabrielCARangel** [comment]
Sorry, I wasn't trying to say that the Doom aspect ratio was wrong or something like that, maybe my wording was wrong.
This "solution" is merely a concession adopted by a variety of emulators / engines of DOS games to maintain pixel perfection while still doing some sort of pixel stretching.
This doesn't preserve the aspect ratio perfectly but it avoids doing any kind of down scaling and making things blurry.

**Comment by mikeday0** [comment]
I am skeptical that a 1280x1000 game view with a black border and incorrect pixel aspect ratio would be an improvement over the current state. The version 11.0.0 defaults (`smooth_scaling` on, `integer_scaling` off and `correct_aspect_ratio` on) are true to the original game art and aren't blurry at all at sufficiently high resolutions. I get it - I'm pretty picky about this pixel stuff too! - but in action I think it looks pretty much flawless.
