### ISSUE TITLE
no native MIDI on MacOS

### ISSUE THREAD

**Issue by ribbiks** [fabiangreffrath/woof#1043]
Greetings, jumping back and forth between Woof-from-early-2022 and latest version I noticed that SDL is no longer available as a midi_player option (on mac SDL uses the default system soundfont which I've grown quite attached to). Instead my only option is OPL, which I guess I might've installed at some point. Doesn't matter what values I feed the cfg, it'll revert to 0 and use OPL. Whereas in the earlier version I can switch between SDL / OPL.

Probably a mac thing? I'm currently running Ventura 13.3.1. Testing out the 11.0.0 win32 binaries in a VM all the usual suspects are present and function as expected, microsoft gs <--> opl <--> fluidsynth.

**Comment by rfomin** [comment]
We switched from SDL_Mixer to OpenAL for audio mixing and lost native MacOS MIDI support. But Fluidsynth should still work - the `fluid-synth` package if you're building with homebrew. I don't know if Fluidsynth is good enough, never used Mac.

**Comment by ribbiks** [comment]
hmmm. unfortunate. not a fan of opl or fluidsynth at all. will stick with the older version then.

**Comment by rfomin** [comment]
The SDL_Mixer MIDI module for MacOS looks simple enough: https://github.com/libsdl-org/SDL_mixer/blob/main/src/codecs/native_midi/native_midi_macosx.c
I'll try to implement in Woof. I hope you test it 😄

**Comment by ribbiks** [comment]
happy to do so!

**Comment by mikeday0** [comment]
> hmmm. unfortunate. not a fan of opl or fluidsynth at all. will stick with the older version then.

Not sure how you're building everything but I just noticed that the Homebrew `sdl2_mixer` package started disabling support for native MIDI back in February.

**Comment by rfomin** [comment]
> I just noticed that the Homebrew `sdl2_mixer` package started disabling support for native MIDI back in February.

Do you know, why? Is this code outdated already?

**Comment by mikeday0** [comment]
I think this was an oversight by the Homebrew devs. I don't see any indication that SDL_Mixer is dropping macOS midi support.
