### ISSUE TITLE
Crash with DSDHacked sound indices greater than 699

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1065]
_Tested on the 11.1.1 release._

I'm working on a DSDHacked patch through the DECOHack utility. When defining sounds with new names, it assigns names to sound indices starting from 700. For whatever reason, that's the very index at which Woof begins to crash. I tried with index 699 and a few lesser indices, and they didn't trigger a crash.

I guess you can test with a patch like this one:
```
Patch File for DeHackEd v3.0

Doom version = 2021
Patch format = 6


[SOUNDS]
700 = CASIN0
```

I also tested on DSDA 0.25.6, and sound index 700 doesn't trigger a crash there; in fact, the sound works just fine in-game, as I'd expect.

**Comment by MrAlaux** [comment]
Hold up!

The game also crashes when using _sprite_ indices greater than 244. I guess that should be fixed too while we're on it.

**Comment by rfomin** [comment]
> The game also crashes when using _sprite_ indices greater than 244. I guess that should be fixed too while we're on it.

It's the same issue: https://github.com/fabiangreffrath/woof/pull/1066/commits/b077841c79b4a59dc38a8ebc5a5063df3c9e4eb4 It seems I forgot to test BEX sounds/sprites.
