### ISSUE TITLE
Some cheat keys bypass the cheats' conditions

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1068]
_Tested on the 11.1.1 release._

Here's a little chart with the differences in conditions:

```
Cheat     | cheat[] conds     | cheat_input[] conds
---------------------------------------------------
idbeholda | not_net, not_demo | always
idbeholdl | not_net, not_demo | always
iddt      | not_dm            | always
```

I'm guessing that the `cheat_input[]` conditions should match the `cheat[]` conditions.

**Comment by rfomin** [comment]
I copied this from DSDA-Doom, these cheats seem to be harmless, they do not affect the demo/net synch. I doubt that anyone will seriously play Woof in deathmatch mode.

**Comment by MrAlaux** [comment]
Indeed, this is harmless to sync, but I'm still worried about it making it easier for players to cheat in netgames. Oh well, it's up to you.

**Comment by fabiangreffrath** [comment]
Well, DSDA-Doom does not have any network game support anymore, so checking for `not_net` or `not_dm` would be moot there. However, these checks are stil relevant for us.
