### ISSUE TITLE
DSDHacked sounds aren't loaded, sprites still crash the game

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1072]
_Tested on the 11.1.2 release._

I shouldn't have waited until an official release to test DSDHacked sounds and sprites again, sorry. I _will_ do it this time around.

For each DSDHacked sound defined in a DeHackEd patch, a `SndFile: Format not recognised.` error is reported on the console output, and the sounds don't work in-game at all. The sound lumps themselves _are_ in Doom Sound format (in fact, they worked just fine previously, when they used `FRE###` names).

Attempting to use any DSDHacked sprites crashes the game.

Both of these things work correctly in DSDA-Doom. It seems like index number is unrelated to these issues.

**Comment by MrAlaux** [comment]
As I said, I'll test this myself once a fix is live. However, if you'd like to test it yourselves, feel free to use this WAD and DEH:

[SD21.zip](https://github.com/fabiangreffrath/woof/files/11542453/SD21.zip)

**Comment by fabiangreffrath** [comment]
```patch
diff --git a/src/r_things.c b/src/r_things.c
index 2d5185a..8a28abb 100644
--- a/src/r_things.c
+++ b/src/r_things.c
@@ -188,7 +188,7 @@ void R_InitSpriteDefs(char **namelist)
   // scan all the lump names for each of the names,
   //  noting the highest frame letter.

-  for (i=0 ; i<num_sprites ; i++)
+  for (i=0 ; i<num_sprites && namelist[i] ; i++)
     {
       const char *spritename = namelist[i];
       int j = hash[R_SpriteNameHash(spritename) % numentries].index;

```

**Comment by MrAlaux** [comment]
Just tested that, and it fixed the sprites crash. We'd just be missing a fix for sounds, then.

**Comment by fabiangreffrath** [comment]
```diff
$ git diff
diff --git a/src/dsdhacked.c b/src/dsdhacked.c
index c630970..d0074ee 100644
--- a/src/dsdhacked.c
+++ b/src/dsdhacked.c
@@ -319,6 +319,7 @@ int dsdh_GetOriginalSFXIndex(const char* key)

   i = atoi(key);
   dsdh_EnsureSFXCapacity(i);
+  S_sfx[i].lumpnum = -1;

   return i;
 }
```

**Comment by MrAlaux** [comment]
Yep, that did it. Sounds are working now.

**Comment by fabiangreffrath** [comment]
The first patch again, a bit more explicit:
```patch
diff --git a/src/r_things.c b/src/r_things.c
index 2d5185a..e460cf2 100644
--- a/src/r_things.c
+++ b/src/r_things.c
@@ -191,7 +191,12 @@ void R_InitSpriteDefs(char **namelist)
   for (i=0 ; i<num_sprites ; i++)
     {
       const char *spritename = namelist[i];
-      int j = hash[R_SpriteNameHash(spritename) % numentries].index;
+      int j;
+
+      if (!spritename)
+        break;
+
+      j = hash[R_SpriteNameHash(spritename) % numentries].index;

       if (j >= 0)
         {

```

@rfomin `break` or `continue`?

**Comment by MrAlaux** [comment]
Tested that patch just in case, seems to be working too.

**Comment by rfomin** [comment]
> @rfomin `break` or `continue`?

`continue` I think. Thanks for fixes.

**Comment by MrAlaux** [comment]
> Could you post that patch here and tell me how to provoke the crash?

Here it is: [SD21-SpriteTest.zip](https://github.com/fabiangreffrath/woof/files/11548780/SD21-SpriteTest.zip)

There are two variants of the DEH patch, both use the same WAD. Look for the `[SPRITES]` section of the DEH, near the end of the file:

`SD21-Good.deh` should be working properly, its `[SPRITES]` section has nothing wrong to it. I tested it both on Woof 11.1.4 and DSDA 0.25.6 with no issues.

`SD21-Bad.deh` is intentionally broken; you may notice that its `[SPRITES]` section has a line that reads `250 = `. In the good patch, that same line reads `250 = S008`.
Sprite index 250 is used by the Chaingun; therefore, to provoke a crash in both Woof 11.1.4 and DSDA 0.25.6, just launch the game and select the Chaingun.
All sprites defined after index 250 are still loaded properly (if you try to equip any other weapon, they should work fine). I don't think there's any issue with this, no one should be trying to use nameless sprites after all.

**Comment by fabiangreffrath** [comment]
Thanks for that! I was concerned that it would *crash* in the "bad" case, but actually it *quits* with a rather explicit error message: "R_DrawPSprite: invalid frame 0 for sprite (null)".
