### ISSUE TITLE
propper console logging system

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#1073]
I'd like to replace all calls to `printf()`/`puts()` with a proper API, e.g. `I_printf(prio, ...)` where `prio` is one of "always" (e.g. for `-version`), "error", "warn", "info" and "debug" (e.g. for extra warnings currently emitted only with `-devparm`).

Pros:
- We would have one clean interface for logging to console.
- We could implement a user-defined verbosity level (e.g. defaulting to info).
- It would be clear which lines go to `stdout` (always, info) and which ones go to `stderr` (error, warn, debug).
- We could print colored lines depending on severity (e.g. error = red, warn = orange, debug = purple).

Cons:
- This will be a massive effort for rather little gain.

Opinions?

**Comment by kraflab** [comment]
This is lprintf in dsda-doom / pr+: https://github.com/kraflab/dsda-doom/blob/master/prboom2/src/lprintf.c

It's pretty convenient to be able to change the verbosity.

**Comment by rfomin** [comment]
We can just delete all useless messages, then we won't need a logging system 😄
Sure, if you want it. Personally, I like plain `printf`.
