### ISSUE TITLE
implement Automap color presets

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#108]
Just an idea, it would be nice to have the ability to easily swap between different automap color presets without having to manually do them by hand. 

Preset ideas:
- Vanilla
- Boom/MBF
- ZDoom

**Comment by fabiangreffrath** [comment]
This is indeed a nice idea. Could you probably provide e.g. a chart with the corresponding values for the automap colors?

**Comment by OpenRift412** [comment]
> Could you probably provide e.g. a chart with the corresponding values for the automap colors?
Well I don't know entirely about ZDoom, Boom/MBF seems to be the current default anyway, but here's my config, which has the vanilla colors matched as best I can. I checked each of the colors in photoshop and they seem to check out. 


[woof vanilla automap.zip](https://github.com/fabiangreffrath/woof/files/5869554/woof.vanilla.automap.zip)

**Comment by fabiangreffrath** [comment]
One issue I have with this idea is that there is already a "reset to defaults" button in the automap colors menu. Adding a second switch of that kind would be pretty redundant. And this all clashes with the idea to reset to the Vanilla color scheme. Probably I'll just include it as a config example.

**Comment by fabiangreffrath** [comment]
Honestly, I don't think we will get any further with this than the config file snippet that we already ship to change the map colors to the Vanilla scheme.

**Comment by OpenRift412** [comment]
Hey @fabiangreffrath so I was thinking recently, since @JNechaevsky's International Doom has its own automap palette preset selector, perhaps that could be implemented into Woof? Or would that not be worthwhile?

**Comment by fabiangreffrath** [comment]
If this gets implemented, I'd argue for removing all but the first page of the Automap setup menu and really just keep the explicit choice of "Boom" or "Vanilla"  color scheme. The config vars would stil be there and available to OPTIONS lumps, but nothing more should really be required.

**Comment by rfomin** [comment]
> If this gets implemented, I'd argue for removing all but the first page of the Automap setup menu and really just keep the explicit choice of "Boom" or "Vanilla" color scheme.

I agree, but it's interesting to get @OpenRift412's opinion. Personally, I've never used the automap color editor.

**Comment by fabiangreffrath** [comment]
> The config vars would stil be there and available to OPTIONS lumps

Speaking if which, do they actually permanently overwrite the player's choice of automap colors once loaded?

**Comment by rfomin** [comment]
> Speaking if which, do they actually permanently overwrite the player's choice of automap colors once loaded?

Yes. We've even grayed out the menu items in their respective colors.

**Comment by fabiangreffrath** [comment]
Hm, I think we need even three settings then, with "Boom" and "Vanilla" having their target colors mapped to the current palette, and "Custom" (or "Default") using the values from the OPTIONS lump / config file.

**Comment by rfomin** [comment]
> What I mean is, are the values set by the OPTIONS lump saved in the config file and then reloaded for all subsequent plays, even without that specific OPTIONS lump?

No, the values from the OPTIONS lump will be applied only for the current game.

**Comment by fabiangreffrath** [comment]
Oh, wow! I didn't even know. Parts of the config/menu system are still a miracle to me. 😁 

So, if it's possible for content creators to temporarily override specific map colors according to their own palette, then we really only need a means to reset colors to either preset.

**Comment by fabiangreffrath** [comment]
> Preset ideas:
> 
> [...]
> * ZDoom

Did ZDoom even have a specific automap color scheme?

**Comment by OpenRift412** [comment]
> > Preset ideas:
> > [...]
> > 
> > * ZDoom
> 
> Did ZDoom even have a specific automap color scheme?

It did, it was kind of similar to Heretic where it was mostly shades of brown, something like that.

**Comment by OpenRift412** [comment]
> > If this gets implemented, I'd argue for removing all but the first page of the Automap setup menu and really just keep the explicit choice of "Boom" or "Vanilla" color scheme.
> 
> I agree, but it's interesting to get @OpenRift412's opinion. Personally, I've never used the automap color editor.

Honestly, while I personally wouldn't mind having the color editor removed, I do get the feeling it's removal would generate some complaints. I think the best medium between the two would be to remove the color editor from the settings menu, but still allow customization through the CFG file. But even then, I don't know if that'd be the best course of action. It's really up to you how you'd want to go about it.

**Comment by fabiangreffrath** [comment]
> I think the best medium between the two would be to remove the color editor from the settings menu, but still allow customization through the CFG file.

That's the plan. It would save us two pages of setup submenus, a whole menu item category (`S_COLOR`), three embedded lumps and a file in `docs/`.
