### ISSUE TITLE
`quickSaveSlot` can remain set to an incompatible savegame slot

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1083]
_Tested in the 11.1.4 release._

I haven't quite checked the code, I just tested this in-game.

Starting from a new game, with `quickSaveSlot` set to -1, when entering the Save or Load Game menus (be it through the main menu or the dedicated function keys) `quickSaveSlot` remains set to -1. Even when saving or loading a game, the latter whether successful or not, `quickSaveSlot` still remains set to -1.

When pressing the Quick Save or Load keys, though, `quickSaveSlot` is set to -2. Then, when saving or loading a game, the latter whether successful or not, `quickSaveSlot` is set to the selected slot. I find this to be quite a nuisance if I accidentally select an incompatible savegame.

It wasn't immediately clear to me that using End Game resets `quickSaveSlot` to -1, which leads me to believe that many other users wouldn't be aware of that either, leaving them with the sole option of restarting the game altogether if they want to reset `quickSaveSlot`.

I suggest that `quickSaveSlot` is set to the selected slot _only_ if the savegame is actually loaded (i.e. if the "incompatible savegame" warning pops up, the user confirms loading of the save anyways), and in case saving can fail too, if the saving is successful. Going further with this, it could also be made so that `quickSaveSlot` is set to the last loaded (not saved!) game, whether it was a Quick Load or not.

**Comment by fabiangreffrath** [comment]
Does this help?

```patch
diff --git a/src/m_menu.c b/src/m_menu.c
index d6f7ed0..f6d70d1 100644
--- a/src/m_menu.c
+++ b/src/m_menu.c
@@ -954,6 +954,8 @@ static void M_VerifyForcedLoadGame(int ch)
 {
   if (ch=='y')
     G_ForcedLoadGame();
+  else
+    quickSaveSlot = -1;
   free(messageString);       // free the message strdup()'ed below
   M_ClearMenus();
 }
```

**Comment by MrAlaux** [comment]
With this change, `quickSaveSlot` is reset to -1 when denying the "incompatible savegame" prompt, even if it was previously set to a valid slot. In my opinion, a bit messy but ultimately preferrable by far.

**Comment by fabiangreffrath** [comment]
Oh, right! How about this then? 

```patch
diff --git a/src/m_menu.c b/src/m_menu.c
index d6f7ed0..f6d70d1 100644
--- a/src/m_menu.c
+++ b/src/m_menu.c
@@ -954,6 +954,8 @@ static void M_VerifyForcedLoadGame(int ch)
 {
   if (ch=='y')
     G_ForcedLoadGame();
+  else if (quickSaveSlot == -2)
+    quickSaveSlot = -1;
   free(messageString);       // free the message strdup()'ed below
   M_ClearMenus();
 }
```

**Comment by fabiangreffrath** [comment]
I think we need a helper function in `m_menu.c` which sets `quickSaveSlot` to the current slot and that gets called from `g_game.c` upon successful loading or saving of the game.

**Comment by MrAlaux** [comment]
Sounds good to me. Though, are we speaking of quick saving/loading or general saving/loading? If the latter, I still think that `quickSaveSlot` should be set to the last successfully loaded game (whichever method of loading) but _not_ the last saved game. 

My reasoning behind this is that I could save a game as some sort of checkpoint on a slot separate from my current slot. Then, if I wanted to, I could roll back to that checkpoint and continue playing from it, having quicksave save on its slot. Of course, this is just my opinion.
