### ISSUE TITLE
Screenshots taken with Aspect Ratio Correction disabled aren't cropped

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1087]
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/5119092179)._

The following screenshots were taken with widescreen disabled. For reference, my screen's resolution is 1366x768.

<details>
<summary>Correction ON</summary>
<br>

Image dimensions: 1024x768
![woof0000](https://github.com/fabiangreffrath/woof/assets/73968015/4a38c8db-0cad-4089-b5b0-9d7a229fb5cd)

</details>

<details>
<summary>Correction OFF</summary>
<br>

Image dimensions: 1366x768
![woof0002](https://github.com/fabiangreffrath/woof/assets/73968015/efa7e600-dfb4-47d5-a6c0-777e61a407a3)

</details>

I had already encountered this issue in Nugget Doom, and fixed it by removing the `useaspect` check in Line 738 here:
https://github.com/fabiangreffrath/woof/blob/4e7ad58a2a9b3869fa1047347e87c4556c2a1f18/src/i_video.c#L736-L740

**Comment by fabiangreffrath** [comment]
Indeed, this might be a copy/paster from Crispy Doom, where `use_aspect == 0` means to allow any arbitrary aspect ratio, which in turn is impossible with Woof. Here, `use_aspect == 0` means the same as `use_aspect == 2` in Crispy.

**Comment by MrAlaux** [comment]
Should I file a PR for it? It's a very small change after all.

**Comment by fabiangreffrath** [comment]
Yes, please.
