### ISSUE TITLE
MUS2MIDI Endianness Issue 

### ISSUE THREAD

**Issue by BeWorld2018** [fabiangreffrath/woof#109]
I port Woof on MorphOS platform (PPC AmigaOS like)
All working... but no music with SDL2_mixer, no error...
I check code quickly and i dont see why :-(

Thanks

**Comment by fabiangreffrath** [comment]
Well, this is hardly Woof!'s fault, it works on any other OS that I've heard about. 

Do other programs using SDL2_Mixer work? Does this only affect music? Do SFX play? Do you have fluidsynth built and installed? Do you have a soundfont installed?

Also, how much is the porting effort? Anything you'd like to share?

**Comment by BeWorld2018** [comment]
Hi,

Sound working find, but no music.
SDL2_mixer working no problem... we use timidity here, not fluidsynth (fluidsynth is not compatible), maybe one explication...

I put some debug output here : https://github.com/fabiangreffrath/woof/blob/master/Source/i_sound.c#L894
I see Mix_loadMUS_RW = ok... but no sound and no error.. strange, maybe data is wrong (big endian)

I can make more test is necessary.....
I can create git with my source, I haven't changed much (just platform specific)

Thanks

**Comment by fabiangreffrath** [comment]
Does it work if you load a PWAD that replaces the MIDI music lumps with MP3/Ogg music, such as https://www.moddb.com/mods/brutal-doom/downloads/doom-metal-soundtrack-mod-volume-5 ?

**Comment by BeWorld2018** [comment]
to be sur, i launch : woof -file DoomMetalVol5.wad ? i need to have DOOM.wad for example ?

**Comment by fabiangreffrath** [comment]
`woof -iwad doom.wad -file DoomMetalVol5.wad`

**Comment by BeWorld2018** [comment]
Work perfeclty !

**Comment by fabiangreffrath** [comment]
Then you need to get MIDI properly setup on your system. Good luck!

**Comment by BeWorld2018** [comment]
Re,

i found :-) endian mistake on mus2mid

Check, can help : https://github.com/sezero/hhexen/blob/2b9f9dc6c0aec6791a47bd8d7b0c1f5dff599b37/base/mus.c#L235

**Comment by fabiangreffrath** [comment]
Glad you found a solution! Would you mind filing a PR with the necessary changes?

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/18bb743540968be3330b6afbd1ffee406b566b10
