### ISSUE TITLE
add obituaries from ZDoom (optional)

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#1092]
Now that we are able to selectively enable or disable specific types of messages in the game, it would be nice to add support for obituaries (as found in the ZDoom family of ports), but have them disabled by default. The obituary strings should be modifyable by DEHACKED. There are default strings available in the old Doom wiki (and in the GZDoom sources, I guess):
https://doom.fandom.com/wiki/ZDoom_obituaries

Since our player "object" does not distinguish between different sexualities, I think it is safest to always refer to them as they/them.

**Comment by fabiangreffrath** [comment]
Substitutions for the format strings:
https://github.com/ZDoom/gzdoom/blob/22271d146a0bca6b432f458c96c4ca18a1b6b143/src/playsim/p_interaction.cpp#L119

**Comment by fabiangreffrath** [comment]
Method of Death types:
https://github.com/ZDoom/gzdoom/blob/22271d146a0bca6b432f458c96c4ca18a1b6b143/src/playsim/p_lnspec.cpp#L113

**Comment by fabiangreffrath** [comment]
Default strings:
https://github.com/ZDoom/gzdoom/blob/22271d146a0bca6b432f458c96c4ca18a1b6b143/wadsrc/static/language.csv#L1191

**Comment by fabiangreffrath** [comment]
@rfomin what would you say, where is the best place to set the player names from the colors to the actual chosen names?

**Comment by rfomin** [comment]
> @rfomin what would you say, where is the best place to set the player names from the colors to the actual chosen names?

I don't know. I found that very few Boom/MBF PWADs have obituaries in Dehacked, this feature might not be worth it.

**Comment by fabiangreffrath** [comment]
> > @rfomin what would you say, where is the best place to set the player names from the colors to the actual chosen names?
> 
> I don't know. I found that very few Boom/MBF PWADs have obituaries in Dehacked, this feature might not be worth it.

Do you mean the obituaries feature itself or just the part that replaces "player 1" or "green player" with their chosen name?

**Comment by rfomin** [comment]
> Do you mean the obituaries feature itself or just the part that replaces "player 1" or "green player" with their chosen name?

I mean the feature itself. I know only two compatible PWADs where it has been used: Ancient Aliens and Doom 2 in Spain Only.

**Comment by fabiangreffrath** [comment]
> I mean the feature itself. I know only two compatible PWADs where it has been used: Ancient Aliens and Doom 2 in Spain Only.

Okay, but we could nevertheless have "Vanilla" obituaries for multiplayer games. The feature doesn't only start to make sense if the strings got dehacked, right?

**Comment by fabiangreffrath** [comment]
What's the default color for obituaries in gzdoom?

**Comment by fabiangreffrath** [comment]
> What's the default color for obituaries in gzdoom?

Seems that's gold, but we should make this configurable anyway.

**Comment by fabiangreffrath** [comment]
> Default strings: https://github.com/ZDoom/gzdoom/blob/22271d146a0bca6b432f458c96c4ca18a1b6b143/wadsrc/static/language.csv#L1191

This file contains a lot of strings. We should *at least* support those listed here:

https://github.com/freedoom/freedoom/blob/c11acd60099e5202ed816139be472d5e35d970f4/lumps/dehacked/dehacked.txt#L612
