### ISSUE TITLE
Simplification of the menu

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#110]
I know, this port should be close to MBF, but I've been playing Doom for 20 years and still forget where to find a specific option in "Setup" or "General". GZDoom recently simplified its menu but retained the old menu structure under the "Full Options" submenu. I like the idea, it makes the port much more convenient. So, for Woof, I suggest making simplified "Controls" and "Video Options" in the main menu, and move everything else to the "Full Options" submenu.

![draft-fin](https://user-images.githubusercontent.com/5077629/105790486-0ad02880-5fb7-11eb-8198-4008a1d7b0bc.png)

(sorry for bad photoshop)

**Comment by fabiangreffrath** [comment]
Sorry, but I feel like this is crossing a line. I already can't sleep whenever I add or remove a single menu item, but a re-arrangement is out of the question.
