### ISSUE TITLE
200p Widescreen is 428x200 instead of 426x200

### ISSUE THREAD

**Issue by Ash5173** [fabiangreffrath/woof#1119]
Title pretty much tells you everything you need to know. The tell here is the tiled texture that's normally on the edges of the status bar showing, but its just a single column of pixels on both edges of the screen. Problem doesn't persist with 400p and I also noticed this in crispy doom as well.

![woof0000](https://github.com/fabiangreffrath/woof/assets/138235103/ffd11f1e-fdc8-437e-a044-64aa53934779)

**Comment by fabiangreffrath** [comment]
This is because SDL expects a pitch that is a multiple of 4 bytes for surfaces. Since we are in palette mode, each pixel only occupies 1 byte, so we need a number of pixels that is a multiple of 4. 426 is not a multiple of 4, but 428 is.
