### ISSUE TITLE
Weapon rendering bug

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1123]
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/5443154043)._

The title is vague because the bug is quite specific: with uncapped framerate, the rightmost visible column of weapon sprites that go beyond the right edge of the screen flickers when the weapon is bobbing right. See for yourself:

![imagen](https://github.com/fabiangreffrath/woof/assets/73968015/2a6189a3-6770-4a22-a527-c9ce741633c1)

I didn't test with sprites that go beyond the left edge of the screen. The bug seems to happen regardless of High Resolution, Widescreen, V-Sync and window/screen size.

**Comment by rfomin** [comment]
This patch is not correct, but it fixes the issue:
```diff
diff --git a/src/r_things.c b/src/r_things.c
index 7966ece..5bddcf6 100644
--- a/src/r_things.c
+++ b/src/r_things.c
@@ -756,7 +756,7 @@ void R_DrawPSprite (pspdef_t *psp)
                     (psp->sy2-spritetopoffset[lump]); // [FG] centered weapon sprite
 
   vis->x1 = x1 < 0 ? 0 : x1;
-  vis->x2 = x2 >= viewwidth ? viewwidth-1 : x2;
+  vis->x2 = x2;
   vis->scale = pspritescale;
 
   if (flip)
@@ -814,7 +814,6 @@ void R_DrawPSprite (pspdef_t *psp)
       int deltax = vis->x2 - vis->x1;
       vis->x1 = oldx1 + FixedMul(vis->x1 - oldx1, fractionaltic);
       vis->x2 = vis->x1 + deltax;
-      vis->x2 = vis->x2 >= viewwidth ? viewwidth - 1 : vis->x2;
       vis->texturemid = oldtexturemid + FixedMul(vis->texturemid - oldtexturemid, fractionaltic);
     }
     else
```

**Comment by fabiangreffrath** [comment]
The latter change was introduced here:
https://github.com/fabiangreffrath/woof/commit/bf27bfe512d8e1148dc99520183bf917aee08f8f

**Comment by rfomin** [comment]
Another variant:
```diff
diff --git a/src/r_things.c b/src/r_things.c
index 7966ece..9bc2021 100644
--- a/src/r_things.c
+++ b/src/r_things.c
@@ -756,7 +756,7 @@ void R_DrawPSprite (pspdef_t *psp)
                     (psp->sy2-spritetopoffset[lump]); // [FG] centered weapon sprite
 
   vis->x1 = x1 < 0 ? 0 : x1;
-  vis->x2 = x2 >= viewwidth ? viewwidth-1 : x2;
+  vis->x2 = x2 > viewwidth ? viewwidth+1 : x2;
   vis->scale = pspritescale;
 
   if (flip)
@@ -814,7 +814,8 @@ void R_DrawPSprite (pspdef_t *psp)
       int deltax = vis->x2 - vis->x1;
       vis->x1 = oldx1 + FixedMul(vis->x1 - oldx1, fractionaltic);
       vis->x2 = vis->x1 + deltax;
-      vis->x2 = vis->x2 >= viewwidth ? viewwidth - 1 : vis->x2;
+      if (vis->x2 > viewwidth)
+        vis->x2 = viewwidth + 1;
       vis->texturemid = oldtexturemid + FixedMul(vis->texturemid - oldtexturemid, fractionaltic);
     }
     else
```
Can we crash with this because of an out-of-framebuffer write? Also I guess we need to modify a check for `x2 == 0`.

**Comment by fabiangreffrath** [comment]
> Can we crash with this because of an out-of-framebuffer write? Also I guess we need to modify a check for `x2 == 0`.

`R_DrawVisSprite()` iterates from `dc_x = vis->x1` to `dc_x <= vis->x2`, so I'm afraid yes.

Also, there is already a `if (x2 < 0) return;` check earlier in `R_DrawPSprite()`.

**Comment by fabiangreffrath** [comment]
The `x2 == 0` case is valid if `x1 == 0`, so it will draw a single column on the left-most side of the window.

**Comment by fabiangreffrath** [comment]
@rfomin could you try `x2` instead of `vis->x2` in the `if (uncapped)` code path? 

Let's say, the weapon vissprite is 110px wide, but had to get capped at 100px on the right side. Its `vis->x2` value had been adjusted accordingly. Now, the weapon is bobbing *away* from the right side of the screen, but between two tics, it's `vis->x2` value isn't recalculated and it still caries the value from the previous tic, where it was capped. Thus, during frames between Thus tic and the next  a gap opens to its right side, which is only closed when `vis->x2` is recalculated in the next tic.
