### ISSUE TITLE
add multi-lined HUD widgets

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#1131]
Bring back the three-lined K/I/S and X/Y/Z widgets. I was reluctant to bring them back, but the requests persists. 😉 This will need some extra care for bottom aligned widgets, because they will have to stack bottom-to-top. While at it, add some 1-char-wide padding to the right of right-aligned widgets.

**Comment by fabiangreffrath** [comment]
> add some 1-char-wide padding to the right of right-aligned widgets.

```patch
diff --git a/src/hu_lib.c b/src/hu_lib.c
index a945e7c..1192251 100644
--- a/src/hu_lib.c
+++ b/src/hu_lib.c
@@ -156,7 +156,7 @@ void HUlib_addStringToTextLine(hu_textline_t *l, char *s)
   while (*--s == ' ')
     w -= 4;

-  l->width = w;
+  l->width = (w + 7) & ~7;
   l->visible = true;
 }


```

**Comment by fabiangreffrath** [comment]
> Bring back the three-lined K/I/S and X/Y/Z widgets.

Not that easy, actually. At least, not as the hu_lib/hu_stuff maze is designed now. We currently have three similar, but different types of text widgets (`hu_stext_t`, `hu_mtext_t` and `hu_itext_t`), which contain differently-sized arrays of `hu_textline_t` - and then we have widgets which only consist of a single `hu_textline_t`. I think I will have to rewrite most of this and abstact it into only one type of "widget", which contains one or more "textlines".

**Comment by fabiangreffrath** [comment]
> While at it, it should be possible to only _change_ the lines explicitly listed in the WOOFHUD lump and _keep the others unchanged_ (changed widgets will have to get moved to the end of the list). Also, it should be possible to assign a widget an explicit y-coordinate and have it centered horizontally ("secret revealed" widget).

**Comment by fabiangreffrath** [comment]
Another question to clarify is how to proceed with '\n' in messages, which are explicitly supported in MBF. Strictly speaking, they will have to trigger writing a new line, which will cause problems with bottom or right aligned widgets.

**Comment by rfomin** [comment]
> Another question to clarify is how to proceed with '\n' in messages, which are explicitly supported in MBF. Strictly speaking, they will have to trigger writing a new line, which will cause problems with bottom or right aligned widgets.

I think it's safe to remove it, although it's probably used in a few menu items.

**Comment by fabiangreffrath** [comment]
The menu has its own font rendering functions (which also support '\n').

**Comment by fabiangreffrath** [comment]
TODO:

- [ ] make `hu_stext_t`, `hu_mtext_t` and `hu_itext_t` "API-compatible"
- [ ] consolidate `hu_stext_t` and `hu_itext_t` into `hu_mtext_t`
- [ ] turn all "widgets" from `hu_textline_t` into `hu_mtext_t`
- [ ] track horizontal and vertical align separately (e.g. for m_secret: h_align centered, v_align direct)
- [ ] turn "exclusive" mode (i.e. widget does not allow any other widget on the same line) from an align into a `hu_mtext_t` property
