### ISSUE TITLE
Direct Vertical Aiming takes effect even with Mouselook disabled

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1132]
_Tested in the latest release._

The issue with this is that if Direct Vertical Aiming were to be enabled while Mouselook is disabled, autoaim would still be disabled, effectively taking away the player's ability to shoot upwards or downwards and also disabling horizontal autoaim for projectiles.

**Comment by fabiangreffrath** [comment]
Right, direct vertical aiming without mouselook is a pretty unfortunate feature combination. 😁

**Comment by fabiangreffrath** [comment]
This should do:
```patch
diff --git a/src/p_map.c b/src/p_map.c
index 098fee4..3f63bff 100644
--- a/src/p_map.c
+++ b/src/p_map.c
@@ -1672,7 +1672,7 @@ fixed_t P_AimLineAttack(mobj_t *t1,angle_t angle,fixed_t distance,int mask)

   // can't shoot outside view angles

-  if (t1->player && CRITICAL(direct_vertical_aiming))
+  if (t1->player && t1->player->lookdir && CRITICAL(direct_vertical_aiming))
   {
     bottomslope = (topslope = PLAYER_SLOPE(t1->player) + 1) - 2;
   }
diff --git a/src/p_mobj.c b/src/p_mobj.c
index fa9c491..49e47e6 100644
--- a/src/p_mobj.c
+++ b/src/p_mobj.c
@@ -1474,7 +1474,7 @@ mobj_t* P_SpawnPlayerMissile(mobj_t* source,mobjtype_t type)
     {
       // killough 8/2/98: prefer autoaiming at enemies
       int mask = demo_version < 203 ? 0 : MF_FRIEND;
-      if (CRITICAL(direct_vertical_aiming))
+      if (CRITICAL(direct_vertical_aiming) && source->player->lookdir)
       {
         slope = PLAYER_SLOPE(source->player);
       }
diff --git a/src/p_pspr.c b/src/p_pspr.c
index 492db27..3a34021 100644
--- a/src/p_pspr.c
+++ b/src/p_pspr.c
@@ -786,7 +786,7 @@ void A_FireOldBFG(player_t *player, pspdef_t *psp)
          // killough 8/2/98: make autoaiming prefer enemies
          int mask = MF_FRIEND;
          fixed_t slope;
-         if (CRITICAL(direct_vertical_aiming))
+         if (CRITICAL(direct_vertical_aiming) && mo->player->lookdir)
          {
            slope = PLAYER_SLOPE(mo->player);
          }
@@ -856,7 +856,7 @@ static void P_BulletSlope(mobj_t *mo)
   // killough 8/2/98: make autoaiming prefer enemies
   int mask = demo_version < 203 ? 0 : MF_FRIEND;

-  if (CRITICAL(direct_vertical_aiming))
+  if (CRITICAL(direct_vertical_aiming) && mo->player->lookdir)
   {
     bulletslope = PLAYER_SLOPE(mo->player);
   }
```

**Comment by MrAlaux** [comment]
At first glance, I gather that this would apply autoaim if `lookdir != 0`, regardless of Mouselook being enabled or not. I think that'd be a bit annoying; if I had both Mouselook and Direct Vertical Aiming enabled, I'd expect to be in full control of vertical aiming -- it _is_ "direct" after all. In short, I would check for `mouselook` instead of `lookdir`.

**Comment by fabiangreffrath** [comment]
Yes, you are right! However, it should be `mouselook || padlook` I guess.

**Comment by MrAlaux** [comment]
Oh, I just noticed you edited the patch. I can't check it out in detail just now, though, it's getting late. I'll see if I can try it tomorrow.

**Comment by fabiangreffrath** [comment]
Some remarks:

- I have missed some occurrences of `direct_vertical_aiming` in my patch. 
- I'd like to disable the "direct vertical aiming" menu entry if neither `mouselook` nor `padlook` are enabled. 
- I'd like to have two separate variables: the `default_direct_vertical_aiming` config variable and an in-game variable that depends on `
