### ISSUE TITLE
Appimage/Flatpak support for Linux

### ISSUE THREAD

**Issue by CaptainMuskrat** [fabiangreffrath/woof#1135]
I would like to request that "Woof" be packaged for Linux distributions via Appimage and/or Flatpak. This would ensure cross-distro compatibility without the need to cater to them all separately.

**Comment by fabiangreffrath** [comment]
Flatpack again. What do we have to do for this?

**Comment by CaptainMuskrat** [comment]
Again?. I didn't see any other requests of this nature, but maybe I missed it. If this question is asked often I apologise, but I really feel it would be of great benefit for this project.

Here are the links I found for making Flatpaks and Appimages.

https://docs.appimage.org/packaging-guide/index.html

https://docs.flatpak.org/en/latest/first-build.html

https://docs.flatpak.org/en/latest/publishing.html

**Comment by fabiangreffrath** [comment]
Oh, sorry, my reply wasn't targeted directly at you. It is just that I have gone through a similar request for Crispy Doom some weeks ago. 😉 

To get things clear from the beginning: I don't use flatpack, I don't care for it and I don't want to be involved in its development. 

However, if there's anything I can do in this project to make its integration into flatpack easier, I'll be happy to help. But please don't expect me to start maintaining a recipe here or similar.

**Comment by CaptainMuskrat** [comment]
What about Appimages?. Those operate differently than Flatpaks, and could be considered the Linux equivalent of a portable Windows binary.

**Comment by fabiangreffrath** [comment]
Same question, what can I do to make work for packagers easier? I maintain quite a number of packages in Debian, but have neglected the entire flarpack/appimage stuff so far.

**Comment by CaptainMuskrat** [comment]
Well the great thing about Appimages is that they are compatible with all distributions, so rather than trying to maintain support for just one distro (like Debian), you could publish an appimage program and have it work on all of them.

You can check out these other links regarding it as well.

https://youtu.be/Wy63jwjpNg4

https://appimage.github.io/appimagetool/

https://docs.appimage.org/index.html

**Comment by CaptainMuskrat** [comment]
Although perhaps it would be more worthwhile if Woof! included a simple GUI launcher with a possible Appimage, allowing you to select the appropriate IWAD and PWAD you want. That is a feature absent from most if not all source ports, and it would certainly make Woof! stand out even more.

**Comment by CaptainMuskrat** [comment]
After doing some more research, I have come to the conclusion that Flatpaks and Snap packages are not desirable after all. It is best to stick to the package manager or use an Appimage.
