### ISSUE TITLE
Syncronous floor/ceiling motion renders oddly with uncapped fps.

### ISSUE THREAD

**Issue by ManxLoaghtan** [fabiangreffrath/woof#1136]
When the floor and ceiling of a sector move in unison from separate triggers the height appears to vary rapidly with an uncapped fps. The collision of the motion works as expected.
![w35](https://github.com/fabiangreffrath/woof/assets/124502884/8e111c90-35ae-46ab-bf26-2fa3a4807583)
![w60](https://github.com/fabiangreffrath/woof/assets/124502884/7fcd20e9-91b5-4c74-a1d0-f5a10858310b)

**Comment by fabiangreffrath** [comment]
Does this happen with the latest release?

**Comment by ManxLoaghtan** [comment]
Wow, it doesn't. I read the release notes but didn't actually test it yet. Sorry for the false alarm and thank you for preemptively fixing it.
