### ISSUE TITLE
suggestion: small QOL features

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#115]
1. Pistol start like in Crispy
2. "A secret is revealed" message
3. Option to autoload last save on death

All this is preferable with menu options.

**Comment by fabiangreffrath** [comment]
In Crispy, (1) is a command line parameter, (2) is a switch in the menu and (3) is a key combo. I  prefer it that way in order not to clutter the menu and especially keep radically game changing features out of it.

**Comment by rfomin** [comment]
> (3) is a key combo

I didn't know that. I will try to implement (1) and (2).

**Comment by fabiangreffrath** [comment]
Yep, you need to keep holding "Run" during resurrection.

**Comment by fabiangreffrath** [comment]
@rfomin DO you have any plans to work on more features?

**Comment by rfomin** [comment]
Not sure about the key combo for save autoload, I think this option is too well hidden. There are no more plans.

**Comment by fabiangreffrath** [comment]
Yes, I know. I am afraid only very few people actually know this exists in Crispy at all. However, I don't want to add a switch to the menu that permanently changes such a fundamental part of the game.

**Comment by rfomin** [comment]
This could be done better than, for example, in GZDoom. If you do not save at the current level, then the standard reborn, otherwise load the last save. This is what players want most of the time.

**Comment by fabiangreffrath** [comment]
Any idea how the last point can be implemented without cluttering the UI or otherwise losing Vanilla behaviour?

**Comment by rfomin** [comment]
No, I was thinking about the menu option.

**Comment by DwarsYT** [comment]
Would it be worthwhile to include an option to always show the level stats like either Crispy or PrBoom+?

**Comment by fabiangreffrath** [comment]
> Would it be worthwhile to include an option to always show the level stats like either Crispy or PrBoom+?

Sure, that's trivial. But let's please not turn this issue into a collection of random thoughts.

**Comment by fabiangreffrath** [comment]
Let's not misuse this as a general collection of random ideas. If we come up with a nice non-intrusive implementation for resurrect-from-savegame then this deserves a separate thread.
