### ISSUE TITLE
Been getting strange crashes only in Woof

### ISSUE THREAD

**Issue by andrikpowell** [fabiangreffrath/woof#1162]
So in multiple projects I've worked on, players have been complaining about random crashes that only happen exclusively in Woof. Sadly I don't have too much information to give other then what other people have said. I will say that the WADs in question have been tested with DSDA Doom and have never crashed once.

Recently in [Limit Buffet](https://www.doomworld.com/forum/topic/138107-limit-removing-megawad-limit-buffet-forcing-mappers-and-musicians-to-play-by-weird-rules-rc1/), we've only gotten crashes only in Woof:

- MAP36, MAP37, & MAP38 can crash when loading a save when monsters are alive:
- MAP36 at the platform with the Plasma Gun and the Super Shotgun.
- MAP37 at the main area.
- MAP38 seems to do that at the room with the V, VI, & VII switches.

In the MBF21 WAD [Corruption](https://www.doomworld.com/forum/topic/133225-corruption-35-map-mbf21-megawad-now-on-idgames/), when thelamp used Woof to play the WAD, after saving and loading every map, randomly he'd have Woof crash while trying to load a save. This happened on every single map he's been playing.

thelamp mentions that it may be a problem relating to the MUSINFO lump which both WADs use.
I will say that both of these WADs also have MAPs and MUSINFO entries past MAP32.

Hopefully that's enough information to help you figure out what's happening.

**Comment by MrAlaux** [comment]
Sounds like https://github.com/fabiangreffrath/woof/issues/1150. It's already been fixed, but there hasn't been a release including the fix yet.

**Comment by fabiangreffrath** [comment]
Most probably a dup of #1150
