### ISSUE TITLE
Top-centered Level Title widget can be off-center

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1163]
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/5741053039)._

See for yourself:
![woof0000](https://github.com/fabiangreffrath/woof/assets/73968015/2a889ce1-fb2a-4249-b4b0-c63a34ee98d4)

That screenshot was taken in [Scorn](https://www.doomworld.com/forum/topic/136718-scorn-4-new-maps-rc3/). I suspect that it has something to do with DeHackEd-replaced strings.

**Comment by fabiangreffrath** [comment]
I am hoping to get this fixed with the `hu_lib.c` rewrite that I am going to approach pretty soon now.
