### ISSUE TITLE
Boolean variables getting other values than 0 or 1 assigned

### ISSUE THREAD

**Issue by coelckers** [fabiangreffrath/woof#1190]
These 3 can have other values than 0 or 1: 'paused', 'deathmatch', 'r_swirl' and should better be declared as int.
In addition 'hires' gets used for shifting other values, which at least in C++ is warned as undefined behavior (but still compiles correctly.)

**Comment by rfomin** [comment]
Perhaps we should simplify this:
https://github.com/fabiangreffrath/woof/blob/6b17ece27516aefb6e54acf9d8d51c4107eec203/src/doomtype.h#L29-L38
to just
```c
 #ifndef __BYTEBOOL__ 
 #define __BYTEBOOL__  
 typedef enum {false, true} boolean; 
 typedef unsigned char byte; 
 #endif 
```
Probably there is a lot of problems with `bool` type.

**Comment by fabiangreffrath** [comment]
Sure we can do that, good idea. Nevertheless, I'd like to get boolean/int clean anyway. For example, `r_swirl` is a real boolean but declared as an int, whereas `paused` is declared as a boolean but takes values >1.

**Comment by kraflab** [comment]
In dsda-doom we dropped the enum: https://github.com/kraflab/dsda-doom/pull/333

**Comment by coelckers** [comment]
I don't think that evading the issue by declaring boolean in a way that's always an enum is a good idea.  After all, a variable's type tells us something about how it is used, and we'd lose that if they are made interchangeable. Also, do we have any guarantee that enum sizes won't ever change?

Using C's real bool type would certainly be best, but it'd also require some review that they are properly used everywhere, of course. I didn't get any warnings for other booleans but that's not a guarantee that some place is soing something wrong with them.

**Comment by rfomin** [comment]
> Using C's real bool type would certainly be best, but it'd also require some review that they are properly used everywhere, of course. I didn't get any warnings for other booleans but that's not a guarantee that some place isn't doing something wrong with them.

The savegame code assumes that `boolean` is a 4-byte integer, although at first glance there is no problem (`bool` is simply automatically converted to `int`).
Anyway, it seems that `bool` is not that useful in pure C, for example, no library function returns `bool`.
