### ISSUE TITLE
Headphones mode remains enabled when switching to PC Speaker

### ISSUE THREAD

**Issue by ceski-1** [fabiangreffrath/woof#1206]
Using the latest action.

1. Start with this:
```
Sound Module: OpenAL 3D
Headphones Mode: No
```
2. Then switch to headphones mode:
```
Sound Module: OpenAL 3D
Headphones Mode: Yes
```
3. Now switch to PC speaker:
```
Sound Module: PC Speaker
Headphones Mode: Yes (Grayed Out)
```
The PC speaker sound will be muffled instead of clear. Example:

https://github.com/fabiangreffrath/woof/assets/56656010/25e33ec7-71af-4f08-a805-162d872cd13c

I can't troubleshoot it at the moment. I can look at it later or if you don't mind taking a look as well @rfomin, thank you.

**Comment by fabiangreffrath** [comment]
Maybe `I_PCS_ReinitSound()` should call `I_OAL_ReinitSound()` at some point?

**Comment by rfomin** [comment]
> Maybe `I_PCS_ReinitSound()` should call `I_OAL_ReinitSound()` at some point?

Yes, I think so. Done this in https://github.com/fabiangreffrath/woof/pull/1207
