### ISSUE TITLE
Native ALSA MIDI backend for Linux

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#1209]
Let's port over the backend from prboom-plus.

**Comment by rfomin** [comment]
I haven't looked into it too much, but ALSA seems low-level and a bit complicated. It doesn't have a MIDI player, but it does have a MIDI sequencer, which I recommend using: https://www.alsa-project.org/alsa-doc/alsa-lib/seq.html.

Our implementation is different from PrBoom+. Perhaps we should implement our own sequencer at this point and synchronize features between Win, macOS, Fluidsynth and OPL backends in the style of ZMusic. This will require some work.

**Comment by fabiangreffrath** [comment]
Ah, I see. I hoped it would be a bit more straightforward.

**Comment by fabiangreffrath** [comment]
We don't have the `MIDI_GenerateFlatList()` and `MIDI_spmc()` APIs in our `midifile.c`, and apart from this porting should be rather straight.

**Comment by rfomin** [comment]
> We don't have the `MIDI_GenerateFlatList()` and `MIDI_spmc()` APIs in our `midifile.c`, and apart from this porting should be rather straight.

That's right, these functions together with `alsa_render()` (or `fl_render()`, etc.) implement the MIDI sequencer in PrBoom+. We can simply copy these functions for the ALSA backend, but it may be worth implementing our own sequencer that can be used in the `i_winmusic.c`, `i_macmusic.c` and other modules. This way we will reduce code duplication and support `i_winmusic.c` features in other modules - MIDI loops, EMIDI support. Although I can't promise I'll do it quickly.

**Comment by fabiangreffrath** [comment]
So, `i_winmusic.c` already has its own sequencer and we could factor that out of this file and use it consistently across all the other MIDI backends?

**Comment by rfomin** [comment]
> So, `i_winmusic.c` already has its own sequencer and we could factor that out of this file and use it consistently across all the other MIDI backends?

No, there is no sequencer in `i_winmusic.c`, it uses the `midiStream()` API. It was simpler at the time, I didn't plan that we would end up with an almost ZMusic analog. It's not that complicated, maybe we can adapt it to each module with minor changes.

**Comment by fabiangreffrath** [comment]
Pardon my ignorance, but obviously I don't have a clue of how MIDI works (and I'm glad that you @rfomin and @ceski-1 know what you are talking about 😉).

So, currently we don't have a MIDI sequencer, but rely on the ones "built-in" into Fluidsynth and Windows' `midiStream()` API (how about OPL), right? This means, however, that we won't have feature parity among the different implementations. And now the difference is that ALSA does not provide the "player" part, because it merely hands over the MIDI to an actual (or virtual) device, but it has its own sequencer. And the additional functions `MIDI_GenerateFlatList()` and `MIDI_spmc()` in prboom's `midifile.c` are required as "glue" between the MIDI file format and the event handling in the sequencer.

Does this make sense?

**Comment by rfomin** [comment]
> Does this make sense?

Yes, it does. Also, PrBoom+ has some infrastructure from where `alsa_render()` is called, so we might need an SDL thread if you want to copy the PrBoom+ implementation.

**Comment by rfomin** [comment]
> So, currently we don't have a MIDI sequencer, but rely on the ones "built-in" into Fluidsynth and Windows' `midiStream()` API (how about OPL), right?

Only Windows has the `midiStream` API and all the unique features. Fluidsynth and macOS have their own MIDI players, OPL is just copied from Chocolate.

Both Fluidsynth and macOS have stream-like sequencer APIs, but we still have to modify OPL. I don't know at what level that would be easier yet.

**Comment by rfomin** [comment]
> What do you think about the portmidi alternative?

Hard to say, I don't use Linux much. The repository doesn't look very active: https://github.com/PortMidi/portmidi Anyway, it's almost the same work, check out portmidiplayer.c in PrBoom+.

**Comment by fabiangreffrath** [comment]
Yes, indeed. Hm, I was hoping we could add this as the "native MIDI player on Linux" solution and it would align nicely with the native Windows/MacOS, Fluidsynth and OPL alternatives. 😞

**Comment by inf78** [comment]
I'm not a coder and I know nothing about MIDI stuff either so it may come up ignorant, but please, no Zmusic clone.
I love Woof!, just as I liked MBF. It's simple yet powerful, compiles like butter and just works.
I guess most people know Doom's sound department through its OPL emulation anyway. It's like those 640KB, it should be enough for everyone. :D

**Comment by rfomin** [comment]
GZDoom+ZMusic may be difficult to compile, but conceptually it's not a bad library. In any case, I assure you that if we implement what is proposed here, compilation will not be complicated and most users will not notice anything, except some retro MIDI lovers 😄

**Comment by inf78** [comment]
Hehe, great!

**Comment by rfomin** [comment]
Source of the `aplaymidi` tool that uses built in ALSA sequencer: https://github.com/alsa-project/alsa-utils/blob/master/seq/aplaymidi/aplaymidi.c I think it might be useful for our implementation.
