### ISSUE TITLE
Allow renderer to be configured?

### ISSUE THREAD

**Issue by ceski-1** [fabiangreffrath/woof#1210]
It could be a decent performance gain for certain configurations:
```
Desktop: i9-9900K, RTX 3080, 2560x1440, Win10
  direct3d      1453 fps
  direct3d11    1780 fps
  direct3d12     977 fps
  opengl        1073 fps
  opengles2     1566 fps

Laptop: i7-5600U, Intel HD 5500, 1920x1080, Arch
  opengl         351 fps
  opengles2      363 fps

setup: doom2 map01, use_vsync 0, widescreen 1, otherwise default woof.cfg
```
Sample code:
```diff
diff --git a/src/i_video.c b/src/i_video.c
index 97af1490..2621447c 100644
--- a/src/i_video.c
+++ b/src/i_video.c
@@ -1414,8 +1414,17 @@ void I_InitGraphics(void)
     I_InitGamma2Table();
 
     I_InitVideoParms();
+
+    SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengles2"); // change me
+
     I_InitGraphicsMode();    // killough 10/98
 
+    {
+        SDL_RendererInfo rinfo;
+        SDL_GetRendererInfo(renderer, &rinfo);
+        I_Printf(VB_DEBUG, "%s", rinfo.name); // did it work?
+    }
+
     M_ResetSetupMenuVideo();
 }
```
Renderers are listed [here](https://github.com/libsdl-org/SDL/blob/SDL2/include/SDL_hints.h#L1410-L1430).

**Comment by rfomin** [comment]
There is an environment variable `SDL_VIDEODRIVER`. I think we can add a config option.

In my experience, default Direct3D9 works best on Windows. For example, screenshots don't work on some backends. Besides, it's still very fast, there's not much difference between 1500 FPS and 1300 FPS, compatibility is more of a priority in my opinion.

**Comment by ceski-1** [comment]
Right, the possibility of introducing new bugs due to SDL handling renderers inconsistently would completely outweigh any benefit. I'm not even sure a config only option is worth risking.
