### ISSUE TITLE
Broken level stats widget in grindfest.wad multiplayer demo

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#1227]
The level stats widget disappears at about 2:30 in [gf32tc2218.zip](https://dsdarchive.com/files/demos/grindfest/82830/gf32tc2218.zip) demo. WAD: [grindfest.zip](https://dsdarchive.com/files/wads/doom2/4411/grindfest.zip)
Command line: `woof -file grindfest.zip gf32tc2218.zip -playdemo gf32b2218 -skipsec 2:25`

It works in Woof 11.3.0
![image](https://github.com/fabiangreffrath/woof/assets/5077629/55bbaad3-0c08-4c7b-b894-397ae116ba33)

Woof 12.0.0
![image](https://github.com/fabiangreffrath/woof/assets/5077629/87ae8b81-a9ae-4080-8bc7-fa526c9c5e4c)

**Comment by fabiangreffrath** [comment]
That's when `strlen(hud_monsecstr) >= HU_MAXLINELENGTH`.

**Comment by rfomin** [comment]
> That's when `strlen(hud_monsecstr) >= HU_MAXLINELENGTH`.

But it seems that in Woof 11.3.0 the length of `hud_monsecstr` is also `80`. Have we just not checked this before? I haven't looked into the new HUD code much.

**Comment by fabiangreffrath** [comment]
Well, there is a range checking bug in `hu_lib:add_char_to_line()`:

```patch
--- a/src/hu_lib.c
+++ b/src/hu_lib.c
@@ -100,7 +100,7 @@ void HUlib_clear_all_lines (hu_multiline_t *const m)
 
 static boolean add_char_to_line(hu_line_t *const t, const char ch)
 {
-  if (t->len == HU_MAXLINELENGTH)
+  if (t->len == HU_MAXLINELENGTH - 1)
     return false;
   else
   {
```

but the underlying bug is that we shouldn't let `hud_monsecstr[]` overflow in the first place:

```patch
--- a/src/hu_stuff.c
+++ b/src/hu_stuff.c
@@ -1158,7 +1158,8 @@ static void HU_widget_build_monsec(void)
   }
   else
   {
-    sprintf(hud_monsecstr + offset,
+    snprintf(hud_monsecstr + offset,
+      HU_MAXLINELENGTH - offset,
       " \x1b%c%d%% \x1b%cI \x1b%c%d/%d \x1b%cS \x1b%c%d/%d",
       kills_percent_color, kills_percent,
       '0'+CR_RED, items_color, items, totalitems,
```

**Comment by fabiangreffrath** [comment]
The actual maximum line length for a single-lined widget was actually `2001`!

https://github.com/fabiangreffrath/woof/blob/cfb6df4bff351c348a561fbfc8e59ff55cc6c397/src/hu_lib.h#L62

**Comment by rfomin** [comment]
> but the underlying bug is that we shouldn't let hud_monsecstr[] overflow in the first place:

Maybe we should use `M_snprintf` instead of `spintf`?

> The actual maximum line length for a single-lined widget was actually 2001!

Good, '80' seems small. The level stats widget can be long.

**Comment by fabiangreffrath** [comment]
So, maybe `100` bytes then, or even `160`?

**Comment by rfomin** [comment]
> So, maybe `100` bytes then, or even `160`?

I like `160`.
