### ISSUE TITLE
suggestion: support for MUSINFO

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#123]
I want to integrate MUSINFO support from Crispy. It seems the only non-trivial part is the extension to savegame.

**Comment by fabiangreffrath** [comment]
Yes, extending the savegame is the tricky part. There is a slot in the MBF savegame format to store the choice of the IDMUS cheat. However, it only takes a single number which corresponds to the index in the `S_music[]` array. But, with MUSINFO you can play music from any arbitrary lump, so we'll have to store the music lump *name* somehow (lump number may change across engine starts).

**Comment by rfomin** [comment]
Can we implement Crispy's solution and write more information at the end of the file?

**Comment by fabiangreffrath** [comment]
That's quite an invasive change as you might imagine. Though at least we won't need to implement Crispy's check for the loaded map coming from the same PWAD, as MBF already had this. But I agree, this is the proper way forward.

I have already extended the current savegame format to write the accumualted level time at the end of the file, but that doesn't scale well as other extensions follow, of course.
