### ISSUE TITLE
Suggestion:  Mirrored Decorations Option?

### ISSUE THREAD

**Issue by Big-the-Fat** [fabiangreffrath/woof#1232]
Would it be possible to add an option to mirror decorations in the same way we can choose to mirror corpses?  I don't think there are any deco's that would goofy and it would add variety to the visuals.  :)

**Comment by fabiangreffrath** [comment]
Hm, I'm not sure if we should change even more random stuff. What do the others think?

**Comment by rfomin** [comment]
Decorations are often placed very carefully by map makers, we can ruin the authors' intent.

**Comment by fabiangreffrath** [comment]
Yep, that was my sentiment as well.

**Comment by fabiangreffrath** [comment]
Thank you for the suggestion!
