### ISSUE TITLE
UMAPINFO handling doesn't end the game properly on secret exits.

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/woof#1247]
When a map has `endgame`, `endcast` etc. defined for a level, DSDA-Doom and PrBoom+UM will still end the game on a secret exit, whereas Woof will take you to the defined secret level. I assume the PrBoom+ behaviour is the correct one.

Here is a testmap, and the UMAPINFO copied and pasted:

```
map MAP01
{
	levelname = "test"
	levelpic = "CWILV00"
	label = clear
	nextsecret = "MAP31"
	exitpic = "INTERPIC"
	intertext = "This is the normal exit.",
		"You should see the cast call next."
	intertextsecret = "This is the secret exit.",
		"You should see the cast call next,",
		"and not go to MAP31."
	endgame = true
	endcast = true
}
```

[umap_exit.zip](https://github.com/fabiangreffrath/woof/files/13245235/umap_exit.zip)

Eternity also behaves like PrBoom+UM, GZDoom doesn't (goes to MAP02 on secret?) but I think it has known UMAPINFO issues anyhow.

**Comment by rfomin** [comment]
I'm not sure which behavior is correct. PrBoom+UM implementation has bugs. If someone wants to end the game on this level, why put a secret exit?

**Comment by kitchen-ace** [comment]
>If someone wants to end the game on this level, why put a secret exit?

In the map I encountered this on, it was because the author wanted an alternate ending text screen.   
https://www.doomworld.com/forum/topic/141192-the-parasite-of-good-will-cl9-rc1/

**Comment by rfomin** [comment]
OK, then we need to fix this for compatibility. Thanks.

**Comment by fabiangreffrath** [comment]
Could this be the culprit?

https://github.com/fabiangreffrath/woof/blob/9ede0ab4718c0b27951bcf80c48d0f6a163ec0ca/src/f_finale.c#L256

**Comment by rfomin** [comment]
> Could this be the culprit?

Yes, it was changed in https://github.com/fabiangreffrath/woof/pull/547, I think we should remove the check now that we have an interesting use case.

**Comment by fabiangreffrath** [comment]
Would you revert that commit?

**Comment by rfomin** [comment]
> Would you revert that commit?

I want to remove the `!secretexit' check. What do you think?

**Comment by fabiangreffrath** [comment]
If that's what PrBoom+ does, yes.

**Comment by fabiangreffrath** [comment]
This should be the corresponding line in PrBoom+. No `!secretexit` check.

https://github.com/coelckers/prboom-plus/blob/969515162c5aebea4ad7a125ee178dcad3d576ad/prboom2/src/f_finale2.c#L122
