### ISSUE TITLE
UMAPINFO names are off centre on intermission screen

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/woof#1250]
If a map has a UMAPINFO name and no graphic, Woof draws the level name off-centre on the intermission screen. Any rendering options I tried (widescreen, high-res) don't change this.

I don't know if the code was adapted from PrBoom+UM (or DSDA-Doom) but those ports draw the start of the graphic at the same place that Woof does but have wider spacing between letters.

Test map: 
[umapname.wad.zip](https://github.com/fabiangreffrath/woof/files/13304135/umapname.wad.zip)

Woof: (checkerboard to show how the title extends too far left)
![woof0001](https://github.com/fabiangreffrath/woof/assets/47063032/f255f576-3d44-47f7-8931-5ed4f65d24c7)

DSDA-Doom:
![doom01](https://github.com/fabiangreffrath/woof/assets/47063032/b1e8cf88-f501-4f41-a4ba-d19a9947690d)

**Comment by fabiangreffrath** [comment]
This looks like the map names start at the right horizontal position, but the string is printed with some condensed spacing. Probably only a matter of printing function selection.
