### ISSUE TITLE
Weird visual artifacts in the middle of the viewport

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1259]
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/6848966764)._

As the title says. Take a look:
![Untitled](https://github.com/fabiangreffrath/woof/assets/73968015/91f3ede0-0503-4770-9f58-259c88f5bf4f)

This is with Hires and Widescreen enabled, and Smooth Pixel Scaling disabled. If I toggle any of those settings, the artifacts disappear.
If I exit fullscreen and resize the window, the artifacting may still manifest depending on the size, albeit differing slightly as the size varies. Worth noting that, in fullscreen, the game window scales to 1363x768 on my display with the aforementioned settings; maybe the uneven resolution is the culprit?

I've noticed this quite a while ago, but never bothered with it because it's hardly noticeable.

**Comment by fabiangreffrath** [comment]
May very well be a result of non-integer scaling factors and application of aspect ratio correction.

**Comment by rfomin** [comment]
Try using `SDL_HINT_RENDER_DRIVER` to test with OpenGL or other Direct3D versions.

**Comment by MrAlaux** [comment]
> Try using `SDL_HINT_RENDER_DRIVER` to test with OpenGL or other Direct3D versions.

I used code from https://github.com/fabiangreffrath/woof/issues/1210#issue-1906007426 to verify if the changes were being applied.

The following seem to be unsupported, falling back to `direct3d`:

- `direct3d9` (not sure if it's meant to be the same as `direct3d` anyways);
- `direct3d10`;
- `direct3d12` (expected to not work, considering my old machine);
- `opengles`;
- `opengles2`.

The following work, with various results (all tested in fullscreen):

`direct3d11` has the same artifacting as `direct3d`.
![rtdirect3d11 - copia](https://github.com/fabiangreffrath/woof/assets/73968015/1470ce06-bcc0-4e94-b57b-7ef8f764c1ed)

`opengl` has slightly different artifacting:
![rtopengl - copia](https://github.com/fabiangreffrath/woof/assets/73968015/d243d9e4-5ea1-4f3c-a8df-529c0e324da5)

`software` seems to get rid of the artifacting, but at a great performance cost and with visual lag despite the game reporting >60 FPS:
![rtsoftware - copia](https://github.com/fabiangreffrath/woof/assets/73968015/ea58ed9a-9326-4ae5-a345-51d9546a868c)

**Comment by rfomin** [comment]
So this is a GPU scaling issue. Since we have "Smooth Pixel Scaling" enabled by default, I don't think anything needs to be done about it.

**Comment by fabiangreffrath** [comment]
Right, this doesn't seem to be under our/ the port's control.
