### ISSUE TITLE
voxel-capable builds crash when using DSDHACKED

### ISSUE THREAD

**Issue by liPillON** [fabiangreffrath/woof#1263]
I was toying around with the latest master branch build and loaded SD21 by @MrAlaux just for fun.
Usually I autoload a map I've made to showcase/detect all sprite replacements made by a pwad.
When warping to this map, Woof crashes without any error message.

The last working build is [this](https://github.com/fabiangreffrath/woof/actions/runs/6824488296), right before voxels support was [merged](https://github.com/fabiangreffrath/woof/actions/runs/6833523760) in the master branch.

Admittedly, this could be an issue with my map - though that would not explain why older builds work just fine.
I guess that having all monsters/pickups/decorations visible right from the player1 starting position might have something to do with the crash.

Steps to reproduce:
1. download one of the affected build and unzip it to a folder
2. download [MINIWADM](https://www.doomworld.com/forum/topic/136409/) and extract MINIWAD2.WAD (I use this for testing, but the crash happens with DOOM2.WAD too)
3. download [my "showroom" map](https://github.com/fabiangreffrath/woof/files/13389689/MAP88.zip) 
5. download [SD21](https://www.doomworld.com/forum/topic/133318) Classic variant (I tested also the full-featured one and it crashes too)
6. start a command prompt session from the folder where the woof binaries are
7. launch the game `woof.com -iwad MINIWAD2.WAD -file MAP88.ZIP SD21-Classic.zip -CompLevel 21 -warp 88`

The crash might happen either as soon as the map has been loaded, or after a couple of seconds.
If the warp command line parameter is omitted, the game loads up fine but crashes after using the IDCLEV88 cheat.

**Comment by rfomin** [comment]
Do you use voxels? DSDHAKED does not currently work with voxels.

**Comment by fabiangreffrath** [comment]
We should add a check for `spr < NUMSPRITES` and `frame < MAX_FRAMES` to `VX_ProjectVoxel()`. Or fix it for DEHACKED. 😛

**Comment by rfomin** [comment]
Yes, the voxels have not been finalized yet.
TODO:
1. `num_sprites` for DSDHACKED.
2. Rotation of items, specifically weapons.
3. Dynamic change of `VX_MAX_DIST`.

**Comment by liPillON** [comment]
> Do you use voxels? DSDHAKED does not currently work with voxels.

Nope, only the pwad in the command line and nothing in the autoload folders.

**Comment by rfomin** [comment]
> Nope, only the pwad in the command line and nothing in the autoload folders.

There is still an incorrect check in `VX_ProjectVoxel()` in DSDHACKED case. Will be fixed later.

**Comment by liPillON** [comment]
yeah I understand this is not ready for primetime yet, take your time

**Comment by fabiangreffrath** [comment]
> 1. `num_sprites` for DSDHACKED.

This means we'll have to dynamically allocate `all_voxels[][]`.

> 2. Rotation of items, specifically weapons.

Yes, this also bothered me. I'd suggest not to rotate them with the player view (or not rorate them *that much* if this makes sense). I have read a suggestion somewhere to align them to the nearest linedef on the map when they are spawned, which sounds quite appealing.

> 3. Dynamic change of `VX_MAX_DIST`.

I guess a dynamic adjustment based on `num_visvoxels` should work. I'm afraid FPS is too fragile as a measure here (i.e. will pop back and forth if reducing the number of rendered visvoxels suceeds to  increase the FPS above the threshold, causing the engine to render more visvoxels further away, which will then in turn push FPS below the threshold, etc.).

**Comment by rfomin** [comment]
> Yes, this also bothered me. I'd suggest not to rotate them with the player view (or not rorate them _that much_ if this makes sense). I have read a suggestion somewhere to align them to the nearest linedef on the map when they are spawned, which sounds quite appealing.

I suggest to always rotate them (only weapons) like in Quake/ZDoom. I think they were made for that.

**Comment by liPillON** [comment]
> I suggest to always rotate them (only weapons) like in Quake/ZDoom. I think they were made for that.

rotate as in "always face the player" or as in "spinning in place" ?

I've noticed that in cheello's latest 2.1 revision the chainsaw and the rocket launcher seem to be modeled using a different "starting angle".
This means that with the current Woof implementation (rotate to face the player) the player sees the side of a weapon, except for the CS and the RL which are seen from the front.
In GZDoom this is not/less noticeable, because the weapons are always spinning in place.

**Comment by fabiangreffrath** [comment]
> "spinning in place" ?

Now that would be cool! 🤔

**Comment by rfomin** [comment]
> > "spinning in place" ?
> 
> Now that would be cool! 🤔

All we need to do is change these angles: https://github.com/fabiangreffrath/woof/blob/7024ffcef591505b89a65c299788a56f2f48feb2/src/r_voxel.c#L511-L520

**Comment by fabiangreffrath** [comment]
Yes, and make them functions of `leveltime`.
