### ISSUE TITLE
Remote key doors and other key actions aren't coloured on automap

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/woof#1286]
Normal doors that need a key are coloured on the automap, but switches, Boom generic linedefs, etc. aren't. Tested with a new config and various automap settings including the presets.

example file:
[key.wad.zip](https://github.com/fabiangreffrath/woof/files/13467963/key.wad.zip)

**Comment by fabiangreffrath** [comment]
Oh, wow! I'm pretty confident we didn't introduce this bug, so this must be as old as Boom itself.

**Comment by kitchen-ace** [comment]
Heh you're right, the key doors don't display properly in boom.exe. 
PrBoom+ must have fixed it at some point as it's not present there or in dsda-doom.

**Comment by fabiangreffrath** [comment]
I see. This is because we only check two-sided lines for being locked with colored keys. This was changed in PrBoom+ some 23 years ago:

https://github.com/coelckers/prboom-plus/commit/caa805a037aee79e08a0dd1d269b80dbc8d02694?diff=unified
