### ISSUE TITLE
Demos set complevel that can persist when loading a game.

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/woof#1293]
-Start a new game without a -complevel switch and a default compatibility of MBF21 (or something other than Vanilla.)

-Save and end the game. You don't need to exit Woof.

-Let the internal Doom 2 demo play. It doesn't matter if it finishes or not.

-Load the game you saved.

-You will now be playing in a vanilla complevel.

Example map with a generic Boom door in case it's helpful for testing:
[cltest.zip](https://github.com/fabiangreffrath/woof/files/13493865/cltest.zip)

Expected behaviour IMO is that the complevel is saved along with the save file. If that isn't feasible, loading a game should use the default compatibility.

**Comment by rfomin** [comment]
> Expected behaviour IMO is that the complevel is saved along with the save file.

We support old saves that were created before the complevel feature, so we support the ability to load saves with different complevel. Usually nothing bad happens.

We can force load complevel from newer saves (after Woof 6.0.0).

**Comment by rfomin** [comment]
> Yes, I think you should always continue a loaded game with the exact same complevel that was active when you saved it.

Done in https://github.com/fabiangreffrath/woof/pull/1294/commits/bd567bc1c5749a66feadfea9195dade4522928dc
