### ISSUE TITLE
more reasonable defaults

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#1297]
As stated elsewhere, I'd like to keep users away from using the menu at all. The following are some of the settings that I always change when I first run the port with a fresh config:

* widescreen 1
* hud_secret_message 1
* sts_always_red 0

Some more debattable changes include:

* colored_blood 1
* flipcorpses 1
* fuzzcolumn_mode 1
* sts_pct_always_grey 1

And there are even some more...

**Comment by rfomin** [comment]
> - sts_always_red 0
> - sts_pct_always_grey 1

I am strongly against this! Doom's vanilla UI is perfect, why people want to change it I don't understand 😄 

> - colored_blood 1
> - flipcorpses 1

I like them, but I think we don't need to stray too far from vanilla.

**Comment by fabiangreffrath** [comment]
Perfect, that's why I put it up for discussion. 😉

**Comment by rfomin** [comment]
If we are going to enable `widescreen`, I think we should enable `st_solidbackground`. @fabiangreffrath Have you changed your mind about official widescreen resources?https://bethesda.net/en/game/doom-widescreen-mods

**Comment by ceski-1** [comment]
> Of those settings, the only one I would change to the default is having the secret message on.

This seems reasonable too. And the survey might be a good idea.

**Comment by fabiangreffrath** [comment]
> If we are going to enable `widescreen`, I think we should enable `st_solidbackground`. 

Okay, we can do this!

> @fabiangreffrath Have you changed your mind about official widescreen resources https://bethesda.net/en/game/doom-widescreen-mods

Nope. 😝

**Comment by ceski-1** [comment]
> Okay, we can do this!

Someone out there probably prefers the ugly green rocks and some wads replace that texture with something that looks nicer than a flat color. I don't really care, but something to consider.

**Comment by fabiangreffrath** [comment]
Alright, but there is consent about the "Secret Revealed" message?

**Comment by ceski-1** [comment]
> Do others have other options that they always change by principle?

I used PrBoom+ long enough to expect `autorun` enabled by default in other sources ports.

**Comment by fabiangreffrath** [comment]
> Weapon Attack Alignment: Centered

I often have this enabled as well, but if it's disabled it takes some time until I realize something feels odd. Probably not to be enabled by default, right?

**Comment by rfomin** [comment]
> > Weapon Attack Alignment: Centered
> 
> I often have this enabled as well, but if it's disabled it takes some time until I realize something feels odd. Probably not to be enabled by default, right?

Ok, it's not that important.

**Comment by fabiangreffrath** [comment]
How about
* map_secret_after 0

**Comment by fabiangreffrath** [comment]
Smooth lines look awful with the ZDoom color preset. Flashing keyed doors are a bit non-Vanilla, not?

**Comment by fabiangreffrath** [comment]
> Perhaps we should remove the smooth lines then. They are not needed with any resolution.

How is this possible?

> Maybe then more users will become aware of this feature. I never knew about it before the feature request 😄

Same could be said about any other feature. 😉 If in doubt, stay with Vanilla defaults.

**Comment by ak-988** [comment]
Maybe porch flash emulation? It's true to vanilla in a way, and maybe the player who now chooses to disable widescreen would enjoy it. At the same time, people might just think 4:3 mode is bugged.

If nothing else, the description in the CFG is accurate but pretty cryptic. Maybe add some description like "Palette tint affects unused screen borders"?

**Comment by ceski-1** [comment]
> Smooth lines look awful with the ZDoom color preset. Flashing keyed doors are a bit non-Vanilla, not?

Smooth lines can be nice but the algorithm seems to assume the background is black. So it probably needs some changes.

> Maybe porch flash emulation?

I like this but the current implementation, which is the same in Chocolate, is too much when using a widescreen monitor. It should be a thin border like it was on a CRT monitor. If that tweak was made in Chocolate and Woof, I'd use it all the time. This was discussed in a Chocolate issue at some point.

**Comment by fabiangreffrath** [comment]
> Smooth lines can be nice but the algorithm seems to assume the background is black. So it probably needs some changes.

But then they necessarily perform bad in overlay mode.

**Comment by ceski-1** [comment]
> But then they necessarily perform bad in overlay mode.

Right, it needs to sample the actual pixels around the line. I haven't looked at the algorithm to see what changes that requires.

**Comment by fabiangreffrath** [comment]
I get that we don't probably need this anymore with increased resolution, but the lines will get thinner and thinner. 🤔

**Comment by fabiangreffrath** [comment]
> `demobar 1`

I set this too, makes sense to me. Should we probably introduce a switch to only show this for single demos and not for the demo reel?

> `show_endoom 2`

I'm afraid that this stands in peoples' way, s it requires an extra click at the end.

> `linearsky 1`

Probably makes sense if we enable widescreen rendering by default.

> `smoothlight 1` 

This won't work. I know that speedrunners sometimes have to rely on exact pixel colors to align for certain glides.

> `full_sounds 1`

May sound odd if enabled unexpectedly.

> `automaprotate 1`

I prefer the static automap.

**Comment by fabiangreffrath** [comment]
> I like this but the current implementation, which is the same in Chocolate, is too much when using a widescreen monitor. It should be a thin border like it was on a CRT monitor. 

According to https://github.com/chocolate-doom/chocolate-doom/issues/832 it should be 8 pixels wide - more or less. 😉

**Comment by mikeday0** [comment]
I might suggest:
* use_vsync 0
* fpslimit 200

I think these are the current GZDoom defaults.

**Comment by rfomin** [comment]
> * use_vsync 0
> * fpslimit 200

I like the vsync enabled. Until fast mouse polling is implemented, high refresh rate is not that interesting. Plus most people have 60 Hz monitors.

**Comment by fabiangreffrath** [comment]
Yes, me too. I think for the time being, `use_vsync 1` is the most reasonable default.

**Comment by pas-de-2** [comment]
I would like to state for the record that I think autorun is a bad default for the IWADs in Doom.

**Comment by pas-de-2** [comment]
`disk_icon 0`
IO is so fast on modern PCs that this thing looks almost like a menu glitch if you aren't already aware that it's supposed to be a floppy disk icon
`autorun 0`
I maintain that the IWADs were not designed for Always Run and do not play well with it enabled

**Comment by fabiangreffrath** [comment]
> `disk_icon 0` IO is so fast on modern PCs that this thing looks almost like a menu glitch if you aren't already aware that it's supposed to be a floppy disk icon 

I can clearly see it in Eviternity, even on my rather modern PC. I like it, it's one more detail to maintain the nostalgic feel.

> `autorun 0` I maintain that the IWADs were not designed for Always Run and do not play well with it enabled

Well, then it's as easy to disable it as it is to enable it. But given that most of us don't focus on playing the IWADs anymore, I think having autorun enabled is the more reasonable default.
