### ISSUE TITLE
MUSINFO fails when loading saves

### ISSUE THREAD

**Issue by DRON12261** [fabiangreffrath/woof#1308]
Hi. I'm in the process of finalizing one large map, and have found a nasty bug with MUSINFO that breaks the game experience on the map and is reproducible in Woof! / Nugget Doom / Cherry Doom (was also in Doom Retro, but had a slightly different problem there).

MUSINFO crashes when loading saves. I made an example wad where the bug is stable, the steps are approximately as follows:
1. There are 3 rooms in the following order - Brown with default soundtrack of level D_RUNNIN, Green with a trigger for the second track D_STALKS (in MUSINFO number 1) and Gray with a trigger for the third track D_COUNTD (in MUSINFO number 2).
2. Go into the green room, trigger the second track, and save.
3. Go into the gray room, trigger the third track, and try to either kill yourself (rocket launcher for this) or just load save in the green room.
4. After loading save again go into the gray room and try to trigger the third track, but this time it's as if the actor with the number 14102 on the map disappears and the track will never change again and will play the one that triggered in the green room.

Something like this.

[MUSINFBG.WAD](https://drive.google.com/file/d/1SdQyghZrGO6V7Gp3WHwNJ7cW2tXgqOy-/view?usp=sharing)

**Comment by DRON12261** [comment]
I didn't mean crashing the game, but the MUSINFO mechanism. Sorry if I was a bit misleading, English is not my native language. I recorded a video for clarity. At timecodes 0:27 and 0:52 the track should have obviously changed, but it didn't, the MUSINFO logic stopped working. I mean this.

https://youtu.be/8jiAspj6fDY

**Comment by fabiangreffrath** [comment]
Hm, the issue may be that `musinfo.mapthing` is still pointing to the MUSINFO mobj in the third room, whereas the music of the MUSINFO mobj in the second room is loaded. So, entering the third room again will not trigger a new song, because `lastmapthing == mapthing` and entering the second room will not trigger a new song, because `mus_playing->lumpnum == lumpnum`.
