### ISSUE TITLE
Eviternity II crashes woof with no error message

### ISSUE THREAD

**Issue by Enator18** [fabiangreffrath/woof#1317]
When trying to launch Eviternity II with woof, it simply does not load. No error message is given however the following warnings are seen in console
R_InitSprites: No patches found for SP06 frame B
R_InitSprites: No patches found for SP06 frame C
R_InitSprites: No patches found for SP06 frame D
R_InitSprites: No patches found for SP09 frame B
R_InitSprites: No patches found for SP09 frame C
R_InitSprites: No patches found for SP09 frame D
R_InitSprites: No patches found for SP11 frame B
R_InitSprites: No patches found for SP11 frame C
R_InitSprites: No patches found for SP11 frame D
R_InitSprites: No patches found for SP17 frame B
R_InitSprites: No patches found for SP17 frame C
R_InitSprites: No patches found for SP17 frame D
R_InitSprites: No patches found for SP30 frame \

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/626021e0eb3a54e18c2f5c72cf13e6278717ed7e

**Comment by Enator18** [comment]
ah nice
