### ISSUE TITLE
[Feature] Level stats also "On HUD" only

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#1322]
I'd appreciate if the "Show Level Stats" widget had an option to show them on the HUD (i.e. non-automap screen) only as well. Since there's already a setting for "On Automap" and "Always", this last choice should cover all needs (such as mine, as I think having the widget on both displays is kinda redundant, and I prefer to see it just where the action happens).

(Showing the widget only on the "action screen" was possible in v12.0 and earlier, but got apparently lost, changed or accidentally removed during a more recent update.)

**Comment by fabiangreffrath** [comment]
With the commit below, I have combined the Level Stats on Automap and on HUD features into a single switch with choices "Off", "On Automap" and "Always". Honestly, I don't see why "Always but not on Automap" should be a desirable choice apart from "it's redundant". :shrug:

https://github.com/fabiangreffrath/woof/commit/780a6c4eccd5a9aa442053de0e2cc9eecee6093c

**Comment by NightFright2k19** [comment]
Alright, so I guess it was done on purpose, it seems. Looks as if there are some less pleasant side effects coming along with this recent "simplification spree".

**Comment by ceski-1** [comment]
> maybe at least the position of the stats on the automap could be reconsidered

Would a custom [woofhud.lmp](https://github.com/fabiangreffrath/woof/blob/master/docs/woofhud.md) do what you want?

```
hud 0
time topleft
stats topleft
fps topright
coords topright
title bottomleft
```

**Comment by fabiangreffrath** [comment]
I'm seriously considering to add this setting back. First, because it was actually possible to set it up like this in the past. Second, because there is at least one user who sincerely asked to bring it back. And implementation wise is just trivial anyway.

**Comment by fabiangreffrath** [comment]
> Maybe the top left corner would be better, provided it's not reserved for anything else.

If you press F5 to toggle through the HUD presets, there is at least one that has the stats widget located in the top left corner. If you change back to the status bar view or the Automap while this specific HUD is active, the widget will stay in its position.

**Comment by NightFright2k19** [comment]
I don't want to make too big of a deal out of this. Anyway, if it won't take considerable effort to make seperate displays possible (again), that'd be one happily resolved ticket more in your "Closed" section. 

And the best part: You wouldn't even have to add a new menu entry, just one additional selection option. Which in return wouldn't put your menu cleanup mission in any danger. ;)
