### ISSUE TITLE
Screen just gets resized

### ISSUE THREAD

**Issue by khades** [fabiangreffrath/woof#1331]
Resolution mode set to high, screen resolution is 2560x1440.

Debian testing, awesomewm.

https://www.youtube.com/watch?v=4q6kICeXdtk&feature=youtu.be

wad is latest eviternity II, have hq sounds and voxels autoloaded. (removed everything, still reproduced)

Does not reproduce on x2\x3\original resolution modes. 

Woof version - latest master.

**Comment by rfomin** [comment]
By default we have dynamic scaling enabled at "high". It looks like `SDL_RenderSetLogicalSize` is not working on your system for some reason. We might get an error message, I've added the logging here: https://github.com/fabiangreffrath/woof/commit/39017451432ae7a8705ad1ee3bb0486584c1a474

**Comment by MrAlaux** [comment]
If I enable integer scaling and trigger dynamic resolution changes, I get comparable results to what's shown in the video.

**Comment by rfomin** [comment]
> If I enable integer scaling and trigger dynamic resolution changes, I get comparable results to what's shown in the video.

Yes, integer scaling has not been tested and most likely does not work correctly. @khades, please check `integer_scaling` in the configuration.

I don't see much point in this feature. @fabiangreffrath should we remove it?

**Comment by bangstk** [comment]
I think integer scaling loses most of its meaning when aspect ratio correction is enabled. The only resolution that could have true integer scaling is 1600x1200, which greatly limits the number of monitors that could actually display that at a reasonable size.

**Comment by fabiangreffrath** [comment]
> I don't see much point in this feature. @fabiangreffrath should we remove it?

Never used it, let's get rid of it. It really only makes a difference when upscaling very low (i.e. vanilla) resolutions.

**Comment by rfomin** [comment]
Removed in https://github.com/fabiangreffrath/woof/commit/8efdd489ce08b1d95d823a908daf682758fba855

**Comment by khades** [comment]
thanks
