### ISSUE TITLE
Screen melt at startup?

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1333]
Oops, I hit Enter early. I'll edit this shortly with a proper description.

---

_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/7223622001)._

A screen melt occurs at the very start of the program, revealing the TITLEPIC. Not a problem per se -- in fact, I like it -- but it definitely wasn't there before. Why?

I suspect it may have to do with DRS, but the melt occurs even if DRS is disabled.

**Comment by rfomin** [comment]
Fixed here: https://github.com/fabiangreffrath/woof/commit/2df5297a8c08222ee97d5f7b10e291ac642731e8 Although, I like it too,
