### ISSUE TITLE
[Suggestion] Add more screenwipe columns for widescreen

### ISSUE THREAD

**Issue by bangstk** [fabiangreffrath/woof#1335]
Recently the wipe transition was changed to use the original Vanilla resolution for screen wipes.
I think it looks good at 4:3, however, these columns are stretched for the whole width of the screen, which means it gets very blocky at 16:9 or 21:9, making it even blockier than vanilla in those cases.

I think NUM_COLUMNS should increase proportionally with the aspect ratio (but continue NOT to increase with hires scaling of course); this will maintain the same vanilla column 'density' no matter what your screen ratio is.

Diet Boom didn't account for this because it doesn't have widescreen at all. But if it did have widescreen, I believe it would do it this way.

**Comment by rfomin** [comment]
Fixed here: https://github.com/fabiangreffrath/woof/commit/73f9a43248db85140caa12fa1dd15cf4946327c6
