### ISSUE TITLE
Widescreen STBAR broke in recent update

### ISSUE THREAD

**Issue by buvk** [fabiangreffrath/woof#1336]
![woof_stbar](https://github.com/fabiangreffrath/woof/assets/2666951/710b4651-0128-44fb-97ed-1736b94f6d75)

**Comment by buvk** [comment]
I'm using the STBAR from the Unity release.  It was working fine up until recently.

**Comment by bangstk** [comment]
Does your wad containing the bar have an X offset on the graphic?
The real Unity IWAD's STBAR has an x offset of 53.
So the change is probably that the old version of Woof always centers the bar graphic (which might probably be the better approach)

**Comment by buvk** [comment]
> Does your wad containing the wide STBAR have an X offset on the graphic? The real Unity IWAD's STBAR has an x offset of 53, and is still positioned fine in this version of Woof. So the change is probably that the old version of Woof always centers the bar graphic (which might probably be the better approach)

No.  I don't recall there being an offset.

I also tried the STBAR from the [Bethesda widescreen pack](https://bethesda.net/es/game/doom-widescreen-mods) and it is broken as well.

**Comment by rfomin** [comment]
@buvk Check artifacts on this page https://github.com/fabiangreffrath/woof/actions/runs/7231103309 (it's from PR #1339)

**Comment by mikeday0** [comment]
I have no issues with the widescreen STBAR on my end. (Testing the latest master) The one I have has an x offset of 83, but if I change this to 0 it still renders correctly.

**Comment by rfomin** [comment]
> I have no issues with the widescreen STBAR on my end. (Testing the latest master) The one I have has an x offset of 83, but if I change this to 0 it still renders correctly.

I've made a new STBAR from Bethesa assets and it's bugged. #1339 fixes it.

**Comment by buvk** [comment]
> @buvk Check artifacts on this page https://github.com/fabiangreffrath/woof/actions/runs/7231103309 (it's from PR #1339)

It is fixed in this version.

**Comment by mikeday0** [comment]
> > I have no issues with the widescreen STBAR on my end. (Testing the latest master) The one I have has an x offset of 83, but if I change this to 0 it still renders correctly.
> 
> I've made a new STBAR from Bethesa assets and it's bugged. #1339 fixes it.

The `SHORT(sbar->width) > video.unscaledw` condition is the problem I assume?

**Comment by rfomin** [comment]
> The `SHORT(sbar->width) > video.unscaledw` condition is the problem I assume?

Yes, I think so.

> > @buvk Check artifacts on this page https://github.com/fabiangreffrath/woof/actions/runs/7231103309 (it's from PR #1339)
> 
> It is fixed in this version.

Thanks!
