### ISSUE TITLE
Pixels getting stuck on right hand side

### ISSUE THREAD

**Issue by buvk** [fabiangreffrath/woof#1337]
![right_pixel](https://github.com/fabiangreffrath/woof/assets/2666951/62547310-905a-46ab-82e1-8e58cf9179f7)

**Comment by buvk** [comment]
There is a thin line of pixels on the far right hand side (the red in the above pic)

**Comment by rfomin** [comment]
Fixed here: https://github.com/fabiangreffrath/woof/commit/39017451432ae7a8705ad1ee3bb0486584c1a474
