### ISSUE TITLE
SDL2: Joystick bug

### ISSUE THREAD

**Issue by BeWorld2018** [fabiangreffrath/woof#134]
hi,

I found a bug (or an optimisation :-)

this variable MAX_JSB 12

On my platform and my gamepad, i have 11 buttons
When function GetButtonsState called, your "for i = 0 to MAX_JSB" seem not good, i have an little error/crash when i call button 12 (doesnt exit), maybe SDL2 have a bug on my platform.

But you can replace MAX_JSB with SDL_JoystickNumButtons(), is more safe :-)

Thanks

**Comment by fabiangreffrath** [comment]
Thanks for the report! My gamepad has 8 buttons and this never happened. But it's good to know how this may break.
