### ISSUE TITLE
Crash when trying to use 21:9 widescreen

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1346]
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/7259540848)._

By setting `widescreen` to `4` in the CFG (so, forcing 21:9) and trying to launch the game, the music starts playing and then the game just crashes.

I also tried the x64 artifact of [this run](https://github.com/fabiangreffrath/woof/actions/runs/7273253217) of #1345. Sometimes it crashes, and sometimes it launches but looks broken:
![woof0000](https://github.com/fabiangreffrath/woof/assets/73968015/494c2ede-941a-44e7-a18f-0def66511ee5)
![woof0001](https://github.com/fabiangreffrath/woof/assets/73968015/c5bc0138-bc37-4bab-80d5-fe10551a151b)

FWIW, I Alt+Tabbed out of the window from which I took those screenshots, and as I clicked on the Explorer tab to enter the folder where the screenshots were, the game crashed out of nowhere, but at least with an error message:
![imagen](https://github.com/fabiangreffrath/woof/assets/73968015/0c61e254-7d4d-4915-b320-b67b5ca94717)

**Comment by fabiangreffrath** [comment]
It crashes reproducibly for me in `V_FillRect()`. This is the content of `dstrect` right before the crashing `while` loop:

```gdb
(gdb) p dstrect
$3 = {
  x = 440,
  y = 0,
  w = 120,
  h = 200,
  cx1 = 440,
  cx2 = 559,
  cy1 = 0,
  cy2 = 199,
  cw = 120,
  ch = 200,
  sx = 1980,
  sy = 0,
  sw = 540,
  sh = 900
}

(gdb) p linesize
$4 = 1920
```

**Comment by fabiangreffrath** [comment]
It seems that `video.width` is determined from `height` and the given aspect ratio without taking screen buffer dimensions (i.e. `pitch`) into account.

```gdb
(gdb) p video
$3 = {
  width = 2520,
  height = 900,
  pitch = 1920,
  unscaledw = 560,
  deltaw = 120,
  xscale = 294912,
  yscale = 294912,
  xstep = 14564,
  ystep = 14564,
  fov = 1437743134
}
```

**Comment by fabiangreffrath** [comment]
This hack prevents the crash at least:

```diff
--- a/src/i_video.c
+++ b/src/i_video.c
@@ -1013,6 +1013,9 @@ static void ResetResolution(int height)
     video.height    = (video.height + 1) & ~1;
     actualheight    = (actualheight + 1) & ~1;
 
+    if (video.width > native_width)
+      ResetResolution((int)(native_width / aspect_ratio / 1.2));
+
     video.deltaw = (video.unscaledw - NONWIDEWIDTH) / 2;
 
     video.fov = 2 * atan(video.unscaledw / (1.2 * SCREENHEIGHT) * 3 / 4) / M_PI * ANG180;
```

**Comment by rfomin** [comment]
> This hack prevents the crash at least:

Yes, I'm planning a refactoring of ResetResolution so that the aspect ratio calculation is a separate function.
