### ISSUE TITLE
WIDESCREEN bug

### ISSUE THREAD

**Issue by BeWorld2018** [fabiangreffrath/woof#135]
When widescreen is activated, graphic "bar stats" is ok :

![image](https://user-images.githubusercontent.com/36823759/108588667-af494e80-735a-11eb-8830-0279219a5c3f.png)

When i disabled widescreen :

![image](https://user-images.githubusercontent.com/36823759/108588655-a0fb3280-735a-11eb-978e-3708b2b6be9f.png)

**Comment by fabiangreffrath** [comment]
Wow, looks like the status bar background isn't rendered at all. Is this the latest development snapshot? Is this the regular IWAD without any PWAD loaded?

**Comment by BeWorld2018** [comment]
Yes.... last snapshot dev.
And yes it's just doom2

**Comment by fabiangreffrath** [comment]
Do you start the game with a command line parameter (e.g. -warp) or from the menu?

**Comment by rfomin** [comment]
Does SDL2 work correctly on this system? In the first screenshot, it seems that the window resize is not correct.

**Comment by BeWorld2018** [comment]
> Do you start the game with a command line parameter (e.g. -warp) or from the menu?

From menu

> Does SDL2 work correctly on this system? In the first screenshot, it seems that the window resize is not correct.

Yes, i port a lot of SDL2 games
I test in OPENGLRENDERER AND SOFTWARE RENDERER, same problem on status bar

**Comment by fabiangreffrath** [comment]
Is this on a big-endian system?

**Comment by BeWorld2018** [comment]
Yes PowerPC :-) MorphOS (AmigaOS like)

**Comment by fabiangreffrath** [comment]
Does this help?
```
--- a/Source/st_stuff.c
+++ b/Source/st_stuff.c
@@ -374,9 +374,9 @@ void ST_refreshBackground(boolean force)
       }
 
       // [crispy] center unity rerelease wide status bar
-      if (sbar->width > ORIGWIDTH && sbar->leftoffset == 0)
+      if (SHORT(sbar->width) > ORIGWIDTH && SHORT(sbar->leftoffset) == 0)
       {
-        V_DrawPatch(ST_X + (ORIGWIDTH - sbar->width) / 2, 0, BG, sbar);
+        V_DrawPatch(ST_X + (ORIGWIDTH - SHORT(sbar->width)) / 2, 0, BG, sbar);
       }
       else
       {
```

**Comment by BeWorld2018** [comment]
Yes !!!! Working ! :-) thanks

**Comment by fabiangreffrath** [comment]
Great! Could you please finish E3M8 and check if the scrolling bunny screen works?
