### ISSUE TITLE
midi not reinitializing on loop [mac, native]

### ISSUE THREAD

**Issue by ribbiks** [fabiangreffrath/woof#1355]
Greetings! When using the new native midi player on mac it seems as though various parameters (such as tempo, pitchbends, and other sorts of control messages) are not resetting to their initial values when the midi repeats. I attached an example that starts at 120bpm, then has a control message to double it to 240.

The expected behavior (which works in opl in the current version, and in sdl in older versions of woof):

1 bar of 120bpm --> 1 bar of 240bpm --> midi loops, going back to 120bpm.

The current behavior:

1 bar of 120bpm --> 1 bar of 240bpm --> midi loops, but it's stuck in 240bpm forever now

[tempo_test.wad.zip](https://github.com/fabiangreffrath/woof/files/13780553/tempo_test.wad.zip)

**Comment by rfomin** [comment]
Could you please test this: #1356 I don't have access to the Mac.

**Comment by ribbiks** [comment]
The midi now plays through once and then this console error pops up at the end:

`SequenceUserCallback: MusicPlayerSetTime failed.`

**Comment by rfomin** [comment]
I seem to have messed up the pointer. Hopefully this will fix it: https://github.com/fabiangreffrath/woof/pull/1356/commits/65f9bb0b905ab93ec881a00a9026074018bd203d Can you try again please?

**Comment by ribbiks** [comment]
Now what happens is that once the end of the midi is reached it gets stuck in `SequenceUserCallback` (throwing a print statement in there will spew a million lines out to console) and the exe has to be killed.

Wish I could be more help with debugging, I'll try poking at it and testing a few things.

**Comment by rfomin** [comment]
Maybe we shouldn't send any pointers at all: https://github.com/fabiangreffrath/woof/pull/1356/commits/e8d6800deb21f8c0857eb412a9b351570a1eebdb
I will try an alternative approach without callbacks if this fails.

**Comment by ribbiks** [comment]
Same result as before.

Not sure how helpful this will be, but I managed to get a "working" version that uses the looping logic from the main branch, but I adapted your callback function to instead insert a copy of the tempo track at the midi's repeat timestamp. This resolves the issue of tempos not being reset properly, but I don't think it would properly reset other control messages like pitchbends and whatnot (but maybe it's a start?).

Attached below is a patch with respect to e8d6800:

```164,167c164,167
<     if (MusicPlayerSetTime(player, 0) != noErr)
<     {
<         I_Printf(VB_ERROR, "SequenceUserCallback: MusicPlayerSetTime failed.");
<     }
---
>     I_Printf(VB_ERROR, "we are looping... %f %f", inStartSliceBeat, inEndSliceBeat);
>     MusicTrack tempoTrack;
>     MusicSequenceGetTempoTrack(sequence, &tempoTrack);
>     MusicTrackCopyInsert(tempoTrack, 0, inStartSliceBeat, tempoTrack, inStartSliceBeat);
248c248
<     if (MusicPlayerSetTime(player, 0) != noErr)
---
>     for (i = 0; i < ntracks; i++)
250,251c250,274
<         I_Printf(VB_ERROR, "I_MAC_PlaySong: MusicPlayerSetTime failed.");
<         return;
---
>         MusicTrack track;
> #if MAC_OS_X_VERSION_MIN_REQUIRED < 1050
>         typedef struct
>         {
>             MusicTimeStamp loopDuration;
>             SInt32 numberOfLoops;
>         } MusicTrackLoopInfo;
> #endif
>         MusicTrackLoopInfo info;
> 
>         if (MusicSequenceGetIndTrack(sequence, i, &track) != noErr)
>         {
>             I_Printf(VB_ERROR, "I_MAC_PlaySong: MusicSequenceGetIndTrack failed.");
>             return;
>         }
> 
>         info.loopDuration = maxtime;
>         info.numberOfLoops = (looping ? 0 : 1);
> 
>         if (MusicTrackSetProperty(track, kSequenceTrackProperty_LoopInfo,
>                                   &info, sizeof(info)) != noErr)
>         {
>             I_Printf(VB_ERROR, "I_MAC_PlaySong: MusicTrackSetProperty failed.");
>             return;
>         }```

**Comment by rfomin** [comment]
> Not sure how helpful this will be, but I managed to get a "working" version that uses the looping logic from the main branch, but I adapted your callback function to instead insert a copy of the tempo track at the midi's repeat timestamp.

That's interesting, thanks. Perhaps we should send a MIDI reset message like we do in the Windows module. But that needs to be tested, perhaps in the future when I at least get a macOS VM. For now I suggest just copying what SDL_Mixer does: https://github.com/fabiangreffrath/woof/pull/1356/commits/fb7731afa0a8907ef44506494eed241dc49c5f01

**Comment by ribbiks** [comment]
Nice! It seems to work now.

I wasn't sure if adding an update function like that was too invasive, but indeed it's surely safer to copy sdl_mixer than to try and manually reset everything.

**Comment by rfomin** [comment]
Thanks for testing!

> I wasn't sure if adding an update function like that was too invasive

We may still need it in the future to avoid unnecessary threads.

**Comment by fabiangreffrath** [comment]
Is this fixed now?

**Comment by rfomin** [comment]
Yes, it should be fixed by https://github.com/fabiangreffrath/woof/commit/b8677656be2826dfb281dc708113aca81136e441
