### ISSUE TITLE
[Bug] Crash to desktop with "Penultimate Breakfast"

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#1367]
When leaving E1M4 of ["Chex Quest: The Penultimate Breakfast"](https://www.doomworld.com/forum/topic/136459-idgameschex-quest-the-penultimate-breakfast-40-map-megawad-for-chexwad-limit-removing-complevel-3/), game crashes to desktop without error before E1M5 can be loaded.

According to the author, there's already a Woof playthrough without this issue, presumably with latest official build. Therefore it is suspected that a more recent commit is causing problems.

Used build: Latest Master (Commit f67fb07, Win x64)

**Comment by rfomin** [comment]
I can't reproduce it yet. Do you have a save before the crash?

**Comment by NightFright2k19** [comment]
Here you go. It's right before the exit, you just have to push the button ahead of you.
[woofsav0.zip](https://github.com/fabiangreffrath/woof/files/13822566/woofsav0.zip)

**Comment by rfomin** [comment]
This save works for me. Command line: `woof -iwad CHEX.WAD -file chextpb.zip`
What is "chex_fix.wad"?

**Comment by NightFright2k19** [comment]
It's this. A custom fix I made with slighly realigned keys and mugshot for the Chex statusbar to properly center them. Shouldn't have anything to do with this issue.

[chex_fix.zip](https://github.com/fabiangreffrath/woof/files/13822717/chex_fix.zip)

**Comment by rfomin** [comment]
It crashes with artifact but works with my RelWithDebInfo local build. Thanks, I will investigate this further later.
