### ISSUE TITLE
Canonicalized Windows paths are not recognized for some reason

### ISSUE THREAD

**Issue by onContentStop** [fabiangreffrath/woof#137]
I gave Woof the following arguments:
```
[src\main.rs:301] &binary = "C:\\Users\\Kyle Coffey\\doom\\.\\engines\\woof\\woof.exe"
[src\main.rs:302] &args = [
    "-iwad",
    "\\\\?\\C:\\Users\\Kyle Coffey\\doom\\iwad\\DOOM2.WAD",
    "-complevel",
    "11",
    "-vidmode",
    "GL",
    "-geom",
    "2560x1440F",
]
```

With these parameters, I am getting an IWAD not found error. Is this a bug in Woof?

**Comment by fabiangreffrath** [comment]
What does the question mark have to do in the `-iwad` parameter? 

Also, the other three arguments are PrBoom'isms and are not supported by Woof!.

**Comment by onContentStop** [comment]
As for your first question, https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea#parameters

I am aware that the -complevel, -vidmode, and -geom parameters are not supported by Woof, but I assumed they would be ignored. Keep in mind my command line launcher passes those args to all engines unconditionally, even GZDoom because I was too lazy to categorize engines (again, under the assumption that unsupported arguments in Doom engines are ignored).

**Comment by fabiangreffrath** [comment]
Woof doesn't use any Windows-specific API to open files, it uses plain POSIX/ISO-C `fopen()`:
https://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html

**Comment by fabiangreffrath** [comment]
I am unsure what to do with this report now.

**Comment by fabiangreffrath** [comment]
@onContentStop Could you name any other Doom source port that supports this file name convention?

**Comment by onContentStop** [comment]
It definitely works on GZDoom and PrBoom+UM.

**Comment by fabiangreffrath** [comment]
Seems to make a difference if you use `open()` or `fopen()`.

**Comment by fabiangreffrath** [comment]
@onContentStop Does this work with Choco or Crispy? Sorry, but I need to gather more information about usage of this unusual file name convention...

**Comment by rfomin** [comment]
Chocolate Doom works with this command line:
`chocolate-doom -iwad \\?\D:\OLD\DOOM\WAD\DOOM.WAD`

**Comment by fabiangreffrath** [comment]
Huh, okay. Can't we just trim away that `\\?\` part? 😜

**Comment by rfomin** [comment]
Choco does some Windows-specific things in the `win_opendir.c`. PrBoom+ does something convoluted. I don't know, maybe we should take the Choco approach.
