### ISSUE TITLE
Some sprites have a black outline

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1371]
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/7412300024)._

See the Fist:
![woof0000](https://github.com/fabiangreffrath/woof/assets/73968015/bf6c51b2-3a08-4093-8787-3612e4008ea8)

That's with _Triple_ resolution. _Original_, _Double_ and _High_ (which is 1364x640 in my case) are unaffected.

Do note that that's not the vanilla Fist sprite, but rather the one from this WAD: [DMSF_ALX-R3_FULL.zip](https://github.com/fabiangreffrath/woof/files/13839311/DMSF_ALX-R3_FULL.zip).
The vanilla sprite is unaffected. Not all other sprites from that WAD are affected either.

FWIW, this same issue is present in Nugget's 3X resolution.

**Comment by fabiangreffrath** [comment]
Probably related:
https://github.com/coelckers/prboom-plus/commit/b8aa0e7d8ba5bb6b27f521135ff23d4c33d0d427

**Comment by NightFright2k19** [comment]
I see the effect as well, but it disappears when moving.
