### ISSUE TITLE
[Possible Bug] Repeatable switch not working in "Nostalgia"

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#1374]
Game: Doom 2
PWAD: [Nostalgia](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/nostalgia)
Used build: Commit [7d1cee0](https://github.com/fabiangreffrath/woof/commit/7d1cee03bc8736eff5b2c0267d28621baee16c46), x64

Issue description:
In MAP21, there is a repeatable switch in the blood lake pit leading to the exit which is supposed to temporarily lower and raise a lift to reach the upper level again. Apparently this doesn't work in latest Woof! snapshots. Elevator just comes down and stays there, plus the switch becomes non-functional. Showstopper alert. 

Note:
Wanted to reproduce it for a savegame dump, but didn't happen during my second playthrough of the map.

Screenshot of location:
![nostalgia_map21](https://github.com/fabiangreffrath/woof/assets/54737241/e83813c5-7c2f-445a-8544-ab7a20157a40)

**Comment by fabiangreffrath** [comment]
Probably wrong complevel?

**Comment by NightFright2k19** [comment]
I used -complevel 2, which should be correct. Plus I didn't change complevel settings between my flawed playthrough and the issue-free one.

**Comment by fabiangreffrath** [comment]
Could you share the coordinates of that point, or even better, the savegame?

**Comment by NightFright2k19** [comment]
Sadly I don't have the savegame with the flawed switch any more. I've played again until the same spot, without pressing the switch at all.
[woofsav0.zip](https://github.com/fabiangreffrath/woof/files/13845740/woofsav0.zip)

**Comment by NightFright2k19** [comment]
Update:
Try to call down the lift, save when it's down and load the savegame. I think we're on to something (see #1375).

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/63e625e295eaa9e72fcc4499654f5ab6c0b1ce79

**Comment by NightFright2k19** [comment]
Confirmed to be working again with latest commit. Thanks!
