### ISSUE TITLE
Lifts break after reloading 

### ISSUE THREAD

**Issue by Satku0** [fabiangreffrath/woof#1375]
When I save shortly after activating a lift and the lift is still down and then reload the save, it will stop working and can cause me to get softlocked. 
Happened on scythe 2, dbp 09 and doom 2.
Commit:  dd4e2b5

**Comment by NightFright2k19** [comment]
I have the suspicion this is directly related to my reported issue.

**Comment by fabiangreffrath** [comment]
@rfomin That `-1` value that we just casted to `intptr_t` is actually saved as a 32-bit int, which is neither `(size_t)-1` nor `(intptr_t)-1` on 64-bit archs:

https://github.com/fabiangreffrath/woof/blob/dd4e2b55b642696cf65e3591e5c5e922c2e5150e/src/p_saveg.c#L1269-L1272

**Comment by rfomin** [comment]
I think it fixed here: https://github.com/fabiangreffrath/woof/pull/1376/commits/467aab5b594bb30dbbe49d134891ecd15e88cb06

> @rfomin That `-1` value that we just casted to `intptr_t` is actually saved as a 32-bit int, which is neither `(size_t)-1` nor `(intptr_t)-1` on 64-bit archs:

That's true, but the C language has conversion rules, so this code probably worked on all platforms: https://godbolt.org/z/bqPqhnGrW

**Comment by fabiangreffrath** [comment]
Right, and AFAIU these rules the `-1` value gets promoted to one of the "larger" int-types that it is compared against. However, this would mean 8 bytes of `0xff`, whereas only 4 bytes have been saved. My idea would have been to explicitly cast `(int)-1` in the comparison to make clear it's 4 bytes of `0xff`.
