### ISSUE TITLE
[Feature] Adjust automap level title color with preset

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#1378]
Could the value of **hudcolor_titl** be set to "14" if "Automap Color Preset" is set to "Vanilla"? This would make sure that map titles are shown in the intended color. Prominent example is Chex where the title is supposed to be green, but the default preset (5) overrides that.

Alternatively (or additionally), it could be considered to simply change the default of **hudcolor_titl** to "14", which would also make sense since **hudcolor_mesg** uses that value already.

**Comment by fabiangreffrath** [comment]
Good point! What's the map name color for the ZDoom color theme, though? I think it's two colored, part red and part gray.

**Comment by NightFright2k19** [comment]
[Should look like this](https://imgur.com/wApRa?r), I guess.

**Comment by fabiangreffrath** [comment]
> [Should look like this](https://imgur.com/wApRa?r), I guess. 

Yep, but that's not *one color*.

> From the top of my head, I dunno the color number for white, but red is 6.

That'd be the gray table, the white one is pretty bright. But still I'll have to choose one of both. I guess I'll go with "none" here as well.

**Comment by NightFright2k19** [comment]
Yeah, I guess that would make sense.

**Comment by fabiangreffrath** [comment]
I have decided to go with CR_GRAY for the ZDoom scheme, because if you disable "Show Map Label" in the GZDoom menu, the entire map title will be gray.
