### ISSUE TITLE
[Feature] Autoload: Doom-All should not affect FreeDoom

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#1381]
As stated in the title. AFAIK this has already been implemented in some other ports (Crispy and International Doom at least, IIRC), but not here. 

Right now, you cannot load e.g. a highres sound replacement mod via Doom-All since it would also affect FreeDoom. Instead, you have to place it in the four folders for all Doom titles (Doom1, Doom2, TNT, Plutonia). On the other hand, there are only two FreeDoom games, so it's certainly less effort to put FreeDoom-specific stuff in two folders instead of Doom-specific content in four.

Other thoughts related to the topic:
- If implemented, the bloodcolor.deh and brghtmps.lmp would probably also have to be copied into autoload\freedoom1.wad and autoload\freedoom2.wad.
- A "FreeDoom-All" folder could be considered, but TBH I doubt it's worth it.
- A "Doom2-All" folder on the other hand (only for Doom2, Plutonia and TNT) could be useful for the spritefixes, which have a file that only works with Doom 1 (Crispy won't load D1 with the D2 fixes) and another for Doom 2.

**Comment by JNechaevsky** [comment]
Indeed, I have replicated Crispy Doom behavior. AFAIR, it was very noticeable while using SPRFIX wad, which have all possible rotations for zombies, while Freedoom itself doesn't have it.

**Comment by NightFright2k19** [comment]
Yeah, that's another very prominent example.

**Comment by rfomin** [comment]
https://github.com/fabiangreffrath/woof/commit/c2ea692e3a33032f22fabf64b91f94faafe3eeac
