### ISSUE TITLE
[Feature] Compact "essentials" for WOOFHUD

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#1396]
How feasible would it be to add an optional display of just the essential stats (Health, Armor, Ammo) in a single line to the WOOFHUD lump (similar to the K/I/S stats)?

Explanation:
Instead of using three separate lines, it would look like this (example):
**HEL 100   ARM 100   AMM 50/50** 
(No progress bars, just the numbers, i.e. _hud_draw_bargraphs_ would have to be set to 0 automatically)

Reasoning:
For absolute minimalists (like me) who want to save as much screen space as possible while still being able to check the most vital stats. Also maybe for those who consider the bars kinda redundant. [Differing from my previous suggestion](https://github.com/fabiangreffrath/woof/issues/1390), this approach would not mix different HUD styles, just reorganize existing ones a bit. 

Possible realization:
- Either introduce a CVAR which toggles between the old look and the single-line mode (setting _hud_draw_bargraphs_ to 0 could e.g. automatically align the three widgets in a single line automatically, showing as many as you have activated)
- Add a new (optional) identifier to WOOFHUD, something like "vitals", "essentials" or "compact"

**Comment by fabiangreffrath** [comment]
Not sure about this.

> HEL 100 ARM 100 AMM 50/50

Would this be the canonical order, or will this have to be customizable as well?

**Comment by NightFright2k19** [comment]
Hum, well I guess it could follow the order you place the entries in WOOFHUD, if that's managable. The sequence of the full display is (from top to bottom) STS, KEY, WEA, AMM, HEL, ARM. Keeping it customizable would probably be the right approach.

**Comment by NightFright2k19** [comment]
Closing my feature request [in favor of this one](https://github.com/fabiangreffrath/woof/issues/1407), which I believe is far more benefitial to the port. After all, whether you have the same info in three lines or one is negligible if you can remove the bars through the menu.

**Comment by NightFright2k19** [comment]
Even though HUD-related feature requests have a hard time around here these days:
After playing around with the Boom HUD a bit more, I've decided to resurrect this. It would be useful to have as an option for the minimal display (hud 0) where you would want all the vital information to consume as little space as possible.

**Comment by fabiangreffrath** [comment]
> * Toggle single-line display of Health/Armor/Ammo via config setting (doesn't need to show in the menu if you can't fit it in)
> * Order depends on entries in woofhud.lmp (not shown if omitted)

With the current implementation, these two won't play along. To get printed on one line, it needs to be one widget

**Comment by NightFright2k19** [comment]
Well, in that case I would say we drop the idea of customization. Offer it as a single, coherent thing, similar to the stats widget (which cannot be customized, either). Probably the easiest approach and then you don't even need a new CVAR for it. Just a need entry for the WOOFHUD lump.

**Comment by fabiangreffrath** [comment]
> **Update Jun 23** Just remembered: Only the numbers should change color, not the labels. Pretty much like the stats widget.

What colors should the labels have then?

**Comment by NightFright2k19** [comment]
The ones from the stats widget are red, which makes sense since the numbers never assume that color. I'd say keep'em white. Health and Armor can still turn white when in god mode, but that's not too confusing. For the numbers, the regular Boom colorization scheme may apply.

**Comment by fabiangreffrath** [comment]
Could you check the current state in #1757, please?

**Comment by fabiangreffrath** [comment]
> While Boom HUD modifications are in the focus anyway, maybe [this thing about blue and yellow tints](https://www.doomworld.com/forum/post/2815052) is also worth mentioning.

Has this always been the case or has this glitch been introduced just recently?

**Comment by NightFright2k19** [comment]
Unfortunately I'm currently abroad and cannot check anything on my PC before I return on Jul 9.

As for the colored font shadows, personally I don't remember a time when this ever looked right. Then again, I mostly used the stats widget only until recently, where it is not so prominently exposed.

**Comment by fabiangreffrath** [comment]
> As for the colored font shadows, personally I don't remember a time when this ever looked right. Then again, I mostly used the stats widget only until recently, where it is not so prominently exposed. I cannot exclude that it changed at some point. Would have to cross-check with a very early Woof build.

I'm afraid the the `W_IsWADLump()` check here always returns `true` since we moved the "internal" resources to `woof.pk3`. Will have time to check tomorrow.

https://github.com/fabiangreffrath/woof/blob/1e9ad29092e8f36cd7fe7063c4fa99f2779b9b12/src/v_video.c#L167

**Comment by NightFright2k19** [comment]
I could also judge from screenshots whether it's the way I imagine it. But as it's not an urgent implementation - if you can wait for 14 days, so can I.

**Comment by rfomin** [comment]
> I'm afraid the the `W_IsWADLump()` check here always returns `true` since we moved the "internal" resources to `woof.pk3`

I can't check it now, but `W_IsWADLump()` should return `false` if the lump is in `woof.pk3`.
