### ISSUE TITLE
[Feature] "Use" button timer

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1403]
As featured in Crispy.

FWIW, Nugget already has it, along with timers for picking up a key and going through a teleporter, but those two seem to be considered TAS (unlike the "Use" one), which somewhat defeats the point.

Let me know if you want me to make a PR, and if so, if you're interested in those other timers.

**Comment by rfomin** [comment]
> Let me know if you want me to make a PR, and if so, if you're interested in those other timers.

Does DSDA-Doom have this? I think I saw a few feature requests about it on the speedrunners discord.

**Comment by MrAlaux** [comment]
> Does DSDA-Doom have this?

It does, but the only way I know to enable it is by passing `-time_use` in the command-line.

**Comment by rfomin** [comment]
> > Does DSDA-Doom have this?
> 
> It does, but the only way I know to enable it is by passing `-time_use` in the command-line.

Is this a speed runner feature? If so, I think we should replicate the behaviour of DSDA-Doom.

> Let me know if you want me to make a PR, and if so, if you're interested in those other timers.

That would be nice 👍

**Comment by MrAlaux** [comment]
> Is this a speed runner feature?

I guess so; the timer serves as a sort of split, giving you an idea of how well you're doing in a run. At least that's how I use it.

> I think we should replicate the behaviour of DSDA-Doom.

A difference I noticed between Crispy and DSDA is that, when using an exit switch, Crispy's timer is one tic behind the time reported in the intermission screen, while DSDA's timer matches the intermission's. I just skimmed through DSDA's implementation, and it simply adds 1 to the "use" time. Apart from that, DSDA's timer seems to be part of a splits system, whose details are unknown to me; maybe it does some logging?

In any case, merely having the use time be displayed on screen momentarily is already pretty helpful for me, and there don't seem to be any differences in that regard between Crispy and DSDA apart from the aforementioned tic difference (excuse me, @kraflab, could you confirm this?).

> That would be nice 👍

Sorry, that's a bit unclear: are you interested in the other two timers or not?

**Comment by rfomin** [comment]
> Sorry, that's a bit unclear: are you interested in the other two timers or not?

To be honest, this is unclear to me as well. But I've seen at least one feature request on the speed runners discord. I don't think we need a complex splitting system, but simple features like this are fine.

**Comment by MrAlaux** [comment]
> To be honest, this is unclear to me as well.

I guess we can omit them. I haven't seen such timers anywhere else, I just came up with them myself, and like I said, they seem to be TAS so they're probably not as useful.

**Comment by rfomin** [comment]
> I guess we can omit them. I haven't seen such timers anywhere else, I just came up with them myself, and like I said, they seem to be TAS so they're probably not as useful.

Okay, sounds good to me.

**Comment by fabiangreffrath** [comment]
Unless otherwise explicitly requested, I'd appreciate a PR to add the "use" timer only. Thanks!
