### ISSUE TITLE
Smooth pixel scaling performance issue

### ISSUE THREAD

**Issue by ceski-1** [fabiangreffrath/woof#1404]
Update: Bad data, not reproducible.

<details><summary>Original Issue</summary>

With higher resolutions, it's more likely that the [scaling factor](https://github.com/fabiangreffrath/woof/blob/2f06e9fcb4e71626a3a4b06073a66ff09705ca09/src/i_video.c#L1129) will be 1 (e.g. triple res in a 1366x768 window). And if the scaling factor is 1, there's no reason to create `texture_upscaled` because the "linear" hint can be applied to the base `texture` [directly](https://github.com/fabiangreffrath/woof/blob/2f06e9fcb4e71626a3a4b06073a66ff09705ca09/src/i_video.c#L1509) to achieve the same effect. Otherwise, an extra and unnecessary copy is [executed](https://github.com/fabiangreffrath/woof/blob/2f06e9fcb4e71626a3a4b06073a66ff09705ca09/src/i_video.c#L470) which seems to cause a performance drop on older systems. So some kind of logic should be added to check this.

There's a quick way to verify this by enabling "linear" filtering on the base `texture` and ignoring the `texture_upscaled` completely. This is what I did:

Start from the latest master with a default woof.cfg and change only the following settings:

```
resolution_mode 2
fullscreen 0
use_vsync 0
window_width 1366
window_height 768
smooth_scaling 0 or 1
```

Then the following quick edits are made to `i_video.c` as a test:

```diff
diff --git a/src/i_video.c b/src/i_video.c
index d4bb13bb..51a3f546 100644
--- a/src/i_video.c
+++ b/src/i_video.c
@@ -467,6 +467,7 @@ static void UpdateRender(void)
     SDL_UpdateTexture(texture, &blit_rect, argbbuffer->pixels, argbbuffer->pitch);
     SDL_RenderClear(renderer);
 
+#if 0
     if (smooth_scaling)
     {
         // Render this intermediate texture into the upscaled texture
@@ -481,6 +482,7 @@ static void UpdateRender(void)
         SDL_RenderCopy(renderer, texture_upscaled, NULL, NULL);
     }
     else
+#endif
     {
         SDL_RenderCopy(renderer, texture, &blit_rect, NULL);
     }
@@ -1506,7 +1508,7 @@ static void CreateSurfaces(void)
         SDL_DestroyTexture(texture);
     }
 
-    SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "nearest");
+    SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "linear");
 
     texture = SDL_CreateTexture(renderer,
                                 SDL_GetWindowPixelFormat(screen),
```

Results of `./woof -warp 1` on an old laptop (i7-5600U, Intel HD 5500, Arch Linux):

```
master (smooth_scaling 1)   150 fps
master (smooth_scaling 0)   210 fps
test (always smooth)        210 fps
```

[Doomworld link](https://www.doomworld.com/forum/topic/125256-nugget-doom-231-updated-december-15th-23/?page=15&tab=comments#comment-2761636)

</details>

**Comment by rfomin** [comment]
Good find, thanks! Interesting that with my NVidia GPUs (very old 520M and newer RTX 3060) I have 0 performance difference.

**Comment by ceski-1** [comment]
I have to admit, I think I messed up somewhere in my original testing as I can no longer reproduce this. I tested the [latest master](https://github.com/fabiangreffrath/woof/tree/8412588aff0b6247f7a601625480de614aa1064c), the snapshot of the [master when initially reported](https://github.com/fabiangreffrath/woof/tree/2f06e9fcb4e71626a3a4b06073a66ff09705ca09), and finally [this PR](https://github.com/fabiangreffrath/woof/pull/1415) with a small edit to toggle smoothing properly. In all cases with the same configs, I got approximately 200 fps with `smooth_scaling 0` and 150 fps with `smooth_scaling 1`. Sorry about that.

**Comment by fabiangreffrath** [comment]
Well, still 50 fps more and one unnecessary rendering step less. 🤷
