### ISSUE TITLE
Using 32:9 aspect ratio crashes game

### ISSUE THREAD

**Issue by ceski-1** [fabiangreffrath/woof#1406]
Using latest master and `widescreen 5` in woof.cfg. Log: [asan.txt](https://github.com/fabiangreffrath/woof/files/14002375/asan.txt)

I might be to blame for this one, but I haven't looked closer.

**Comment by rfomin** [comment]
> I might be to blame for this one, but I haven't looked closer.

I think it's a video buffer/array size issue (`CreateSurfaces` and `R_InitAnyRes`). I will look into it when the menu is done.

**Comment by rfomin** [comment]
This change 65dff40 fixes the crash for me. I still need to rework this to allow higher than native resolutions.

**Comment by fabiangreffrath** [comment]
> I still need to rework this to allow higher than native resolutions.

Keep in mind, though, that this may lead to problems with 1px wide automap lines, which then get reduced to 0px width.

**Comment by ceski-1** [comment]
> This change [65dff40](https://github.com/fabiangreffrath/woof/commit/65dff4019fdcd3992c21c7ef7d83224621ecfb5d) fixes the crash for me. I still need to rework this to allow higher than native resolutions.

Unfortunately it still crashes. Make a debug build with ASAN support, clear the woof.cfg except for `widescreen 5` and launch the game. [asan2.txt](https://github.com/fabiangreffrath/woof/files/14158386/asan2.txt)

**Comment by fabiangreffrath** [comment]
At this point:

```gdb
(gdb) p video.pitch 
$7 = 1920
(gdb) p dstrect.sw
$8 = 1922
```

**Comment by fabiangreffrath** [comment]
Does `V_TileBlock64()` need a `V_ClipRect()` call?

**Comment by rfomin** [comment]
I'm working on the issue, the plan is to recreate the video buffer/surface when the resolution scale/aspect ratio is changed.

> Does `V_TileBlock64()` need a `V_ClipRect()` call?

I don't think we need `V_ClipRect()` at all, `V_ScaleRect` is enough. I will try to remove it.
