### ISSUE TITLE
[Feature] Stretch 4:3 statusbars to fit screen

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#1407]
In widescreen, offer an option to stretch standard size statusbars to cover the gaps on both sides. Useful for pwads which don't have a widescreen replacement available and user still wants to make the background image disappear.

Possible behavior if a widescreen statusbar is loaded:
- Ignore/override the setting (dynamically) or
- Stretch it anyway (in which case port must take actual STBAR width and properly cut it down to 320p again).

Feature is already implemented in DSDA-Doom.

Note:
Could theoretically be expanded to be applied to menu lumps (TITLEPIC, INTERPIC, BOSSBACK etc) as well.

**Comment by ak-988** [comment]
It's not stretching, but have you tried the "solid statusbar background" option in general settings?

![av](https://github.com/fabiangreffrath/woof/assets/76888018/725fcbb3-234b-4b7b-9831-2365410e8376)

**Comment by rfomin** [comment]
I don't like this kind of stretching, and we currently have no support for it in the patch drawing system. Perhaps it's more interesting to improve the "solid statusbar background" feature. Which status bars look bad?

**Comment by NightFright2k19** [comment]
An alternate idea would be to let the user choose the background tile from patches of the current iwad/pwad loaded. STBAR lumps are often made from those patches, so chances are there is one which fits.

**Comment by rfomin** [comment]
> An alternate idea would be to let the user choose the background tile from patches of the current iwad/pwad loaded.

I like the idea, but there are a lot of 64x64 tiles in Doom. Should this be a config-only option?

**Comment by rfomin** [comment]
> 2\. Determine the predominant color in the STBAR lump and automatically adjust the background color to it.

We are already trying to do this, but perhaps failing in some cases.

**Comment by NightFright2k19** [comment]
Well, you could let it tile by default. Often it works. Config only could be ok, but without being able to see the tile via menu, one would have to browse through the patches in SLADE, which isn't too user-friendly.

**Comment by rfomin** [comment]
> Config only could be ok, but without being able to see the patch via menu, one would have to browse through the patches in SLADE, which isn't too user-friendly.

According to SLADE there are 147 flats in DOOM2.WAD. Still it could be an interesting "widget", I will at least try it.

**Comment by NightFright2k19** [comment]
Maybe for the pro user one could consider adding a lump that, if added, predetermines which patch should be used for such purposes. However, since that would be a very specific feature, it's doubtful it would really be used unless more ports pick it up.

**Comment by fabiangreffrath** [comment]
Not sure, guys. Vanilla Doom already makes pretty clear which flat is meant to get drawn around the view port. For those who don't like it, we have the solid status bar background feature - and I'd be fine to improve on it if there's still potential. But for everything else, you could still load custom widescreen status bar background patches and be done with it.

**Comment by rfomin** [comment]
Another idea is a special tile name that the port would check first. This would allow users to autoload it. E.g. `STBGTILE.lmp`

**Comment by ceski-1** [comment]
When I saw this I immediately thought of Strife which has a config option to change the border, or a WOOFBDR lump that can be prioritized if found.

However, some people actually prefer the default one, there are also wads that replace it with something that may look nice which would be missed if it was overridden, and for current alternatives it's easy enough to use widescreen replacements or the solid color option. There's also multiple fullscreen hud options as a last resort.

I don't like the stretched status bar appearance and I'm not sure if adding another replacement option is worthwhile considering the above.

**Comment by fabiangreffrath** [comment]
> However, some people actually prefer the default one, there are also wads that replace it with something that may look nice which would be missed if it was overridden, and for current alternatives it's easy enough to use widescreen replacements or the solid color option. There's also multiple fullscreen hud options as a last resort.

Agreed to everything that was said here. 

> I don't like the stretched status bar appearance and I'm not sure if adding another replacement option is worthwhile considering the above.

Agreed again.

**Comment by NightFright2k19** [comment]
Well, it was worth a try. Back to the 600p+ res fixes then, I guess. :)
