### ISSUE TITLE
Crispy-like Autoload Folder?

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#141]
I think it would be nice to see the ability to autoload certain WADs and dehacked files (i.e. widescreen assets), based on what IWAD/PWAD is loaded manually, as seen in Crispy Doom.

**Comment by fabiangreffrath** [comment]
Sure, that's possible. Did you know that you can define 2 WAD and 2 DEH files to get autoloaded in the menu?

**Comment by OpenRift412** [comment]
> Sure, that's possible. Did you know that you can define 2 WAD and 2 DEH files to get autoloaded in the menu?

I did, yes.

**Comment by fabiangreffrath** [comment]
The question is where to sort WADs and DEHs in the loading order? We have IWADs, DEHACKED lumps in IWADs, PWADs loaded on the command line, PWADs loaded as preincludes, DEHACKED lumps in PWADs, DEHs loaded on the command line, DEHs loaded as preincludes, etc. 

And, the default order in MBF is different from the one in Choco, so we have to be careful here!

**Comment by fabiangreffrath** [comment]
I guess we should just do as if all the files in the autoload folders were the third, forth, sixth, etc. files set in the "files preloaded at startup" section in the menu.

**Comment by OpenRift412** [comment]
Just following up on this, did you implement the IWAD-dependent auto-load folders yet or just the doom-all folder?

**Comment by fabiangreffrath** [comment]
Per-IWAD autoload folders are available.

**Comment by OpenRift412** [comment]
> Per-IWAD autoload folders are available.

Do I have to specify a path in the CFG or should it just do it automatically? Because I put a widescreen graphics WAD in a folder named "doom2.wad", but it doesn't seem to take effect. The doom-all folder seems to work fine, since I have the widescreen statusbar in there and it loads fine. Am I missing something here?

**Comment by rfomin** [comment]
> PWAD graphics don't override autoload graphics

This is because of the load order. Everything from the autoload folder is loaded last. Also, we tried to fix your previous issue, can you try a new build?

**Comment by OpenRift412** [comment]
> > PWAD graphics don't override autoload graphics
> 
> This is because of the load order. Everything from the autoload folder is loaded last. Also, we tried to fix your previous issue, can you try a new build?

I just did, it seems to work fine, thanks.
