### ISSUE TITLE
Smooth scaling is enabled from launch regardless of setting

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1417]
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/7707769071)._

Regardless of whether `smooth_scaling` is `0` or `1`, the app seems to always start with smooth scaling enabled, and it's only disabled when toggling it off from the menu.

**Comment by fabiangreffrath** [comment]
Probably because this part is missing a check for `smooth_scaling`:

https://github.com/fabiangreffrath/woof/blob/4f7a4f70d79dbd54176f9ebb42fab4efc73932cd/src/i_video.c#L664-L668

**Comment by fabiangreffrath** [comment]
Does this fix it?

```patch
--- a/src/i_video.c
+++ b/src/i_video.c
@@ -663,7 +663,8 @@ void I_FinishUpdate(void)

     if (need_resize)
     {
-        CreateUpscaledTexture(false);
+        if (smooth_scaling)
+            CreateUpscaledTexture(false);
         need_resize = false;
     }

```

**Comment by fabiangreffrath** [comment]
It does, thank you!
