### ISSUE TITLE
Problem Compiling

### ISSUE THREAD

**Issue by Enator18** [fabiangreffrath/woof#1418]
This is probably user error and not a bug with the project but I didn't really know where else to ask for help about it. When I try to open the source folder for this project with Visual Studio 2022, with vcpkg installed on my system, I get this error in visual studio:
![image](https://github.com/fabiangreffrath/woof/assets/62544405/f6ef3764-252d-40e3-aee5-7ac9e63e9f76)

and when I open the log file its talking about, the file contains only this:

"Error: Cannot resolve a minimum constraint for dependency libxmp from :x64-windows.
The dependency was not found in the baseline, indicating that the package did not exist at that time. This may be fixed by providing an explicit override version via the "overrides" field or by updating the baseline.
See `vcpkg help versioning` for more information."

What does this mean and how do I fix it?

**Comment by rfomin** [comment]
> What does this mean and how do I fix it?

You probably have an old version of vcpkg. Try updating it:
```
cd c:\vcpkg
git pull
```

**Comment by Enator18** [comment]
yeah, that was the problem, thank you!
