### ISSUE TITLE
[Feature] Blink missing keys on HUD

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1424]
Once again, as featured in Crispy: when you try to open a key-locked door while missing the necessary keys, make said missing keys blink on the HUD.

_Once again,_ I've already implemented this in Nugget with the necessary adaptations to make it work with Boom's generalized doors, so if you're interested, I can make a PR.

**Comment by rfomin** [comment]
> _Once again,_ I've already implemented this in Nugget with the necessary adaptations to make it work with Boom's generalized doors, so if you're interested, I can make a PR.

Sure, it seems like a nice feature to have, thank you. It's not optional in Crispy, is it? I think we can just enable features like this without an option.

**Comment by MrAlaux** [comment]
> It's not optional in Crispy, is it?

Last I checked, it wasn't.

> I think we can just enable features like this without an option.

I insist in having a CVAR for it, just in case someone wants to disable it. No need for a menu item, though.

**Comment by rfomin** [comment]
> I insist in having a CVAR for it, just in case someone wants to disable it. No need for a menu item, though.

I'm fine with that.

**Comment by fabiangreffrath** [comment]
Yes, please add this. I assume this will only apply to the Crispy HUD?

**Comment by MrAlaux** [comment]
> I assume this will only apply to the Crispy HUD?

The way I implemented it, it also applies to the traditional Status Bar, intentionally. I think I never tried it on the Boom HUD, though.

In any case, I'd personally make it apply to all HUDs with a keys display.

**Comment by rfomin** [comment]
> Difficult, I think I'd rather leave the traditional status bar untouched. What do the others think?

Oh, it was only in the full screen HUD, that's why I never noticed it. I am not against it on the classic status bar.

**Comment by fabiangreffrath** [comment]
If we apply it to all HUDs, should ww better have a switch for it?

**Comment by rfomin** [comment]
> If we apply it to all HUDs, should ww better have a switch for it?

I think this feature is harmless.

**Comment by ceski-1** [comment]
I like this feature, but I vote to keep the original status bar as vanilla as possible. It seems like a nice addition to the fullscreen HUDs.

**Comment by fabiangreffrath** [comment]
> I like this feature, but I vote to keep the original status bar as vanilla as possible. It seems like a nice addition to the fullscreen HUDs.

Yes, I feel the same. So, we either need a menu switch for this, or we forcefully enable it for fullscreen HUDs and disable it for the classic status bar.

**Comment by MrAlaux** [comment]
If you don't want it on the Status Bar, that's alright, we can leave it untouched.

I'd personally leave the setting as just a CVAR in the CFG with three possible values: something like "off", "fullscreen only" (default) and "always".

Other than that, IIRC the established Crispy way is to only apply it to the Crispy HUD, so we could simply extend that to the Boom HUD and maybe give it an on/off CVAR.

**Comment by fabiangreffrath** [comment]
We can still decide later about these details.
