### ISSUE TITLE
Question about Complevels

### ISSUE THREAD

**Issue by snekyo** [fabiangreffrath/woof#1441]
Hey, how does setting a complevel with a string work? Do you just say -complevel boom? 

Also, just to confirm this, the reason vanilla has multiple complevels is to represent all of the updates to vanilla, with the highest listed level for vanilla being the most up to date, right?

**Comment by rfomin** [comment]
> Do you just say -complevel boom?

Yes.

> Also, just to confirm this, the reason vanilla has multiple complevels is to represent all of the updates to vanilla, with the highest listed level for vanilla being the most up to date, right?

[MBF21](https://doomwiki.org/wiki/MBF21) is the most advanced level. In most cases there is no need to change the default complevel, unless you are playing a very old vanilla mapset.

**Comment by snekyo** [comment]
> > Do you just say -complevel boom?
> 
> Yes.
> 
> > Also, just to confirm this, the reason vanilla has multiple complevels is to represent all of the updates to vanilla, with the highest listed level for vanilla being the most up to date, right?
> 
> [MBF21](https://doomwiki.org/wiki/MBF21) is the most advanced complevel. In most cases there is no need to change the default complevel, unless you are playing a very old vanilla mapset.

Yes, but just for reference, is the highest level for vanilla the most up to date official vanilla release? And does putting into the command line -complevel vanilla set it to the highest vanilla complevel automatically?

**Comment by rfomin** [comment]
> Yes, but just for reference, is the highest level for vanilla the most up to date official vanilla release?

`-complevel vanilla` emulates the Doom v1.9 DOS executable (Doom 1/Ultimate Doom/Doom2/Final Doom is automatically selected depending on IWAD).

**Comment by snekyo** [comment]
> > Yes, but just for reference, is the highest level for vanilla the most up to date official vanilla release?
> 
> `-complevel vanilla` emulates the Doom v1.9 DOS executable (Doom 1/Ultimate Doom/Doom 2/Final Doom is automatically selected depending on IWAD).

So it emulates the last official update to the engine other than the unity update?

**Comment by fabiangreffrath** [comment]
It emulates `DOOM2.EXE` version 1.9 that came with Doom 2 (and the latest Shareware and non-Ultimate Doom 1 releases). Unless you explicitly specify differently on the commend line. Or you feed it an Ultimate Doom IWAD, in which case it emulates `DOOM.EXE` version 1.9 that came with Ultimate Doom. Ir you feed it a Final Doom IWAD, in which case it emulates `DOOM2.EXE` version 1.9 that came with Final Doom.

Indeed, these versions are all called 1.9 and the differences between them are tiny. You can find the whole story here:

https://doomwiki.org/wiki/Versions_of_Doom_and_Doom_II#v1.9

**Comment by snekyo** [comment]
Ah, I get it.
