### ISSUE TITLE
Two Questions: How does smooth HP and Armor work, and how do IWAD unique settings work?

### ISSUE THREAD

**Issue by snekyo** [fabiangreffrath/woof#1443]
**Note: I know the way I'm explaining it is confusing, so just let me know if you want me to elaborate on anything.**
- Question 1: How does smooth HP and Armor work?
What if in the middle of the HP or Armor counting up, you take damage? Does it stop the animation, calculate how much damage you took compared to the amount of HP you would have by the end of the animation, and then play a smooth animation to that value? 
Is the current health displayed in the animation your HP, or does it compare it to the amount you will have by the end of the animation?
- Question 2: How do IWAD unique settings work?
Let's say I turn on the pre-beta BFG setting. Does it look for if the IWAD is from the base game? Does this setting apply to mods that have the BFG in them? What if a mod that uses DOOM II's IWAD doesn't have the BFG in it. Does it just ignore it? Is there a line of code in the weapon that defines it as a BFG, so that Woof can apply the change?

Thanks,
sneky

**Comment by snekyo** [comment]
Also uh, how do I add labels to this issue? I'd like to put the "Question" label to this.

**Comment by rfomin** [comment]
> Let's say I turn on the pre-beta BFG setting.

This is a joke setting from the original MBF port. It should work OK for casual play with most IWADs/PWADs (it uses the standard BFG sprite). Do not use it if you are serious about demo recording or compatibility.

We have a channel on the Chocolate Doom Discord: https://discord.gg/5M8K6vQ You may be able to get answers more quickly there.
