### ISSUE TITLE
Save logo appearing when it's not supposed to

### ISSUE THREAD

**Issue by snekyo** [fabiangreffrath/woof#1444]
So I noticed something while running Woof.
When the game boots, the save icon in the bottom right corner pops up for a split second. 
When I press enter to get to the main menu, it appears for a split second again.
Not sure if it's a feature or a bug, and it's possible that it shows up at other points it's not supposed to. Those two are the only ones I can remember right now.

**Comment by rfomin** [comment]
It's not a save logo, it shows reading from the hard drive, it's from vanilla DOS Doom. You can disable it in General->Display->Disk IO Icon.

@fabiangreffrath Should we disable it by default?

**Comment by fabiangreffrath** [comment]
Yes, let's disable it by default. I guess 30 years later the floppy disk metaphor does not work that well anymore.
