### ISSUE TITLE
[Feature] Voxel switch

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#1446]
Now that voxel support has become a prominent feature of this port, I'm wondering whether it might make sense to add a menu option which allows you to toggle voxels. 

Reasoning:
Like this, users could place the voxel pack in their autoload folders and turn it on or off as they please. Especially useful in case a PWAD replaces the default sprites in some way.

**Comment by NightFright2k19** [comment]
Thanks, guys!

**Comment by rfomin** [comment]
> Thanks, guys!

Wait, it hasn't been approved yet.  I think it's a nice option, though.

**Comment by fabiangreffrath** [comment]
> Wait, it hasn't been approved yet. I think it's a nice option, though.

Consider it approved. 😉
