### ISSUE TITLE
[Feature] 'Flashing Keyed Doors' for Vanilla Automap Preset

### ISSUE THREAD

**Issue by Terraformer9x** [fabiangreffrath/woof#1447]
I noticed that Woof's automap doesn't have locked doors flash with the `Flashing Keyed Doors` option turned on while under the vanilla preset.

I'm wondering if the option under the vanilla preset could allow it to replicate how Crispy-Doom displays locked door in it's automap where it flashes between the key color and a dark grey line.

**Comment by fabiangreffrath** [comment]
Yes, right. This isn't strictly Vanilla compatible, of course, but I understand that people got used to it from Crispy. It will look a bit awful, because red and yellow lines are already taken by the Vanilla scheme, but it might still help to make them blink. It can still be disabled after all.

**Comment by Terraformer9x** [comment]
The way Crispy's automap made them stand out more is by having it flash between the key color and dark grey.

![flashlock](https://github.com/fabiangreffrath/woof/assets/83795041/421c6d07-fc8a-4248-8c37-81afcdab69e2)

**Comment by fabiangreffrath** [comment]
> The way Crispy's automap made them stand out more is by having it flash between the key color and dark grey.

Woof now does the same. Well, it was supposed to do so anyway, but there was a bug that prevented this.
