### ISSUE TITLE
crashes when changing resolution while Automap is open

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#1452]
Changing e.g. from 300% to 200% while in the Automap leads to a segmentation fault.

**Comment by fabiangreffrath** [comment]
```patch
--- a/src/am_map.c
+++ b/src/am_map.c
@@ -1051,6 +1051,7 @@ void AM_Ticker (void)
 static void AM_clearFB(int color)
 {
   int h = f_h;
+  fb = I_VideoBuffer;
   byte *src = fb;
   while (h--)
   {
```

**Comment by rfomin** [comment]
> ```diff
> fb = I_VideoBuffer;
> ```

Right, that fixed it for me. Currently we recreate `I_VideoBuffer` when the resolution scaling changes.

**Comment by fabiangreffrath** [comment]
We could just replace `fb` with `I_VideoBuffer` in `src/am_map.c`. 

https://github.com/fabiangreffrath/crispy-doom/commit/04a3d30d3711efe8297fe5730f9c33ea193ef9c0

**Comment by rfomin** [comment]
> We could just replace `fb` with `I_VideoBuffer` in `src/am_map.c`.
> 
> [fabiangreffrath/crispy-doom@04a3d30](https://github.com/fabiangreffrath/crispy-doom/commit/04a3d30d3711efe8297fe5730f9c33ea193ef9c0)

Good idea, I will try it.
