### ISSUE TITLE
STBAR/Fullscreen HUD switch

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#1457]
@liPillON on Discord:
> stbar/hud settings are neatly organized now, but I seem to be having trouble locating the option to switch between the two
I can't find the "screen size" control anywhere
I know there are several default keybinds (F5, KP+, KP-) which would do the job, but new users might be puzzled by the lack of an explicit "use HUD instead of STBAR" option

Should we add "use HUD instead of STBAR" option?

**Comment by ceski-1** [comment]
I was brainstorming a bit earlier and was thinking that we may want to add a "Screen Size" thermo to the "Status Bar / HUD" menu that would replace "HUD Mode". It could look like this:

- `0-7` Smallest to largest status bar sizes, like you typically see in conservative ports.
- `8-10` These have the number replaced with strings that depend on whether the Crispy or Boom HUD is active, same as what "HUD Mode" does now.

That's just a rough idea to help generate discussion.

**Comment by rfomin** [comment]
>  "Screen Size" thermo to the "Status Bar / HUD" menu that would replace "HUD Mode"...

I like the idea.

**Comment by liPillON** [comment]
fwiw, is there still use for screenblocks<10?
I mean, a third option for "hud mode" would be enough.. the screen size thermo is not necessary nowadays imho

**Comment by rfomin** [comment]
> fwiw, is there still use for screenblocks<10?

I saw someone on Jimmy Discord playing the dev build of Woof with screenblocks 9 and scale 100%. 😄 I agree that it's no longer practical, but it reminds vanilla.

**Comment by ceski-1** [comment]
> is there still use for screenblocks<10?

I agree that it's archaic and wouldn't mind seeing it go, but that's just my personal opinion. If we try to build an argument in favor it's basically: the related code is a headache and removing it could lead to a more intuitive HUD menu. Is that strong enough? I don't know.

**Comment by fabiangreffrath** [comment]
I doubt anyone is seriously using it. My guess is that ports keep it as a proof of how faithful to Vanilla they still are. Woof is no exception here. 😉 

I wouldn't mind anymore if we remove it at some point. But please not in this release cycle.

**Comment by ceski-1** [comment]
https://github.com/fabiangreffrath/woof/pull/1479
