### ISSUE TITLE
Lighting is affected by FOV

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1468]
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/7868482791)._

At least up until the last Woof release -- not to say in vanilla -- wall/sprite lighting was partially determined by the scale of the texture.

I'm not sure if the latest Woof master still does that to calculate lighting, but if it does, you can guess that changing FOV affects the scale and therefore lighting of stuff being drawn. This could very well be something you want to keep, but if the FOV range were broader, it would be a bit questionable to be able to see in dark far places by decreasing FOV, or otherwise having reduced visibility when increasing it.

In any case, [this](https://github.com/MrAlaux/Nugget-Doom/commit/99fc0d4fa65fe846211b9f1d3018d3443e1ca3c3) is the solution I employed in Nugget, where `fovdiff = [current FOV] / [original FOV]`.

**Comment by rfomin** [comment]
You may be right, but I can't see it in DOOM2.WAD MAP01. How to spot it?

**Comment by fabiangreffrath** [comment]
Have a look at the two columns with the inverted crosses to the left and right at the start. If you increase FOV and thus zoom out, they appear far away and at value 120 become so dark that you can hardly see the cross contours anymore. If you decrease FOV and thus zoom in, the crosses become more and more visivble until they are outright bright at value 60.
