### ISSUE TITLE
`cosmetic_bobbing` affects "Weapon Recoil" menu item instead of "Weapon Alignment"

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1470]
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/7868482791)._

If you disable `cosmetic_bobbing`, the "Weapon Recoil" item will be disabled instead of the intended "Weapon Alignment" one.

This seems to be because the `weap2` enum has an unused `weap2_title1`, which shifts the values of all other constants in it:
https://github.com/fabiangreffrath/woof/blob/37bed431e993b0a1c1d37cc683a8601cc48cdbb7/src/m_menu.c#L3040-L3046

**Comment by rfomin** [comment]
Fixed in https://github.com/fabiangreffrath/woof/commit/99bb2f1d83de5d316fe0d6840ace9ce08bbc0304 Thanks.
