### ISSUE TITLE
Show crosshair preview?

### ISSUE THREAD

**Issue by ceski-1** [fabiangreffrath/woof#1475]
Should we draw a crosshair preview? Two ideas:
1. Allow `HU_DrawCrosshair()` to execute if the current menu is the crosshair menu. Some of the crosshair menu item names will have to be shortened so the crosshair can be seen. This won't be useful if the menu backdrop is set to texture.
2. Run a function that draws the current crosshair patch to the right of "Enable Crosshair". So it would be "None", "+", etc. instead of "None", "Cross", etc.

**Comment by rfomin** [comment]
> Run a function that draws the current crosshair patch to the right of "Enable Crosshair". So it would be "None", "+", etc. instead of "None", "Cross", etc.

Good idea. Also, I think "chevrons" is by far the best crosshair, what if we put it first in the list?

**Comment by ceski-1** [comment]
> I think "chevrons" is by far the best crosshair, what if we put it first in the list?

Gotta have "+" as the first option. It's an FPS tradition!
