### ISSUE TITLE
Inconsistent free look toggle

### ISSUE THREAD

**Issue by ceski-1** [fabiangreffrath/woof#1476]
Brief overview:

Pressing the free look key while the mouse and gamepad have mismatched states (that is, `mouselook` and `padlook` are different values), results in the wrong "Free Look On/Off" message being printed.

If the key press comes from `ev_mouseb_down` then it makes sense to only change `mouselook`. Same for `ev_joyb_down` and `padlook`. But what about `ev_keydown`? Now we have a problem because we don't know the intent.

https://github.com/fabiangreffrath/woof/blob/aa3425522d42bde451207fe09273d7d50a3d0b1d/src/m_menu.c#L4925-L4932

Other things that may need to be changed for consistency:
- Change string: `key to toggle mouselook` --> `key to toggle free look`
- Change variable: `input_mouselook` --> `input_freelook`

https://github.com/fabiangreffrath/woof/blob/aa3425522d42bde451207fe09273d7d50a3d0b1d/src/m_misc.c#L1179-L1185

**Comment by rfomin** [comment]
> If the key press comes from `ev_mouseb_down` then it makes sense to only change `mouselook`. Same for `ev_joyb_down` and `padlook`. But what about `ev_keydown`? Now we have a problem because we don't know the intent.

The original plan was to have separate inputs for `padlook` and `mouselook`, but we don't have the space.

> Change variable: input_mouselook --> input_freelook

Yes, and we should just enable both `padlook` and `mouselook`. I think it's intuitive.
