### ISSUE TITLE
suggestion: add UMAPINFO support

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#148]
I recently helped add support for UMAPINFO to Doom Retro, but this parser is very relaxed. Or we can use the adapted to C version from the PrBoom libretro port (https://github.com/libretro/libretro-prboom/commit/5a995122e3743aba179cdf1bfeaebc5b47d40304) or write a new parser from scratch. Basically, I excited about this https://www.doomworld.com/forum/topic/120424-wip-epoch-the-xasermap-mixtape-megawad/ and I like the idea of the "Boom-plus-plus" format. What do you think?

**Comment by fabiangreffrath** [comment]
In general, I am not opposed to adding UMAPINFO support, although this is going to be a big, invasive change. For me, it would be alright to use the original C++ parser from prboom-plus 2.6um.

**Comment by rfomin** [comment]
Great! I will try to integrate prboom-plus 2.6um version. But we don't have to support the UM extension demo format, right?

**Comment by fabiangreffrath** [comment]
> But we don't have to support the UM extension demo format, right?

Well, sooner or later we should. But it's okay without it for a start...

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/fcd3df5bbbfe81c2baff3828469e3943e20851a0
