### ISSUE TITLE
Freeze when opening menu in Long Road, No Turns

### ISSUE THREAD

**Issue by jackrjli** [fabiangreffrath/woof#1480]
Opening the menu when playing [Long Road, No Turns](https://www.doomworld.com/idgames/levels/doom2/Ports/j-l/longroad) causes Woof to freeze, forcing me to kill the process to close the game.

OS: Fedora 39
Version: Latest commit as of writing this (d3db71a12e14eccb255ffba9d7e3bfffbd13648c). Issue is not present in the 12.0.2 release.
Config: Default

**Comment by rfomin** [comment]
Fixed in https://github.com/fabiangreffrath/woof/commit/af1f3e6b549b82bba30f0aab19e37c39e4a05830
