### ISSUE TITLE
[Feature] Separate view and weapon bobbing

### ISSUE THREAD

**Issue by jackrjli** [fabiangreffrath/woof#1481]
I'd like to be able to disable view bobbing (camera moving up/down as the player moves) without disabling the weapon bobbing (weapon moving from side to side and up/down). The existing `cosmetic_bobbing` setting is a good start, but the 75% value is still a bit much for me, while 0% looks weird to me with the weapon not moving at all and also prevents one from using the weapon bobbing to time damaging floors.

There are existing implementations in dsda-doom (which has separate on/off switches for view and weapon bobbing) and Nugget Doom (which has a percentage value for view bobbing).

**Comment by fabiangreffrath** [comment]
Yes, that'd be nice.
