### ISSUE TITLE
ST_Init : MorphOS (BE) non official build

### ISSUE THREAD

**Issue by BeWorld2018** [fabiangreffrath/woof#1482]
Hi,
I just build 14.0.0 release and i have some problem to launch Woof:

![image](https://github.com/fabiangreffrath/woof/assets/36823759/68096b81-05f3-47d2-b1b3-c91e615a36fd)

I dont check, maybe you have an idea ?!
Thanks

**Comment by fabiangreffrath** [comment]
Endianess issue: `7936 == 31 << 8`

**Comment by BeWorld2018** [comment]
ok thanks you, 
No more message about Non-standard.
but i have now :
VX_Init : Voxels not found
and game crash

**Comment by BeWorld2018** [comment]
Seem crash inside this function:
https://github.com/fabiangreffrath/woof/blob/master/src/v_video.c#L444
I trace crash with objdump

**Comment by fabiangreffrath** [comment]
This one should now be fixed as well.

**Comment by BeWorld2018** [comment]
lol i test that :-) thanks

**Comment by BeWorld2018** [comment]
![image](https://github.com/fabiangreffrath/woof/assets/36823759/a4fa9b47-5f34-4b32-bb5e-f7976eec7d7e)

Yeaaahh

**Comment by fabiangreffrath** [comment]
Thanks for testing!
