### ISSUE TITLE
Misaligned menu text

### ISSUE THREAD

**Issue by ceski-1** [fabiangreffrath/woof#1483]
Using latest master.

1. Go to Options -> Doom Compatibility.
2. Toggle "Strict Mode".
3. Move away and then back to "Strict Mode".
4. The text "Current Value Differs From Default" is misaligned.

**Comment by rfomin** [comment]
> 4\. The text "Current Value Differs From Default" is misaligned.

Maybe we should remove that warning, I can't remember why it's needed.
