### ISSUE TITLE
Can't have one key to both strafe on + turn left/right

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/woof#1500]
I like to bind `q` to both strafe on (input_strafe) and turn right (input_turnright) so I can do easy SR50 movement by pressing `qwd` at the same time. Currently Woof doesn't seem to allow this; version 12 did, by editing the cfg file.

I also have space set to both use and run (with autorun on, so holding it down functions as walk) and this works fine.

**Comment by rfomin** [comment]
Does DSDA-Doom allow this? Not sure if we want "simple" SR50. We now have the "Auto SR50" option.

**Comment by fabiangreffrath** [comment]
Do we know *why* this is not possible anymore in v14?

**Comment by rfomin** [comment]
> Do we know _why_ this is not possible anymore in v14?

I did some refactoring and probably fixed it (I didn't know about this speedrunning technique). I will investigate.

**Comment by rfomin** [comment]
It is still possible to bind `input_turnright` and `input_strafe` to the same key in config. It works differently from Woof 12.0.2 due to changes in `G_BuildTiccmd`: https://github.com/fabiangreffrath/woof/blob/29687d96a698c99c669050ade095502b4ea98c87/src/g_game.c#L593
@ceski-1  Why has it been changed?

**Comment by ceski-1** [comment]
> @ceski-1 Why has it been changed?

That was a small refactor I did for the mouse and gamepad changes, but the behavior should be identical to before.

**Comment by rfomin** [comment]
> but the behavior should be identical to before.

I think this code is missing, not sure:
https://github.com/fabiangreffrath/woof/blob/f75ebb283f8318f8ed54f1448d1808fce01fb18c/src/g_game.c#L391-L397

**Comment by ceski-1** [comment]
> I think this code is missing, not sure:

It's still there.

**Comment by rfomin** [comment]
> > I think this code is missing, not sure:
> 
> It's still there.

OK, then I don't know. It seems to work the same way as before.

**Comment by ceski-1** [comment]
> OK, then I don't know. It seems to work the same way as before.

I don't know either. I tried a clean config for both Woof 12.0.2 and 14.0.0 with the only changes being `input_turnright` and `input_strafe` bound to `q` and pressing `q + w + d` performs an SR50 the same way in both versions.

@kitchen-ace Can you share your configs for both versions?

**Comment by kitchen-ace** [comment]
>Can you share your configs for both versions? 

Argh, sorry, this was totally user error from using multiple configs. Thanks for investigating anyhow.
