### ISSUE TITLE
Option to disable menu "glow" when navigating with the mouse

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#1504]
Just an idea, not really super important, but an option to disable the glow when selecting a menu item with the mouse would be good for custom menu graphics that might end up looking a bit funky in a "glowing" state.

**Comment by rfomin** [comment]
I have tested a lot of PWADs with custom graphics, it looks OK in most cases. We choose this method of "highlighting" carefully. Do you know of any bad cases?

**Comment by OpenRift412** [comment]
> I have tested a lot of PWADs with custom graphics, it looks OK in most cases. We choose this method of "highlighting" carefully. Do you know of any bad cases?

I thought I did at one point, but I'll have to check again.

**Comment by OpenRift412** [comment]
Okay, maybe I was confusing it with something else, my bad. Still, would be a nice option to throw in the CFG at some point. Not super necessary but yknow

**Comment by fabiangreffrath** [comment]
Sorry, but "might look funky with some custom graphics" is a bit vague. Please come back with an example.

> would be a nice option to throw in the CFG at some point

Sorry, no. We have tried different approaches and have decided that *this* will be how we highlight menu items on mouse hover. Adding a switch for this is exactly the kind of micro-management that we wanted to get rid of.

**Comment by OpenRift412** [comment]
> Sorry, but "might look funky with some custom graphics" is a bit vague. Please come back with an example.
> 
> > would be a nice option to throw in the CFG at some point
> 
> Sorry, no. We have tried different approaches and have decided that _this_ will be how we highlight menu items on mouse hover. Adding a switch for this is exactly the kind of micro-management that we wanted to get rid of.

I think one example of this causing oversights is with menu graphics that introduce a sort of "background".

For example, Plutonia 2's skill select screen:
![image](https://github.com/fabiangreffrath/woof/assets/29780788/4fc1afac-c2aa-4701-ae70-60af4acef36c)

I think it might be worth taking into consideration.

**Comment by ceski-1** [comment]
Maybe something like the following:
Don't apply highlighting on the main menu or the options menu if custom patches are detected and the keyboard or gamepad is the currently active input. The highlighting still seems necessary for mouse input.

**Comment by OpenRift412** [comment]
> The highlighting still seems necessary for mouse input.

I would disagree, since the selection sprite that's shown on the side(s) of the current selection already serves that purpose, but that's ultimately up to you guys, I suppose.

**Comment by rfomin** [comment]
> I think one example of this causing oversights is with menu graphics that introduce a sort of "background".

BTSX series does this correctly:
![woof0000](https://github.com/fabiangreffrath/woof/assets/5077629/e7ae34f0-e8c7-42e4-9094-8085bbb15223)

I know about this issue, but I still think "highlighting" is important. Try mouse in the GZDoom menu which doesn't have it, it doesn't feel right. I agree with Fabian, we don't want too many little options like this.

**Comment by OpenRift412** [comment]
> I know about this issue, but I still think "highlighting" is important. Try mouse in the GZDoom menu which doesn't have it, it doesn't feel right. I agree with Fabian, we don't want too many little options like this.

I do have a counterpoint:

I was talking with @ceski-1 and I came up with the idea of having custom cursor sprites that are scaled to the same resolution as the menu graphics, so I made a set of cursors:
![Woof Cursors Concept](https://github.com/fabiangreffrath/woof/assets/29780788/39c16622-cb11-479d-abcb-e5dab5dcfc9b)

Red would be the standard cursor, yellow is while left clicking, and grey is while right clicking. I made both outline and non-outline variants, the latter of which would need a sort of shadow effect for best visibility (possibly through using the same trick that menu dimming uses)

I think this implementation would help with the visibility issue that you see in say, GZDoom, because in there the cursor isn't scalled at all and is just tiny. But in my concept, they'd be scaled to 200p.

Some additional screenshots:
cursors (scaled in photoshop):
![image](https://github.com/fabiangreffrath/woof/assets/29780788/a308974a-c28c-4c47-a704-03b3f94d20ef)

cursors in relation to Doom's menu resolution:
![image](https://github.com/fabiangreffrath/woof/assets/29780788/404a714b-f489-4eed-b9c9-a3acb9928797)

Of course, this could introduce the possible caveat of issues with custom palettes, but maybe there's a way to implement in a way that makes it either independent of or adaptive to said palettes?

I dunno. Any thoughts on this?

**Comment by ceski-1** [comment]
I think that's a great idea. Even at 2560x1440 the default OS mouse cursor seems too small relative to the rest of the UI. A scaled mouse cursor would be easier to see and make navigating a little easier. No need to change the highlighting in my opinion.

**Comment by rfomin** [comment]
> I came up with the idea of having custom cursor sprites that are scaled to the same resolution as the menu graphics, so I made a set of cursors:

Thanks for the graphics! It's important to have a "system" cursor (at least on Windows) that is independent of the frame rate and has instant response. I think there are some restrictions for this, so scaling and paletted graphics may not work, I haven't tested it yet.

**Comment by OpenRift412** [comment]
> > I came up with the idea of having custom cursor sprites that are scaled to the same resolution as the menu graphics, so I made a set of cursors:
> 
> Thanks for the graphics! It's important to have a "system" cursor (at least on Windows) that is independent of the frame rate and has instant response. I think there are some restrictions for this, so scaling and paletted graphics may not work, I haven't tested it yet.

Actually, I did have a thought: maybe cursor color could be processed in the same way that crosshair color is? Or does that have its own set of issues?

**Comment by rfomin** [comment]
> Actually, I did have a thought: maybe cursor color could be processed in the same way that crosshair color is? Or does that have its own set of issues?

The crosshair is a regular Doom patch. I suspect that the "system" mouse cursor can only be made without palette, so it might not look right with custom graphics menus.

**Comment by fabiangreffrath** [comment]
> For example, Plutonia 2's skill select screen:

This works very well for me. First, it only appears if you actually use the mouse to select the menu items and second, the highlighting makes it clear that you can click anywhere on the skill name patches to select them.

**Comment by fabiangreffrath** [comment]
I don't consider this an issue anymore.
