### ISSUE TITLE
Translucency looks weird at lower resolutions and/or greater distances

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1513]
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/7958321362)._

I'm not sure if this is an issue per se, but as the resolution scale decreases, translucent textures and sprites behave rather weirdly as you get away from them: they look a bit too pixelated and warpy, even a bit fuzzy. It might also be occurring at higher resolutions, but the smaller pixels make it harder to notice. Translucency in Woof 12.0.2 and earlier appears more stable.

I suggest you try it in-game yourselves, but here's a little video showing a window in BOOMEDIT.WAD:

https://github.com/fabiangreffrath/woof/assets/73968015/9896a842-2057-43c0-bc2d-b15f5292b889

Again, this could very well be the intended effect. It just looks weird to me.

**Comment by fabiangreffrath** [comment]
> Translucency in Woof 12.0.2 and earlier appears more stable.

It should look absolutely identical if you lock v14 at 200% resolution.

**Comment by MrAlaux** [comment]
> It should look absolutely identical if you lock v14 at 200% resolution.

Doesn't seem like it:
![ezgif com-added-text](https://github.com/fabiangreffrath/woof/assets/73968015/021d60ab-3bb6-42c7-a6ba-b986152653bf)

The translucency filter percentage is 66 in both. Is there any other setting that could be affecting translucency?

**Comment by fabiangreffrath** [comment]
Is this because we use patch column drawing functions for actual texture drawing?

**Comment by fabiangreffrath** [comment]
Got it!

```patch
--- a/src/r_draw.c
+++ b/src/r_draw.c
@@ -267,6 +267,7 @@ void R_DrawTLColumn (void)
             *dest = tranmap[(*dest<<8)+colormap[brightmap[src]][src]]; // phares
             dest += linesize;   // killough 11/98
             frac += fracstep;
+            src = source[(frac>>FRACBITS) & heightmask];
             *dest = tranmap[(*dest<<8)+colormap[brightmap[src]][src]]; // phares
             dest += linesize;   // killough 11/98
             frac += fracstep;
```

**Comment by rfomin** [comment]
> ```diff
> src = source[(frac>>FRACBITS) & heightmask];
> ```

I can confirm, this fixed it to me. It's the same in Eternity too.
