### ISSUE TITLE
Allow higher mouse sensitivity in the menus

### ISSUE THREAD

**Issue by ceski-1** [fabiangreffrath/woof#1515]
From Maribo:
> you can set the sensitivity values higher than the sliders allow in the cfg (30, 40, 50, etc), but the in-game display will still show 20 at most. not asking for values higher than 20 to be clamped but displaying the value it's set to even when above 20 would be neat

In previous versions of Woof, it was possible to increase mouse sensitivity indefinitely, even when the thermo reached the end. This was pretty nice because the current cap of 20 isn't that fast. I'm not sure if that functionality is compatible with mouse dragging as it might be confusing to see the number continue to rise. So maybe as a compromise the slider range can be increased to some reasonably higher max value.

**Comment by rfomin** [comment]
> In previous versions of Woof, it was possible to increase mouse sensitivity indefinitely, even when the thermo reached the end. 

It still should work if using keyboard/gamepad, I just break it. Fixed here: https://github.com/fabiangreffrath/woof/commit/928311a5742a97e45034cc2b4936fb20a32fb6c8

> So maybe as a compromise the slider range can be increased to some reasonably higher max value.

Yes, probably. How about 50?

**Comment by ceski-1** [comment]
> Yes, probably. How about 50?

I tried it and it seems like a reasonable max value. It wouldn't hurt to get at least one more opinion though.

**Comment by fabiangreffrath** [comment]
As a data point: Crispy goes up to 255.

**Comment by ceski-1** [comment]
https://github.com/fabiangreffrath/woof/commit/928311a5742a97e45034cc2b4936fb20a32fb6c8 and https://github.com/fabiangreffrath/woof/pull/1519
