### ISSUE TITLE
Demo progress bar crash

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/woof#1517]
For some reason (at least on my system) having the demo progress bar turned on crashes the game when the first demo should play.
I'm playing this on a 32 bit Windows 10 system.
This happens regardless of how the game is launched (parameters, PWADs, shortcut/ no shortcut, complevel).
Since the crash always starts with music hanging, I thought it might be an audio-related issue, but neither audio or visual options (fullscreen, exclusive fullscreen, resolution, aspect ratio, vsync) had any effect for me. The only thing that fixed this crash was turning off the demo progress bar.
For Woof 14.0.0 I did the closest thing to a "clean" install, meaning that I deleted everything except for the IWADs and PWADs from my folder, but I'm wondering if there might be other files in other folders that might be causing this.
Demos play without any issues with this option set to 0.

**Comment by rzhxiii** [comment]
I could, but only during the weekend as until then I won't have access to my computer.

**Comment by rfomin** [comment]
> I could, but only during the weekend as until then I won't have access to my computer.

When you get a chance, please test the current master branch, I think it will work.

**Comment by rzhxiii** [comment]
Yep, the current master branch fixes the issue.
