### ISSUE TITLE
Automap map name is placed an extra pixel above the hud.

### ISSUE THREAD

**Issue by Terraformer9x** [fabiangreffrath/woof#1528]
I don't know if this was an intentional change but I noticed that the automap name was a pixel higher off the HUD than usual so I thought to bring it up here.

![amname](https://github.com/fabiangreffrath/woof/assets/83795041/3a46146b-8b18-4d41-88b8-3c46be2f5843)

**Comment by fabiangreffrath** [comment]
Thanks for noticing! I think I'll have to do the following:

```patch
--- a/src/hu_lib.c
+++ b/src/hu_lib.c
@@ -65,7 +65,7 @@ static int align_offset[num_offsets];

 void HUlib_reset_align_offsets (void)
 {
-  int bottom = SCREENHEIGHT - 1;
+  int bottom = SCREENHEIGHT;

   if (scaledviewheight < SCREENHEIGHT ||
       draw_crispy_hud ||
```
