### ISSUE TITLE
Rate widget can overlap with widgets on the other side

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1533]
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/8030788479)._

As the title says, especially at "thinner" aspect ratios.

Here's an example in 4:3 aspect ratio:
![woof0000](https://github.com/fabiangreffrath/woof/assets/73968015/137318df-a2a4-4bd0-8712-bcec66ddc1ea)

Perhaps the Rate widget should be exclusive (i.e. have a whole row for itself) like Messages?

**Comment by rfomin** [comment]
I think the "rate" widget is for debugging/testing, so it's okay if it's not compatible with some HUD configurations.

**Comment by fabiangreffrath** [comment]
We could move the FPS counter to the next line.
