### ISSUE TITLE
[Feature Request] Alternate invulnerability colormap

### ISSUE THREAD

**Issue by trzyglow** [fabiangreffrath/woof#1541]
This feature request is related to additional/optional quality-of-life improvemets.
The main idea is to have a toggleable option to switch the vanilla invulnerability colormap to a colormap which is easier on the eyes, similar to the feature that GZDom has implemented.

The concept visualized:
![ABComp](https://github.com/fabiangreffrath/woof/assets/115739838/d6cd4d95-96d4-456d-9418-83778b1b8b20)

_Note - The Image was edited, the alternative side doesn't incorporate a true doom colormap._

**Comment by Terraformer9x** [comment]
Couldn't this be handled via loading a custom COLORMAP?

**Comment by fabiangreffrath** [comment]
> Couldn't this be handled via loading a custom COLORMAP?

Yes, of course. But we are going to reintroduce the option to let invulnerability affect the sky anyway, so adding a third option with an alternate map was only obvious.
