### ISSUE TITLE
Eviternity WAD's included built-in demos not playing automatically. 

### ISSUE THREAD

**Issue by PerseusAegis** [fabiangreffrath/woof#1544]
For some reason, the included built-in demos for Eviternity do not play automatcally on the main menu title screen. I've done some testing, and built-in demos for other wads play automatically as expected, but not Eviternity. I would try to play Eviternity's manually as a test, but I have no idea how to do that. Tested with Woof versions 14.0.0 & 14.1.0.

**Comment by fabiangreffrath** [comment]
That's because Eviternity's internal demos have been recorded in some PrBoom+-specific demo format (v214) that we just can't play back.

**Comment by PerseusAegis** [comment]
> That's because Eviternity's internal demos have been recorded in some PrBoom+-specific demo format (v214) that we just can't play back.

Ah, I see now. Much thanks for the answer.
