### ISSUE TITLE
Demo header comp array mismatch

### ISSUE THREAD

**Issue by kraflab** [fabiangreffrath/woof#155]
The `comp` list is stored and retrieved from demo headers:

https://github.com/fabiangreffrath/woof/blob/master/Source/g_game.c#L2453-L2457
https://github.com/fabiangreffrath/woof/blob/master/Source/g_game.c#L2539-L2543

A previous PR (https://github.com/fabiangreffrath/woof/pull/45) added `comp_3keydoor == comp_zerotags + 1`.

However, in pr+, we have this:
https://github.com/coelckers/prboom-plus/blob/master/prboom2/src/doomstat.h#L111

That is, `comp_moveblock == comp_zerotags + 1`.

Unfortunately, that means that a demo recorded in pr+ can load into woof with a different `comp` array than what it was recorded with, and vice versa. Since most mbf demos are coming from pr+, I think the pr+ comp indices should be adopted here for compatibility's sake, at least as placeholders (AND we must add `comp_3keydoor` to pr+ to make sure that index isn't used for another purpose):
```c
  comp_moveblock,
  comp_respawn,  /* cph - this is the inverse of comp_respawnfix from eternity */
  comp_sound,
  comp_666,
  comp_soul,
  comp_maskedanim,

  //e6y
  comp_ouchface,
  comp_maxhealth,
  comp_translucency,

  // woof
  comp_3keydoor,
```

Of course, even with the indices matching, the demos might still desync if the logic behind the comp flags isn't implemented as well. I don't know what all of these flags do, if they all affect compatibility, but at least the meaning should be consistent in the header I think.

This is all assuming that you are adopting "prboom-flavoured mbf" compatibility, which I think is what you're working on 🙂 

Btw, `comp_3keydoor` would be number `29`...only 3 left, so let's make them count 😉

**Comment by kraflab** [comment]
Seems like all the "new" comp options I listed there are actually disabled for complevel 11 in pr+, so they are only relevant when recording in the prboom compatibility levels 12-17... Seems like there's no reason to implement that logic in woof since it isn't even implemented for cl 11 in pr+, but putting in placeholders seems like the safe choice. There _are_ plenty of cl 17 demos out there, so I think the cat is out of the bag on that one.

**Comment by rfomin** [comment]
I guess we shouldn't read and write `comp_3keydoor` to demos:
https://github.com/fabiangreffrath/woof/blob/b6b7d999f27d070909faca0ecd0de8c83674a877/Source/g_game.c#L2541-L2542

**Comment by fabiangreffrath** [comment]
I believe @rfomin is right and we should keep `comp_3keydoor` out of the `comp[]` array and handle it as a separate config switch instead.
