### ISSUE TITLE
Partial DBIGFONT support

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#1559]
I think it would be a good idea to have support for DBIGFONT in the case of the main settings menu (plus submenu titles) and for custom episodes menus. Would that be something within Woof's scope?

**Comment by rfomin** [comment]
At least Ancient Aliens, Dimension of the Boomed and Eviternity 1/2 have DBIGFONT in ZDoom's FON2 format: https://zdoom.org/wiki/FON2

Function from SLADE: https://github.com/mykola-ambar/SLADE/blob/d8e9928280d4b1de5b5f7e73739521d0b2cafac7/src/Graphics/SImage/SImageFormats.cpp#L205C12-L205C22

**Comment by fabiangreffrath** [comment]
> Would that be something within Woof's scope?

In general yes, but a major effort obviously.
