### ISSUE TITLE
suggestion: MBF+ / a new complevel

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#156]
I really like this thread: [[doomworld]](https://www.doomworld.com/forum/topic/120616-lets-talk-about-mbf-a-new-complevel/). I think it's wrong that Woof! stuck with PrBoom+ complevel 11.
Current feature / bugfix list:
1. Fix boom generalized crushers.
2. Fix 3﻿key door﻿s﻿.
3. Restore MBF's P_CreateBlockMap().
4. Allow longtics when recording.
5. Add a line that is "block non-flying monsters".
6. Xaser's dehacked pointers [[doomworld]](https://www.doomworld.com/forum/topic/120616-lets-talk-about-mbf-a-new-complevel/?do=findComment&comment=2280349)
7. Instadeath floor [[doomworld]](https://www.doomworld.com/forum/topic/120657-port-compact-doom-format-instadeath-floors/)

What is possible from this list?

**Comment by fabiangreffrath** [comment]
Honestly, I don't see Woof! as such an avant-garde port. If a standard has been established, I am open to apply it. But currently, the main goal for this is still to be MBF ported forward to present day (i.e. not future). :wink: 

Also, how would you like to add support for a new complevel if we don't even have implemented complevels at all, yet?

**Comment by rfomin** [comment]
> don't even have implemented complevels at all

Let's introduce complevels, all demos seem to work, why not?

**Comment by fabiangreffrath** [comment]
> why not?

Laziness :grin:

**Comment by rfomin** [comment]
Okay, I can do PR, but I have a pretty rough implementation - I just change `demo_version`. On the plus side, code changes are minimal.

**Comment by fabiangreffrath** [comment]
Different complevels will require different demo header formats.

**Comment by rfomin** [comment]
I know about demo headers. I've tried implementing this here: https://github.com/fabiangreffrath/woof/pull/157

**Comment by rfomin** [comment]
When implementing complevels, I forgot about `comp_3keydoor`. Maybe we left everything as it is and wait for mbf21 for a proper fix?

**Comment by fabiangreffrath** [comment]
What do you mean? I see `comp_3keydoor` is properly set in `G_ReloadDefaults()` and it's only relevant for Boom abd MBF anyway. 

And what us mbf21?

**Comment by rfomin** [comment]
PrBoom+ complevel 11 does not fix this bug. So if the user records `-complevel mbf` demo, he might desync.
mbf21 is a new standard from dsda_doom.

**Comment by fabiangreffrath** [comment]
So, in Pr+ the bug is present in complevel 11 but fixed in complevel 9 and it will slso be fixed in mbf21, right? We should follow suit then. I guess this will make `comp_3keydoor` entirely obsolete, right?

**Comment by rfomin** [comment]
> I guess this will make `comp_3keydoor` entirely obsolete, right?

Yes, I think so. As far as I know, MBF wads do not use 3-key doors, so we can fix this only for Boom.

**Comment by kraflab** [comment]
One thing I just want to point out is, as it says in that file you linked, the stuff there is not a spec, not final, not anything - it's feasibility demonstration in dsda-doom and a "living proposal" based on what has been implemented and tested, but it's all subject to change (and some of it has changed since you linked that even). I don't want anyone to feel like they wasted time implementing a feature that ends up not being supported in the standard :^)

All that being said I will be super happy if we can bring mbf21 to woof 😉

**Comment by rfomin** [comment]
> not a spec, not final

I know, I follow the development of dsda-doom. Personally, I'm happy with the spec, thank you and Xaser for great work!

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/blob/master/prboom2/doc/mbf21.md

The codepointers are still being worked on, but the rest of the features in there should be pretty safe to start working on if you like, and should be organized a lot better now. I don't expect anything new to be added (besides codepointers).

**Comment by kraflab** [comment]
https://github.com/kraflab/mbf21 here's the official spec release 🙂

**Comment by rfomin** [comment]
Congratulations on the release! I am looking forward to implementing this spec in Woof.

**Comment by kraflab** [comment]
Small v1.1 update to give more control to the wall scrolling speed of the new specials: https://github.com/kraflab/dsda-doom/commit/75618973eb031f91b06ef1dd3961b7cfc1fc92be

**Comment by rfomin** [comment]
Thanks for the update, fixed in https://github.com/fabiangreffrath/woof/commit/289688cf99f9f73948310a725759c20608246116

**Comment by kraflab** [comment]
Another small update for v1.2 (doesn't affect demo sync) https://github.com/kraflab/dsda-doom/commit/08cc8edd46277fd1829f3d7138ee6557298f0b8d
The BOSS flag is redundant now, but this is basically a holdover from eternity / heretic 🤷

**Comment by fabiangreffrath** [comment]
Could you guess how many percent of the spec do we already have implemented in Woof! @rfomin ?

**Comment by rfomin** [comment]
I think 50%. The main part is codepointers. I plan to make big PR this week.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/360a5e87abd9245440435f1ecd2f7e34134d5ce0
https://github.com/fabiangreffrath/woof/commit/08f7d6a7d92fc64ea57551c25711cc4d9d370883
https://github.com/fabiangreffrath/woof/commit/2bcc61d5db4107acb37ddd9dbe1f25846e054d34
https://github.com/fabiangreffrath/woof/commit/289688cf99f9f73948310a725759c20608246116
https://github.com/fabiangreffrath/woof/commit/5502693db0a3a2e5af25c5751684ed1af9183cdb
https://github.com/fabiangreffrath/woof/commit/005e3b0f68e1af92d626f3556739c95dadc1bc7d
https://github.com/fabiangreffrath/woof/commit/107f6f6e52a15784e0bd3e3b251c3fa605a46419
https://github.com/fabiangreffrath/woof/commit/da167a9804fc823abe9138fe3d5693f680693d51
https://github.com/fabiangreffrath/woof/commit/aec69d97c6d741b8f01c8e9c5146d10b9f14bbe3

**Comment by fabiangreffrath** [comment]
Thank you @rfomin !

**Comment by kraflab** [comment]
So cool to have this in woof, thanks for all the hard work!

**Comment by fabiangreffrath** [comment]
Indeed! Did I already say "Thank you @rfomin?", Oh, I did. Never mind: Thank you!

**Comment by rfomin** [comment]
It's a pleasure. I was happy to work on it, it exceeds all my expectations.

**Comment by fabiangreffrath** [comment]
Fine! Is there anything more - apart from some testing, of course - require before the 6.0.0 release?

**Comment by rfomin** [comment]
No, I think it's done. Did you say there is a problem with the autoload directory on non-WIN32 systems, or is it just for Pr+?

**Comment by fabiangreffrath** [comment]
> No, I think it's done. 

Great!

> Did you say there is a problem with the autoload directory on non-WIN32 systems, or is it just for Pr+?

It's not a problem, actually. My issue is that there is currently no way to install system-wide autoload files, they are restricted to the user's config dir in his $HOME. However, a lot of legitimate concern was expressed about the idea to entirely replace hard-coded game logic, e.g. for NERVE.wad, with an autoloaded UMAPINFO lump, that I think the idea is currently laid on ice. The main issue being that the mere introduction of a UMAPINFO lump will currently force usage of the UMAPINFO demo format, which is probably not desired for an official PWAD with dozens of demos already available.

**Comment by rfomin** [comment]
In fact, someone has already tried to play the UMAPINFO demo at Woof/Crispy [[doomworld]](https://www.doomworld.com/forum/topic/118074-dsda-doom-source-port-v0197/?do=findComment&comment=2325332), so maybe we should implement 255 demo extension. It's not difficult, I just don't like it.

**Comment by fabiangreffrath** [comment]
> It's not difficult, I just don't like it.

Me neither. 😁 But we somehow need to indicate UMAPINFO usage in demos, so yes, I think we need it.
