### ISSUE TITLE
[Feature Request] Consumption of extra Dehacked actor obituary strings

### ISSUE THREAD

**Issue by SirBofu** [fabiangreffrath/woof#1562]
In GZDoom, new Dehacked actors can have custom obituaries set. These are consumed from the LANGUAGE lump as follows (the same lump can also be used to change the obituary messages for existing enemies):

`Obituary_Deh_Actor_163  = "%o got melted by the Cybermancubus.";`

Right now, there isn't any parity between Woof and GZDoom in this regard; Woof reads from the DEHACKED lump, which is fine, but only supports the existing obituary strings for existing enemies.

It would be great if we could have Woof consume obituaries for new actors either from LANGUAGE or DEHACKED lumps via the same methodology. The DEHACKED format (assuming it's supported) would be:

`Obituary_Deh_Actor_163 = %o got melted by the Cybermancubus.`

**Comment by fabiangreffrath** [comment]
Do you have a minimal example wad file to show case this issue?

**Comment by SirBofu** [comment]
Much appreciated compliment, @rfomin ! I will work to produce something much simpler and minimal tonight, however.

MAP30 is a good one to test on in the meantime, as there are three different Deh_Actor Things that are monsters throughout the level, though one's projectile produces an additional non-missiles thing that deals radius damage - I wouldn't expect that one to inherit an obituary to the original monster.

**Comment by fabiangreffrath** [comment]
> `Obituary_Deh_Actor_163 = %o got melted by the Cybermancubus.`

This concept doesn't distinguish between distant and melee attacks?

**Comment by SirBofu** [comment]
> > `Obituary_Deh_Actor_163 = %o got melted by the Cybermancubus.`
> 
> This concept doesn't distinguish between distant and melee attacks?

If I recall correctly, the GZDoom handling is to append _Melee to the end of the monster class name for defining a melee obituary.
