### ISSUE TITLE
crosshair fuzzy targets

### ISSUE THREAD

**Issue by KABOM93** [fabiangreffrath/woof#1569]
add the option to turn on crosshair highlight on spectres

**Comment by fabiangreffrath** [comment]
I'm not going to change this.

**Comment by MrAlaux** [comment]
I hope you don't mind self-promotion, but [my fork of Woof](https://github.com/MrAlaux/Nugget-Doom) has the feature, among others.

**Comment by KABOM93** [comment]
> I hope you don't mind self-promotion, but [my fork of Woof](https://github.com/MrAlaux/Nugget-Doom) has the feature, among others.
> 
> Actually, I'll take the chance to ask: @fabiangreffrath, do you mind if I direct people towards Nugget in cases like this one, where Nugget has a feature that Woof doesn't and probably won't have?

yeah i know nugget actually tho there is a problem with the resolution. i have a 4k monitor so 1800p looks so close yet so far from native and also on the sides its wierdly pixelated

**Comment by MrAlaux** [comment]
> > I hope you don't mind self-promotion, but [my fork of Woof](https://github.com/MrAlaux/Nugget-Doom) has the feature, among others.
> > Actually, I'll take the chance to ask: @fabiangreffrath, do you mind if I direct people towards Nugget in cases like this one, where Nugget has a feature that Woof doesn't and probably won't have?
> 
> yeah i know nugget actually tho there is a problem with the resolution. i have a 4k monitor so 1800p looks so close yet so far from native and also on the sides its wierdly pixelated

Hopefully soon, I'll make a new official release merging Woof's new features, including the higher resolutions; they're already available in the latest autobuilds, actually.
