### ISSUE TITLE
[feature request] allow control of fluid_synth_set_gain in config

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/woof#1570]
In Crispy Doom the option `fsynth_gain` is passed to fluidsynth directly, controlling its internal gain.

In Woof, `mus_gain` is passed to OpenAL, while `fluid_synth_set_gain` in `i_flmusic.c` is fixed at 1.0.

(I'm sure there are other differences in music playback.)

The issue is that if you have a loud soundfont and/or midi, fluidsynth will distort if its gain is too high. In Woof if it distorts, lowering the `mus_gain` just makes the overall output quiter but doesn't fix the distortion -- I guess the output is being passed to OpenAL before any volume adjustment is made. Recompiling with a lower `fluid_synth_set_gain` does reduce or eliminate the distortion, though.

Having the `mus_gain` setting control fluidsynth directly, or adding another config option to control it, would solve the problem. 

(In an ideal world the music volume slider in sound options would control this gain instead, though I'm unsure if this presents any other problems from `fluid_synth_set_gain` being too low; knowing fluidsynth it's not out of the question. In any case this is a more invasive change and not all that necessary.)

Here's an example overly loud midi inside a wad for MAP01. It uses duplicate notes which some midi playback systems (like Windows General Midi) will basically ignore, but in FluidSynth it should be fine. 
[loudmidi.zip](https://github.com/fabiangreffrath/woof/files/14539084/loudmidi.zip)

**Comment by rfomin** [comment]
With #1571 Fluidsynth gain will be lower for most users, but I think that's fine as it's too loud now.

> In an ideal world the music volume slider in sound options would control this gain instead, though I'm unsure if this presents any other problems from `fluid_synth_set_gain` being too low;

This is how it worked until Woof 14.2.0. We have simplified the music backends a bit, now we control the gain via OpenAL.

**Comment by kitchen-ace** [comment]
>This is how it worked until Woof 14.2.0

Yeah I thought it was a new problem but I couldn't be sure. 

0.2 should definitely be low enough.

**Comment by rfomin** [comment]
Interestingly, the default has recently been changed to 0.6:
https://github.com/FluidSynth/fluidsynth/commit/bd04f3f6c81a114f3ad52c8e29be3b44dccd010f#diff-82123927c0d3484c50a583467cc7e6f9e8d674c51ab75d77ea71acb8d78ec06cR226

**Comment by kitchen-ace** [comment]
Maybe it should be set explicitly at a lower value, then? 0.6 is still (slightly) high IMO.
