### ISSUE TITLE
framerate problem only on internet servers

### ISSUE THREAD

**Issue by IIFirenII** [fabiangreffrath/woof#1572]
Hello
I have some framerate problem when I launch or join a server (as you can see in the video), im not very good in computer science so maybe it's easy to fix, but I couldn't find the solution by myself. I disable/enable vsync, change screen resolution, change framerate (in game and on my screen) but nothing. The strangest thing (for me) it's that work perfectly in solo :(
(sorry if this issue is allready fixed in an other post)

https://github.com/fabiangreffrath/woof/assets/162725574/07b26709-588d-46ac-9b32-42c9144f6287

**Comment by rfomin** [comment]
Try creating a multiplayer game with the `-oldsync` command line parameter, you will get a "smooth" interpolated player view, but worse lag.
The default "newsync" mode only looks stable in "capped" mode (35 fps). We have plans to improve this.

**Comment by IIFirenII** [comment]
omg thank you so much it's working! :D
