### ISSUE TITLE
Load a saved game without close the server

### ISSUE THREAD

**Issue by IIFirenII** [fabiangreffrath/woof#1574]
Hello,

I think it's a very specific request, maybe it's possible but I don't find where. I explain:
A friend and I would like to speedrun ep1 of Doom II HoE in uvmax, the problem is if we want to train a specific level which need weapons from levels before we need to restart the server, use the command "-loadgame n" and then restart it to the saved level we want to do, that's a bit annoying.

Maybe I am completely stupid and there is a method to avoid that, but I can't find it... I feel very dumb to create a ticket for that, but on the other hand I want to know if there is a solution for my problem...

Sorry for the inconvenience

**Comment by rfomin** [comment]
It sounds like you're doing everything right, if I understand correctly.

Currently our multiplayer is very similar to vanilla Doom (it is compatible with Chocolate Doom). We have plans to improve it while maintaining compatibility. If successful, we will add the ability to load the game from the menu while in net game.

**Comment by IIFirenII** [comment]
Okay, thanks for your reactivity, we will be patient then!
