### ISSUE TITLE
warping to a map from the command-line always starts me rotated

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/woof#1594]
If I run `woof -warp 1` for example I will start rotated to the right. The amount seems to be based on the mouse sensitivity/acceleration; turning mouse sensitivity to 0 means I'm not rotated.

Any other time I start a map, like through the new game menu or if I hit the "restart map" key, I'm facing the right way.

Using Linux, woof git compiled from source.

**Comment by ceski-1** [comment]
This happens with Woof 12.0.2 on Linux as well. It seems like depending on where the mouse is positioned on the screen and how it's grabbed, the view will be randomly rotated.

**Comment by kitchen-ace** [comment]
I did notice it on previous versions of Woof but it seemed like it wasn't as bad -- maybe different mouse settings, maybe I just wasn't as attentive at the time.

**Comment by mikeday0** [comment]
I'm not able to reproduce this on any recent version of Woof. I'm on Ubuntu 22.04. I wonder if this issue depends on SDL version.

**Comment by rfomin** [comment]
I can't replicate it in Arch Linux (SDL 2.30) either. @kitchen-ace, could you try AppImage?

It's possible to move the mouse during the wipe phase, but this is vanilla behaviour (tested in Chocolate Doom and Doom v1.9 in DosBox).

**Comment by kitchen-ace** [comment]
Indeed, this doesn't happen with the AppImage.

@ceski-1 is right that the position of the cursor on screen when Woof is started affects the amount of rotation, but it's not a strict one-to-one mapping as far as I can tell.

It's definitely not mouse movement during the wipe phase. Actually if I disconnect all pointer devices the map starts with me facing in the proper direction. However even with just the laptop trackpad on and the cursor somewhere other than the left of the screen, rotation still occurs.

**Comment by ceski-1** [comment]
For me, it happens with the AppImage, the latest release, older versions, etc. This is on Arch with SDL 2.30.1-1. What appears to be happening is the mouse capturing is inconsistent. Sometimes you can see the "I" mouse cursor for a split second, sometimes it stays visible until the mouse is moved, and in both instances the view will suddenly rotate. This doesn't have anything to do with turning during a wipe.

**Comment by rfomin** [comment]
Maybe it's a mouse driver issue? I use a very basic Logitech M100 mouse.

**Comment by MrAlaux** [comment]
FWIW, this also happens on my Win7 machine with Nugget builds I made, even with a fresh config file -- I do have a rather-outdated SDL 2.24.1-1, though.

On the other hand, judging from some quick testing, the latest [Woof](https://github.com/fabiangreffrath/woof/actions/runs/8300926191) and [Nugget](https://github.com/MrAlaux/Nugget-Doom/actions/runs/8304824461) master artifacts (x64) don't have the issue.

**Comment by ceski-1** [comment]
I can make this happen with Chocolate Doom when setting `startup_delay` to `0`. Built from latest master.

**Comment by rfomin** [comment]
I don't understand, does it depend on the SDL version? I can't replicate it with anything.

I also use the basic X11/xfce4 configuration on Arch.

**Comment by ceski-1** [comment]
This feels like an SDL issue so far.

**Comment by kitchen-ace** [comment]
I am also using KDE Plasma. (On x11 in case that matters.)

**Comment by ceski-1** [comment]
> I also use the basic X11/xfce4 configuration on Arch.

I just tried xfce and it happend in fullscreen but not windowed.

**Comment by rfomin** [comment]
> I just tried xfce and it happens in fullscreen but not windowed.

I can confirm - it only happens to me in borderless fullscreen. Works fine in exclusive fullscreen mode. Looks like an SDL issue.
