### ISSUE TITLE
"A secret is revealed!" message prevents the crosshair from being drawn

### ISSUE THREAD

**Issue by Ciliane** [fabiangreffrath/woof#1598]
Somewhat niche and minor bug, secret revealed message interferes with crosshair which will be invisible for as long as the message text is on screen. First noticed in 14.2.0 but this happens in 14.3.0 as well.

**Comment by ceski-1** [comment]
This seems like a feature, not a bug? Otherwise the crosshair may interfere with the ability to read the secret notification. It's been like this for two years: https://github.com/fabiangreffrath/woof/commit/a8d0cda6f70bc6d7b23b25fea87ef746a9c85b7d

**Comment by rfomin** [comment]
We can move the secret message higher, above the crosshair. The current position is taken from PrBoom+.

**Comment by fabiangreffrath** [comment]
If both fit, let's draw both. 🤷 

Related:
https://github.com/coelckers/prboom-plus/commit/b2503fa073298ead6b10a74ca5d0f0ca2d9b27d2

**Comment by fabiangreffrath** [comment]
> it seems to be already high enough to not overlap even with big cross, unless using lock on target

Eh...

![woof0001](https://github.com/fabiangreffrath/woof/assets/6449237/ee17a44f-b877-4ee1-b8e0-f3513358d695)

**Comment by fabiangreffrath** [comment]
Same in PrBoom+:

![doom02](https://github.com/fabiangreffrath/woof/assets/6449237/ad47dc1b-0fb4-40f1-aa15-52b42854d971)
