### ISSUE TITLE
Dark strips of light on very-close walls

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1603]
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/8320355314)._

If I get very close to a wall texture (either a midtex, or a solid one-sided wall by using noclip), some sort of banding is visible on it. If you look closely enough, you can even see a smooth transition between the properly-lit strips and the dark ones.

See for yourself:
![woof0001](https://github.com/fabiangreffrath/woof/assets/73968015/660e58ee-6708-4898-a047-a9436f691812)

The resolution is shown on the image because the number of strips seems to be tied to it: more, thinner strips appear at higher resolutions.

This doesn't occur in 12.0.2:
![woof0000](https://github.com/fabiangreffrath/woof/assets/73968015/2c6a4f98-2f85-4a89-8f8e-0d6490123814)

Planes may also be affected, but I had no handy way to get close enough to the floor or ceiling to check.

**Comment by rfomin** [comment]
I can't get this problem, does it only manifest when using noclip? I don't think this is worth investigating.

**Comment by MrAlaux** [comment]
> Do you have a practical example/save?

I'm afraid I just got off my computer, so I can't provide the save I used for the screenshots until tomorrow.

> Also how it works in other ports (DSDA/Eternity)?

Haven't checked.

**Comment by fabiangreffrath** [comment]
But it only occurs if you get close to a wall using the noclip cheat?

**Comment by fabiangreffrath** [comment]
I guess that's just Doom's renderer, which has to scale wall textures according to the distance of the view point to the wall. And if you get closer to the wall than the engine usually allows, you have to divide by numbers very close to zero. And thus some single pixels are scaled up by absurd amounts.

**Comment by MrAlaux** [comment]
> But it only occurs if you get close to a wall using the noclip cheat?

Again, it happens with mid-textures too, no noclip required. I tried a white-marble (?) fake wall with some pinkies behind in Doom2 Map29, and albeit hardly visible, the banding was there.

> I guess that's just Doom's renderer

Maybe, but I never noticed this in previous Woof releases. To test this (and to take the screenshots you see above), I noclipped into a wall in 12.0.2 and made a save that I then loaded in the latest master; sure enough, the banding was nowhere to be seen in 12.0.2 but then appeared in the latest master.

**Comment by MrAlaux** [comment]
Alright, here's a zip with saves:
- `woofsav0` is the very save I used to take the screenshots above (Doom2 Map01)
- `woofsav1` is a new save made in another wall where the effect is much more noticeable (same map as above)
- `woofsav2` is another new save made in a midtex (Doom2 Map28 -- I mistakingly said Map29 in my previous comment)

[woofsav.zip](https://github.com/fabiangreffrath/woof/files/14643551/woofsav.zip)

All saves were made in Woof 12.0.2, so you can load them there to compare.

<details>
<summary>Screenshots</summary>

`woofsav1`, 12.0.2:
![woof0001](https://github.com/fabiangreffrath/woof/assets/73968015/e15830c9-0d17-4375-a8bd-22455212b45f)

`woofsav1`, latest master:
![woof0001](https://github.com/fabiangreffrath/woof/assets/73968015/214fafbb-66ac-499e-a71a-7dffa2ef4ecf)

`woofsav2`, 12.0.2:
![woof0002](https://github.com/fabiangreffrath/woof/assets/73968015/ddce44f1-fe64-4fc7-a60f-d7f4ea7b1859)

`woofsav2`, latest master:
![woof0002](https://github.com/fabiangreffrath/woof/assets/73968015/28947e31-b931-4de6-b431-03a0dae79ea8)
</details>

**Comment by rfomin** [comment]
Thanks for the saves.

I still think it's not a very practical issue - it took me a while to stand like that in vanilla Doom on DosBox 😄  [DOOMSAV0.zip](https://github.com/fabiangreffrath/woof/files/14643842/DOOMSAV0.zip) (also works in Choco/Crispy). Indeed, it seems that Woof doesn't draw this as vanilla Doom, but I think this issue is very low priority.
