### ISSUE TITLE
No HOMs with dark overlay

### ISSUE THREAD

**Issue by jackrjli** [fabiangreffrath/woof#1609]
The hall of mirrors effect doesn't work when the dark overlay is active; missing textures render as black.
Screenshot from wow.wad:
![darkhom](https://github.com/fabiangreffrath/woof/assets/2382506/7a36192c-4026-4297-b4ac-3416a39fc2c2)

**Comment by rfomin** [comment]
Fixed in https://github.com/fabiangreffrath/woof/commit/e81db0ae778da97052b231093034b2e70fa984e1
