### ISSUE TITLE
Credits Screen Swap?

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#161]
I was thinking, would it be possible to make it so after the first title screen demo, it uses the IWAD/PWAD credits screen instead of showing Woof's credit screen? Woof's credits could be shown after the second demo as a compromise, or have it emulate vanilla behavior and go back to the title screen after the second demo.

Main reasoning is when you load a PWAD in Woof it would give the WAD authors priority in terms of credit.

**Comment by fabiangreffrath** [comment]
I guess we could add a check to `M_PageDrawer()` if a `CREDIT` lump has been loaded from a PWAD and draw that instead of calling `M_DrawCredits()` if `pagename == NULL`.

**Comment by rfomin** [comment]
Or we could make M_DrawCredits() closer to PrBoom+'s variant. Personally, I vote for vanilla behavior.

**Comment by fabiangreffrath** [comment]
I'd rather not revert an MBF-specific change back to Vanilla behavior. However, I agree that a PWAD's credit screen should have precedence over Woof's own. 

Would exchanging the third and fifth block in `demostates[][]` come close enough?

**Comment by rfomin** [comment]
> Would exchanging the third and fifth block in `demostates[][]` come close enough?

Good enough for me.

**Comment by OpenRift412** [comment]
> I'd rather not revert an MBF-specific change back to Vanilla behavior. However, I agree that a PWAD's credit screen should have precedence over Woof's own.
> 
> Would exchanging the third and fifth block in `demostates[][]` come close enough?

Both the PWAD and IWAD credit screen should have precedence in my opinion, for consistency's sake.

**Comment by fabiangreffrath** [comment]
A PWAD always overrides an IWAD's credit screen,  they are never shown in the same loop.

**Comment by fabiangreffrath** [comment]
Sorry, I guess I have misread your message. With my proposed change, the CREDIT screen will appear after the first demo - no matter if from a PWAD or IWAD -  and the Woof! credit screen will appear after the second demo.

**Comment by OpenRift412** [comment]
Tested the current version, works for Doom II, but not for Ultimate Doom. It just takes you bake to the title screen after the first demo.

**Comment by fabiangreffrath** [comment]
Because that's what would have happened after demo2 before.

**Comment by OpenRift412** [comment]
> Because that's what would have happened after demo2 before.

I see. Do you plan on changing that behavior for Ultimate Doom?

**Comment by fabiangreffrath** [comment]
Sure, what do you suggest?

**Comment by OpenRift412** [comment]
> Sure, what do you suggest?

Probably doing an order like this:

DEMO1>WAD Credits>DEMO2>Woof Credits>DEMO3>DEMO4
