### ISSUE TITLE
View border and status bar background overlap when vertical widget layout is enabled

### ISSUE THREAD

**Issue by xemonix0** [fabiangreffrath/woof#1616]
Woof version: 14.3.0
Vertical Layout: ON
![vertical_layout_on](https://github.com/fabiangreffrath/woof/assets/76173331/e70655ca-3ea6-43a0-80b9-488b11763119)

Vertical Layout: OFF
![vertical_layout_off](https://github.com/fabiangreffrath/woof/assets/76173331/3c79e32c-4fb4-4057-a11e-15003e485404)

**Comment by fabiangreffrath** [comment]
Something seems to be odd with the `HU_Erase()` function.
