### ISSUE TITLE
HOM in Automap with solid background

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1624]
_Tested in the [almost-latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/8428043530)._

See for yourself, on top of the Status Bar:
![woof0001](https://github.com/fabiangreffrath/woof/assets/73968015/c573463f-e7c1-4069-a67d-93eaa0c469bd)

My native resolution (the one shown in the screenshot) is the only one with which I could get the HOM to manifest. Of course, I couldn't try higher resolutions.

**Comment by MrAlaux** [comment]
I just realized: perhaps this issue is what https://github.com/fabiangreffrath/woof/issues/1601#issuecomment-2002443412 was referring to?

**Comment by rfomin** [comment]
> I just realized: perhaps this issue is what [#1601 (comment)](https://github.com/fabiangreffrath/woof/issues/1601#issuecomment-2002443412) was referring to?

Yes, probably. It seems that the st_bar coordinates are not always correct, I will investigate.
