### ISSUE TITLE
Yellow keycard is displayed in place of the blue skull key on Boom HUD

### ISSUE THREAD

**Issue by xemonix0** [fabiangreffrath/woof#1627]
Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/8447502663)
The issue was introduced in this commit: https://github.com/fabiangreffrath/woof/commit/b32c4df60f0405184d357e1ec16488664206fa0a
Commenting out the line that specifies the locale fixes the issue:
https://github.com/fabiangreffrath/woof/blob/bb47d3f103b83555cb453f9b0ebd25267bffbf47/src/i_main.c#L55-L57

**Comment by ceski-1** [comment]
I don't see how those two things are related. Everything looks normal to me:

https://github.com/fabiangreffrath/woof/assets/56656010/8edbdba8-153f-4587-83ff-6fd5fdcd294a

Test wad: [keys.zip](https://github.com/fabiangreffrath/woof/files/14784358/keys.zip)

**Comment by MrAlaux** [comment]
I also fail to understand how they could be related, but if it's a locale issue, then it makes sense that it would behave differently across different machines with different locales. If @xemonix0 could tell us which locale is being set in their case, maybe we could try setting it ourselves to potentially reproduce the issue.

**Comment by fabiangreffrath** [comment]
That's somehow illogical, because according to `setlocale(3)`:

> On startup of the main program, the portable "C" locale is selected as default.

**Comment by xemonix0** [comment]
How is that illogical, though? Doesn't it mean that both `setlocale(LC_TIME, "C")` and not calling `setlocale` set the locale to the "C"? This aligns with what I said - the issue doesn't appear when the line is removed and when the locale is manually set to "C".

To recap, the bug occurs with all locales I've tested except the "C" locale.

**Comment by fabiangreffrath** [comment]
It's illogical that all locales are left at "C", except for the one that's responsible for *time strings*, which is set to *your system's own current locale*, and this should affect the key display in the HUD? 🤷

**Comment by rfomin** [comment]
I can confirm, ideed `setlocale(LC_TIME, "");` somehow affect blue skull display in Boom HUD. Tested on Win10, latest MSVC/UCRT.

**Comment by fabiangreffrath** [comment]
Maybe it's the format string in
https://github.com/fabiangreffrath/woof/blob/b6f7bfead8a4d4ed9c41220393d03dd2be508c4f/src/hu_stuff.c#L463

**Comment by rfomin** [comment]
This fixed it for me, also the time locale works correctly (dd:mm:yyyy in my locale)
```diff
diff --git a/src/i_main.c b/src/i_main.c
index 76d0ab1..b654fb8 100644
--- a/src/i_main.c
+++ b/src/i_main.c
@@ -53,7 +53,7 @@ int main(int argc, char **argv)
    myargv = argv;
 
    // Print date and time in the Load/Save Game menus in the current locale
-   setlocale(LC_TIME, "");
+   setlocale(LC_ALL, ".UTF-8");
 
    I_Printf(VB_ALWAYS, "%s (built on %s)\n", PROJECT_STRING, version_date);
 
```
Not sure if it's compatible with Win7 and other operating systems.

> Maybe it's the format string in

This seem to work correctly.

@fabiangreffrath Maybe we shouldn't use the same font printing function for key patches?

**Comment by MrAlaux** [comment]
> Not sure if it's compatible with Win7 and other operating systems.

I can try it later, although FWIW, I didn't get the key mismatch to begin with.

**Comment by rfomin** [comment]
> I can try it later, although FWIW, I didn't get the key mismatch to begin with.

We need to test it with static CRT (like our release binaries). If you are using your system CRT behaviour may be different. I will make PR for artifacts.

**Comment by fabiangreffrath** [comment]
If this is some unicode/codepage thing, we could embrace your fix in an `#if MSVC` macro. Linux always uses unicode, and apparently MinGW/MSYS2 as well.

**Comment by rfomin** [comment]
> If this is some unicode/codepage thing, we could embrace your fix in an `#if MSVC` macro. Linux always uses unicode, and apparently MinGW/MSYS2 as well.

MSYS2 MinGW/Clang uses Windows UCRT and behaves the same way. The problem may be in the `toupper` function.

**Comment by fabiangreffrath** [comment]
> The problem may be in the `toupper` function.

Good point. We could restrict its usage to actual letters and be done with it.

**Comment by rfomin** [comment]
We decided to just remove the `setlocale` call from the Windows version for now: https://github.com/fabiangreffrath/woof/commit/4aab690db399f9022f7972c42cd4b8e7681094d7
