### ISSUE TITLE
Sky is lower than it should be

### ISSUE THREAD

**Issue by Terraformer9x** [fabiangreffrath/woof#1639]
I noticed that Woof renders skies lower than they should be in Vanilla. Oddly, increasing the screen resolution up to native shifts it almost back up to where it should be.

![woofsky](https://github.com/fabiangreffrath/woof/assets/83795041/14c5149d-535f-4ed2-9f74-76ce5897bed8)

**Comment by ceski-1** [comment]
This should be fixed already: https://github.com/fabiangreffrath/woof/pull/1608/files

**Comment by Terraformer9x** [comment]
Oops, I should've checked with the latest commit first.

In that case, I'll close.
