### ISSUE TITLE
[Feature Request] Disable or improve sound pitch randomization for Moving Floors/Elevators and Explosions

### ISSUE THREAD

**Issue by bangstk** [fabiangreffrath/woof#1646]
This may be personal preference but hear me out:

Sound Pitch Randomization helps monsters feel more unique from each other when you're shooting a bunch at once, but it has a really offputting 'phasing' effect when a very multisectored floor is lowered, which happens in many maps. Additionally explosions from the Icon of Sin have the same effect. This is caused by many copies of the identical sound being played at just about every pitch in the random range at once.

So, I propose an option (or permanently making it) so that specifically the sounds: sfx_stnmov and sfx_barexp, do not have pitch altered by pitch randomization, regardless of whether you have pitch randomization enabled.

I don't think this takes anything away from fans of the random pitch option, and makes it more palatable to try for those who are not.

I understand that not every instance of the 'phasing' effect can be removed simply due to the nature of randomized sound pitches, but these are the cases where it is by far the most egregious.

I'll say outright that Chocolate Doom has the same 'phasing' effect with those sounds, but since vanilla accidentally removed random sound pitch entirely, I think it's fair to try to improve the random pitch option just a little bit.

GZDoom doesn't seem to have this problem - I'm not sure what it does differently but it sounds much more pleasant with random pitch enabled. I think mainly in GZDoom each sector keeps its same randomized pitch until it stops moving, rather than randomizing it every time its loop sound restarts. This naturally spaces out the overlapping sounds so that they do not all play at the same time. And maybe it's further delaying some of the overlapping sounds so that they don't all trigger at once. But short of doing GZDoom's more advanced sound engine, simply disabling random pitch for the plats/explosions should still make it a lot more tolerable.

Below are some recordings of what I am talking about and without it.
[Platforms - With Random Pitch](https://www.dropbox.com/scl/fi/2jw2gu9u1xft8izrtx26j/loweringfloors_random_pitch.mp3?rlkey=bdlol2begs8pf7iq0flvnveft&dl=0)
[Platforms - With Their Random Pitch Commented Out](https://www.dropbox.com/scl/fi/9hkk73gyozkeb83207rkw/loweringfloors_no_random_pitch.mp3?rlkey=lcocki6guwyaap05blidvym3f&dl=0)
[Icon Of Sin Dying - With Random Pitch](https://www.dropbox.com/scl/fi/jfo87d7q1qbarkzslujor/iconofsindie_random_pitch.mp3?rlkey=0ps20jzi4b4qhmblpmt2twf8w&dl=0)
[Icon Of Sin Dying - With Their Random Pitch Commented Out](https://www.dropbox.com/scl/fi/d1zu2542fjm34ietnwe3s/iconifsindie_no_random_pitch.mp3?rlkey=q51144yny21imlm1z2azntz2j&dl=0)

[Platforms - With Random Pitch - GZDoom](https://www.dropbox.com/scl/fi/8s7k4n6op0lwucy8m2g09/loweringfloors_random_pitch_gzdoom.mp3?rlkey=zv8fygasp72tfwtu6uquuk4u6&dl=0)

**Comment by fabiangreffrath** [comment]
> but since vanilla accidentally removed random sound pitch entirely, I think it's fair to try to improve the random pitch option just a little bit.

Very good point! I wonder if we should implement this based on the actual sound (e.g. `sfx_barexp` does not get pitch shifting) or based on the situation in which it gets played (e.g. sounds played from `A_BrainExplode()` do not get pitch shifting).
