### ISSUE TITLE
missing Boom HUD in latest dev build

### ISSUE THREAD

**Issue by liPillON** [fabiangreffrath/woof#1648]
Hi guys
so I just downloaded the latest auto build, to try out the latest midi changes.
I launched the program and noticed how the boom hud does not show up.

So I tried again with a fresh config file and no autoloaded pwads: same result.

Step to reproduce:
1. download the win64 artifact from [this](https://github.com/fabiangreffrath/woof/actions/runs/8734058675) workflow run
2. unzip the archive somewhere
3. place an iwad (i used the shareware doom one) alongside the executable
4. launch the game and go to the statusbar/hud setting page
5. set the screen size to "fullscreen"
6. try to change the hud mode to "crispy" and then back again to "boom"

**Comment by fabiangreffrath** [comment]
> 3. place an iwad (i used the shareware doom one) alongside the executable

Yep, that's the culprit. The HUD definitions are now autoloaded, but autoloading is forbidden for the Shareware IWAD. I'll have to change that.

**Comment by liPillON** [comment]
oh I did not realize that a WOOFHUD lump must now always be present for the Boom HUD do function properly

**Comment by fabiangreffrath** [comment]
Yes, and it was meant to be always available. I de-hardcoded the HUD and moved it out from the source code into the definition file.

**Comment by liPillON** [comment]
Thank you!

I'll add a couple consideration, though: 
- why de-hardcoding the boom hud and leave the crispy hud in? (I'd say the reasoning here is that only the former can be user-manipulated - so no real complaints here)
- having the boom hud being available only when a proper woofhud lump has been loaded, means being unable to test the hud against different pwads (usually I try new pwads using the `-NoAutoLoad` parameter to avoid/identify potential conflicts) 

What about shipping a "woof.wad" which would always be loaded on startup regardless of the autoload status/contents? 
Some ports do this for de-hardcoded core functionalities (eg: dsda-doom.wad, gzdoom.pk3w).
