### ISSUE TITLE
Coop is very choppy

### ISSUE THREAD

**Issue by Aaron03071991** [fabiangreffrath/woof#1652]
Hello there

So i decided to play coop game with my kid.
Setting up coop game in woof-setup works fine, all good here.

But when we entered game, it was extremely choppy, its like game would repeat each frame few times before turning camera.
Running in 120, 60 and 35 fps doesnt solve the issue.

Link to vid of this issue [MEGA](https://mega.nz/file/L4YlxTQJ#a7QRZWyTk1cZon63TQ6gJKlpBGmC4XjzZC1dQYWjpNk)

**Comment by rfomin** [comment]
Try runing the game with `-oldsync` command line parameter.

**Comment by Aaron03071991** [comment]
Thanks!

Works now like a charm.

**Comment by fabiangreffrath** [comment]
We need to do something about this. Either default to oldsync, or force disable uncapped framerate, or at least print a warning to command line.

**Comment by rfomin** [comment]
I think we can try to make oldsync the default for now.

**Comment by Aaron03071991** [comment]
> We need to do something about this. Either default to oldsync, or force disable uncapped framerate, or at least print a warning to command line.

Uncapped fps was on (i mentioned 35 fps in 1st post), didnt change much tbh.

**Comment by rfomin** [comment]
> Uncapped fps was on (i mentioned 35 fps in 1st post), didnt change much tbh.

By default, "newsync" (it's from Chocolate Doom) is optimised for "capped" mode ("uncapped" is off). It looks very choppy unless you set your monitor to 70Hz, but even then it's not good. We plan to improve this in the future.

**Comment by Aaron03071991** [comment]
Wouldn't 120Hz CRT display it without an issue? (Yeap, I play on good old CRT, "Boomer" thing).

I could ofc swich my CRT to 70Hz (would have to actually force it in driver, as after 60Hz next thing for me is 75Hz in nVidia CP).

Still, game even without interpolation was choppy, less ofc, but still choppy. Someone could say 35 FPS feels that way, but nope, single player 35 FPS feels different than 35 FPS with "newsync".

PS. Footage was from kids laptop, only 60Hz LCD panel there.

**Comment by rfomin** [comment]
> Wouldn't 120Hz CRT display it without an issue? (Yeap, I play on good old CRT, "Boomer" thing).

Yes, a CRT should display it well (although I didn't have one).

 > Still, game even without interpolation was choppy, less ofc, but still choppy. Someone could say 35 FPS feels that way, but nope, single player 35 FPS feels different than 35 FPS with "newsync".

"newsync" should work better on a bad connection. It was implemented in Chocolate Doom a long time ago.

> Edit: PS2. Does woof for dos (i assume its that .com file purpose) default to 70Hz? Maybe i could check it there? I think FreeDos could be booted from PenDrive.

`woof.com` is a hack to make console output work in windows. If you type just `woof` in the console, `woof.com` will be called.
