### ISSUE TITLE
solo-net vs coop_spawns

### ISSUE THREAD

**Issue by Aaron03071991** [fabiangreffrath/woof#1653]
Hello there

-solo-net vs -coop_spawns

What's the difference between those 2?

I guess solo-net will respawn player when killed + coop exclusive weapons and monster spawns, no save game.
Coop_spawns will spawn coop exclusive weapons and monsters on top of SP content but no player respawn, also saving game is possible.

Am I guessing right? Are there any other differences?

**Comment by rfomin** [comment]
Save game is possible in coop mode, but load game only works from command line (`-loadgame`). `-solo-net` is an old option, it's for compatibility with PrBoom+.

**Comment by fabiangreffrath** [comment]
The `-solo-net` parameter emulates a network game with a single player, i.e. the spawns are the same as in multiplayer and the chat system works and the intermission screen shows the multiplayer table, but there is still only one player. This is mostly interesting to port developers to check network game code paths or to map developers to check the multiplayer experience without other players required.

The `coop_spawns` parameter adds the items usually spawned in multiplayer coop games only, but even in single player games. That's it.
