### ISSUE TITLE
Mouse selects menu options despite moving only before the menu was opened

### ISSUE THREAD

**Issue by Ciliane** [fabiangreffrath/woof#1658]
It's a little difficult to explain what I mean in a short title. What happens is that if you move the cursor while no menus are opened, open one and the cursor happens to be over any of the buttons they will be selected. To see what I mean do this: Start map01, pause the game, hover the cursor over the "new game" button, unpause, move your mouse slightly down, pause again and now options or load game are instantly selected because of prior mid-game mouse movement.

Generally not a big deal, but it can be irritating if you relied on the game remembering your menu selects to do repetitive menu actions quickly. For example F2 then Enter to overwrite last used save, F3 then Enter to load last used save, ESC then Enter then Enter to load last used save

**Comment by rfomin** [comment]
We are working on this issue here: #1651. If you are using Windows, you can try the development build from this page: https://github.com/fabiangreffrath/woof/actions/runs/8777489348?pr=1651 (Artifacts, Win-x64)

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/44045866fa04df3e45eb42bfc420c5e7578cb8f2
