### ISSUE TITLE
Exit text is lower than it should be

### ISSUE THREAD

**Issue by Terraformer9x** [fabiangreffrath/woof#1660]
The exit text is lower than it should be normally.

Example using Woof, Vanilla, and Crispy-Doom as comparisons:
![quit](https://github.com/fabiangreffrath/woof/assets/83795041/a7472420-c7ab-4f72-910d-0c440e606780)

**Comment by fabiangreffrath** [comment]
Looks like our `M_StringHeight()` implementation has lost the ability to measure multi-line texts @rfomin ?

![image](https://github.com/fabiangreffrath/woof/assets/6449237/0375bf13-5801-4acc-a518-7807cb6285cc)

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/1503cfed67833f76b75186933a81900475c20e23#diff-a8699a5e1e9e829a36353036431ffe9f9394fd60fa463c085e053d106f600fbeL6565

**Comment by rfomin** [comment]
> Looks like our `M_StringHeight()` implementation has lost the ability to measure multi-line texts @rfomin ?

Right, but I forgot why I changed it. I think we can restore it.
