### ISSUE TITLE
[Feature Request] Option to have "Secret Revealed" message appear in the message log

### ISSUE THREAD

**Issue by Terraformer9x** [fabiangreffrath/woof#1663]
Pretty niche but I was wondering if we could have an option to make the "Secret Revealed" message behave similarly to how the Unity port and Eternity Engine displays it in the message log rather than center of the screen?

![20240425064448_1](https://github.com/fabiangreffrath/woof/assets/83795041/b90176f9-098a-4546-a317-3ff7bfa86338)
![etrn00](https://github.com/fabiangreffrath/woof/assets/83795041/b3aa1fdc-ec88-49bb-9652-5b1d6aa9e577)

**Comment by fabiangreffrath** [comment]
You can move the "secret" widget to either "topleft" or "0 0" in the WOOFHUD lump.

**Comment by Terraformer9x** [comment]
You can but it doesn't truly make it part of the message log, I was wondering if it would be possible to have it as an option to have it be apart of the message log. I can understand if it's not worth it since this would be a pretty niche feature.

**Comment by fabiangreffrath** [comment]
May I ask why you want it like that? The message will get lost pretty quickly in the regular message log.

**Comment by Terraformer9x** [comment]
Mostly aesthetic reasons but I do think it's a way of making it less obtrusive. I do understand that it would get lost fast if it was like this but I think the sound cue would make up for it.

**Comment by fabiangreffrath** [comment]
> Pretty niche but I was wondering if we could have an option ...

Sorry for being so stubborn, but this is exactly the kind of micro-management that I want to avoid at any cost in my projects. As a compromise, if you'd like to rely on the sound effect and give lower priority to the actual message being displayed, you could set it to an empty string with dehacked patch.

**Comment by Terraformer9x** [comment]
It's fine, and that's completely fair.

**Comment by fabiangreffrath** [comment]
Just realized that assigning an empty string doesn't work, but this will do:
```
[STRINGS]
HUSTR_SECRETFOUND = \n
```

**Comment by fabiangreffrath** [comment]
> It's fine, and that's completely fair.

So, may I assume this issue is resolved?
