### ISSUE TITLE
automap line draw order

### ISSUE THREAD

**Issue by ribbiks** [fabiangreffrath/woof#1665]
Greetings! This is extremely minor and also subjective, but I'm going to ask anyway: Would it be possible to change the order that automap lines are drawn such that walls are drawn after interior fchg/cchg/etc lines? I ask because I've been messing with mapcolor_* variables via OPTIONS, trying to make a more minimalist automap that's easier to parse at a glance. I've been wanting to make walls brighter than interior linedefs, but interior lines seem to be drawn on top of the wall lines so the result looks a bit messy:

<img width="1337" alt="Screenshot 2024-04-25 at 4 15 46 PM" src="https://github.com/fabiangreffrath/woof/assets/74789959/0638dd28-3df8-4638-ae35-5598e5b90a2a">

(my grievance is with the dark pixels breaking up the white wall lines)

**Comment by rfomin** [comment]
Could you please upload the OPTIONS file with the colour configuration?

**Comment by ribbiks** [comment]
Here's the OPTIONS values:

```
mapcolor_back 247
mapcolor_grid 104
mapcolor_wall 96
mapcolor_fchg 110
mapcolor_cchg 6
mapcolor_clsd 111
mapcolor_rkey 16
mapcolor_bkey 114
mapcolor_ykey 166
mapcolor_rdor 16
mapcolor_bdor 114
mapcolor_ydor 166
mapcolor_tele 122
mapcolor_secr 176
mapcolor_revsecr 22
mapcolor_exit 0
mapcolor_unsn 7
mapcolor_flat 7
mapcolor_sprt 112
mapcolor_hair 208
mapcolor_sngl 208
mapcolor_plyr 4
mapcolor_ply1 4
mapcolor_ply2 88
mapcolor_ply3 64
mapcolor_ply4 176
mapcolor_frnd 252
mapcolor_prtl 109
```

While I'm at it, can I ask what string woof uses for changing player color? In am_map.h I see `mapcolor_plyr[4]` but I don't know what string it's expecting in OPTIONS. Eternity engine uses `mapcolor_ply1`, `mapcolor_ply2`, etc, but that didn't seem to work here. I also tried `mapcolor_plyr` but that didn't work either.
