### ISSUE TITLE
Automap Color Selector Misaligned in Widescreen

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#167]
Noticed an issue when customizing automap colors where the color selector will be misaligned to the left if set to widescreen mode.
![image](https://user-images.githubusercontent.com/29780788/115269332-3459a580-a109-11eb-920b-6532d73cb00e.png)

**Comment by rfomin** [comment]
Fixed here https://github.com/fabiangreffrath/woof/commit/fd60d9fdfeae1a230cf0ab8287b54e8cdcf26289

**Comment by fabiangreffrath** [comment]
Thanks!
