### ISSUE TITLE
Menu selection graphics don't move according to cursor selection

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#1673]
Don't know if this is intentional or not, but the menu item selection graphics (M_SKULL1/M_SKULL2 + the brackets around items in the options menus), don't seem to react to the cursor hovering over the respective item. The item will still be highlighted, but the skull graphic will remain in its original place as selected by the arrow keys and the brackets will _only_ show when using the arrow keys.

If this was intentional, I'd advise reverting it to the 14.3.0 behavior, as it currently has less visual feedback and feels less consistent and someone redundant in relation to the menu's core design language.

**Comment by fabiangreffrath** [comment]
This is the reverse bug report to

https://github.com/fabiangreffrath/woof/issues/1658

and

https://www.doomworld.com/forum/topic/125256-nugget-doom-300-updated-march-17th-24/?page=19&tab=comments#comment-2781706

**Comment by OpenRift412** [comment]
> This is the reverse bug report to
> 
> #1658
> 
> and
> 
> https://www.doomworld.com/forum/topic/125256-nugget-doom-300-updated-march-17th-24/?page=19&tab=comments#comment-2781706

Ehhhh.... honestly I feel like this kind of falls under what I can only describe as "use-case creep".

I think the best compromise would probably be having a toggle similar to GZDoom's where you can change between the "touchscreen-like" menu navigation, the older "direct" menu select style, and disabling it entirely. I know that sounds like a possibly superfluous toggle to have, but I really do think that the old style meshed far better with the design language of Woof's menu system. Also I'd consider such a setting to be on-par with toggles like "Menu Backdrop", so it's not _too_ superfluous in my opinion.

**Comment by fabiangreffrath** [comment]
I was also skeptical at first, but got used to it within minutes. The chances for another menu switch for this are very low.

**Comment by fabiangreffrath** [comment]
I don't think we are going to change this back anytime soon @rfomin ?

**Comment by rfomin** [comment]
> I don't think we are going to change this back anytime soon @rfomin ?

Personally, I like how it works currently.

**Comment by fabiangreffrath** [comment]
Me too.
