### ISSUE TITLE
-noautoload disables HUD stats

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/woof#1675]
I'm guessing that `-noautoload` disables all the autoload resources that come with Woof, but this means disabling some other features you might not want. Sometimes you need `-noautoload` to not conflict with wads that have custom resources, e.g. [Pirate Doom 2](https://www.doomworld.com/forum/topic/143805-pirate-doom-ii-finished-beta-testers-needed/) can crash if loaded with the [Minor Sprite Fixing Project](https://www.doomworld.com/forum/topic/62403-doom-2-minor-sprite-fixing-project-v20-release-updated-112822/), wads that use custom Dehacked can conflict with casual play mods I normally autoload, and of course I want to disable autoload stuff when recording demos

Ideally I would love to be able to have different levels of autoload in the woof config dir, so that for example `-noautoload 1` (or just `-noautoload`) disables only the things I've put in some directories that are likely to conflict with other wads, `-noautoload 2` disables everything in the autoload woof dir, and `-noautoload 3` disables even the Woof-provided resources.

edit: I'm on Linux and the Woof autoload resources are installed in their own directory, maybe that isn't the case with Windows though.

**Comment by rfomin** [comment]
> Other ports do this by storing essential lumps in port-specific pwads (dsda-doom.wad, gzdoom.pk3, etc..)

Yes, we are planning to do that.

**Comment by rfomin** [comment]
Fixed in https://github.com/fabiangreffrath/woof/commit/51cb24de4a5ed08479060745a90d38d18c4f4ae8
