### ISSUE TITLE
Obituaries for custom MBF actors not applying

### ISSUE THREAD

**Issue by Raddatoons** [fabiangreffrath/woof#1689]
I wanted to add the obituaries for the MBF mapset _Eviternity_'s unique monsters so my co-op friend and I could identify which monster was the one to slay the other person.  However, either I am misunderstanding how the strings are established, or I do not understand the DeHackEd/BEX format properly.  I have updated to 14.5.0, so the feature to update obituaries for custom actors should be added.

Here's my attempted additions to the obituary strings.  There are no obituaries set for the other things/actors, so I tried to use the new strings suggested by @SirBofu in issue #1562, and added in commit #1636, as seen here:

> [STRINGS]
> OB_WOLFSS = %o was destroyed by a Former Captain.
> OB_BARON = %o underestimated an Annihilator.
> OB_BARONHIT = %o underestimated an Annihilator.
> Obituary_Deh_Actor_140_Melee = %o was crushed by a Nightmare Demon.
> Obituary_Deh_Actor_27 = %o was destroyed by the Archangelus.
> Obituary_Deh_Actor_144 = %o was ripped and torn by the Archangelus.
> Obituary_Deh_Actor_25 = %o was burned down by an Astral Cacodemon.

The Former Captain and Annihilator work fine, as they replace already-existing obituary lines.  (I did shorten the Annihilator line because it bled off-screen with the more classic-scaled HUD, even in widescreen.)  However, upon dying to the Nightmare Demon or Astral Cacodemon, it just gives me the default "Player died" obituary message.  I'm wondering if I did something wrong with pointing towards the actors, or if I need to set something within the actors' specific DeHackEd entries to point towards the strings.  This could be a simple DeHackEd mistake on my end, but I'd rather ask to see if it's an issue on Woof's end just in case.  Thanks in advance for the help!

**Comment by SirBofu** [comment]
@Raddatoons Your Deh_Actor numbers are off. The Nightmare Demon is Deh_Actor_139; the Astral Cacodemon is Deh_Actor_24. The Deh_Actor number is 1 less than the Thing ID in DEHACKED.

`Obituary_Deh_Actor_139 = %o was crushed by a Nightmare Demon.`

**Comment by SirBofu** [comment]
I should add that you also don't need the _Melee part if a monster only does melee damage.

**Comment by Raddatoons** [comment]
Didn't catch that in any of the guides I found, thanks @SirBofu!
