### ISSUE TITLE
NERVE.WAD mode?

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#169]
Would be nice to see a built-in mode for running No Rest for the Living, akin to Crispy Doom. This doable?

**Comment by rfomin** [comment]
For cases like this, we can write a bunch of UMAPINFO files. Nerve.wad, Master Levels, old versions of Sigil, etc.

**Comment by fabiangreffrath** [comment]
Right, we shouldn't hard-code what we could achieve just as well with a UMAPINFO lump.
