### ISSUE TITLE
[Feature request] Restore original secret reveal sound as an audio option

### ISSUE THREAD

**Issue by Patrxgt** [fabiangreffrath/woof#1718]
It would be nice to have to [original/vanilla](https://www.youtube.com/watch?v=0vyUhiNK8hs) sound effect, that plays after finding a secret.

**Comment by fabiangreffrath** [comment]
There is no such sound. Vanilla Doom didn't play any sound when a secret was revealed. If you want to play a different sound than the current one, provide it as a lump called `dssecret`.
