### ISSUE TITLE
No such option '-dedicated'

### ISSUE THREAD

**Issue by rah2501** [fabiangreffrath/woof#1726]
It looks like here's a bug either in the source code or in [the wiki](https://github.com/fabiangreffrath/woof/wiki/Command-Line-Parameters).  If I call woof with `-dedicated`, it tells me there's no such option even though such an option is listed in the wiki page for command-line parameters:

```
$ woof -server -privateserver -dedicated -servername test -nodes 4 -altdeath -frags 30
No such option '-dedicated'.
```

This is using [the Debian package](https://packages.debian.org/bookworm/woof-doom) but Debian's source is [unpatched](https://salsa.debian.org/games-team/woof-doom/-/tree/master/debian).

**Comment by fabiangreffrath** [comment]
The version of Woof in Debian stable is 10.5.1. This version doesn't have the `-dedicated` command line option, neither does its manpage claim it has. The `-dedicated` command line option was added in Woof 11.3.0. You may want to install the `woof-doom` package from Debian testing for a more recent version.
