### ISSUE TITLE
Severe Input Lag on Steam Deck

### ISSUE THREAD

**Issue by superboo07** [fabiangreffrath/woof#1727]
While using the controller on steam deck there is severe delay on inputs including turning.

**Comment by fabiangreffrath** [comment]
Which version of Woof is this?

**Comment by superboo07** [comment]
The latest avaliable for download, and is running through proton.

**Comment by ceski-1** [comment]
> The latest avaliable for download, and is running through proton.

Were you using the AppImage from the [latest release](https://github.com/fabiangreffrath/woof/releases)? Can you try the AppImage at the bottom of [this page](https://github.com/fabiangreffrath/woof/actions/runs/9413700990)? Are there any other details you can share?

**Comment by ceski-1** [comment]
I don't have a Steam Deck so I tried the next closest thing which is launching Woof through Steam "big picture" mode with Steam Input enabled and gamepad connected to it. The only way to make the gamepad behave oddly is by messing with both Woof and Steam Input settings at the same time and setting intentionally extreme values. So I would double check the Steam Input settings on your Steam Deck. Maybe also check gyro settings as well. There is at least one other Steam Deck user who didn't have any issues, so I'm not sure if this issue is on Woof's side.

**Comment by ceski-1** [comment]
Another guess: do you have the Steam Deck framerate limiter enabled? If so, disable it and use Woof's instead.

References:
1. https://www.reddit.com/r/SteamDeck/comments/ug9kc2/psa_enabling_the_framerate_limiter_adds/
2. https://github.com/ValveSoftware/gamescope/issues/474

**Comment by superboo07** [comment]
unfortunately disabling the frame limiter doesn't help, also the app image has the same results.

**Comment by superboo07** [comment]
one other thing I noticed however is it appears other source ports like doom retro also suffer from this input lag, but GZDoom doesn't.

**Comment by ceski-1** [comment]
@superboo07 Try these settings with the AppImage:

![woof0000](https://github.com/fabiangreffrath/woof/assets/56656010/a4390ea7-9b2e-413f-8b36-664e6e82a618)

**Comment by rfomin** [comment]
> also the app image has the same results

Could you try the latest AppImage from this page: https://github.com/fabiangreffrath/woof/actions/runs/9441150859 Our release build has old SDL.

**Comment by superboo07** [comment]
Input lag in latest app image feels significantly worse somehow, we're talking full seconds before an input is registered. Using the settings shown above don't fix it.

**Comment by ceski-1** [comment]
I'm going to track down a Steam Deck and see if I can reproduce this.

**Comment by ceski-1** [comment]
@superboo07 Switch to desktop mode, launch the Steam app, and add the Woof AppImage as a non-Steam game. Then launch the game from Steam and it will work correctly. If you switch back to gaming mode, you can find Woof under "Library -> Non-Steam" and launch it that way too.
