### ISSUE TITLE
Chex Quest - Clicking Sound Effects

### ISSUE THREAD

**Issue by ak-988** [fabiangreffrath/woof#1730]
Reported here [https://www.doomworld.com/forum/post/2809339](url)

I can reproduce this clicking and the other observations in that thread on Windows 10. DSITEMUP is a good test candidate (scrolling a submenu.) Somehow, DSDA and PrBoomX don't have this issue. GZDoom and Woof do. Woof even has it back to early releases with SDL Mixer.

Pretty sure this abrupt drop at the end of DSITEMUP is the culprit, and Woof is just playing it faithfully:

![dip](https://github.com/fabiangreffrath/woof/assets/76888018/9d4bb010-a92c-445a-988a-b4ff21f44239)

Same thing with DSBFG:

![Screenshot 2024-06-07 020217](https://github.com/fabiangreffrath/woof/assets/76888018/de76508f-e030-4c9f-8da7-6027786110a7)

The DSITEMUP that comes with Vanilla Chex 3 doesn't have it, and doesn't pop with a current build of Woof:

https://melodic-spaceship.neocities.org/chex3v/downloads

![Screenshot 2024-06-07 015702](https://github.com/fabiangreffrath/woof/assets/76888018/8671034f-3c26-4caa-98a7-0218d9206fe7)

This seems like something Woof's fading to avoid clicks could address. But, how do those other ports avoid it? I tried a quick look around and didn't find any obvious "Fix Chex sound" commits.

Edit: Just to help verify things, here's a sound replacement WAD for Chex Quest that allows it to be played in current Woof with no issues that I heard: https://www.doomworld.com/applications/core/interface/file/attachment.php?id=301455

**Comment by fabiangreffrath** [comment]
Looks like we need to extend `FadeInMono8()` to `FadeInAndOutMono8()` here:

https://github.com/fabiangreffrath/woof/blob/80d92fa2aeca9cab69e7c363251808bae2177a6b/src/i_oalsound.c#L613-L627

**Comment by fabiangreffrath** [comment]
Looks like we need to extend `FadeInMono8()` to `FadeInAndOutMono8()` here:

https://github.com/fabiangreffrath/woof/blob/80d92fa2aeca9cab69e7c363251808bae2177a6b/src/i_oalsound.c#L613-L627

**Comment by fabiangreffrath** [comment]
Even I can hear this and this patch fixes it for me:
```patch
--- a/src/i_oalsound.c
+++ b/src/i_oalsound.c
@@ -610,12 +610,12 @@ static boolean IsPaddedSound(const byte *data, int size)
     return true;
 }
 
-static void FadeInMono8(byte *data, ALsizei size, ALsizei freq)
+static void FadeInOutMono8(byte *data, ALsizei size, ALsizei freq)
 {
     const int fadelen = freq * FADETIME / 1000000;
     int i;
 
-    if (data[0] == 128 || size < fadelen)
+    if ((data[0] == 128 && data[size - 1] == 128) || size < fadelen)
     {
         return;
     }
@@ -623,6 +623,7 @@ static void FadeInMono8(byte *data, ALsizei size, ALsizei freq)
     for (i = 0; i < fadelen; i++)
     {
         data[i] = (data[i] - 128) * i / fadelen + 128;
+        data[size - 1 - i] = (data[size - 1 - i] - 128) * i / fadelen + 128;
     }
 }
 
@@ -687,7 +688,7 @@ boolean I_OAL_CacheSound(sfxinfo_t *sfx)
 
             // Fade in sounds that start at a non-zero amplitude to prevent
             // clicking.
-            FadeInMono8(sampledata, size, freq);
+            FadeInOutMono8(sampledata, size, freq);
         }
         else
         {
```

**Comment by ceski-1** [comment]
> ![Screenshot 2024-06-07 020217](https://private-user-images.githubusercontent.com/76888018/337559630-de76508f-e030-4c9f-8da7-6027786110a7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjcyNjYsIm5iZiI6MTcxNzc2Njk2NiwicGF0aCI6Ii83Njg4ODAxOC8zMzc1NTk2MzAtZGU3NjUwOGYtZTAzMC00YzlmLThkYTctNjAyNzc4NjExMGE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEzMjkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmN2VmZjZjMmYzYjg1YzhkNzJiMjY1ZTZiMjlhYzNiNGE5MzViMzkyZTFkNjM3NDk5ZTQ1NzUxOWM1MTY3MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._yqMlMgy_FAye-d4JKCr7cax6UVJh2-7xsAqKiYd6Uc)

This was my suspicion, thanks for investigating!

**Comment by ceski-1** [comment]
Most of the Chex Quest sounds have issues: [chex_sfx.txt](https://github.com/user-attachments/files/15742453/chex_sfx.txt) (for comparison, [doom2_sfx.txt](https://github.com/user-attachments/files/15742466/doom2_sfx.txt) is less severe)
The range is -128 to 127, so roughly half the Chex Quest sounds have the last sample at full volume. Very poor mastering.
