### ISSUE TITLE
No random pitched sound effect even the random pitch sound effect option is on

### ISSUE THREAD

**Issue by skyrain128** [fabiangreffrath/woof#1734]
There's no random pitched sound effect even the random pitch sound effect option is on

Woof version is 14.5.0 Win64
IWAD is DOOM II

**Comment by fabiangreffrath** [comment]
Try to increase the `pitch_bend_range` config variable to e.g. `200`.

**Comment by skyrain128** [comment]
It works, thank you!

**Comment by fabiangreffrath** [comment]
Thanks for your feedback!
