### ISSUE TITLE
Network game feels laggy

### ISSUE THREAD

**Issue by skyrain128** [fabiangreffrath/woof#1735]
Network game feels laggy even the player is only me alone
I started the network game through the setup program. Player was only me alone. There's no other players
I don't think it's network problem because I am the host and there's no same problem in Chocolate Doom, Crispy Doom (6.0) or International Doom
(Crispy Doom had same bug years ago, but fixed)

https://github.com/fabiangreffrath/crispy-doom/issues/959

Same bug existed in Crispy Doom 5.12.0
But it's fixed in latest version of Crispy Doom

**Comment by skyrain128** [comment]
Version is Woof 14.5.0 Win64
IWAD is DOOM II 1.9

**Comment by rfomin** [comment]
Try running the game with the `-oldsync` command line parameter.

> Crispy Doom had same bug years ago, but fixed...

We've removed this fix in Woof, it doesn't work properly. We have plans to improve this in the future.

**Comment by skyrain128** [comment]
Thank you! It works fine when I use -oldsync command line parameter. How about using oldsync mode by default in the next release?
I usually run the network game through setup program.

**Comment by fabiangreffrath** [comment]
> How about using oldsync mode by default in the next release?

We should take something like this into consideration. Thank you!
