### ISSUE TITLE
Automap input persists when being closed due to death

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1737]
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/9433713966)._

As you know, the automap is closed automatically upon the player's death. However, when that happens, the inputs aren't cleared, and so they persist when the automap is brought up again.

**Comment by rfomin** [comment]
Could you please write steps to reproduce the issue. Not sure I understand what the problem is.

**Comment by MrAlaux** [comment]
> Could you please write steps to reproduce the issue. Not sure I understand what the problem is.

Sure thing:

- Warp to Doom2 Map09
- Walk onto the damaging floor
- Open the automap
- Just before you're about to die (e.g. at 10% health), press and hold any of the automap scroll keys (e.g. right arrow)
- Upon death, the automap should be closed automatically; let go of the scroll key(s)
- Open the automap

You should see the automap still scrolling despite no keys being pressed.

**Comment by fabiangreffrath** [comment]
Does this fix it?

```patch
--- a/src/am_map.c
+++ b/src/am_map.c
@@ -676,6 +676,7 @@ void AM_Stop (void)
   automapactive = false;
   ST_Responder(&st_notify);
   stopped = true;
+  memset(buttons_state, 0, sizeof(buttons_state));
 }

 //
@@ -843,7 +844,6 @@ boolean AM_Responder
     {
       bigstate = 0;
       viewactive = true;
-      memset(buttons_state, 0, sizeof(buttons_state));
       AM_Stop ();
     }
     else if (M_InputActivated(input_map_gobig))
```
