### ISSUE TITLE
Crash Logs

### ISSUE THREAD

**Issue by BigStronk64** [fabiangreffrath/woof#1748]
Say you're developing a mod and it repeatedly crashes, there is nothing that tells you what causes the crash.
I feel there should be a feature where if a crash occurs a txt would be exported detailing what caused the crash

**Comment by rfomin** [comment]
There should be an error message in the popup window or in the console. If there is any other kind of crash, just upload the mod here with steps on how to reproduce the crash and we will investigate.

**Comment by BigStronk64** [comment]
So I figured out the issue, I used the A_SkullAttack in a pinky state in order to replicate a sort of launch attack where the pinky launches itself towards you. The sourceport (after enough A_SkullAttack functions are called) shits itself and crashes as it cannot handle it, is there anyway this could be fixed? or is this an intentional limit?

**Comment by rfomin** [comment]
It should probably work. If you upload your test WAD/DEHACKED, I will debug it.

**Comment by BigStronk64** [comment]
[Debug.zip](https://github.com/user-attachments/files/15886402/Debug.zip)
Here you go

**Comment by fabiangreffrath** [comment]
Well, this little patch fixes the crash, but I'd like to know how `numspechits` could get below zero in the first place.

```patch
--- a/src/p_enemy.c
+++ b/src/p_enemy.c
@@ -415,7 +415,7 @@ static boolean P_Move(mobj_t *actor, boolean dropoff) // killough 9/12/98
          return true;
         }
 
-      if (!numspechit)
+      if (numspechit <= 0)
         return false;
 
       actor->movedir = DI_NODIR;
 ```

**Comment by fabiangreffrath** [comment]
DSDA-Doom crashes just alike, so maybe @kraflab would like to join the discussion.

**Comment by rfomin** [comment]
> is there anyway I could implement this patch myself into my build?

Try Win-64 artifact from this page: https://github.com/fabiangreffrath/woof/actions/runs/9578082056
