### ISSUE TITLE
Status bar borders not drawn when toggling automap modes

### ISSUE THREAD

**Issue by ceski-1** [fabiangreffrath/woof#1762]
Latest master. This happens intermittently, so keep repeating the steps until it happens.

<details><summary>Steps to reproduce:</summary>

1. Start with fullscreen view:

![woof0000](https://github.com/fabiangreffrath/woof/assets/56656010/32313b1b-5a77-4a38-b9f6-f69c3b8a7909)

2. Press Tab:

![woof0001](https://github.com/fabiangreffrath/woof/assets/56656010/841e46c0-6fbf-4a84-a89d-f2a03c0b9b51)

3. Press O:

![woof0002](https://github.com/fabiangreffrath/woof/assets/56656010/80b137bf-2d66-4168-a21f-b7931af10dfb)

4. Press O again:

![woof0003](https://github.com/fabiangreffrath/woof/assets/56656010/eb407737-6939-4679-a363-c6de8dfe635b)

</details>

**Comment by fabiangreffrath** [comment]
It seems that `st_classicstatusbar` is sometimes miscalculated. It's set in the `ST_Drawer()` function so maybe a racing condition with some other variable which is set in a ticker function?
