### ISSUE TITLE
Shift doesn't work when typing savegame names

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1773]
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/9763797786)._

As the title says: when entering the name for a savegame, the shift key doesn't seem to have any effect, e.g. holding it and pressing 1 still results in `1` being written instead of the expected `!`.

**Comment by fabiangreffrath** [comment]
Looks like we need to use the `shiftxform[]` array somewhere around here:

https://github.com/fabiangreffrath/woof/blob/80740b0b1f22e38ca3c67aada0ea0c3166f18324/src/mn_menu.c#L2705
