### ISSUE TITLE
Overlapping music strings in console

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1778]
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/9802804920)._

See for yourself, third-to-last line:
![imagen](https://github.com/fabiangreffrath/woof/assets/73968015/572c8c78-4992-4942-bb65-e3a809a935be)

As you may gather, I'm using FluidSynth with a specific soundfont that seems to lack some instruments, and the MIDI seems to expect one of them, triggering the warning -- I had to run with `-verbose` for it to show up.

I'd guess that you would need the WAD and soundfont (`GM.sf2`) in question to debug this, but I'm not sure if I should share the latter, and without it, the former may be useless. Let me know what to do.

**Comment by rfomin** [comment]
Not sure if we can fix this, Fluidsynth uses threads internally. We can disable Fludsynth logging completely.

**Comment by fabiangreffrath** [comment]
I guess it's okay to display Fluidsynth's warning messages in `VB_DEBUG`/`-verbose` mode only and take into account that they will mix up with the port's own. For the regular mode, we display only Fluidsynth's serious error messages, which I think is alright as well.

**Comment by fabiangreffrath** [comment]
I don't think this needs a fix.
