### ISSUE TITLE
Previous/next-weapon button issues

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1779]
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/9802804920)._

With `doom_weapon_toggles` disabled, the next-weapon button stops working once the Fist or Shotgun are selected (either as pending or ready weapon). The previous-weapon button doesn't get stuck, but it skips the Chainsaw and SSG altogether.

With `doom_weapon_toggles` enabled, the next-weapon button skips the Fist (even with Berserk) and Shotgun. Also, the non-Berserk Fist is skipped by both buttons even in non-vanilla complevels where it _can_ be switched to manually through its dedicated button, although this could be intentional.

**Comment by fabiangreffrath** [comment]
I think this is already in the original Chocolate Doom implementation, i.e. that you can forward switch to certain weapons but not backward switch to them. Maybe @fragglet could elaborate, please?
