### ISSUE TITLE
Voxel models override sprites regardless of load order

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1808]
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/10160109603)._

If a voxel model corresponding to a given sprite is loaded, said model will be used even if sprite replacements come later in the load order. An example setup that's affected by this is: a sprite in the IWAD, a model for it in an autoloaded PWAD, and a sprite replacement in a `-file` PWAD.

This might be intentional, but it's a bit inconvenient; the models override what could be simple edits of the sprites which follow the same animations (e.g. A to D for walking, E to G for attacking, etc.) or all-new designs which might have different animations, in which case the models would make things look wrong.

**Comment by rfomin** [comment]
This is intentional, voxels are currently in a separate namespace (`VX_START/VX_END` and `voxels` subfolder).
I think the combination of sprites and voxels wouldn't look good anyway, so the complication is not worth it.

**Comment by fabiangreffrath** [comment]
If Voxels are loaded and enabled, then Voxels take precedence. It's just like that.
