### ISSUE TITLE
suggestion: port netcode from Chocolate Doom

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#181]
Yesterday I tried it, it seems doable. What do you think of this idea?

**Comment by fabiangreffrath** [comment]
DO you mean it would be possible to join a Chocolate server with Woof? This would be incredible!

**Comment by rfomin** [comment]
Maybe in theory. I've only tested Woof clients on the local network. I will try to make PR this week.

**Comment by OpenRift412** [comment]
> Maybe in theory. I've only tested Woof clients on the local network. I will try to make PR this week.

If this could work, and you could get MBF/Boom compatible play between Woof clients, this would be HUGE

**Comment by OpenRift412** [comment]
Also, just as a suggestion, if you _do_ manage to implement it, you may also want to look into Eternity Engine's netcode as well, because while it's convoluted to get connected to each other, it is reeeeaaaally smooth.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/2c2eff19d296f2519dd630f9aebe8b1efbc3dce8

**Comment by OpenRift412** [comment]
> [2c2eff1](https://github.com/fabiangreffrath/woof/commit/2c2eff19d296f2519dd630f9aebe8b1efbc3dce8)

Exciting stuff! So is the plan to just have this operate solely via commandline or will there be a sort of Chocolate-esque launcher/browser?

**Comment by rfomin** [comment]
> So is the plan to just have this operate solely via commandline or will there be a sort of Chocolate-esque launcher/browser?

This will be the same UI as Chocolate, but without the setup utility. I want to write a DWANGO style launcher/browser (can I call it TWANGO?), but it may not be ready for the next version.

**Comment by fabiangreffrath** [comment]
DWOOFGO? 😁

**Comment by OpenRift412** [comment]
> > So is the plan to just have this operate solely via commandline or will there be a sort of Chocolate-esque launcher/browser?
> 
> This will be the same UI as Chocolate, but without the setup utility. I want to write a DWANGO style launcher/browser (can I name it TWANGO?), but it may not be ready for the next version.

Ha! Well, it would have to support DOSBox IPX tunnelling for it to bear that name ;)

Honestly though, I love the idea. It makes me wonder: what if it was a standalone UI? Think Doom Explorer but for Chocolate-net ports (Choco, Crispy, RUDE, Woof, etc.). Would be pretty cool though to have a multi-port netplay standard!

 Sorry, I'm just daydreaming again. You do you.

**Comment by rfomin** [comment]
I am planning to do a simple thing like Choco setup utility, but with a DWANGO style user interface. There are some advanced launchers/browsers out there, and Choco-style multiplayer is a niche thing.
Perhaps in the future if there is a demand for textscreen-style programs :smile:

**Comment by OpenRift412** [comment]
> I am planning to do a simple thing like Choco setup utility, but with a DWANGO style user interface. 

I probably shouldn't have used Doom Explorer as an example, but I moreso just meant a simple UI like what you're describing, but it allows you to start/join a game from any choco-net port. No fancy ZDaemon IRC or any bloat like that.

>Choco-style multiplayer is a niche thing. 

Indeed, but then why even had multiplayer support? :P 

Joking aside, I think the reason it's so niche in the first place is because most people don't even know Chocolate Doom even has a server list, which is why nobody seems to play. Plus, this is like the only netplay standard where several different source ports can connect to a server. I'd say that's pretty cool, and definitely deserves more recognition. Sorry if I'm rambling, it's just exciting stuff.

**Comment by fabiangreffrath** [comment]
> I am planning to do a simple thing like Choco setup utility, but with a DWANGO style user interface. There are some advanced launchers/browsers out there, and Choco-style multiplayer is a niche thing. Perhaps in the future if there is a demand for textscreen-style programs 😄

Are you going to maintain this as part of the Woof code base or will this be a separate project?

**Comment by rfomin** [comment]
> Are you going to maintain this as part of the Woof code base or will this be a separate project?

I want to maintain it as part of Woof code base, like a simplified Choco setup.
