### ISSUE TITLE
Demo playback randomly crashes the port

### ISSUE THREAD

**Issue by lvl1337** [fabiangreffrath/woof#1820]
When attempting to play various Doom 2 v1.9 compatible demos on woof (such as 22no0804, 30uvx942, 30no1552, 30uv2325) the game just closes itself for no reason. This is random, it might not happen at all during a full playback but when it does happen, it's usually a short while into the demo. I've tried setting the compatibility level for it but that didn't solve the issue.

All demos I've tested play back absolutely fine under PrBoom+ (UMAPINFO), dsda-doom 0.27.5 and doom2.exe

**Comment by ceski-1** [comment]
Please provide the Woof version, OS, and woof.cfg (zip it and attach to comment).

Does it happen in the middle of the level or at the intermission screens?

Does this happen during normal gameplay, or just demo playback? Does it happen with other demo types?

If you run the game from a terminal and use the `-verbose` argument, you might be able to catch an error message in the terminal text the next time it happens, which would be useful.

**Comment by fabiangreffrath** [comment]
`FixedDiv()` again? I don't think this is with the released version. We would have got a lot more bug reports then...

**Comment by fabiangreffrath** [comment]
Is Voxel rendering involved?

**Comment by lvl1337** [comment]
Hi, got on the computer again. No, I didn't use any voxel rendering. PC(laptop) details are as follows:

AMD Ryzen 7 7840HS processor running at stock clock speeds
16 GB (2x8 sticks) of DDR5-5600 RAM
1 TB OEM NVME SSD
Radeon 780M APU
NVIDIA RTX 4060 Mobile DGPU
Windows 11 IoT Enterprise 23H2 (22631.3880)
[demoandcfg.zip](https://github.com/user-attachments/files/16530876/demoandcfg.zip)
(archive includes 22no0804 by Looper, a demo that would either play to the end or randomly crash)

Woof version: Latest release right now (14.5.0)

It happens during a level or right when the beginning tic of a level is seen visually.

I haven't had it happen during normal gameplay yet (then again, I've barely played around normally, been infatuated with this demo situation) I don't know what you mean by demo types as the only one I know of is .lmp (complevels is what you mean, maybe?)

Other ports I've tested were dsda-doom 0.27.5, prboom-plus UMAPINFO master built in MSYS2, doom2.exe under Windows 95 in 86Box and none of them crashed after 10 playbacks per port.

Could visual settings be causing the issue? (I went for a 16:9 vanilla aesthetic) I'll do a verbose test and see I guess.

**Comment by ceski-1** [comment]
Thanks, that's helpful. I was able to reproduce the issue twice using the 14.5.0 release. Unfortunately, it just exits with nothing useful in the output. I can't seem to make it happen consistently and it doesn't happen with a debug build. Needs more investigating.

**Comment by rfomin** [comment]
> `midifile.c` is calling `mem_*` functions that work off the zone memory, so that is going to cause issues.

I think that's where the problem lies. We can simply not use the zone memory functions in `memio.c` (this file was copied from Chocolate Doom with minor modifications). Or not load/parse the midi file in the player thread.

**Comment by ceski-1** [comment]
I'd like to keep midi loading on the player thread if possible, if it's not too much of a hassle to create non-zone versions of the `memio.c` functions.

**Comment by fabiangreffrath** [comment]
> I think that's where the problem lies. We can simply not use the zone memory functions in `memio.c`

Hm, but why? All memory is allocated with `PU_STATIC` and the zone itself doesn't change.

**Comment by fabiangreffrath** [comment]
Okay, but isn't the race independent of the actual malloc implementation?

**Comment by rfomin** [comment]
Zone has a list of memory blocks. As far as I understand from asan's [report](https://github.com/user-attachments/files/16538057/asan.txt), the MIDI player thread freed a memory block, and then this block was accessed in `Z_Malloc` in the main thread.

If we remove zone memory from `memio.c`, we don't have to deal with a list of memory blocks from two threads.
