### ISSUE TITLE
More Than 8 Episodes In UMAPINFO?

### ISSUE THREAD

**Issue by JohnMason1986** [fabiangreffrath/woof#1821]
**UMAPINFO** can let creators to create their own episodic system for their **WAD**s.
But this system works not so ideal in ["Woof!"](https://github.com/MrAlaux/Nugget-Doom/) and its relatives (["Nugget Doom"](https://github.com/MrAlaux/Nugget-Doom/) & ["Cherry Doom"](https://github.com/xemonix0/Cherry-Doom)).
In examples below, you can see various tests with a small project (that is currently in its compilation stage) that contains 9 mappers, so there were a 9 episodes defined in **UMAPINFO** lump:

"DSDA-Doom":
![9EPs_DSDA-Doom](https://github.com/user-attachments/assets/4f0f69dd-0dc7-40ee-93ed-a5b2cdfd80f9)

"ZDoom":
![9EPs_ZDoom](https://github.com/user-attachments/assets/1b6325d9-4c20-4fcd-9589-71b198fde997)

"Woof!" (result were same in "Nugget Doom" & "Cherry Doom"):
![9EPs_Woof!](https://github.com/user-attachments/assets/0f2eea2d-8cd8-4d25-a8d3-aa38dae656b9)

In the last example we have only 8 episodes in menu while defined 9 of them.
Thing is that on **1080P** monitor (that is not only considering very common in the **2024**, but also it is kinda old (since **2K** and **4K** monitors is becoming more common)) not just only 8, but 9 or even 10 episodes can be easily displayed.
It can be just nice to have more that 8 episodes to be shown up in "Woof!'s" episodes screen. And I am sure that "Nugget Doom" & "Cherry Doom" gonna inherit that feature as well.

**Comment by fabiangreffrath** [comment]
I agree that we should either bump the limit on number of episodes to 10, or remove that limit altogether - but then we would be lacking a means to scroll through the episodes list with the current menu implementation.

> In the last example we have only 8 episodes in menu while defined 9 of them. Thing is that on **1080P** monitor (that is not only considering very common in the **2024**, but also it is kinda old (since **2K** and **4K** monitors is becoming more common)) not just only 8, but 9 or even 10 episodes can be easily displayed. It can be just nice to have more that 8 episodes to be shown up in "Woof!'s" episodes screen. And I am sure that "Nugget Doom" & "Cherry Doom" gonna inherit that feature as well.

Screen size is entirely unrelated here, because Doom is only able to render to a logical vertical resolution of 200 px.

**Comment by JohnMason1986** [comment]
> I agree that we should either bump the limit on number of episodes to 10, or remove that limit altogether...

I was told that [UMAPINFO](https://github.com/kraflab/umapinfo/blob/master/docs/spec.md) specification says that it is only up to 8 episodes is allowed to be specified.
Then I want an explanation why then ["DSDA-Doom"](https://github.com/kraflab/dsda-doom) have no problems to show up 9 episodes?

I see that we have two ways:
1) Implement a showing support of 9 (10 at best) episodes in "Woof!".
2) Update **UMAPINFO** specs so it can have 9 (10 at best) episodes to be defined.

**Comment by fabiangreffrath** [comment]
> I was told that [UMAPINFO](https://github.com/kraflab/umapinfo/blob/master/docs/spec.md#episode) specification says that it is only up to 8 episodes is allowed to be specified. Then I want an explanation why ["DSDA-Doom"](https://github.com/kraflab/dsda-doom) have no problems to show up 9 episodes?

That's a good question that only @kraflab can aswer. 😉 

> 1. Implement a showing support of 9 (10 at best) episodes in "Woof!".
> 2. Update **UMAPINFO** specs so it can have 9 (10 at best) episodes to be defined.

I'd say we should go for both solutions (and maybe let the port print a warning once the 9th episode is added to the menu).

> Please notice than with 10 defined episodes we can have nice stuff like: 90 usual maps + 9 secret ones. I wonder how many time gonna pass when some group of strong mappers can provide us a "giga-WAD" with 99 maps.

😮

**Comment by fabiangreffrath** [comment]
> 2. Update **UMAPINFO** specs so it can have 9 (10 at best) episodes to be defined.

https://github.com/kraflab/umapinfo/pull/3

**Comment by fabiangreffrath** [comment]
Hm, maybe we should stop at 9 episodes, else the map lump names for the next one will be called E10M1 and so on.

**Comment by JohnMason1986** [comment]
Creator of "DSDA-Doom" & **UMAPINFO** spec commented situation with episodes count on their "Discord" server.
As I understood, they are insisting on your updating of the "Woof!" source port so it can show 9+ episodes in its GUI.
I guess that "Nugget Doom" & "Cherry Doom" creators would like to update that part in their source ports too.

**Comment by kraflab** [comment]
I didn't insist on anything, I rather said that if you want woof to support more episodes, you should ask for it. I also mentioned that I don't think it makes any sense to change the spec.

**Comment by JohnMason1986** [comment]
Brad Harding recently made an ASAP [update](https://www.doomretro.com/2024/08/doom-retro-v551.html) due to [remaster](https://store.steampowered.com/app/2280/DOOM__DOOM_II/) that is out now and there is a one line about multiple episodes:
`Up to 9 episodes can now be specified using EPISODE and will display correctly in the episode menu.`
I guess that is the number that we can use, so semi-vanilla source-ports can be more consistent between each other.

**Comment by fabiangreffrath** [comment]
Once the first PWAD with 10 episodes is released, this will work in Woof, dsda-doom and gzdoom, but not Doom Retro. 🤷
