### ISSUE TITLE
ResetPitchBendSensitivity sometimes doesn't work properly under MSGS

### ISSUE THREAD

**Issue by MIDIMan2** [fabiangreffrath/woof#1828]
The function `ResetPitchBendSensitivity` in `i_midimusic.c` has a chance of not working properly when using the Microsoft GS Wavetable Synth with `midi_complevel` set to 2 and `midi_reset_delay` set to 0.

If the MIDI in question has a GM or GS (or possibly XG) reset sysex at the beginning, the pitch bend sensitivity acts as if it was set to +/- 0 semitones instead of +/- 2 semitones.

This bug does not affect other MIDI devices installed on the OS. I have only tested this on Windows 11.

Example WAD: [PitchBendSensitivityTest.zip](https://github.com/user-attachments/files/16563418/PitchBendSensitivityTest.zip)
(Uploaded as a ZIP, since GitHub won't let me upload WADs directly)

This WAD contains a single MIDI lump, `D_RUNNIN`, to demonstrate this bug.

**Comment by ceski-1** [comment]
If you change `midi_reset_delay` to a value other than -1 (Auto), then you'll have to adapt it to the MIDI device you're targeting. For my system, MS GS Synth needs about 110 ms to process the reset messages sent to it. For comparison, a VSTi may work fine with a 0 ms delay, while a hardware SC-55 may need more than 200 ms.

**Comment by MIDIMan2** [comment]
So far, I've tested the WAD using these settings with four other MIDI devices: OmniMIDI, Nuked SC-55 (in mk2 mode), my actual SC-55mkII, and my MU2000. None of them have this problem; It is specifically a problem when using the Microsoft GS Wavetable Synth.

It should also be noted that I tested all of these with `midi_reset_type` set to 0.

**Comment by ceski-1** [comment]
The example you've provided has no delay between the SysEx GM reset and the first Note On. That's going to make hardware MIDI devices stutter for the first few notes.

For the MS GS Synth issue, I don't think there's much I can do. It has many issues that already require special handling (see the numerous code comments). Broken GS and XG support, doesn't support reverb or chorus, doesn't follow MIDI spec when responding some GM events, and so on.

I don't consider this to be an issue and recommend leaving the MIDI settings at their defaults, especially when using MS GS Synth. There's some additional information [here](https://github.com/fabiangreffrath/woof/wiki/MIDI).
