### ISSUE TITLE
Unable to load nerve.wad and masterlevels.wad included in DOOM + DOOM II release

### ISSUE THREAD

**Issue by buvk** [fabiangreffrath/woof#1830]
I am unable to load nerve.wad and masterlevels.wad that are included in the new DOOM + DOOM II release.  When I try to launch woof, the application does not open.

Launching as follows:

woof.exe -iwad doom2.wad -file nerve.wad
woof.exe -iwad doom2.wad -file masterlevels.wad

**Comment by rfomin** [comment]
Should work with master branch. Artifacts: https://github.com/fabiangreffrath/woof/actions/runs/10321660503

**Comment by buvk** [comment]
The issue is fixed in this build.
