### ISSUE TITLE
M_DOOM Graphic for 2024 Master Levels WAD is off-center

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#1835]
As the title suggests, see image below. I'm not entirely sure if this is an alignment problem or not, but this issue also seems to be present in other ports I tested i with (Crispy and DSDA). 
![image](https://github.com/user-attachments/assets/d9dcd928-62fc-4693-85f7-163b640d1168)

Here's how it looks in the remaster:
![image](https://github.com/user-attachments/assets/4f6dfd20-ddd5-42d4-8d92-9085de7208e6)

I don't know if this is something that will be fixed in later updates, so I'm not certain if this is an issue worth fixing or waiting on.

**Comment by NightFright2k19** [comment]
I think the Nightdive port is scaling the image down a bit, and offsets are adjusted accordingly. I might be wrong, though.

**Comment by rfomin** [comment]
The original Doom code and PrBoom+ don't have a centering for `M_DOOM`. If we change this, older PWADs may look wrong.

**Comment by fabiangreffrath** [comment]
Typical case of "Why did they change this? Are we now supposed to change this, too?"

**Comment by OpenRift412** [comment]
> The original Doom code and PrBoom+ don't have a centering for `M_DOOM`. If we change this, older PWADs may look wrong.

I was thinking moreso an exception could be made for this specific WAD, having it center just for this specific version of masterlevels.wad since it's an official WAD file. But if that clashes too much with the port's design philosophy, we can just ignore this, I suppose.

**Comment by fabiangreffrath** [comment]
Sure we could fix it, that'd be a two lines patch. The question is rather, where do we start and where do we stop adding exceptions and fixing bullshit that's outside our own responsibility.

Similar example: https://github.com/fabiangreffrath/woof/issues/1747

My general stance is, if content creators decide to mess things up, it's not our job to get it right again.

**Comment by ceski-1** [comment]
> I don't know if this is something that will be fixed in later updates, so I'm not certain if this is an issue worth fixing or waiting on.

Every `M_DOOM` lump I've seen uses offsets to ensure they're centered correctly. It looks like someone forgot to add them here:

![Untitled](https://github.com/user-attachments/assets/59e54f69-d059-4c8a-a49e-fed866afa454)

I'm guessing the KEX port doesn't use offsets at all, and simply centers the image based on dimensions. So it was probably an oversight or simply not considered. It would be nice if this was fixed by the creators, rather than hacking in something for just one image.

**Comment by NightFright2k19** [comment]
I guess there could be a general implementation like "center it if offsets are [0,0], otherwise ignore"?

**Comment by rfomin** [comment]
In some PWADs, unusual things are done with `M_DOOM`. For example, Hell Revealed 2 (hr2final.wad)

![image](https://github.com/user-attachments/assets/9f587a76-5e2b-4d33-b558-c8c5a49eae2d)

I think the new "masterlevels.wad" problem is not that serious, better not touch this code.

**Comment by ceski-1** [comment]
> Could there be a general implementation like "center it if offsets are [0,0], otherwise ignore"? (Unless the recent code update does that already.) Then at least it wouldn't only be for this one lump. However... since every other port requires offsets, that would make the whole thing questionable. Unless there will be more Kex-specific pwads with this issue at some point.

Hacking in workarounds has a tendency to cause other issues (what if another wad already uses [0,0] for `M_DOOM`?). If there are wads that target the KEX port, it will be up to the author to decide if they want compatibility with more than one port by playtesting, that's always been the case.

I suggest reporting this as a bug to the KEX team or, if they can't fix it, create a community fix pack similar to the minor sprite fixing project. It's clear there are changes with this port that break with established practices:

![kex](https://github.com/user-attachments/assets/aca3f1b9-1660-459d-8cae-701773a0643c)
![vanilla](https://github.com/user-attachments/assets/0c4b65f8-f5ec-40f0-ae25-b6d8e442ac26)

**Comment by ceski-1** [comment]
@NightFright2k19 Do you have any interest in providing a fixed `M_DOOM` in [your patch](https://forum.zdoom.org/viewtopic.php?t=79354)?

**Comment by NightFright2k19** [comment]
Sure thing. [It's done!](https://forum.zdoom.org/viewtopic.php?t=79354)

[Comparison screenshot](https://i.imgur.com/hEjfXB9.png)

**Comment by ceski-1** [comment]
Thank you!

**Comment by fabiangreffrath** [comment]
Thanks, I guess that's it then.
