### ISSUE TITLE
Fullscreen CWILV doesn't work in "Entering" screen with UMAPINFO

### ISSUE THREAD

**Issue by bangstk** [fabiangreffrath/woof#1840]
This may be an issue that appeared after [fullscreen cwilv fix](https://github.com/fabiangreffrath/woof/commit/ae7b1403b59b9c2f6b7145c2e6a18a74c0267fd1)

If a UMAPINFO refers to "levelpic"s that are fullscreen graphics, the "Finished" CWILV/levelpic draws fine but the "Entering" CWILV/levelpic does not seem to draw at all. The same CWILV works fine in the "Finished" screen when that upcoming level exits.

If there is no UMAPINFO both fullscreen CWILVs draw properly.

A test case is to use this UMAPINFO lump with Eviternity.
[UMAPINFO.txt](https://github.com/user-attachments/files/16620409/UMAPINFO.txt)

In DSDA and even GZDoom they both draw.

Thanks

**Comment by rfomin** [comment]
It works if `enterpic` and `exitpic` are specified:
```
map MAP02
{
	label = "Level 2"
	levelname = "Subterranean"
	levelpic = "CWILV00"
	exitpic = "CWILV00"
	enterpic = "CWILV01"
	author = "Dragonfly"
	skytexture = "OSKY28"
	music = "D_STALKS"
	partime = 80
}
```
It seems that our `levelpic` implementation has a bug.
