### ISSUE TITLE
[Feature] Automap color scheme for Remaster

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#1842]
If it's possible, the automap color scheme for the new Remaster could be added.

As far as I can see, it follows the vanilla scheme with three differences:
- Key doors are color-coded
- Walls have a darker red (to distinguish them from red doors)
- Yellow lines are white (to distinguish them from yellow doors)

(It's also possible to adjust line thickness, but that probably falls outside of this request.)

Realization:
- Add a new scheme labeled "Remaster" (ideally placed between "Vanilla" and "Crispy" regarding its selection order)
- Automatically turn on "Color Keyed Doors" if selected (door colors probably wouldn't have to be changed)

**Comment by fabiangreffrath** [comment]
So, this is pretty much already covered by the Crispy scheme if you enable colored keyed doors.

**Comment by NightFright2k19** [comment]
Well, Crispy seems to have these green lines in it, I dunno what they stand for. These don't appear in the Remaster, as far as I can tell. Also, yellow lines in Crispy are rather brown like the others. I guess these are rather minor distinctions though which could be manually adjusted if needed.
