### ISSUE TITLE
Could Not Write Defaults To tmpwoof.cfg

### ISSUE THREAD

**Issue by mfdoo** [fabiangreffrath/woof#1846]
![Woof Problem](https://github.com/user-attachments/assets/9f05b384-56d7-4e54-9eab-90fda6d52614)

For some reason every time I exit out of the woof application this window pops up, the changes I made to the settings aren't saved when I reopen woof. Is there any way to solve this

**Comment by fabiangreffrath** [comment]
You don't seem to have write permissions to this directory.

**Comment by mfdoo** [comment]
> You don't seem to have write permissions to this directory.

Would I have to change it to a different directory? Like regular program files?

**Comment by rfomin** [comment]
Do not run classic Doom ports from the “Program Files” directory. Try “C:\Games\Woof” or something like that.

**Comment by mfdoo** [comment]
> Do not run classic Doom ports from the “Program Files” directory. Try “C:\Games\Woof” or something like that.

Yeah I just did that!! Thanks for the help 👍
