### ISSUE TITLE
`CREATE_WAITABLE_TIMER_HIGH_RESOLUTION` prevents compilation on Windows 7

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1848]
See [this section](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createwaitabletimerexw#parameters) of the `CreateWaitableTimerExW` article: 

> **CREATE_WAITABLE_TIMER_HIGH_RESOLUTION** - Creates a high resolution timer. [...] **This value is supported in Windows 10, version 1803, and later.**

Knowing that Win7 has reached its EOL, I'm not going to insist on that you apply a fix. However, if there _is_ a fix (version macros, maybe?), I'd be thankful if you could inform me about it so I can apply it in Nugget (at least in my local build).

**EDIT:** _Now_ I understand why I was mentioned in https://github.com/fabiangreffrath/woof/pull/1744#issuecomment-2172742151; I didn't catch this because I used an autobuild instead of compiling it myself. Unfortunately, I didn't remember until after opening this issue.

**Comment by ceski-1** [comment]
Yeah, it needs to fall back to the non-Ex function if it fails a Windows version check.

**Comment by fabiangreffrath** [comment]
We could let cmake check for that symbol.
