### ISSUE TITLE
Kex-Style Fullscreen HUD Preset

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#1850]
The fullscreen HUD from the new remaster seems simple enough to add as an option, would that be doable?

**Comment by SladeWilson52** [comment]
I agree with this. All it is is an extra HUD option so I don't see why it would be too much of a hassle.

**Comment by lychnisvakter** [comment]
agree, the status bar face in full screen is really welcome, a very good complementary health indicator, I find that I'm way more careful during gameplay when I have a better visual representation of my status and not just numbers

**Comment by fabiangreffrath** [comment]
> I agree with this. All it is is an extra HUD option so I don't see why it would be too much of a hassle.

You have never touch one line of code yourself, right?

**Comment by MrAlaux** [comment]
I'd like to mention that Woof supports modification of the Boom HUD, but the same can't be said about the Crispy HUD (which is what the KEX port's HUD is more akin to). If such a thing doesn't come to fruition, it might be worth mentioning that [my fork of Woof](https://github.com/MrAlaux/Nugget-Doom) does allow to modify the Crispy HUD; I'd say that recreating the KEX HUD is one of the simpler things that can be done with its HUD-customization capabilities.

P.D.: I still don't know if there are any objections against "advertising" Nugget in this repository.

**Comment by fabiangreffrath** [comment]
> P.D.: I still don't know if there are any objections against "advertising" Nugget in this repository.

It's okay, I guess, we don't have anything to hide anyway.

**Comment by NightFright2k19** [comment]
We don't really have to imitate other ports IMHO. If you want the mugshot in the fullscreen HUD, DSDA-Doom will support it eventually according to Kraflab. 

It's enough to support the new episode, but we don't need to imitate port features (came to realize that after asking for a new automap color scheme from Kex which was basically already included).

**Comment by NightFright2k19** [comment]
Maybe more moddability could be added, but adding more and more HUD options may go too far. I'm glad the minimum one-line Boom HUD was added, but that was done because it fit with the existing style and wasn't too much effort. Recreating an entirely different HUD will give poor Fabian and his associates needless headaches.

**Comment by rfomin** [comment]
I think we will try to implement SBARDEF, but I can't promise quick results.

**Comment by OpenRift412** [comment]
> I think we will try to implement SBARDEF, but I can't promise quick results.

All good, it's no rush.

**Comment by NightFright2k19** [comment]
I guess that's a fair move. Let people build their own bars if they want. Custom defs will pop up in no time, problem solved.

**Comment by rfomin** [comment]
Implemented in https://github.com/fabiangreffrath/woof/commit/2b05d6d6abbe2299e4080b987a790e9c5f574260
