### ISSUE TITLE
[Feature Request] More weapons toggle buttons

### ISSUE THREAD

**Issue by Darthtallgeese** [fabiangreffrath/woof#1855]
Is possible to add more toggles just like SG/SSG and Fist/Chainsaw?, by example Plasma/BFG or Chaingun/Rocket launcher.

Would be very comfortable while using a controller.

**Comment by ceski-1** [comment]
I've been experimenting with mode shifting since it's the preferred modern approach to weapon selection for gamepads. I'm not sure if or when that will be completed. In the meantime, you can use Steam Input to achieve pretty much anything you want, if you don't mind launching Woof through it.

**Comment by ceski-1** [comment]
> I was thinking something like this:

Yes, that's one of several approaches, all of which have a surprising number of "gotchas" hidden along the way. Some careful planning will be needed for something that seems so simple at first.

> And thanks for Woof!.

I contribute where I can, but credit should go mainly to @fabiangreffrath and @rfomin for bringing this port to life.

**Comment by JustinWayland** [comment]
@Darthtallgeese

I like your idea. Seems much less janky and easier to set up than my current approach, which is to map joystick presses, bumpers, and remappable back buttons to individual weapons and shove the pistol on the screenshot button.  Your approach is easier to remember, gives a use to the currently useless dpad, and can be used on any old controller from the last decade.  Mine does have a couple of advantages

The first advantage my setup has is a dedicated pistol button for those mods that overhaul the pistol into something actually useful (ex. Eviternity, Ray Mohawk 2), but this is easily fixable given that two of the face buttons on a gamepad are currently unused under Woof!'s current default control scheme.  The second advantage is a minor comfort increase for rightys using flick stick and gyro, but the keyword there is _minor,_ as a simple test indicates that at least for me it's not too far of a reach.

And @ceski-1 your contributions, especially the gyro and flick stick ones, make the playing experience for controller players rival KEX Doom, which is a mean feat.
