### ISSUE TITLE
More flick stick options should be exposed through the GUI

### ISSUE THREAD

**Issue by JustinWayland** [fabiangreffrath/woof#1856]
Finally had time to test out the gyro and flick stick implementation.  Thought I had a problem with the 8-way stuff, but that was because of controller deadzone issues that I now know how to fix.

That being said, I think a couple more of the options for the Flick Stick control scheme in the text file should be exposed in the GUI.  The biggest one I can think of the option ```joy_flick_snap```, although for accessibility reasons ```joy_flick_time``` might be good as well.

Other than that, I really like what was done with this.

**Comment by ceski-1** [comment]
I appreciate the testing and feedback, thank you. What kind of controller(s) did you end up using? It's not practical for me to test every type, so I'm curious.

As for exposing more settings in the menu, there's not much room left, so additional flick stick settings will remain config-only for now. If the menu system is expanded in the future (e.g. submenus or popup menus become possible), I'll carefully reconsider every setting that didn't make the cut.

Also, I still need to write some documentation. The gamepad overhaul actually started a few releases back, and some more details will be useful I think.

**Comment by JustinWayland** [comment]
I used an 8BitDo Ultimate Bluetooth Controller, which was masquerading as a Switch Pro controller over Bluetooth (only way to get gyro on the PC with this controller unfortunately). The issue was the values emitted when the joysticks are at rest after the controller booted were way beyond the default 15% deadzone, which was odd because they were Hall Effect sticks.  The fix was to just rotate both sticks fully once, which caused the resting values to go to something imperceptible even at 1% deadzone.

**Comment by ceski-1** [comment]
> The fix was to just rotate both sticks fully once

Yeah, that appears to be a known issue with Switch controllers (or ones that emulate them) since there's some kind of auto-calibration mechanism in the firmware. Here's an SDL discussion about it: https://github.com/libsdl-org/SDL/issues/932

I'm guessing it's not an issue in USB or 2.4GHz modes because the 8BitDo controller behaves as an Xinput device (but you lose gyro as you mentioned).
