### ISSUE TITLE
Menu bug/crash

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1857]
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/10449481625)._

Steps to consistently cause a visual bug, with a fresh config file:

- Go to `Options > Weapons > Preferences`
- With the mouse, hover over the `Pre-Beta BFG` item
- Using the mouse wheel, switch to the `Cosmetic` tab

You should see a `( Del ) to clear` text appear on the bottom, out of nowhere.

Following similar steps in other menus can yield similar results, and even crashes. Check this out (look at the mugshot):

<details><summary>Screenshot</summary>
<p>

![imagen](https://github.com/user-attachments/assets/35173663-f3a8-4143-8e71-d4b38231351d)
</p>
</details> 

If I had to guess, some pointers aren't being properly updated. Sometimes, the text on the bottom even changes all by itself periodically, without any input from my end.

**Comment by ceski-1** [comment]
Can you check if this happens with the commit just before the big gyro update? I made changes to help text behavior so it's possible I introduced an issue there.

**Comment by MrAlaux** [comment]
> Can you check if this happens with the commit just before the big gyro update?

I wouldn't say my testing was particularly thorough, but from what I can gather, [this](https://github.com/fabiangreffrath/woof/actions/runs/10321660503) (right before the gyro commit) is unaffected, whereas [this](https://github.com/fabiangreffrath/woof/actions/runs/10338067568) (the gyro commit) is affected. Indeed, it looks like something went wrong in the latter commit.

**Comment by ceski-1** [comment]
Thank you. I won't be able to look at this closer until tomorrow, but that helps narrow it down.
