### ISSUE TITLE
Option for Quit Sound Effects

### ISSUE THREAD

**Issue by hkight** [fabiangreffrath/woof#1871]
Other source ports have an option to re-enable the quit sound effects present in vanilla Doom, but as far as I can tell, Woof does not have this option. If possible, it would be nice to have this option available.

**Comment by fabiangreffrath** [comment]
Well, we can talk about that. But which other source port has this as an option?

**Comment by hkight** [comment]
It was recently implemented in the Nugget Doom fork as an option in the config file. It's tied to the ENDOOM screen, but was made a separate option enabled by default.

**Comment by ceski-1** [comment]
Personally, I'd like to avoid yet another setting or menu item, so how about reworking the current "Endoom Screen" menu item into something like this?

"Exit Sequence"
- Off
- Sound Only
- PWAD Endoom
- On

"Off" remains the default.
