### ISSUE TITLE
menu: thermo descriptions highlighting

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#1882]
Thermo descriptions are only highlighted when the mouse hovers the thermo, not when the mouse hovers the actual description.

**Comment by rfomin** [comment]
This was done intentionally. In the case of other menu item types, if the user clicks on the description, he still selects/changes the item, in the case of thermo it is not clear how to change the value of the item.

**Comment by fabiangreffrath** [comment]
To me it looked like an oversight. I interpret the highlighting as "you are here" and not as "you can change by clicking now".
