### ISSUE TITLE
Dark overlay/backdrop darken walls with delay

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1883]
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/10741219991)._

As the title says: when the dark automap background or the dark menu backdrop are applied, planes and sprites are darkened together, but walls are darkened in the next frame. I can already notice this with the game running at 60 FPS, and it's even more noticeable by capping the framerate and reducing the game speed (which essentially caps the framerate even further).

**Comment by rfomin** [comment]
Honestly, I'm not sure the current shading method is a good idea. It helps in the case of HOM, but it still doesn't look very good ([wow.wad](https://doomwiki.org/wiki/Wow)):

https://github.com/user-attachments/assets/eff27af5-ad3f-49c1-9a84-1247c3525bde

Should we go back to the old method?

**Comment by MrAlaux** [comment]
> It helps in the case of HOM

I think issues with HOMs can be excused. Intentional HOMs don't seem to be very common anyways.

> Should we go back to the old method?

Wouldn't we lose the increased performance of this method? If I'm not mistaken, the old method is just a post-processing filter (i.e. extra work), whereas this one already draws the world darkened.

**Comment by rfomin** [comment]
> Wouldn't we lose the increased performance of this method? If I'm not mistaken, the old method is just a post-processing filter (i.e. extra work), whereas this one already draws the world darkened.

Right, but the current method is over-complicated and the performance gain is not that great. The main motivation was to fix the map overlay on the HOM, it works but is far from perfect. I think it still needs to be post-processing, but perhaps done in a different way, such as using the GPU. Maybe in SDL3 we can revisit this (and add a bunch of other shaders/filters), but for now let's go back to the old method.

**Comment by MrAlaux** [comment]
> The main motivation was to fix the map overlay on the HOM

My reasoning about HOMs is as follows:
If darkening is applied, it means that you've opened either the automap or menu, which implies that you want to look at those instead of the game world. If there's anything important to see -- enemies and maybe geometry, but not HOMs since they're arguably just "garbage" -- you can still see it.

**Comment by rfomin** [comment]
> If there's anything important to see -- enemies and maybe geometry, but not HOMs since they're arguably just "garbage" -- you can still see it.

[wow.wad](https://doomwiki.org/wiki/Wow) is obviously a joke, but there are serious wads that use HOM effect. I think I saw it in [icgya](https://doomwiki.org/wiki/I_CANT_GIVE_YOU_ANY_THING).

**Comment by MrAlaux** [comment]
> [wow.wad](https://doomwiki.org/wiki/Wow) is obviously a joke, but there are serious wads that use HOM effect. I think I saw it in [icgya](https://doomwiki.org/wiki/I_CANT_GIVE_YOU_ANY_THING).

I'm aware; what I mean is that HOMs aren't concrete visuals, but rather literal leftovers -- what was on that part of the screen in the previous frame.
