### ISSUE TITLE
Add Mouse Button Menu Prompts

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#1892]
I noticed in the new dev build, button prompts have been added for gamepad and keyboard controls in the menus. I'd suggest also having something similar for using the mouse as well.

**Comment by ceski-1** [comment]
This is an intentional change. Please read this: https://github.com/fabiangreffrath/woof/pull/1890#pullrequestreview-2288468622

**Comment by ceski-1** [comment]
Or rather, an intentional limitation. But let me think about it some more.

**Comment by OpenRift412** [comment]
> This is an intentional change. Please read this: [#1890 (review)](https://github.com/fabiangreffrath/woof/pull/1890#pullrequestreview-2288468622)

Good point.
