### ISSUE TITLE
Kex-Style Quicksave/Quickload Main Menu Shortcuts

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#1893]
In the Kex port, pressing LB or RB on the pause/main menu will quicksave or quickload respectively. Would it be possible to implement something like this for Woof? These would be separate binds from the typical F6 and F9 quicksave/load functions. Or would that be too redundant of an addition?

**Comment by rfomin** [comment]
Yeah, I like that idea, otherwise there aren't enough buttons on the gamepad. By the way, the KEX port has a separate slot for quick save:

![image](https://github.com/user-attachments/assets/4d177746-de4d-492b-8c12-8890d01f0f94)

**Comment by OpenRift412** [comment]
> Yes, I like that idea, otherwise there aren't enough buttons on the gamepad. By the way, the KEX port has a separate slot for quick save:
> 
> ![image](https://private-user-images.githubusercontent.com/5077629/365492771-4d177746-de4d-492b-8c12-8890d01f0f94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTEzMTUsIm5iZiI6MTcyNTg1MTAxNSwicGF0aCI6Ii81MDc3NjI5LzM2NTQ5Mjc3MS00ZDE3Nzc0Ni1kZTRkLTQ5MmItOGMxMi04ODkwZDAxZjBmOTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDlUMDMwMzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGI1ZmRhODJkZWI1ZjNmNjNlZGYzOWQ2YzFjNTZhZTkyMWE5NWNiOGI0NjkwNzFmYmQ3N2Q3NmE3Zjc5ODkxOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5K4QIStUTC3-0ul1-el2Rtbup-18ueHmGd0BjI2Sn5E)

I think the dedicated quicksave slot is good if you have the "Organize Save Files" option enabled, but not so much otherwise.

**Comment by ceski-1** [comment]
I've been following comments about this feature and have noticed reports (not just on Doomworld) of accidentally saving/loading when opening the main menu and setting the controller down quickly, causing the triggers to activate.

So I don't think it should be implemented exactly the same way as the KEX port, but maybe an input combination could work, to make sure it was intentional. For example, hold LB or RB then press A at the main menu.

**Comment by OpenRift412** [comment]
> I've been following comments about this feature and have noticed reports (not just on Doomworld) of accidentally saving/loading when opening the main menu and setting the controller down quickly, causing the triggers to activate.
> 
> So I don't think it should be implemented exactly the same way as the KEX port, but maybe an input combination could work, to make sure it was intentional. For example, hold LB or RB then press A at the main menu.

I've given this some thought, and I think what could be done is we could repurpose the old quicksave/quickload confirmation dialogues from vanilla doom to be that safety buffer. In other words, when LB or RB are pressed on the main menu during an active game, a confirmation dialogue will appear asking if you would like to quicksave/quickload.

**Comment by ceski-1** [comment]
I've been experimenting with this but I'm not yet convinced that it's a good idea. Without prompts, it's too easy to accidentally trigger a quick save/load. With prompts, the extra button presses make it pointless since it's about the same amount of work as using the "save game" menu. Anyone have thoughts on where to go from here?

https://github.com/user-attachments/assets/3665ac86-3fc1-441c-97ea-fd7bf314564a

**Comment by ceski-1** [comment]
There also seems to be a mouse cursor bug in that video. It shouldn't be appearing.

**Comment by rfomin** [comment]
> Without prompts, it's too easy to accidentally trigger a quick save/load. With prompts, the extra button presses make it pointless since it's about the same amount of work as using the "save game" menu. Anyone have thoughts on where to go from here?

I think it's useless with the prompts. How about double tapping the buttons?

**Comment by ceski-1** [comment]
> How about double tapping the buttons?

Still not great.

I think all of this experimenting demonstrates why this feature isn't seen very often in games. In the process of simplifying an already simple task, it actually creates other usability issues.

If people are requesting this, I think it's less about wanting the exact feature, and more a symptom of other issues with a game's menu system.

For Woof, saving/loading is already simple. However, I think if we made name entry for saving a little less clunky when using a gamepad (trying to cancel name entry is awkward), it would basically achieve nearly the same result without creating other issues.

**Comment by ceski-1** [comment]
Another idea is to implement an intelligent auto save system.

**Comment by OpenRift412** [comment]
> > How about double tapping the buttons?
> 
> Still not great.
> 
> I think all of this experimenting demonstrates why this feature isn't seen very often in games. In the process of simplifying an already simple task, it actually creates other usability issues.
> 
> If people are requesting this, I think it's less about wanting the exact feature, and more a symptom of other issues with a game's menu system.
> 
> For Woof, saving/loading is already simple. However, I think if we made name entry for saving a little less clunky when using a gamepad (trying to cancel name entry is awkward), it would basically achieve nearly the same result without creating other issues.

What about long-pressing? Do you think that would be a more elegant way to implement it?

**Comment by rfomin** [comment]
> I think if we made name entry for saving a little less clunky when using a gamepad (trying to cancel name entry is awkward), it would basically achieve nearly the same result without creating other issues.

This is a good idea.

> Another idea is to implement an intelligent auto save system.

Even a simple autosave at the beginning of the level would be nice.

**Comment by ceski-1** [comment]
> What about long-pressing? Do you think that would be a more elegant way to implement it?

No, not really. I think it's better to ask: What is it about this port that would motivate someone to think this feature is needed?

We have identified two areas to focus on:
- The save game menu can be clumsy to use with a gamepad
- There are no autosaves so it's easy to forget to save and lose all progress

I think we'll start there. I don't think KEX-style quicksaving is the appropriate solution.

**Comment by ceski-1** [comment]
Closing in favor of:

- https://github.com/fabiangreffrath/woof/pull/1929#issue-2558035715
- https://github.com/fabiangreffrath/woof/pull/1939#issuecomment-2392474108
