### ISSUE TITLE
Add ways to leave F1 help screen with mouse

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#1897]
As it stands, the F1 help screen is kind of in a weird place. You can only really exit the screen with the escape and enter keys (and their gamepad equivalents), which is a bit inefficient for mouse input. 

I would suggest having left and right click on the mouse return the main menu, and maybe backspace as well.

**Comment by rfomin** [comment]
Fixed in https://github.com/fabiangreffrath/woof/commit/ad47fe9d7386d3ddd7b90ce682d1dc7022f4ba32
