### ISSUE TITLE
When set to 16:9, resolution is actually 1917x1080

### ISSUE THREAD

**Issue by JustinWayland** [fabiangreffrath/woof#1905]
Proof of settings: 
![Screenshot_20240913_160623](https://github.com/user-attachments/assets/488c8027-a152-4904-b9b4-beefff93b3fd)

Proof of resolution (provided by ```obs-gamecapture```):
```
[obs-vkcapture] Init GLX 1.5.1 (64bit)
I_OpenGamepad: Found a valid gamepad, named: Nintendo Switch Pro Controller
S_ChangeMusic: D_INTRO (DOOM.WAD)
[obs-vkcapture] Texture GL_RGBA 1917x1080
[obs-vkcapture] ------------------ opengl capture started ------------------
```

This is mostly annoying for OBS users.

**Comment by rfomin** [comment]
> Texture GL_RGBA 1917x1080

This is our internal resolution, due to aspect ratio correction and integer math there are rounding errors. We do this on purpose to make the DRS feature less noticeable. It shouldn't concern OBS users, the output resolution will match the window or display resolution.

**Comment by ceski-1** [comment]
> [obs-vkcapture] Texture GL_RGBA 1917x1080

I haven't tried OBS on Linux yet, but on Windows there is a way to capture the entire window or monitor resolution, rather than grabbing the texture as it seems to be doing there. So give that a try if it's an option available to you.

**Comment by JustinWayland** [comment]
You know what, I should have just posted the two relevant lines from the config file.

```
[0-5(1)] Widescreen (0 = Off; 1 = Auto; 2 = 16:10; 3 = 16:9; 4 = 21:9; 5 = 32:9) 
widescreen                   3
```
...
```
[0-?(1065)] Window width 
window_width                 1917

[0-?(600)] Window height 
window_height                1080
```

So it seems to be the window itself that is 1917x1080.

If this is uncorrectable due to rounding errors, feel free to close this.

**Comment by rfomin** [comment]
> If this is uncorrectable due to rounding errors, feel free to close this.

I think there is no perfect solution, it will always be a compromise. The image will look a bit more blurry, or the proportions will be a bit off, or the dynamic resolution will be more distracting. We're always looking for a better solution, but for now I think we'll keep the current implementation.
