### ISSUE TITLE
"Next Map" isn't working in Episode 4

### ISSUE THREAD

**Issue by hackneyed-one** [fabiangreffrath/woof#191]
Pressing Next Map on the map to the left take me to the map on the right.

e4m1 = e4m1
e4m2 = e4m1
e4m3 = e4m1
e4m4 = e4m1
e4m5 = e4m1
e4m6 = e4m3
e4m7 = e4m2
e4m8 = e1m1 !!! Yes Episode 1 Map 1
e4m9 = e4m3

**Comment by rfomin** [comment]
Fixed in https://github.com/fabiangreffrath/woof/commit/589d8c4f79c5803597a481ef186e2587c417076e
