### ISSUE TITLE
Dedicated menu graphics take precedence over `DBIGFONT` regardless of load order

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1912]
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/10875724653)._

If a WAD provides a dedicated graphic for a menu item, said graphic will be used even if a later WAD provides a `DBIGFONT`.

In the following example, I first loaded a WAD of mine which provides multiple Doom-styled (red) dedicated graphics (including `M_GENERL`), then a modified `btsx_e1a.wad` (which provides a `DBIGFONT`) without its own BTSX-styled (cyan) version of that graphic:
![imagen](https://github.com/user-attachments/assets/5c3cb840-0e98-4c33-92f0-e93197c32a34)

This inconsistency would obviously be corrected by using the `DBIGFONT` _if_ it comes later in the load order, like in this case. However, I'm not entirely sure if that would be wise -- any potential issues you can think of?

**Comment by rfomin** [comment]
> This inconsistency would obviously be corrected by using the `DBIGFONT` _if_ it comes later in the load order, like in this case. However, I'm not entirely sure if that would be wise -- any potential issues you can think of?

With current WAD system, it is not easy to determine if a menu lump has a lower priority than `DBIGFONT` or vice versa, we can only check if the lump came from IWAD. I'm not sure it's worth inventing some kind of priority/order system.

**Comment by fabiangreffrath** [comment]
> With current WAD system, it is not easy to determine if a menu lump has a lower priority than `DBIGFONT` or vice versa, we can only check if the lump came from IWAD. I'm not sure it's worth inventing some kind of priority/order system.

We should at least make sure that menu graphics and bigfont menu entries don't mix up.

**Comment by fabiangreffrath** [comment]
I think I just understood the issue at hand. So, you have menu graphics lumps for each menu item, but you mixed them up from different sources. So, no bigfont menu rendering is involved in the above screenshot?

Well, if all graphics lumps are provided for each menu item, how are we supposed to know that we should switch to the bigfont rendering?

**Comment by MrAlaux** [comment]
> I think I just understood the issue at hand. So, you have menu graphics lumps for each menu item, but you mixed them up from different sources. So, no bigfont menu rendering is involved in the above screenshot?

Correct. It's all dedicated graphics from one WAD or another.

> Well, if all graphics lumps are provided for each menu item, how are we supposed to know that we should switch to the bigfont rendering?

As I said, based on load order: if a `DBIGFONT` comes after a dedicated graphic, it might imply that it is "styled" akin to the dedicated graphics that come in the same WAD (and maybe later ones?) as it.

Given the following WAD load order (top is first):

```
mywad.wad, including:
- M_GENERL

btsx.wad, including:
- DBIGFONT
- M_# (the rest of dedicated graphics)
```

My idea is that `btsx.wad`'s `DBIGFONT` is used instead of `mywad.wad`'s `M_GENERL`, to prevent the style mismatch seen in the screenshot.

However, a shortcoming that I'm seeing with this now is that if two or more WADs meant to be loaded together (case in point: `btsx_e1a.wad` and `btsx_e1b.wad`) have dedicated graphics in a former WAD and a `DBIGFONT` in a latter one, this system would ultimately completely skip the dedicated graphics; I think we'll agree on that such outcome is unacceptable.
