### ISSUE TITLE
misaligned sky

### ISSUE THREAD

**Issue by elborbahquarama** [fabiangreffrath/woof#1914]
i'm a playtester for an mbf21 wad and in a level someone made, she used this sky but in woof (and dsda-doom in opengl rendering mode) the sky is misaligned (it shows higher than it's supposed to), but it shows up normally in dsda-doom in software rendering mode
![OSKY46](https://github.com/user-attachments/assets/0bc10b87-6c57-4693-81df-e2592e286007)

**Comment by fabiangreffrath** [comment]
Do you have "Stretch Short Skies" enabled on the Display tab of the General menu?

**Comment by elborbahquarama** [comment]
no it's off

**Comment by rfomin** [comment]
It's looks the same to me.
DSDA-Doom (software):
![dsda](https://github.com/user-attachments/assets/92cdc537-6965-4c7b-8bdd-81c38c224b04)
Woof:
![woof](https://github.com/user-attachments/assets/697e287d-587e-498e-a621-9579b7a5deb5)

Test WAD: [sky-a.zip](https://github.com/user-attachments/files/17052024/sky-a.zip)

**Comment by fabiangreffrath** [comment]
@elborbahquarama Could you post a screenshot of the problematic scene?

**Comment by elborbahquarama** [comment]
yes, there you go
![woof0003](https://github.com/user-attachments/assets/89643d2d-92d0-4ca7-81af-26e31a487185)
this is the screenshot i first took to report the misaligned sky in the playtesting channel
![Screenshot_2024-09-16_214155](https://github.com/user-attachments/assets/fe68164d-da12-460c-9d79-0ca2f29d70da)
here is also a screenshot that somebody else took after that using dsda-doom with software rendering, to show me it worked fine there (we're three persons to have looked it up and it showed the same for all of us) also the level uses mbf21 compatibility, though i don't think that changes anything...
also i don't know much about this, but the sky doesn't show the same in the level as in your screenshots, it doesn't have that "cut" at the two extremities of the image, instead it "loops" properly (i hope i'm not wasting your time with that stuff...)

**Comment by rfomin** [comment]
It looks like the sky is being stretched using the definition in the TEXTURE1 lump. So to reproduce this, we need the same scaling settings as in your PWAD. For example, in the SLADE editor:
![image](https://github.com/user-attachments/assets/7f71751b-d46a-434c-9056-55ff1762186a)

**Comment by fabiangreffrath** [comment]
You mean we use `textureheight[]` and this is set to `128` (and thus causes a stretched sky), instead of `patch->height` which would be the actual value of `200`?

**Comment by rfomin** [comment]
> You mean we use `textureheight[]` and this is set to `128` (and thus causes a stretched sky), instead of `patch->height` which would be the actual value of `200`?

I think using `textureheight[]` is correct, Pr+/DSDA do the same. The difference is in this line:
https://github.com/kraflab/dsda-doom/blob/acb9194b8dd48058b436c4763700212d7312dfb4/prboom2/src/r_sky.c#L100
(we have `>=` here).

**Comment by fabiangreffrath** [comment]
Ouch!

**Comment by rfomin** [comment]
Since we have different min/max angles for mouselook than in Hexen, maybe we need different `skytexturemid` values for the “tall” sky.

**Comment by rfomin** [comment]
> hmmm i'm so sorry guys i'm way out of my league here lol, i'm not gonna be able to help more, but i was told "the scale was 0 / 0" and that "it's reproducible by adding to texturex + patch in slade without further modification"

Thanks, that's sufficient information. There is a slight difference between Woof and DSDA-Doom, if the sky height was > 200px it would work the same.

**Comment by fabiangreffrath** [comment]
So, this is the fix?

```patch
--- a/src/r_sky.c
+++ b/src/r_sky.c
@@ -205,9 +205,10 @@ void R_InitSkyMap (void)
   // [FG] stretch short skies
   int skyheight = textureheight[skytexture] >> FRACBITS;
 
+  skytexturemid = 0;
   if (stretchsky && skyheight < 200)
     skytexturemid = -28*FRACUNIT;
-  else if (skyheight >= 200)
+  else if (skyheight > 200)
     skytexturemid = 200*FRACUNIT;
   else
   skytexturemid = 100*FRACUNIT;
```

**Comment by rfomin** [comment]
> So, this is the fix?

Yes, but I think it's a bug. But if people use it that way, then we have to replicate it.
