### ISSUE TITLE
Incomplete text

### ISSUE THREAD

**Issue by Swordman14** [fabiangreffrath/woof#1915]
I tried the "Bethesda Version" of the Ancient Aliens mod (link here: https://mods.bethesda.net/en/doom_doomii/details/6e6eb953-9d34-48a9-8acd-08d7cfd956a1/Ancient_Aliens__Official_Upload_) and noticed something in this port exclusively: the ending text doesnt show completely. This is how it shows in Woof:
![nugg0000](https://github.com/user-attachments/assets/a99f237f-63f0-480b-aeca-f08315f4180c)
And this is how it should be (Used DSDA-Doom):
![dsda](https://github.com/user-attachments/assets/93739578-35c1-4b2f-b65e-b28f99da995a)

**Comment by fabiangreffrath** [comment]
I think this is fixed by this commit:

https://github.com/fabiangreffrath/woof/commit/ce57d6a44d7874208d466f3213d865a137f69708
