### ISSUE TITLE
Custom IWAD intermission screen crash

### ISSUE THREAD

**Issue by elf-alchemist** [fabiangreffrath/woof#1917]
Similar problem to #1880.

I've recently been working on a personal use IWAD that merges all of UD, D2 and NRFTL into a single eight episode commercial mode WAD. I was going to test the `InterText` messages and Woof simply crashes.

I tried it out some days ago and it was working fine but after coming back to it and doing `git pull`, I keep crashing, a fresh `woof.cfg` made no difference but [here is mine](https://github.com/elf-alchemist/dotfiles/blob/main/local/share/woof/woof.cfg), either way.

It happens on the most recent commit, and both a4eb56e4ce20b1a6e0550b4c8ea9111d0dc1813d and cbf2e289b8fbcb887a5479b8740ec557d3b5a167, which were the last times I `git pull`ed.

This does not happen on Nugget.

https://www.youtube.com/watch?v=NP-2BnKO1OM

**Comment by elf-alchemist** [comment]
For reference, the following is the `UMAPINFO` definitions I have:
https://gist.github.com/elf-alchemist/7b519bd333edeb874d2132dbc7ac96f8

**Comment by MrAlaux** [comment]
> This does not happen on Nugget.

Must be that whatever Nugget build you're using is based on a Woof version different from the one you tried; I'm pretty sure I haven't made any changes that would affect this.

**Comment by rfomin** [comment]
> I've recently been working on a personal use IWAD that merges all of UD, D2 and NRFTL into a single eight episode commercial mode WAD. I was going to test the `InterText` messages and Woof simply crashes.

Would you mind sharing your IWAD somewhere privately? For example, by direct message on DW. I can't reproduce it yet, and it doesn't seem easy to replicate your test.

**Comment by elf-alchemist** [comment]
> > I've recently been working on a personal use IWAD that merges all of UD, D2 and NRFTL into a single eight episode commercial mode WAD. I was going to test the `InterText` messages and Woof simply crashes.
> 
> Would you mind sharing your IWAD somewhere privately? For example, by direct message on DW. I can't reproduce it yet, and it doesn't seem easy to replicate your test.

Most definitely, I'll hit you up on DW, I go by the same name and profile picture.

**Comment by elf-alchemist** [comment]
I've `git pull`ed, rebuilt, and it's working, now, many thanks @rfomin :smile:
