### ISSUE TITLE
Falling off ledges is active in complevel vanilla...

### ISSUE THREAD

**Issue by hackneyed-one** [fabiangreffrath/woof#192]
but disabled for playback causing a "correct" desync of an incorrectly recorded demo. ha ha!

Ok, so I was playing PRCP.wad MAP27 and I noticed the chaingunners were falling off the platforms when I set Woof for vanilla compatibility. This map is a favorite of mine so I knew this was off. I recorded a demo to show the behaviour but upon playback it "correctly" follows vanilla compatibility meaning my live play and recording is bugged but playback is fine.

Here is how the demo was made and what happens:

./woof -iwad plutonia.wad -file PRCP.wad -skill 4 -warp 27 -complevel vanilla -record woof-falling

When I was recording it the chaingunner on the right is knocked off the platform totally alive and starts firing at the Revenants. After that I just move around watching him for a bit, pick up the SSG and quit. However when playing it back in Woof, Chocolate-Doom and PrBoom-Plus-UM the chaingunner doesn't fall or start firing back at the Revenants. All my movements are correct. I am still looking at where he should be on the ground behind the platform.

If I force a complevel of Boom or MBF with PrBoom-Plus-UM by adding the -complevel command to playback it desyncs yet another way for Boom and another for MBF.

[woof-falling.zip](https://github.com/fabiangreffrath/woof/files/6434899/woof-falling.zip)

**Comment by fabiangreffrath** [comment]
Just today I merged a pull request by @rfomin which is supposed to fix this kind of Vanilla demo compatibility issue, so you are probably unlucky and recorded with the old buggy state.

**Comment by hackneyed-one** [comment]
Yep! I feel a bit silly now. I've updated Woof and the behaviour is correct during live play. Thanks! Great work everyone. Nothing to see here...
