### ISSUE TITLE
BRGHTMPS not working on custom IWAD

### ISSUE THREAD

**Issue by elf-alchemist** [fabiangreffrath/woof#1922]
Another issue to the same custom IWAD that I mentioned in #1917. The `BRGHTMPS` lump is not being loaded even when embedded into the WAD file itself. I tought that that by modifying it to enable the DOOM1 brightmaps as well as the Doom 2 ones, it was causing the issue, but even with a fresh Woof `BRGHTMPS` it'll not be detect at all.

Custom IWAD:
![woof0001](https://github.com/user-attachments/assets/f6a98063-ad3c-403e-bbfd-5a455fbbfbd8)

Doom II
![woof0002](https://github.com/user-attachments/assets/4f1e6c5f-da80-4db7-b666-2e0cad69e636)

**Comment by rfomin** [comment]
We plan to drop support for `BRGHTMPS` in favor of GZDoom-style brightmaps, see: https://github.com/fabiangreffrath/woof/pull/1921

**Comment by elf-alchemist** [comment]
Oh, I see.
I really liked the simplicity of the `BRGHTMPS` text-based definition, so it's a little sad to hear that, but I do like the power of the PNG brightmaps, too.
I'll close the issue, many thanks @rfomin.
