### ISSUE TITLE
Weapon Switch Sprites

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#1925]
Mostly thinking about having the option for a weapon selection indicator akin to what's seen in the Kex port when pressing the assigned next/previous weapon buttons (see image below for example), either using the sprites from extras.wad or using the weapon pickup sprites from the IWAD or PWAD (both of these options have their pros and cons). 

![image](https://github.com/user-attachments/assets/b464b9a1-de0e-4629-9778-0e35b3a163cb)

**Comment by ceski-1** [comment]
It's something I've thought about, but it raises some questions. For example, how would you visualize vanilla switching restrictions? When fully equipped, "next" skips fist and shotgun, "prev" includes them, plus the chainsaw/fist/berserk condition. Now take the solution you come up with and realize it won't look right when using Boom/MBF/MBF21. The KEX port seems to ignore these restrictions, so it's free to draw a straight line of weapons all the time. There are many tough questions like this.

**Comment by OpenRift412** [comment]
> It's something I've thought about, but it raises some questions. For example, how would you visualize vanilla switching restrictions? When fully equipped, "next" skips fist and shotgun, "prev" includes them, plus the chainsaw/fist/berserk condition. Now take the solution you come up with and realize it won't look right when using Boom/MBF/MBF21. The KEX port seems to ignore these restrictions, so it's free to draw a straight line of weapons all the time. There are many tough questions like this.

Let's see, I think, we can do it like so:

- In vanilla compat mode, if the player has chainsaw and no berserk, do not show the fist in the weapon select graphics.
  - If the player has the chainsaw AND berserk, switching to slot 1 will equip the chainsaw first. In this scenario, the fist graphic will be shown above the chainsaw, indicating that they occupy the same weapon slot and that the player must press the previous weapon button to switch to it (this can also be done for Boom/MBF/MBF21 modes too regardless of if the player has berserk).
- For the shotguns, it would work similarly. The shotgun sprite will be shown on top and the SSG below it, switching from slot 2 to slot 3 will equip the SSG, highlighting the SSG sprite below the regular SG.

Does this account for everything you're talking about?

**Comment by ceski-1** [comment]
Okay interesting, I have that sketched out exactly in one of three layouts, so maybe there's a solution here that isn't too confusing in prectice. We'll try a few things after getting some other items wrapped up first.

**Comment by ceski-1** [comment]
> How do we picture the fists or pistol if no additional PWAD is loaded?

That's one of about two dozen questions I have in my notes. We have to find CC licenced fallbacks like the dogs.

**Comment by MrAlaux** [comment]
> We have to find CC licenced fallbacks like the dogs.

I've a friend who could make some under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/), should he proceed? If so, bare fist or with brass knuckles?

**Comment by fabiangreffrath** [comment]
CC-NC is not an option, sorry. We canont forbid anyone to sell Woof and its assets.

**Comment by MrAlaux** [comment]
> CC-NC is not an option, sorry. We canont forbid anyone to sell Woof and its assets.

I've been using his assets under that very license in Nugget for over two years... oops.

**Comment by OpenRift412** [comment]
> How do we picture the fists or pistol if no additional PWAD is loaded?

That's why I was mentioning the pros and cons of either using the weapon select sprites from Kex's extras.wad or using weapon pickup sprites from the IWAD/PWAD. If we do the latter, I could probably make some fist and pistol sprites that could be included in Woof.pk3.

**Comment by MrAlaux** [comment]
> CC-NC is not an option, sorry. We canont forbid anyone to sell Woof and its assets.

What about just CC BY-SA?

Even then, how exactly would you determine the license of the assets? My friend would make them, but as far as you'd see, I would be the one sending them and stating their license.

**Comment by elf-alchemist** [comment]
As far as the licensing issue is concerned, an artist could be asked make a CC0 pistol sprite based on actual [CC0 pictures of real Berettas](https://openverse.org/search?q=Beretta&license_type=commercial,modification&license=pdm,cc0) and a brand new hand sprite from scratch, perhaps modeled on someone here's actual hand. If that artist releases both sprites publicly, also as CC0 then Woof could use it.

Or if only the pistol is to be provided, the ultimate backup plan for the hand sprite could be to just use the Medikit and Berzerk sprites.

~~Or if a \_very\_ generous artist can find the interest to donate an \_entire\_ set of `SM*` sprites that would be cool, too, but that's a big if.~~

**Comment by elf-alchemist** [comment]
Well, I asked an artist friend of mine, Amaruq Wulfe, and they made the missing weapon wheel sprites, published via [DW status](https://www.doomworld.com/profile/46930-amaruq-wulfe/?status=1747489&type=status) and, specifically as CC0, so these are fine to include:

[WeaponIcons.zip](https://github.com/user-attachments/files/17159687/Weapon.Icons.zip)

**Comment by JNechaevsky** [comment]
This opportunity is quite hard to come by. ❤️ 

The mission was to make "Doom weapon sprites, except they must not be a Doom weapon sprites", so here's a PWAD, by the request of @rfomin: [WoofWeap.zip](https://github.com/user-attachments/files/17178292/WoofWeap.zip)

Scaled mockup, so you can examine all the pixels (click to enlarge):
![WOOF_WEAPONS](https://github.com/user-attachments/assets/6aeb2e53-4ef0-43cf-9a0f-e9cab913e252)

**Comment by NightFright2k19** [comment]
It would kind of suck in PWADs which modify weapon sprites, though. These menu gfx would always stay the same since it's unlikely people start to provide replacements in their wads. But well, this is a thought Nightdive has obviously discarded already, so...

**Comment by elf-alchemist** [comment]
At that point, if the weapon wheel becomes a more widely adopted feature, it would be more so responsibility of new PWADs to support it themselves, or other artists to make patches for old ones.

Otherwise, Woof could add an option to show the pickup sprites themselves, using Amaruq's supplementary sprites. 

![SMUNKN0](https://github.com/user-attachments/assets/0119a2a2-aff0-40db-aec9-f8c939c51630)
![SMFIST0](https://github.com/user-attachments/assets/ffb28a9b-339d-4454-aedb-b20f9b269e5c)
![SMPISG0](https://github.com/user-attachments/assets/5dc8aa66-7036-423e-8e67-c4526867a259)

**Comment by OpenRift412** [comment]
> The only solution could be to directly utilize the weapon sprites from the I-/PWAD and possibly apply some custom tint to them. Then again, there are no pickup sprites for the fist and pistol.

I don't think they would need a custom tint at all, I think what could be done is that the selected weapon will have a yellow outline applied to it by the engine. The fist and pistol could just use built-in fallback sprites.
