### ISSUE TITLE
Organize Save Files per IWAD Option

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#1932]
So we have an option to sort savegame files per PWAD, but would it possible have the option to do so per-IWAD as well? Or is that not worth pursuing?

**Comment by rfomin** [comment]
I think it already works. For example, with DOOM2.WAD saves go to the `doom2.wad` directory.

**Comment by OpenRift412** [comment]
> I think it already works. For example, with DOOM2.WAD saves go to the `doom2.wad` directory.

What I mean is all PWAD savegames that use say DOOM2.WAD as the IWAD will be organized to a specific folder.

**Comment by fabiangreffrath** [comment]
What would be the advantage?

**Comment by OpenRift412** [comment]
> What would be the advantage?

There's not really an inherent advantage, I guess it's more of just a personal taste thing. But I suppose it would be a good medium between having all your saves in one place and having savegames organized for every single PWAD. It's more like having separate lists of saves for each "game" so to speak. It's not super important, I just thought I'd throw the idea out there.

**Comment by NightFright2k19** [comment]
I would rather have a pwad loading the proper iwad along with it automatically. (If that's necessary or possible). For savegames I don't see any big benefit, to be honest.

**Comment by fabiangreffrath** [comment]
> having all your saves in one place and having savegames organized for every single PWAD

I don't think we are going to change this.
