### ISSUE TITLE
umapinfo: add `author` entry to level name announcement

### ISSUE THREAD

**Issue by elf-alchemist** [fabiangreffrath/woof#1936]
The `author` field remains unfortunately underutilized. A feature request I'd like to make to remedy this is to add a second line of text (below the level's name to enable more space for multi-author maps or lengthened names), to announce the level's author as well (if it isn't empty or only made out of whitespace).

Current Woof:
![woof0033](https://github.com/user-attachments/assets/b6c64911-58c3-40a9-aab5-0d8ccf38c7a3)

Current DSDA:
![doom01](https://github.com/user-attachments/assets/89ffc913-d6e4-4893-8810-a2a7ced5437a)

Overflow example:
![doom00](https://github.com/user-attachments/assets/fffb890e-8553-440a-aa18-6d9e87e5d50f)

**Comment by fabiangreffrath** [comment]
We now ave this since https://github.com/fabiangreffrath/woof/commit/2b05d6d6abbe2299e4080b987a790e9c5f574260:

https://github.com/fabiangreffrath/woof/blob/8fc5d4b42a35fd78bdd460b1831ccc523b4637d7/src/st_widgets.c#L621-L627

**Comment by elf-alchemist** [comment]
Many thanks, @fabiangreffrath!
