### ISSUE TITLE
Windows artifacts throw `I_InitTimer` error at startup

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1944]
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/11227383319)._

See for yourself:
![imagen](https://github.com/user-attachments/assets/f4ea71e6-f516-4658-9bac-1c7caa813628)

As always, I'm on Win7. My own build of the latest master doesn't throw this error.
https://github.com/fabiangreffrath/woof/commit/5c952ca4a6b6cfb079357508319edeb90e9923e8 seems to be the culprit.

**Comment by rfomin** [comment]
Should be fixed in https://github.com/fabiangreffrath/woof/commit/154ccf88494b86ae73ab30d14d0505e7cb47255c and https://github.com/fabiangreffrath/woof/commit/ff65fd60b80fe41f3de03f0373ef914e762279c8

**Comment by MrAlaux** [comment]
Yep, I don't get the error on the [latest Win-64 artifact](https://github.com/fabiangreffrath/woof/actions/runs/11238459182).
