### ISSUE TITLE
Which episode? Selection menu suggestion.

### ISSUE THREAD

**Issue by PorpiangWriter** [fabiangreffrath/woof#1945]
![Screenshot 2024-10-08 102728](https://github.com/user-attachments/assets/36727225-e9da-49f8-8e3d-fb6e855994e6)
![Screenshot 2024-10-08 102801](https://github.com/user-attachments/assets/d7ca7b99-71e8-42d3-9283-cff547917446)
Please update the episode selection in case Sigil & Sigil II wads are in the Woof! Folder for the Ultimate Doom 1, and masterlevels.wad, nerve.wad, and id1.wad in the Woof! Folder for Doom II. As what you did in Crispy Doom 7.0.

**Comment by fabiangreffrath** [comment]
Crispy Doom and Woof follow different approaches. Woof doesn't support "side loading", i.e. automatic detection and loading of supplemental PWADs and integration into a hard-coded menu. Instead, it offers more flexibility by supporting the UMAPINFO lump, which allows for complete customization of level progression, intermission screens, skies, music, etc. The disadvantage is that things don't work "out of the box" that easily. However, UAPINFO is an accepted standard even upstream at ID software. Recent reelases of e.g. Sigil contain that lump by default and integrate seamlessly into the game menu - you just have to load them explicitly. Having both - side loading and UMAPINFO support - is impossible in the worst case or at least very complicated to implement and is definitely not planned for the future.

**Comment by PorpiangWriter** [comment]
Thank you so much, I understand your decision.
