### ISSUE TITLE
Show Level Number in Savegame Preview

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#1948]
As it stands currently, when at the save and load game menus, the savegame preview will show the timestamp below the thumbnail. Would it be possible to have it display the map number as well? Probably not the full map name, as that would take too much space, but  maybe like the map header (ExMx, MAPxx, etc.)?

**Comment by ceski-1** [comment]
We tried it and decided to pass on this feature: https://github.com/fabiangreffrath/woof/pull/1954

**Comment by OpenRift412** [comment]
> We tried it and decided to pass on this feature: #1954

Fair point.
