### ISSUE TITLE
Auxiliary Compatibility Levels

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#1950]
So I know that one of Woof's design goals is more or less to simplify the modern Doom experience as much as possible while retaining the core features and compatibility. That being said, I think there are a few compatibility levels that I think do have practical use in some capacity. 

These compatibility levels wouldn't be selectable in the in-game menu for simplicity's sake but could be defined via the command line or via the COMPLVL lump if it could be extended to cover more complevels, as well as implementing the [GAMEVERS](https://github.com/andrikpowell/nyan-doom/blob/v1.1.9.1/docs/gamevers.md) lump from Nyan-Doom. These would also be useful for demo playback.

**Legacy Vanilla Complevels**
- 1.2 - mostly for historical purposes and for running early demos
- 1.666 - This is currently being relied on by [Arsinikk's RUST](https://www.doomworld.com/forum/topic/144559-rust-the-infernal-machine/) and perhaps other WADs as well. Woof is the only major source port that isn't properly compatible with this WAD
- If left undefined, assume 1.9/Ultimate/Final based on IWAD when complevel is vanilla.

**Other Complevels**
- PrBoom-plus Default - This is used for demo playback in Eviternity for example. Would probably be useful for other WADs too, given PrBoom-plus was the defacto standard port for such a long time.

**Comment by rfomin** [comment]
> 1.666 - This is currently being relied on by [Arsinikk's RUST](https://www.doomworld.com/forum/topic/144559-rust-the-infernal-machine/) and perhaps other WADs as well. Woof is the only major source port that isn't properly compatible with this WAD

It works with the `-complevel 2` parameter. We discussed this a while ago: https://www.doomworld.com/forum/topic/144676-the-complvl-lump/

> PrBoom-plus Default - This is used for demo playback in Eviternity for example.

Aside from a demos I'm not aware of any content that made specifically for PrBoom+ complevel.

I think that if simplification is the goal, we don't need a lot of rarely used complevels.

**Comment by fabiangreffrath** [comment]
Same opinion here. The mere fact that some mapper relies on an obscure quirk from an ancient complevel doesn't turn this complevel "relevant" over night. Especially, if that same quirk can be achieved with a complevel that we already have.

Regarding PrBoom-plus, `prboom_6_compatibility` has never been a relevant complevel for demo recording and I consider the fact that Eviternity's internal demos have been recorded in this format as an oversight. Implementing this would require to add *a lot* of PrBoom'isms, just to ignore them for any other complevel.

> I think that if simplification is the goal, we don't need a lot of rarely used complevels.

Exactly this. If a "universal demo playback machine" is needed, there's still DSDA-Doom. 😉
