### ISSUE TITLE
`stretchsky` affects vertically scrolling skies

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1955]
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/11253311884)._

If `stretchsky` is enabled, vertically scrolling skies (at least some with certain heights?) are stretched and get a seam that isn't there otherwise.

Here's an example from [Box Doom](https://www.doomworld.com/forum/topic/146901-box-doom-rc2-is-out), at around `X -3000 Y -1800`:

<details><summary>Screenshots</summary>
<p>

`stretchsky` off:
![imagen](https://github.com/user-attachments/assets/9579f855-ef08-42cc-a498-edfabbf806e7)

`stretchsky` on:
![imagen](https://github.com/user-attachments/assets/193c9248-7b6b-4de4-8444-cb0e9872f9fe)

The seam becomes more visible as the sky continues to scroll downwards.

---

</p>
</details> 

If the sky scrolls vertically, couldn't we just assume that it doesn't need any stretching at all?
If so, I believe that the following code should be `stretch && !vertically_scrolling`:
https://github.com/fabiangreffrath/woof/blob/5af52a72020a0c5f94c03957643785fca000a3ff/src/r_plane.c#L527

Mentioning #1230 for convenience.

**Comment by fabiangreffrath** [comment]
Relevant commit:
https://github.com/fabiangreffrath/woof/commit/bdd1deef595f92f4ba8ba194ee042158acbc623b
