### ISSUE TITLE
decrease verbosity

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#1959]
So, what would you say if we would decrease all these `P_SetupLevel`, `S_ChangeMusic`, `S_ChangeMusInfoMusic`, `G_DoPlayDemo`, etc. messages to `VB_DEBUG` verbosity? Either this, or we introduce another verbosity level that's equivalent to `VB_INFO` during `demoplayback` and `VB_DEBUG` else?

**Comment by rfomin** [comment]
I would remove these messages altogether, the original Doom didn't have them.

If we decide to keep them, I think we should make them more useful. For example, `S_ChangeMusic` should report the format of the music file (`MIDI`, `MUS`, `mp3`, etc.)

**Comment by fabiangreffrath** [comment]
Good point. However, I find it useful to know which complevel a demo was recorded with, or what the level time is of a savegame.

**Comment by elf-alchemist** [comment]
Just my own two cents, but I agree on keep them around as `DEBUG`-level messages, especially the logging of music being played, since if support for the `TRAKINFO` lump is ever considered, knowing which track is being played, and it's type, `*.mid/*.mus/*.mp3/*.ogg/*.xm/*.it`, would be very useful.
