### ISSUE TITLE
Auto-save load menu doesn't change `lastOn` properly

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1960]
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/11290836989)._

Steps to reproduce:

- Launch the game normally
- Enter the Load menu
- Move the cursor with the keyboard
- Change the page

You should see the cursor reset to the first slot, regardless of whichever slot you were on before changing the page. The cursor for the auto-save load menu itself isn't updated either: it too will be on the first slot when you return to said menu.

**Comment by ceski-1** [comment]
https://github.com/fabiangreffrath/woof/commit/59f016d24149ea6d00b93eda3fabecea0e80871a

This is a compromise since a better solution means writing a new load/save menu system which I'm not interested in doing.
