### ISSUE TITLE
`-speed` can be overridden by game-speed keys but not menu item

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1965]
_Tested in the [latest master](https://github.com/fabiangreffrath/woof/commit/d3ccce3675d63d6fbff5729d95a76a2213cf02f1) (own build)._

If a game speed value is forced through the `-speed` parameter, it is still used if I attempt to change game speed through the menu item (which calls `MN_ResetTimeScale()`), but it is overridden by changing game speed through keys (which call `I_SetTimeScale()` directly).

I was about to open a PR making it so that neither method can override the parameter, but I figured that I'd first ask what the intended behavior is.

**Comment by fabiangreffrath** [comment]
I think if the `-speed` parameter is given, it should not be possible to override it from in-game, no matter how.
