### ISSUE TITLE
suggestion: coloured blood and rotating/transparent maps 

### ISSUE THREAD

**Issue by srludicolo** [fabiangreffrath/woof#197]
1)  The mouse movement on Crispy Doom seems a bit laggier on Crispy Doom than Woof!, although that may just be me being stupid and not having raw mouse input checked or something.

2) I think it would be great for the ability to have rotating and background-less maps with the H and O hotkeys respectively like on Crispy Doom. I think these are awesome features that Crispy Doom has, but Woof! doesn't. Maybe coloured blood too?

**Comment by fabiangreffrath** [comment]
I guess I answered most of this by private e-mail already, but anyway...

> 1. The mouse movement on Crispy Doom seems a bit laggier on Crispy Doom than Woof!, although that may just be me being stupid and not having raw mouse input checked or something.

Crispy Doom features some mouse acceleration whereas Woof! doesn't. You'll need to increase mouse sensitivity in the in-game menu in Woof.

> 2. I think it would be great for the ability to have rotating and background-less maps with the H and O hotkeys respectively like on Crispy Doom. I think these are awesome features that Crispy Doom has, but Woof! doesn't. Maybe coloured blood too?

Automap overlay and rotate mode are on the agenda, colored blood currently isn't.

**Comment by srludicolo** [comment]
Shit, did I already send an email? I apologize, sir.

**Comment by fraansg** [comment]
Thanks for the implementation of coloured blood, but I would like to know if you consider it appropriate to move its location in the options menu from 'enemies' to 'general' or any other, because the first one cannot be modified in complevels other than mbf

**Comment by fabiangreffrath** [comment]
Oh, I'd say it definitely belongs into the enemies menu, and this one should always be enabled for this one item and all other items disabled based on complevel.

**Comment by rfomin** [comment]
> because the first one cannot be modified in complevels other than mbf

Fixed in https://github.com/fabiangreffrath/woof/commit/09f4841df42a9a18346a565a38157d4cc4ef58c5

**Comment by srludicolo** [comment]
I just wanna say that 5.2.0/6.0.0 is looking to be very exciting. Nice job, guys! Now I must ask the burning question; when can we expect the next official release?

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/68fed677ac9fd5fe2b24b7eb2837dbe2dab10320
