### ISSUE TITLE
[Bug] "Announce Revealed Secrets" resets itself

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#1980]
With latest dev snapshot (https://github.com/fabiangreffrath/woof/commit/bd11c0ce9a0c80b039a515c5dda1453c255d02ea), the option "Announce Revealed Secrets" resets itself to default (Off) after quitting and relaunching the game. This happens regardless whether you set it to "On" or "Count". The available settings themselves are fully functional while playing.

**Comment by fabiangreffrath** [comment]
The order of arguments should be (default, min, max) here:
https://github.com/fabiangreffrath/woof/blob/bd11c0ce9a0c80b039a515c5dda1453c255d02ea/src/st_widgets.c#L1090-L1093

**Comment by rfomin** [comment]
Fixed in https://github.com/fabiangreffrath/woof/commit/8fc5d4b42a35fd78bdd460b1831ccc523b4637d7
