### ISSUE TITLE
Restore Widget Font Option

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#1984]
I don't know if this conflicts with the ID24 SBARDEF spec, but if not, I think it would be a good idea to re-implement the widget font option from before the merge. 

I know a lot of people prefer the Boom/DSDA style widgets, but in my opinion having it use the standard small font in from the IWAD/PWAD is more aesthetically cohesive.

**Comment by rfomin** [comment]
It's possible to set font per-widget in SBARDEF. Search for `"widget"` elements `"type": 0` (stats):
```json
{
  "widget":
  {
    "x": 2,
    "y": 152,
    "alignment": 16,
    "tranmap": null,
    "translation": null,
    "type": 0,
    "font": "Digits",
    "conditions":
    [
      {
        "condition": 19,
        "param": 1
      }
    ],
    "children": null
  }
}
```
You can set `"font": "Console"` for standard small font.

We could just force the font for all widgets, but that might break the custom SBARDEFs. We can implement it for now though.
