### ISSUE TITLE
Add support for DMXOPL GENMIDI lump

### ISSUE THREAD

**Issue by ceski-1** [fabiangreffrath/woof#1987]
Save this for after the next release. Implementation is TBD, but as an example, `OPL3 Emulation` could be split into two "devices":

```
OPL3 Emulation: Vanilla
OPL3 Emulation: DMXOPL
```

Info:
- https://github.com/sneakernets/DMXOPL
- https://doomwiki.org/wiki/DMXOPL

**Comment by fabiangreffrath** [comment]
How would we implement support for that lump? Does our OPL3 emulator already provide it?
