### ISSUE TITLE
Level time/use-button timer issue

### ISSUE THREAD

**Issue by ceski-1** [fabiangreffrath/woof#1990]
It looks like the use-button timer doesn't clear after a few seconds. I don't use this feature, so I don't know what the exact behavior is supposed to be.

Also, there is an extra space between the map title and level time/use-button timer line. Not sure if that's intentional.

https://github.com/user-attachments/assets/41b1e72b-860d-4820-ae86-3616e70edbb3

**Comment by rfomin** [comment]
> It looks like the use-button timer doesn't clear after a few seconds. I don't use this feature, so I don't know what the exact behavior is supposed to be.

I don't know how it works either. @MrAlaux could you please explain?

**Comment by fabiangreffrath** [comment]
This is actually a Crispy feature that either Looper or ZeroMaster asked me to implement back then. The idea is that the split second in which you used the "use" key is shown for some time. Then it reverts back to normal level time.

**Comment by fabiangreffrath** [comment]
It seems that `player->btuse_tics` is never decreased in the new code.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/2b05d6d6abbe2299e4080b987a790e9c5f574260#diff-67532b3043b66e4348b4f6652d5767385fefb36aab675469992f7f28f5e49896L1751-L1752

**Comment by fabiangreffrath** [comment]
```patch
--- a/src/st_widgets.c
+++ b/src/st_widgets.c
@@ -841,6 +841,7 @@ static void UpdateStTime(sbe_widget_t *widget, player_t *player)
         M_snprintf(string + offset, sizeof(string) - offset,
                    GOLD_S "U %d:%05.2f\t", player->btuse / TICRATE / 60,
                    (float)(player->btuse % (60 * TICRATE)) / TICRATE);
+        player->btuse_tics--;
     }
 
     ST_AddLine(widget, string);
```
