### ISSUE TITLE
Death Exit in Eviternity Map05 not working. 

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#200]
Started playing Eviternity today, and found that the death exit on Eviternity's Level 5 doesn't seem to work as intended. You're meant to be warped to the next level on death, but instead you just die, and that's it. I'm using -complevel 11, that being Eviternity's intended complevel. Is this a code issue or am I just missing something here?

**Comment by rfomin** [comment]
Check "Zombie players can exit levels" compatibility flag. It should be set to "Yes". We fixed that, but you probably have an old config.

**Comment by OpenRift412** [comment]
> Check "Zombie players can exit levels" compatibility option. It should be set to "Yes". We fixed that, but you probably have an old config.

Damn, you're right. Thanks for pointing that out. Are there any other options that would be affected by me having an old config?

**Comment by rfomin** [comment]
> Are there any other options that would be affected by me having an old config?

You should be fine.

**Comment by fabiangreffrath** [comment]
"Build stairs exactly the same way that Doom does" should be disabled, at least it is by default in Pr+.

**Comment by fabiangreffrath** [comment]
Seems to be resolved now.
