### ISSUE TITLE
Blinking "You are here" sprite missing from Legacy of Rust episode 2 intermission screen.

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#2000]
As the title says. Also the splat sprite seems to be in the wrong spot.

Here it is in Woof:
![image](https://github.com/user-attachments/assets/86904578-d610-4d7e-b3b5-355cc8f2d39a)

And in Kex:
![image](https://github.com/user-attachments/assets/3629ab5f-fc5c-4a3d-9d69-4227a50c7b66)

**Comment by fabiangreffrath** [comment]
Cannot reproduce with the latest master. For me the intermission screen looked as on the second screenshot.

**Comment by OpenRift412** [comment]
> Cannot reproduce with the latest master. For me the intermission screen looked as on the second screenshot.

I just tried it with the latest master with the default settings and it still had the problem. Did you try with a default config?

**Comment by fabiangreffrath** [comment]
Em, yes, default config. I have to say that I started the second episode from the menu and clipped right to the exit. Did you play an episode 1 map before?

**Comment by fabiangreffrath** [comment]
Proof :innocent: 

![grafik](https://github.com/user-attachments/assets/69ee6eb7-34a8-4b38-9ebe-3f76e35e6c36)

**Comment by OpenRift412** [comment]
> Em, yes, default config. I have to say that I started the second episode from the menu and clipped right to the exit. Did you play an episode 1 map before?

I tried that. It works fine in episode 1, but not in episode 2. I don't understand why it's doing that.

**Comment by fabiangreffrath** [comment]
What's your command line and what do you have in your autoload directories? Any chance to load the game in a terminal with the `-verbose` parameter?

**Comment by OpenRift412** [comment]
> What's your command line and what do you have in your autoload directories? Any chance to load the game in a terminal with the `-verbose` parameter?

I did it with an essentially empty autoload folder. 

Here's the console output I get when running it with `-verbose`, copied to a TXT:
[id1_verbose.txt](https://github.com/user-attachments/files/17689107/id1_verbose.txt)
