### ISSUE TITLE
Restore User-facing Options for Automap Ratio and Line Smoothing

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#2004]
I think as a good rule of thumb, options that stray from a vanilla-esque presentation should remain user-facing in the menus, especially if they're going to be enabled by default. 

In this case, this would be the Automap Ratio and Line Smoothing settings. I can understand the reasoning for wanting to cut these settings in order to trim the fat, but I'd like to make some suggestions for how these can be displayed in a more user-friendly manner.

For the aspect ratio option, I would suggest re-labelling it to something like "Line scaling" or "Automap scaling" and label the options as "original" and "squared".

For the line smoothing, I think this could probably be config-only, but in my opinion it should be off by default because it's really the only place that this quasi-anti-aliasing is used, and thus feels out of place when the main in-game view still has jagged edges. If there was Heretic and Hexen support, I'd feel differently but that's not the case.

**Comment by ceski-1** [comment]
The defaults for Woof are a mix of vanilla and non-vanilla settings, with a balance that sometimes favors quality of life improvements. The last round of changes were made carefully with this in mind, with some settings moved to the config file. Please give these changes a try for at least one release and then see if you actually miss having these settings in the menu. I'm closing this issue but the feedback is appreciated--I'll be keeping a close eye on this.
