### ISSUE TITLE
Remove translucency filter option, lock to 66%

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#2012]
I'm not sure if there's much reason for this option to still be around, given this can make or break certain level effects in WADs that make use of it. Removing the option wouldn't change how anything in the vanilla game looks, as far as I know, so it shouldn't mess with anything in that regard either. 

That being said, I think until DECOHACK-defined sprite translucency is added, the Sprite Translucency option can stay.

**Comment by rfomin** [comment]
Trasnclucency flag is a Boom feature, we already support it. I suggest moving the discussion to https://github.com/fabiangreffrath/woof/issues/2013
