### ISSUE TITLE
TNT map 30 is unbeatable

### ISSUE THREAD

**Issue by klearscreen** [fabiangreffrath/woof#2014]
The Cyberdemon's room in TNT's map 30 has a key on top of a pillar, and you need to activate a switch that raises a staircase for the key. Woof! doesn't raise the floor correctly and the key becomes unreachable.
![1](https://github.com/user-attachments/assets/20b57980-73f7-491c-8214-ee9062758ee1)
![2](https://github.com/user-attachments/assets/11172805-0964-4f69-a5c1-15482e3e7cef)

**Comment by rfomin** [comment]
This is a known Boom problem. Try playing the level with vanilla compatibility.
