### ISSUE TITLE
[Bug?] Crash during specific savegame loading sequence

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#2018]
There seems to be a way to make the port crash to desktop with the following message:
**(Filepath)/MBFSAV-1.dsg: No such file or directory**

Tested with: 
Woof https://github.com/fabiangreffrath/woof/commit/1b8cb0d888f1b97954dac97aa52bd712cd2fa58c, Win x64

Steps to reproduce:
1) Play through any level, create a quicksave (F6)
2) Enter the next level to create an autosave
3) Press F9 and chose the quicksave from the previous map
4) Load autosave from next map once again
5) Press F9

**Comment by ceski-1** [comment]
Thanks for providing detailed steps.
