### ISSUE TITLE
level time widget 1px too low on Automap

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#2021]
![grafik](https://github.com/user-attachments/assets/fc4e5438-1872-40ae-9066-21f07cf204be)

**Comment by fabiangreffrath** [comment]
I don't know which is the right field to modify in the SBARDEF lump. Could you please have a look @rfomin ?

**Comment by rfomin** [comment]
Should be fixed in https://github.com/fabiangreffrath/woof/pull/2008

**Comment by rfomin** [comment]
Fixed in https://github.com/fabiangreffrath/woof/commit/0d5505bce4d9b1650f5a7ff1ad36038cb9f43951
