### ISSUE TITLE
Command history widget should appear on intermission screen

### ISSUE THREAD

**Issue by ceski-1** [fabiangreffrath/woof#2022]
Before sbardef PR:

![woof0001](https://github.com/user-attachments/assets/4bb640a7-d950-4fed-80b3-f481b53eedc1)

**Comment by ceski-1** [comment]
I'm actually not sure how to do this with the new widget drawing system. It was already a hack to get it working correctly with the old system.

**Comment by rfomin** [comment]
> I'm actually not sure how to do this with the new widget drawing system. It was already a hack to get it working correctly with the old system.

There is `WI_DrawWidgets` function. I will do it.
