### ISSUE TITLE
suggestion: add PWAD support to 'autoload' feature

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#203]
In this thread [[doomworld]](https://www.doomworld.com/forum/topic/121385-widescreen-assets-appreciation-thread/) people collect various assets for PWADs. I think it will be simple and convenient to add PWAD support to the autoload feature. For example:
```
autoload/
├── aaliens.wad/
│   ├── aaliens_ws.wad
│   ├── UMAPINFO

```

**Comment by fabiangreffrath** [comment]
Hm, we'll probably end up pretty quickly with several hundred empty subdirectories in the executable's own directory.

**Comment by rfomin** [comment]
We may not create directories automatically, as we do for IWADs. Users can create subdirectories themselves or copy the prepared collection to the autoload directory.

**Comment by fabiangreffrath** [comment]
Yes, that's good. So, we iterate through all the wad files added with the `-file` parameter, check if there is an autoload directory available with its basename and load all the files in there. Right?

**Comment by rfomin** [comment]
Yes, I think that's right.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/37b5d4f7e1af717bb2fb922c193843863caae24c
