### ISSUE TITLE
Swap Positions of Secret and Level Title Messages

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#2039]
I always considered it to make more sense to have the map title announcement be front and center instead of being a normal message, a la EDuke32. Having the secret announcements be shown as a normal message is more fitting, given it matches the more modern standard set by the Unity and Kex ports. 

I would also suggest tying both to the "colorize messages" option, having them otherwise use the native text color when the option is disabled.

**Comment by fabiangreffrath** [comment]
The "secret revealed" message comes from Hexen and has been in Doom ports like this since literally decades.

**Comment by fabiangreffrath** [comment]
> Fair point. Then I would just suggest making the map title use the same space and the colorize thing, then.

The map announcement can get really long if the "author" field is filled in the UMAPINFO lump. I wouldn't want to occlude the player's view with such a wall of text in the midle of the screen right at the map start.

However, it has been reported that the map announcement gets cut short by the autosave message. 🙄
