### ISSUE TITLE
Spectre Visibility Aid?

### ISSUE THREAD

**Issue by a1-21** [fabiangreffrath/woof#2040]
Is it possible to add a spectre visibility aid option? Maybe instead of it using an alternating pixel pattern, it has a constantly translucent silhouette. Anything would help. Also would like if it didn't clash with the strict compatibility option.
I don't know about a vast and well defined dsda recording ruleset, so I think if different ports can handle spectre rendering basically any way they like, a slightly more visible spectre effect would be permissible.
I just wanted to get this out here before an update comes out, because I have no experience in building from source code, and this spectre issue is a pain in the neck for me.

**Comment by rfomin** [comment]
In Woof, we implement "blocky" spectre rendering, so the effect looks exactly like vanilla at any resolution.
Original algorithm, resolution scale 100% (320x200):
![woof0003](https://github.com/user-attachments/assets/d0b1b32c-7715-4a09-9bbb-7c9d33591b47)
"Blocky" algorithm, resolutions scale 300% (600p):
![woof0002](https://github.com/user-attachments/assets/3b17fe4c-c1f9-4ae7-aa27-9e4393e898b0)

> I don't know about a vast and well defined dsda recording ruleset, so I think if different ports can handle spectre rendering basically any way they like, a slightly more visible spectre effect would be permissible.

This is a technical limitation, spectre drawing is hard to implement like vanilla in OpenGL. But in recent versions of DSDA-Doom it's very close.

**Comment by a1-21** [comment]
I know about that option, but I find it doesn't help me that much. It definetly makes them prettier, but isn't much in terms of visual aid

**Comment by fabiangreffrath** [comment]
> Is it possible to add a spectre visibility aid option? Maybe instead of it using an alternating pixel pattern, it has a constantly translucent silhouette. Anything would help. Also would like if it didn't clash with the strict compatibility option.

Spectres are hardly visible for a reason, they are supposed to be like this. So, if you are asking for an option to make them less hardly visible, and you record demos with this option, then that would be unfair against others who record demos with the standard spectre visibility. Thus it's bound to strict mode.

What you could do, though, is make a DEH patch that removes the `MF_SHADOW` flag from the spectre actor and e.g. set the `MF_TRANSLUCENT` flag instead, and then auto-load this DEH patch. That would still be strictly unfair for demo recording, though, but that's nothing that the port would be able to detect and prevent.

**Comment by fabiangreffrath** [comment]
@rfomin What do you think? I am inclined to close this as "wontfix", because I am not going to change the appearance of a Doom monster to increase its visibility. On the other hand, we already have an option to change the appearance of the invisibility powerup. 🤷

**Comment by ceski-1** [comment]
This sounds like the [selective fuzz darkening](https://www.doomworld.com/forum/post/2600907) feature I added to Nugget Doom (because the idea was rejected for Woof). Why not port that back to Woof and update it with [these changes](https://github.com/fabiangreffrath/woof/commit/bc2f6d3aeb98c18f8f6fdc8b0d139e2e420f4546)? It can have a strict mode condition.

**Comment by fabiangreffrath** [comment]
Is it right that the only difference between this mode and the original fuzzy rendering mode is that instead of always darkening the neighbor pixels using the 6th colormap, it randomly uses the 6th, 4th, or 8th colormap?

**Comment by a1-21** [comment]
What's the change to the invisibility powerup?
+That selective fuzz actually looks good compared to vanilla

**Comment by ceski-1** [comment]
> Is it right that the only difference between this mode and the original fuzzy rendering mode is that instead of always darkening the neighbor pixels using the 6th colormap, it randomly uses the 6th, 4th, or 8th colormap?

No, it's really simple. Basically, only one darkening pass is used. There's a explanation by Linguica in the link.

**Comment by rfomin** [comment]
I like "selective darkening" option, it looks interesting

**Comment by rfomin** [comment]
> I'm not sure if you meant me by
> 
> > I don't think spectre rendering is a big problem for a11y.

Sorry, I meant accessibility (a11y).

**Comment by fabiangreffrath** [comment]
If people really suffer from deciphering the spectre pixel salad, I think we can colormap the sprites to gray and apply translucency. @JNechaevsky didn't you have something like this for Inter Doom?

**Comment by JNechaevsky** [comment]
A bit offtopic for current Woof's renderer, but I'll just leave it here for better times. 😉


<details>

```c
const uint32_t I_BlendDarkDesaturated (const uint32_t bg_i, const int d)
{
    tcpixel_t bg, ret;
    uint8_t r, g, b, gray;

    bg.i = bg_i;

    r = bg.r;
    g = bg.g;
    b = bg.b;
    gray = (((r * 299 + g * 587 + b * 114) / 1000) * d) >> 8;

    ret.a = 0xFFU;
    ret.r = ret.g = ret.b = gray;

    return ret.i;
}
```

![bw-fuzz](https://github.com/user-attachments/assets/f32e5209-22e1-4dcf-beec-6628993d4f76)


</details>

**Comment by NightFright2k19** [comment]
I don't know about this. Seeing them better is de facto a cheat. I mean, in singleplayer it probably wouldn't matter, but in MP anyone with this turned on would have an advantage. Having the greyscale invulnerability mode is OK since it reduces eyestrain. Here we're talking gameplay changing tweaks.
