### ISSUE TITLE
[bug] [trakinfo] option setting not togglable if lump is inside IWAD

### ISSUE THREAD

**Issue by elf-alchemist** [fabiangreffrath/woof#2051]
I've tested this with `TRAKINFO` sets built-in `doom.wad`, `doom2.wad` and in `chex3v.wad`, without loading the lump in a PWAD the option is entirely blanked out.

I've built the latest `master` locally, simply running `woof -iwad chex3v_with_trakinfo.wad` i can see this:
https://drive.google.com/file/d/1bCt5StEkX2VtYS-E2B-xNiv8V1BY_DEn/view

![woof0173](https://github.com/user-attachments/assets/a6da1450-f167-487b-96ed-be5c7bead77e)

**Comment by fabiangreffrath** [comment]
Indeed we are only looking for the TRAKINFO lump in PWADs here:

https://github.com/fabiangreffrath/woof/blob/71bb824efa47deb053d6a424a3e42afa7b724c16/src/d_main.c#L2406

We need a way to tell `W_ProcessInWads()` to take both IWADs and PWADs into account, e.g. 

```c
W_ProcessInWads("TRAKINFO", S_ParseTrakInfo, PROCESS_IWAD|PROCESS_PWAD);
```
