### ISSUE TITLE
Loading an invalid `SBARDEF` crashes the game

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#2062]
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/12066091410)._

If I load an invalid `SBARDEF` (I tested one with version 1.2.0, which obviously goes beyond the supported 1.1.0), it is detected successfully and not loaded. However, the game crashes after that.

I believe this code in `ST_Init()` is the issue:

https://github.com/fabiangreffrath/woof/blob/34b1291dfffd24d9b34be1f5bb761050597e6615/src/st_stuff.c#L1808-L1811

Although the rest of `ST_Init()` beyond that point can probably be run without issues even if `sbardef == NULL`, the `return` prevents it from happening. The big omission here is loading of the console font, which is used in many other places without checking if it is available to begin with.

I would suggest simply removing that block of code. I did so in the latest Nugget master based on the Woof 15.0.0 release, and it works as expected: the HUD fails to be rendered in-game because it's missing, but the game seems to run properly otherwise.

**Comment by rfomin** [comment]
Fixed in https://github.com/fabiangreffrath/woof/commit/3ba6c84663e9b3e52f8c4257c41e10c035de19d5
