### ISSUE TITLE
Add a "Window Size" Option.

### ISSUE THREAD

**Issue by ShroomiePerson** [fabiangreffrath/woof#2083]
i just think it'd be helpful to scale the window up with a slider in the options instead being stuck with the -1, -2, and -3 parameters (which also scale the resolution, which isn't something i want), or manually trying to do the very confusing math that i'm never completely certain of to scale the window from the end of my desktop environment.

**Comment by rfomin** [comment]
> manually trying to do the very confusing math that i'm never completely certain of to scale the window from the end of my desktop environment

You know that it is possible to resize the window with the mouse, right? Woof will always keep the correct aspect ratio.

**Comment by fabiangreffrath** [comment]
Honestly, I also cannot understand this request.

**Comment by ShroomiePerson** [comment]
oh, sorry for being unintelligible
