### ISSUE TITLE
The Escape/Backspace keys can interfere with menu sliders

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#2100]
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/12442848697)._

Steps to reproduce:

- Enter `Options > General > Video`, set resolution to max
- Move the resolution slider to 100%, but don't let go of left click
- Press Escape or Backspace; the General menu should now be closed, with no apparent resolution change
- Enter any setup menu; the resolution change will suddenly take effect

I would expect the setting change to be completely cancelled instead of being left "pending".

**Comment by fabiangreffrath** [comment]
>     * Enter any setup menu; the resolution change will suddenly take effect

I cannot reproduce this part of the issue. But what I see is that the resolution slider is still active if I enter the setup menu again and changes whenever I move the mouse horizontally. The problem seems to be that sliders set their changes instantly when the mouse button is clicked, but only actually apply it once the mouse button is released. And only in the latter case the slider is "deactivated" again.

**Comment by fabiangreffrath** [comment]
This mitigated the worst part of the issue for me:

```patch
--- a/src/mn_setup.c
+++ b/src/mn_setup.c
@@ -4212,6 +4212,8 @@ static boolean NextPage(int inc)
     return true;
 }
 
+static setup_menu_t *active_thermo = NULL;
+
 boolean MN_SetupResponder(menu_action_t action, int ch)
 {
     // phares 3/26/98 - 4/11/98:
@@ -4460,6 +4462,7 @@ boolean MN_SetupResponder(menu_action_t action, int ch)
         set_weapon_active = false;
         default_verify = false;              // phares 4/19/98
         print_warning_about_changes = false; // [FG] reset
+        active_thermo = NULL;
         M_StartSound(sfx_swtchx);
         return true;
     }
@@ -4526,8 +4529,6 @@ boolean MN_SetupMouseResponder(int x, int y)
         return true;
     }
 
-    static setup_menu_t *active_thermo = NULL;
-
     if (M_InputDeactivated(input_menu_enter) && active_thermo)
     {
         int flags = active_thermo->m_flags;
```

**Comment by rfomin** [comment]
> This mitigated the worst part of the issue for me:

Looks good.
