### ISSUE TITLE
loud fluidsynth popping

### ISSUE THREAD

**Issue by msx2plus** [fabiangreffrath/woof#2104]
just wanted to report that the current version of fluidsynth in woof seems to have an issue with MIDIs that use lowpass changes that causes loud pops as the filter position is changed. this is seemingly fixed in 2.4.1 and i'd recommend an update for the sake of saving folks' ears :)

**Comment by fabiangreffrath** [comment]
Issue in an external library, already fixed in that library.

**Comment by rfomin** [comment]
> Issue in an external library, already fixed in that library.

Should we do another bugfix release?

**Comment by fabiangreffrath** [comment]
Sure, we could do that.

**Comment by fabiangreffrath** [comment]
> Should we do another bugfix release?

@rfomin 
I guess that would be justified now. Would you like to prepare a changelog for that?

**Comment by rfomin** [comment]
> > Should we do another bugfix release?
> 
> @rfomin I guess that would be justified now. Would you like to prepare a changelog for that?

Yes, I will do it. Should we wait for #2141?
