### ISSUE TITLE
suggestion: better reporting of SDL_Init errors

### ISSUE THREAD

**Issue by MartinHowe426** [fabiangreffrath/woof#227]
As I mentioned on Woof!'s DoomWorld thread, if Woof! can't initialise SDL, it simply says just that. There may be other places in the code that initialise libraries, but SDL is the big one for games. Please could the SDL initialisation code at least print the SDL_GetError() message as well? For example:

```
   puts("Failed to initialize SDL library.\n  ");
   puts(SDL_GetError());
   puts("\n");
   return -1;
```

**Comment by fabiangreffrath** [comment]
Yes, sure, thanks for the suggestion!
