### ISSUE TITLE
Some MBF21 flags not working properly, also bad sfx error.

### ISSUE THREAD

**Issue by AureliusGit** [fabiangreffrath/woof#236]
Using the 6.1.0 version, it seems that some of the MBF21 flags are still not supported. I have a melee weapon with the +SILENT flag, but still wakes up all monsters in a regular fashion, and a projectile that has the +RIP flag but does not pierce through enemies.

I'm also still getting a "bad sfx #:0" error. It seems to happen when I set Args3 to 0 for A_MonsterMeleeAttack (the arg that determines what sound is played on hit).

Provided is a DEHACKED that:
- adds +SILENT to the fist
- adds +RIP to the plasma projectile
- changes the Demon (Pinky) melee attack to A_MonsterMeleeAttack(20, 0 ,1)

[dehacked.txt](https://github.com/fabiangreffrath/woof/files/6762057/dehacked.txt)

**Comment by fabiangreffrath** [comment]
Thank you for your report!

> I'm also still getting a "bad sfx #:0" error. It seems to happen when I set Args3 to 0 for A_MonsterMeleeAttack (the arg that determines what sound is played on hit).

By setting it to `0` you want to achieve that no sound is played at all?

**Comment by AureliusGit** [comment]
> By setting it to 0 you want to achieve that no sound is played at all?

I assumed it to be the correct way, since clearing a sound in DEHACKED means you set it to 0, and DSDA Doom seemed not to mind the notation. According to the MBF21 documentation, the Arg3 for A_MonsterMeleeAttack is an unsigned integer, but there is no specific mention of what value should be considered as "no sound".
