### ISSUE TITLE
suggestion: smooth pixel scaling

### ISSUE THREAD

**Issue by ZDHellser** [fabiangreffrath/woof#247]
I'm curious if it's possible to pull the Smooth Pixel Scaling option from Crispy Doom for use in Woof. I think it might work well with the project and its intentions - and it's truly a 'quality of life' feature.

If it's not feasible, I get it. :)

**Comment by fabiangreffrath** [comment]
The difference between the original "nearest" rendering and smooth pixel scaling is present, but barely noticable with the increased 640x400 resolution that ports like Woof or Crispy feature. Thus, I'd like to avoid the maintenance overhead and performance penalty of introducing an intermediate texture for up- and downscaling.

Comparison screenshots with "smooth pixel scaling" disabled and enabled from a Crispy Doom issue:

https://user-images.githubusercontent.com/121589683/210443858-d661e5f1-13aa-43c7-94f5-f92ecdb26563.png

https://user-images.githubusercontent.com/121589683/210444526-2daf2e79-b300-4926-91af-9d199e61bbbd.png

**Comment by rfomin** [comment]
Personally, I like this "bilinear sharpening" effect, it improves the non-square pixel problem a bit:
![image](https://user-images.githubusercontent.com/5077629/212694790-019b9517-8a35-4bd3-ac8b-acbbe0851e99.png)
![image](https://user-images.githubusercontent.com/5077629/212694848-62453e3d-376c-4b22-ab07-7d29835a2d8b.png)

Still blurry for my taste. Should we add support for shaders?

**Comment by fabiangreffrath** [comment]
I don't know. How would that look like? What does it mean to "support shaders"?

**Comment by rfomin** [comment]
I suggest looking at the DosBox-X fork: https://github.com/joncampbell123/dosbox-x/tree/master/contrib/glshaders

**Comment by fabiangreffrath** [comment]
Erm, I'n not sure. Not a fan of this "enforced vintage style". Most of the "hey this looks *exactly* like a CRT back then" effects present in many console emulators actually look like crap and I never use them.

**Comment by rfomin** [comment]
I really like them, I played console games as a kid and some of them used CRT TV blureness heavy (EarthWorm Jim!)

I think for Doom we can try shaders that sharpen non-square pixels. They seem to work, but not perfectly.

**Comment by fabiangreffrath** [comment]
Alright, feel free to convince me. 😁

**Comment by rfomin** [comment]
Something like this: https://github.com/rsn8887/Sharp-Bilinear-Shaders/releases/tag/1.61

I will try to experiment with it.

**Comment by fabiangreffrath** [comment]
Okay, this looks reasonable and is PD-licensed. 👍

**Comment by ZDHellser** [comment]
A tiny touch of blurriness is fine by me. My original recommendation was a personal preference to help fix any nearest scaling issues with the HUD, especially numbers.
