### ISSUE TITLE
No music on Arch Linux

### ISSUE THREAD

**Issue by TheMadScientist1234** [fabiangreffrath/woof#251]
I'm trying to use Woof on my Arch Linux system, however there is no music. I don't have any midi card so I just use SDL_mixer. The sound works fine, but the music is nonexistent.

**Comment by fabiangreffrath** [comment]
On Linux, SDL_Mixer defaults to use Fluidsynth as its music backend, which in turn needs a soundfont installed and get configured to work with it. So, this is most probably a configuration issue on your side.

**Comment by TheMadScientist1234** [comment]
I got it working! Thanks!
