### ISSUE TITLE
I compiled it with cmake 3.10

### ISSUE THREAD

**Issue by MarkJeronimus** [fabiangreffrath/woof#252]
The source states that cmake 3.12 is required because of something called "modern FindPython", however with this simple modification I could compile it with 3.10 (which is the latest bundled with Ubuntu), and judging by prboom+'s CmakeLists.txt, it could work down to 3.0 (although this is untested).

```cmake
cmake_minimum_required(VERSION 3.10) # or 3.0
project("Woof" C)
set(VERSION 6.3.0)
set(DESCRIPTION "Woof! is a continuation of Lee Killough's Doom source port MBF targeted at modern systems.")
set(HOMEPAGE_URL "https://github.com/fabiangreffrath/woof")
```

Of course cmake complains (see blow), but it succeeds without error. Compilation then also succeeds without error.

```
CMake Warning at CMakeLists.txt:235 (find_package):
  By not providing "FindPython3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Python3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Python3" with any
  of the following names:

    Python3Config.cmake
    python3-config.cmake

  Add the installation prefix of "Python3" to CMAKE_PREFIX_PATH or set
  "Python3_DIR" to a directory containing one of the above files.  If
  "Python3" provides a separate development package or SDK, be sure it has
  been installed.
```

**Comment by fabiangreffrath** [comment]
May I hear your opinion @AlexMax?

**Comment by rfomin** [comment]
Python is needed for win_textfile script (converts text files to a format usable by Windows Notepad). We can potentially use Python for cp-with-libs as well.

**Comment by fabiangreffrath** [comment]
Sorry, but with https://github.com/fabiangreffrath/woof/commit/123423c7ad9bcc62b722e6c6909676e6ac4d4681 we even bumped the cmake requirement to 3.16.

**Comment by rfomin** [comment]
cmake 3.16 is needed only for MinGW packages. We can add this:
```cmake
if(MINGW)
    cmake_minimum_required(VERSION 3.16)
else()
    cmake_minimum_required(VERSION 3.12)
endif()
```
Python is not that important too.

**Comment by fabiangreffrath** [comment]
cmake 3.16 is available even in Debian oldoldstable and oldstable through backports, Debian stable and up already have newer versions:

```
o-o-stable: 3.7.2-1
o-o-bpo: 3.16.3-1~bpo9+1
oldstable: 3.13.4-1
old-bpo: 3.18.4-2~bpo10+1
stable: 3.18.4-2+deb11u1
stable-bpo: 3.22.1-1~bpo11+1
testing: 3.22.1-1
unstable: 3.22.1-1
```

**Comment by MarkJeronimus** [comment]
```
$ apt search cmake|grep cmake/

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

cmake/bionic-updates,now 3.10.2-1ubuntu2.18.04.2 amd64 [installed]
icmake/bionic 9.02.06-1 amd64
$
```
<rant>I know, I'm using 18.04, but it's supposed to be supported until well into 2023, and dist-upgrading to 20.04 is blocked because some [nasty package issues](https://askubuntu.com/a/1205596/495443) (caused by Canonical carelessly changing repositories), and I don't have time to install it fresh. Although this isn't the first time I downloaded something and it \*required* packages only available on 20.04. In fact I'm so fed up with Canonical's policies that I'll be moving to another distro anyway.</rant>

**Comment by AlexMax** [comment]
@MarkJeronimus Have you tried using the statically linked CMake binaries from [cmake.org](https://cmake.org/download/)?  Kitware is aware of the disastrous state of distro packaging and really tries to go out of its way to make modern versions of CMake accessible to developers on Linux.

**Comment by rfomin** [comment]
I have built Woof on Debian 8 vm with CMake 3.6. Also on Windows XP vm with CMake 3.6 and Visual C 6 (required a few code changes and crash on boot, but I think it might work). Thus, all modern CMake features are only needed for MinGW targets.
@fabiangreffrath, should we support old C compilers?

**Comment by fabiangreffrath** [comment]
Sure, why not, if it's not too much effort.

**Comment by rfomin** [comment]
Success :smile:
![VirtualBox_winxp_24_12_2021_18_17_45](https://user-images.githubusercontent.com/5077629/147348459-80e3b065-8bac-46d1-a39f-91f5cd5f71d2.png)

**Comment by fabiangreffrath** [comment]
What was necessary to achieve this?

**Comment by rfomin** [comment]
> What was necessary to achieve this?

Old versions of MSVC support only C89/C90. The main problem is `PACKED_STRUCT` macro and `<stdint.h>` types.

**Comment by fabiangreffrath** [comment]
If you could provide a PR, I'd be all ears.
