### ISSUE TITLE
1280x720 Resolution

### ISSUE THREAD

**Issue by srludicolo** [fabiangreffrath/woof#257]
Hi Fabian et al.!

I think it would be really cool if we could get 1280x720 resolution mode for Woof. I know this is a port that adheres to Lee Killough's original intentions with the port, but I think this would be an awesome QOL feature. I started using prboom+ for this reason, but I like Woof! more in every other way. The resolution gives me nausea, even at 640x480 but 1280x720 doesn't seem to. I completely understand if this isn't possible, but extra accessibility features never hurt anyone :)

**Comment by fabiangreffrath** [comment]
Sorry, but this won't happen.
