### ISSUE TITLE
Bug with pain overlay for some WADs

### ISSUE THREAD

**Issue by srludicolo** [fabiangreffrath/woof#259]
![doom01](https://user-images.githubusercontent.com/83472414/130695201-5578debf-b81a-465b-a23c-df5d393230e2.png)

For a couple of WADs I've played through (particularly Struggle: Antaresian Legacy), there is a strange issue where there is way too much contrast on the pain overlay. In this screenshot, I point-blanked myself with a rocket launcher and you can see how bright and opaque the red and black is, where it should just be a transparent salmon color. It makes it incredibly hard to see when you take large amounts of damage. If you need to recreate this bug, I sent a save file with the exact location I shot myself in. Just load it in the 6.3.1 release with the WAD below and fire. Make sure its set to -complevel 2 as well :)

Struggle: Antatresian Legacy WAD: https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/strg

Save file: [woofsav7.zip](https://github.com/fabiangreffrath/woof/files/7042341/woofsav7.zip)

**Comment by rfomin** [comment]
This is the specific mod implemented in Struggle: Antaresian Legacy, it works the same in Crispy Doom and PrBoom+.
