### ISSUE TITLE
Mac build

### ISSUE THREAD

**Issue by atsb** [fabiangreffrath/woof#271]
Mac build does not compile without a small patch:

```
wi_stuff.c:366:19: error: redefinition of 'time' as different kind of symbol
static patch_t*   time;
/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include/time.h:118:8: note: previous definition is here
time_t time(time_t *);
```

All 'time' usages in wi_stuff need to be changed from 'time' to something else.  I used 'woof_time' (and in the related places required) and it compiled cleanly afterwards.

**Comment by fabiangreffrath** [comment]
Should be fixed since last week: 
https://github.com/fabiangreffrath/woof/commit/99b56dd71f678d1220c3b1ce670dd7051c6e795a

**Comment by atsb** [comment]
Building from master works yes, just not the latest releases.  I'll close this issue, thanks!
