### ISSUE TITLE
Automap overlay + Follow mode off doesn't turn player

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#275]
If Automap overlay mode is enabled and Follow mode is disabled, it is impossible to turn the player.

**Comment by rfomin** [comment]
It is possible if you rebuild "shift left" and "shift right" keys in Options->Setup->Key Bindings->Automap

**Comment by fabiangreffrath** [comment]
Possibly, but then I would have to remember two separate key bindings for normal view and automap overlay.
