### ISSUE TITLE
Feature request: Using enter key on exit screen

### ISSUE THREAD

**Issue by Aaron03071991** [fabiangreffrath/woof#295]
Hello there

How about using "enter" key on exit screen besides "Y" key?
I mean, both can be used at the same time, just if I want to finish carnage, pressing "Q" and "enter" twice is more handy than "Q, enter, Y".

**Comment by rfomin** [comment]
We've done this along with improved key bindings and gamepad support. This will work in the next version.

**Comment by rfomin** [comment]
Fixed in 5c82a471186879401599606ea0244b0fb61f4eae
