### ISSUE TITLE
No Rest for the Living support (with its midipack).

### ISSUE THREAD

**Issue by Aaron03071991** [fabiangreffrath/woof#296]
So, despite having nerve.wad in same folder as doom2.wad, Woof! 7.0 doesnt add it as episode, unless i load nerve.wad as an pwad file. That would be fine, but NRftL midi pack doesnt quite work with such approach (out of the box), renaming midi files inside midi pack wad is required.

Tried both Doom 3 BFG wads and Unity wads, same result.

**Comment by rfomin** [comment]
> Does it have something to do with UMAPINFO?

Yes, the NRTL midi pack authors have updated their work in such a way that it is incompatible with Woof UMAPINFO. We'll fix that.

**Comment by srludicolo** [comment]
Sounds good! I should probably play NRFTL again...

**Comment by Aaron03071991** [comment]
I guess we have to wait until Woof 7.1 then
