### ISSUE TITLE
wacky texture rendering

### ISSUE THREAD

**Issue by ribbiks** [fabiangreffrath/woof#301]
Migrating email correspondence over to a github issue as requested.

While playing large maps with extensive deh changes, textures will sporadically go awry, looking inverted and clearly glitchy. Flats are unaffected. I've been unable to construct a minimal example wad, as the issue only seems to occur in very large maps. I had emailed Fabian a video showing the problem, which I do not wish to post publicly. I can confirm the issue occurs in Windows (6.3.1 release) and on Mac (compiled from latest commit as of 09/16/2021), and that playing around with "-mb" input options did not resolve the issue.

**Comment by fabiangreffrath** [comment]
It seems to be related to texture composition, likely related to #299 .
