### ISSUE TITLE
Bug? Unable to climb on crates

### ISSUE THREAD

**Issue by Aaron03071991** [fabiangreffrath/woof#307]
For some odd reason doomguy is unable to climb on those crates in E2M7. Retried this level few times, problem persists. Woof 7.0.0 with Unity wad.
![Screenshot_78](https://user-images.githubusercontent.com/80612252/137601585-01dfb97c-9dac-4b9c-9c5b-8e3adf836f93.png)
![Screenshot_79](https://user-images.githubusercontent.com/80612252/137601586-70f432b7-5e66-4e49-aca8-6add7410a0ca.png)

**Comment by rfomin** [comment]
Try to use `-complevel vanilla`.

It works with any complevel except MBF21. DSDA-Doom behaves the same way. @kraflab what do you think? Looks like an MBF21 bug.

**Comment by Aaron03071991** [comment]
Indeed `-complevel vanilla` solve this issue.

**Comment by kraflab** [comment]
That's because e2m7 has a bunch of extra flags set on lines for some reason. I was thinking about what the best way to fix this would be. Possibly just explicitly detect for this map and clear the extended line flags.

**Comment by fabiangreffrath** [comment]
WAD name is a weak heuristic. We could probably go by IWAD and matching value of numlines instead.
