### ISSUE TITLE
(Question) Stats above HUD?

### ISSUE THREAD

**Issue by srludicolo** [fabiangreffrath/woof#308]
I was watching Decino's latest viewer submission WAD playthrough, and I noticed this in the corner;

![image](https://user-images.githubusercontent.com/83472414/137601815-cca130db-a5c0-4e18-98dc-5c345045088e.png)

I know that you can get something similar to this in Woof! by pressing the F5 key, but I haven't seen this specific HUD widget. Speaking of which, I can't seem to be able to get the widgets to stay alongside the full status HUD

![image](https://user-images.githubusercontent.com/83472414/137601848-c1b881cf-7231-4ce2-906a-d50b0009295b.png)

Am I just dumb, or is this a prboom+um only feature? If it is, I suppose you could say this is a suggestion :^)

**Comment by Aaron03071991** [comment]
Theres different way to have stats in Woof, its in top left corner, same as in Crispy.
![image](https://user-images.githubusercontent.com/80612252/137601945-8eccb490-1c20-4b13-a6eb-ae2bb7d94e1b.png)

**Comment by fabiangreffrath** [comment]
That'd be this commit from Pr+:
https://github.com/coelckers/prboom-plus/commit/c170d6362c7556bbbb7011dd4d58a8eefbd24305#diff-e8e91720ab0b9aea8c1556e13291aeb15cb7c575450ff2eeefedd521c22e5538

**Comment by srludicolo** [comment]
I see. Seeing as this is a much cleaner looking one compared to the crispy stats, I think it would be a pretty good idea, especially for pedantic UVMAXers like myself, haha

**Comment by srludicolo** [comment]
That would be a good idea. This is definitely not a priority subject obviously, but it'd be nice to have :)
