### ISSUE TITLE
(Support) Offer to Write DeHackEd Patch for Chex Quest Support

### ISSUE THREAD

**Issue by srludicolo** [fabiangreffrath/woof#309]
For curiosity's sake, I loaded up Chex Quest in Woof!, and it played near-flawlessly, with a couple of issues that could be solved by a DeHackEd patch. Would @fabiangreffrath and @rfomin be interested in including such a patch in a Chex Quest autoload folder? I would gladly write it myself :)

**Comment by bradharding** [comment]
This might also be of interest :wink: : https://www.doomworld.com/idgames/utils/exe_edit/patches/chexdeh

**Comment by srludicolo** [comment]
Understood
