### ISSUE TITLE
Things do not rotate with the map

### ISSUE THREAD

**Issue by hackneyed-one** [fabiangreffrath/woof#314]
Open the map and do the iddt cheat twice. If rotating automap is enabled the green and red triangle things will not rotate with the map.

I have a vague memory that this might have been mentioned on Doomworld awhile ago. I don't know but I came across it today so I'll put this here in case. I compiled again from source 5 minutes ago at commit f79738e on Ubuntu-Mate 20.04 to be sure I'm up to date.

**Comment by rfomin** [comment]
Thanks for the report, fixed in https://github.com/fabiangreffrath/woof/commit/d87c9534f96d9f5873add68ef29a316290b61c64
