### ISSUE TITLE
The Next Level key doesn't go from e4m8 to e5m1

### ISSUE THREAD

**Issue by hackneyed-one** [fabiangreffrath/woof#316]
Again, I was playing dtwid-le.wad with the umapinfo that @rfomin posted on Doomworld allowing for Episode 5 and 6 in the menu.

The "Next Level" key works really well. If I start on e5m1 in Woof I can "next level" all the way through ep5 into and through ep6 until the last map where it wraps around to e1m1. But If I warp to e4m8 and press "next level" I'm taken back to e1m1. Okey, Woof (and PrBoom-Plus-UM) are hard coded to wrap around after Episode 4. But should it? Maybe it should check for extra Episodes before wrapping back to e1m1. I don't know, and what about map33 in PL2.wad. Should Woof "next level" into map33 from map 30? Maybe not but what if the umapinfo for a mod says there is a map33 or more? What then...

Maybe I just think too much, or not enough.

**Comment by fabiangreffrath** [comment]
So, how do we proceed with this issue?

**Comment by fabiangreffrath** [comment]
I think we should probably support non-canonical level progression so far that ExMy leads to ExM(y+1) unless otherwise defined by UMAPINFO. But cross-episode transitions like ExMy to E(x+1)M1 are hypothetical and should not necessarily be supported, i.e. I don't consider this a bug.

**Comment by fabiangreffrath** [comment]
I guess we agree that we don't want to engine to guess that "if Map Y is the last map in Episode X, then jump to Episode (X+1) Map 1" without explicit hints from the UMAPINFO lump. But I see that we are still missing rangechecks for `doom2_next[]` and a check if the next map's lump does actually exist - both of which are there in Pr+.

**Comment by rfomin** [comment]
> and a check if the next map's lump does actually exist

Do you mean check in `G_InitNew`?

**Comment by fabiangreffrath** [comment]
I mean this check:
https://github.com/coelckers/prboom-plus/blob/9e2c5543cfe9ba97a2b83ce73c2bf1471279d41a/prboom2/src/e6y.c#L496

**Comment by rfomin** [comment]
It looks like DSDA-Doom doesn't have this check. I looked at the wrong codebase :smile:

**Comment by fabiangreffrath** [comment]
I consider the current behaviour of our Next Level key to be absolutely reasonable and I have just modified PrBoom+'s one to behave the same, thus closing. 

@kraflab you might want to have a look:
https://github.com/coelckers/prboom-plus/commit/d648724ccddc6ec00dec5075cfdb9c5b05f2eeb2
