### ISSUE TITLE
implement "strict" mode

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#322]
This will be a command line parameter `-strict` which will forcefully disable optional QOL features and enhancements, e.g. colored blood or translucent ghosts monsters, to make sure recorded demos are compliant to speed running rules. This is supposed to be kept in Sync with DSDA-Doom.

**Comment by fabiangreffrath** [comment]
Not sure about this request anymore. I mean, Woof is not DSDA-Doom and thus does not *have to* adhere to DSDA's rules. But it's good to know that it still *can* be configured (and is so by default) to do so. But, do we need more?

**Comment by kraflab** [comment]
I think you can basically consider this as being like a "standard" but for the configuration itself. Supporting it will be a convenience for speedrunners but it also needs to be maintained when you add new things. The big benefit of this versus just sharing a compliant config file is that it's dynamic - a user can keep their casual play config like normal, and it just tweaks things when the option is supplied.

**Comment by rfomin** [comment]
I think it's a good idea, I just need to finally pull myself together and do it. Completely forgot about this issue :smile:
