### ISSUE TITLE
Exclusive full screen for Freesync monitors

### ISSUE THREAD

**Issue by Kappa971** [fabiangreffrath/woof#334]
As described in the title, it would be useful to have the exclusive full screen as﻿ it allows Freesync to work for those who own a VRR display. It isn't a personal request but I think it is a useful feature as these types of displays are increasingly popular and will probably be even more so in the future. This would also apply to Crispy Doom and wolf4sdl.

**Comment by rfomin** [comment]
Should FreeSync support borderless windowed mode? I couldn't find a definite answer.

**Comment by Kappa971** [comment]
The answer is yes and no. On Nvidia cards (I don't know if even with AMD cards) it is possible to force the operation of it in borderless full screen (from the Nvidia control panel or from Nvidia Inspector, in case you want to activate Freesync on borderless full screen for single applications) but it is not the best way to make freesync work (I don't know if it's just my impression, but the games seem to go less smoothly so). Either way, with an exclusive full screen mode, you are 100% sure it works.

**Comment by rfomin** [comment]
I tried experimenting with exclusive fullscreen mode and it is glitchy on my system. Even GZDoom doesn't have an exclusive fullscreen option, so if the problem is solved for you, I vote to keep only the borderless fullscreen mode.

**Comment by fabiangreffrath** [comment]
Don't need it either.

**Comment by Kappa971** [comment]
> I tried experimenting with exclusive fullscreen mode and it is glitchy on my system. Even GZDoom doesn't have an exclusive fullscreen option, so if the problem is solved for you, I vote to keep only the borderless fullscreen mode.

Now on Windows 11 it works fine for me but maybe others, like in your case, might have problems, and having an exclusive full screen mode ensures that it works for everyone.
In GZDoom to me Freesync works with Software and OpenGL render, in Vulkan render, I don't know why, but you need to activate vsync from GZDoom settings for freesync to work, so I guess it supports exclusive full screen.
If @fabiangreffrath doesn't want to implement this function, I can still close the issue.

**Comment by rfomin** [comment]
> It is strange that the exclusive full screen in your PC performs poorly, as it should guarantee the best performance.

It performs well but has strange issues with alt-tab, windowed mode toggle, etc. Not only in Woof but in other games too.

**Comment by Kappa971** [comment]
> > It is strange that the exclusive full screen in your PC performs poorly, as it should guarantee the best performance.
> 
> It performs well but has strange issues with alt-tab, windowed mode toggle, etc. Not only in Woof but in other games too.

On Windows 11 (but also on Windows 10 21H1) I have no problems with alt-tabs in games. My PC: Ryzen 5 1600 (not officially supported by Windows 11, thanks Microsoft) and gtx 1060, what PC do you have and what OS do you use?

**Comment by fabiangreffrath** [comment]
Choco and Crispy already have an exclusive fullscreen mode which you can enable by setting the `fullscreen_width` and `fullscreen_height` config variables. However, I never use it, that's why I said I don't need it in Woof!. It should be rather straightforward to port over, though, since the rest of our video mode code is also already based on the Choco implementation. 

Why a game like wolf4sdl would need an exclusive fullscreen mode is beyond me, though.

**Comment by rfomin** [comment]
I have Windows 10 desktop and an old Windows 7 laptop. I must admit on Windows 10 exclusive fullscreen works better.

**Comment by Kappa971** [comment]
> Choco and Crispy already have an exclusive fullscreen mode which you can enable by setting the fullscreen_width and fullscreen_height config variables.

I didn't know, I'll try it. Thanks

> However, I never use it, that's why I said I don't need it in Woof!

With a monitor without Freesync there is no reason to use the exclusive full screen in Woof! or Crispy Doom.

> Why a game like wolf4sdl would need an exclusive fullscreen mode is beyond me, though.

wolf4sdl (like ECWolf) only runs at 70fps so unless you have a Freesync monitor or a monitor set to 70hz, there will be stuttering. If someone is having trouble getting Freesync to work in borderless full-screen, stuttering occurs.

**Comment by rfomin** [comment]
FreeSync also lets you set 35Hz if I understand correctly. I need to buy one :smile:

**Comment by Kappa971** [comment]
> FreeSync also lets you set 35Hz if I understand correctly. I need to buy one 😄

Freesync monitors with LFC (Low framerate compensation) with Refresh rate from 120hz upwards (FreeSync Premium) yes. If you have an Nvidia video card, "G-Sync compatible" ones are recommended.
Freesync monitors have operating ranges (eg 48-144hz), under the minimum refresh rate, the LFC is activated which duplicates/triples the frames so that it remains within the operating range. 75hz monitors for example don't have LFC, so Freesync doesn't work at 35fps.

**Comment by Kappa971** [comment]
> Choco and Crispy already have an exclusive fullscreen mode which you can enable by setting the fullscreen_width and fullscreen_height config variables.

This actually makes Crispy Doom run in exclusive full screen mode.

**Comment by fabiangreffrath** [comment]
> This actually makes Crispy Doom run in exclusive full screen mode.

That's what I said, right?

**Comment by Kappa971** [comment]
> That's what I said, right?
Yes, I confirm

**Comment by fabiangreffrath** [comment]
Okay, maybe we should just import the few lines of code to support this.
