### ISSUE TITLE
save/load bug in map02 AD_MORTEM.wad

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#339]
WAD: [[doomworld]](https://www.doomworld.com/forum/topic/125461-ad-mortem-a-mbf21-halloween-themed-megawad-beta/)
How to reproduce: at the beginning of map02 grab the Rocket Launcher which activates Cacodemos, save the game. Loading this save crashes the port.
Same bug in DSDA-Doom 0.21.3 and the latest build of Woof.
I think it's related to Pushers. @kraflab

**Comment by fabiangreffrath** [comment]
Could this probably be fixed by properly saving mobj pointer indices for pushers as is already done for other thinkers?
https://github.com/fabiangreffrath/woof/blob/c9455a7d779faaa8c598d217c9582be8027c881d/Source/p_saveg.c#L2079

**Comment by rfomin** [comment]
It restores source mobj with P_GetPushThing: https://github.com/fabiangreffrath/woof/blob/c9455a7d779faaa8c598d217c9582be8027c881d/Source/p_saveg.c#L2641

**Comment by kraflab** [comment]
Is this bug also in prboom+? If it is just pushers and not mbf21-specific, we should probably patch it there as well.

**Comment by rfomin** [comment]
> Could this probably be fixed by properly saving mobj pointer indices for pushers as is already done for other thinkers?

Еhis approach seems to be better

**Comment by rfomin** [comment]
> Is this bug also in prboom+?

Probably, I haven't tested.

**Comment by rfomin** [comment]
AD_MORTEM.wad has been updated, the bug is no longer reproducible: [[doomworld]](https://www.doomworld.com/forum/topic/125461-ad-mortem-a-mbf21-halloween-themed-megawad-beta/?do=findComment&comment=2408622)

**Comment by fabiangreffrath** [comment]
Okay, we don't need an over-engineered fix for a mapping error then. It would still be useful, though, to report a warning if `P_GetPushThing()` returns `NULL`. Something like "Pusher thinker without pusher object" or similar.

**Comment by fabiangreffrath** [comment]
Shouldn't this rather mean `continue`? Else this function will return `NULL` if the *first* thing in the sector's think list is neither a pusher nor a puller.

https://github.com/fabiangreffrath/woof/blob/c9455a7d779faaa8c598d217c9582be8027c881d/Source/p_spec.c#L3239

**Comment by rfomin** [comment]
> Shouldn't this rather mean `continue`? Else this function will return `NULL` if the _first_ thing in the sector's thing list is neither a pusher nor a puller.
> 
> https://github.com/fabiangreffrath/woof/blob/c9455a7d779faaa8c598d217c9582be8027c881d/Source/p_spec.c#L3238-L3239

AD_MORTENv2.wad map02 crashes on load with this change.

So, are we call `I_Error` if `P_GetPushThing()` returns `NULL` when loading the save?

**Comment by fabiangreffrath** [comment]
I guess we can do better than erroring out. Could you please upload the crashing WAD here, now that it has been replaced in the DW thread?

**Comment by rfomin** [comment]
[AD_MORTEMv2.zip](https://github.com/fabiangreffrath/woof/files/7458982/AD_MORTEMv2.zip)

**Comment by fabiangreffrath** [comment]
I still don't quite get it. When spawning pushers, all sectors with the same tag as the corresponding special linedef are scanned for pusher things. And only if such a think is found, a thinker is spawned and the sector which holds the thing is stored in its `affectee` field. So, why can't we find the pusher thing again in the very same sector when restoring from a savegame?

Is it possible for pusher objects to move to a different sector? Or is it possible to remove them off the map or crush them, without their connected thinker getting removed?

**Comment by fabiangreffrath** [comment]
```patch
--- a/Source/p_saveg.c
+++ b/Source/p_saveg.c
@@ -1792,7 +1792,7 @@ static void saveg_write_pusher_t(pusher_t *str)
     saveg_write32(str->y);

     // int affectee;
-    saveg_write32(str->affectee);
+    saveg_write32(str->source ? str->source->subsector->sector - sectors : str->affectee);
 }

 //
```

**Comment by rfomin** [comment]
> ```diff
> --- a/Source/p_saveg.c
> +++ b/Source/p_saveg.c
> @@ -1792,7 +1792,7 @@ static void saveg_write_pusher_t(pusher_t *str)
>      saveg_write32(str->y);
> 
>      // int affectee;
> -    saveg_write32(str->affectee);
> +    saveg_write32(str->source ? str->source->subsector->sector - sectors : str->affectee);
>  }
> 
>  //
> ```

This patch doesn't work for me. Try this save: [woofsav0.zip](https://github.com/fabiangreffrath/woof/files/7461277/woofsav0.zip)

**Comment by fabiangreffrath** [comment]
Well, it's in the writer function, so it doesn't fix broken savegames. But newly saved games will be fine - at least as far as my testing went.

**Comment by rfomin** [comment]
That is a new save. If you save right in the moment activation, pushers don't work.

**Comment by rfomin** [comment]
I don't know, but my PR works for saves like that.

**Comment by fabiangreffrath** [comment]
With your PR, savegames saved with an old version and loaded with a patched one will still crash, right? So, we will still need a check if `pusher->source == NULL` before calling `P_AddThinker()` and error out in that case - indeed.

**Comment by rfomin** [comment]
Eh, you're probably right about overengineering. This is an unconventional use of pushers, so maybe we just erroring out?

**Comment by fabiangreffrath** [comment]
Another idea: If `P_IndexToThinker()` is unable to translate `str->source` into a proper thinker in `saveg_read_pusher_t()`, then that's probably because it hasn't been converted into an index before but is still a saved pointer address, i.e. it has been saved with an old version of the engine. In that case, `P_IndexToThinker()` returns `NULL` and overrides that field, so we know just as much as before. Then, we just need to check if `pusher->source == NULL` in `P_UnArchiveSpecials()` and only call `P_GetPushThing()` in that case. This way, we can get away without bumping savegame version but can just "sneek" this improvement in.

**Comment by fabiangreffrath** [comment]
> Is it possible for pusher objects to move to a different sector?

Apparently, this is before and after collecting the rocket launcher:

![doom01](https://user-images.githubusercontent.com/6449237/139880760-bab961e0-9598-446f-8c27-83c5161dea0b.png)

![doom02](https://user-images.githubusercontent.com/6449237/139880776-b66459f3-140b-4eeb-86f3-c65724c14e95.png)

**Comment by rfomin** [comment]
> Another idea: ...

I have implemented this in https://github.com/fabiangreffrath/woof/pull/340/commits/e580f490f4125b8161bc303a2d42443bcbba7982
