### ISSUE TITLE
Possible performance improvement

### ISSUE THREAD

**Issue by kraflab** [fabiangreffrath/woof#349]
Since we were talking about performance earlier, I thought I'd share something interesting I noticed in pr+ some time ago:

https://github.com/kraflab/dsda-doom/blob/master/prboom2/src/SDL/i_video.c#L920-L934

It tests a nonstandard pitch for the screen buffer (width + 32 instead of width) and picks the fastest one. On my pc the +32 version yields a performance improvement of ~10%, so it's quite significant for the software renderer. This _does_ add some extra startup time though fyi.

Not sure if it's applicable for woof but wanted to share 🙂

**Comment by fabiangreffrath** [comment]
I know this code, but never paid much attention to it. But apparently you did, which is good. :wink: What I don't understand is how just adding 32 to the screenwidth value could lead to a performance increase. I could understand if rounding up of some oddball resolution's screenwidth to the next integer multiple of 32 would bring a benefit. But just adding 32? I don't understand it, but this is how it's explained in the comment, so...

**Comment by srludicolo** [comment]
I don't think Proff was known for spaghetti code, but since it's such an old bug, it might be something really deep in there. If @kraflab found the culprit with that string, that could seriously be huge. I think that bug has been around since roughly the late 2000s so that could have its roots deep in PrBoom.

**Comment by fabiangreffrath** [comment]
Which bug? This is about an optional performance tuning which was obviously added by entryway.

**Comment by srludicolo** [comment]
I'm referring to the issue where vsync and fullscreen cause insane stuttering

**Comment by fabiangreffrath** [comment]
This is unrelated.

**Comment by srludicolo** [comment]
Weird. Either way, any performance improvements that don't affect quality of life are always appreciated, haha. Sorry for any confusion

**Comment by fabiangreffrath** [comment]
Implementing this means to replace `SCREENWIDTH` with `SCREENPITCH` in about a gazillion places, right?

**Comment by fabiangreffrath** [comment]
> I know this code, but never paid much attention to it. But apparently you did, which is good. 😉 What I don't understand is how just adding 32 to the screenwidth value could lead to a performance increase. I could understand if rounding up of some oddball resolution's screenwidth to the next integer multiple of 32 would bring a benefit. But just adding 32? I don't understand it, but this is how it's explained in the comment, so...

Maybe @andrey-budko can shed some light on this?

**Comment by andrey-budko** [comment]
IIRC, screen wiping on p4 was ~2 fps without this. Related to cache aliasing probably.

From Intel Pentium 4 Processor Optimization Reference Manual, under the heading "Memory Accesses":
> Lay out data or order computation to avoid having cache lines that have linear addresses that are a multiple of 64KB apart in the same working set. Avoid having more than 4 cache lines that are some multiple of 2KB apart in the same first-level cache working set, and avoid having more than 8 cache lines that are some multiple of 32KB apart in the same second-level cache working set. Avoid having a store followed by a non-dependent load with addresses that differ by a multiple of 16KB

https://pastebin.com/v9RW6U5A

**Comment by fabiangreffrath** [comment]
Wow, that's really low-level, at least more than I am used to. Thank you for the elaboration!

**Comment by ClassicSSGEnjoyer** [comment]
What I don't understand is how just adding 32 to the screenwidth value could lead to a performance increase. 


Will this help increase the fps ?

**Comment by ClassicSSGEnjoyer** [comment]
> I know this code, but never paid much attention to it. But apparently you did, which is good. :wink: What I don't understand is how just adding 32 to the screenwidth value could lead to a performance increase. I could understand if rounding up of some oddball resolution's screenwidth to the next integer multiple of 32 would bring a benefit. But just adding 32? I don't understand it, but this is how it's explained in the comment, so...

Will this help increase the fps ?

**Comment by kraflab** [comment]
Cleaning up (closing) some old issues
