### ISSUE TITLE
i_video.c: memory leak when quit game

### ISSUE THREAD

**Issue by BeWorld2018** [fabiangreffrath/woof#353]
hi,

I see a little bug, not sur if affect Windows...

in function "I_ShutdownGraphics", you dont free SDL resources.

I test that on this function : 

>  if (argbbuffer != NULL)
>    {
>       SDL_FreeSurface(argbbuffer);
>       argbbuffer = NULL;
>    }
>    if (sdlscreen != NULL)
>    {
>       SDL_FreeSurface(sdlscreen);
>       sdlscreen = NULL;
>    }
>    if (texture != NULL)
>    {
>       SDL_DestroyTexture(texture);
> 	  texture = NULL;
>    }
>    if (renderer != NULL)
>    {
>       SDL_DestroyRenderer(renderer);
>       renderer = NULL;
>    }
>    if (screen != NULL)
>    {
> SDL_DestroyWindow(screen);
>       screen = NULL;
>    }

**Comment by fabiangreffrath** [comment]
Yes, you are right, we are not freeing our resources, though, the entire process is closed just within the same split second, implicitely freeing the resources anyway. However, let's play it right. @BeWorld2018 would you like to submit a PR for this, please?

**Comment by fabiangreffrath** [comment]
Please note, though, that this must not break the ENDOOM screen and in-game hires switching!

**Comment by BeWorld2018** [comment]
ok i see you created a commit for it.
I will test your branch later ( in few hours )

**Comment by fabiangreffrath** [comment]
Although it works for me, I *know* it has some issues. For example, when we switch from the game to the ENDOOM screen, we pass over the current renderer and window as pointers to the libtextscreen library. The window is reused, but the renderer gets destroyed and a new one created. The code in i_video.c, though, doesn't know that its renderer has been destroyed and attempts to destroy it again - which for some reasons succeeds. Furthermore, destroying a renderer also destroys all textures that are connected to it, but the code in i_video.c still doesn't know about this and destroys the texture connected to the original renderer again - again sucessful. Somehow this mustn't work, but it does. 😉

**Comment by rfomin** [comment]
We don't need to destroy the renderer for the ENDOOM screen from my testing.

**Comment by fabiangreffrath** [comment]
Yes, or we destroy it immediately after we called TXT_PreInit() and set its and the texture pointer to NULL afterwards.

**Comment by BeWorld2018** [comment]
i test with endoom and all seem ok for me.

**Comment by fabiangreffrath** [comment]
What's left to find out is what happens to a renderer when a new one is connected to the same window.

**Comment by fabiangreffrath** [comment]
It shouldn't even be possible. I'm confused now:
https://github.com/libsdl-org/SDL/blob/665865eda294a2e03aaa9def1c8b6045cd0e406d/src/render/SDL_render.c#L908

**Comment by BeWorld2018** [comment]
Endoom seem use Window and renderer from Woof directly.
I dont know how atexit order work but I_Quit seem the first function call...
( you define:
atexit (SDL_Quit)
atexit (I_Quit_Video)
atexit (I_Quit) )

In Txt_sdl.c : https://github.com/fabiangreffrath/woof/blob/master/textscreen/txt_sdl.c#L270
i see if renderer exist, destroy and recreate new one on same pointer
finally I_Quit_Video seem destroy all
