### ISSUE TITLE
Double clicking sensitivity change

### ISSUE THREAD

**Issue by simc2** [fabiangreffrath/woof#357]
The double clicking in Woof 8.0.0 doesn't feel to work the same way as it did in 7.0.0. Overall it works but it's less sensitive. As if only the first two clicks were counted as the double click.

I can repeat this on Windows x64 computers, with mouse and laptop touchpad buttons: 

Start Woof fresh without the config.
Only change Options > General (page 2) > Double click acts as "Use": yes.
Run Doom2 MAP01/nomonsters and go to the exit door (type 1 DR Open door, wait 4, close).

Click mb2 or the right touchpad button four times in a row.*

In Woof 7.0.0 the door starts to open but it changes direction and closes.
In Woof 8.0.0 the door opens fully and closes after the normal delay.

This happens even at "modest" clicking speed. The closing/reopening works only if I keep a short break (less than half a second) in between the clickings. In Woof 7.0.0 or most other ports such breaks weren't needed.

(*This issue happens with mb3 too. But (as in PrBoom) by default mb3 doesn't do double clicking. It seems to work only after mb3 has been bind to either moving forward or strafing.)

**Comment by rfomin** [comment]
Yes, we are now using SDL2 for double click detection, so I assume it is the same as in OS.

**Comment by fabiangreffrath** [comment]
Can we set an OS independent double click interval in SDL and adjust it to match the previous implementation?

**Comment by kraflab** [comment]
I mentioned this side effect here: https://github.com/fabiangreffrath/woof/pull/292#commitcomment-57899404
You can fix it by checking for values above 2 instead of just 2, if you want to anyway :^)

**Comment by fabiangreffrath** [comment]
Either that,  or actually only every second key in a mash, i.e. `& 2`.
