### ISSUE TITLE
Interpolation doesn't work after pause/enter the menu in singleplayer mode

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#373]
After saving in single-player mode (not netgame) in Woof and Crispy it always `realtics == 1`:
https://github.com/fabiangreffrath/woof/blob/6a93b4fc3552cc2dd00892fc67ac62f79cd8f1f9/Source/d_loop.c#L724
So, after savegame uncapped framerate doesn't work in singleplayer mode.

**Comment by fabiangreffrath** [comment]
Hm, any idea why this happens?

**Comment by rfomin** [comment]
> Hm, any idea why this happens?

I was wrong, it happens after pause/enter the menu because of this code:
https://github.com/fabiangreffrath/woof/blob/1dc57a508a6759c749a6bc0231e469abb603da4b/Source/p_tick.c#L254-L264
