### ISSUE TITLE
Request Boom HUD option for thresholds.

### ISSUE THREAD

**Issue by hackneyed-one** [fabiangreffrath/woof#399]
I've been playing more with the Boom HUD again lately and I would really appreciate the "Backpack changes thresholds" option like in PrBoom-Plus-UM. I would really like to see this option in Woof since its my main port now. It is way more helpful to know if I have between 0 to 12 (red) or 13 to 25 (yellow) rockets/shells as opposed to the larger range of 0 to 25 or 26 to 50 with the backpack. 

Thanks!

**Comment by fabiangreffrath** [comment]
I am not exactly sure why there is a separate option to only affect the max threshold in PrBoom+, do we need this? Also, we should provide an option to color the armor widgets by armot type, not value.
