### ISSUE TITLE
Wrong windowed screen size

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#402]
If you exit Woof in fullscreen mode, the next time you start the game and turn on windowed mode, the window size will be the same as the fullscreen resolution. Tested on the latest master build.

**Comment by fabiangreffrath** [comment]
I guess this line needs a `if (!fullscreen)` guard:
https://github.com/fabiangreffrath/woof/blob/30c99dd1a5648c3150ac33eea9c32376a6b8e92d/Source/i_video.c#L1415

**Comment by rfomin** [comment]
> I guess this line needs a `if (!fullscreen)` guard:
> 
> https://github.com/fabiangreffrath/woof/blob/30c99dd1a5648c3150ac33eea9c32376a6b8e92d/Source/i_video.c#L1415

Yes, this guard fixes it for me.
