### ISSUE TITLE
Request - Ammo colors with backpack

### ISSUE THREAD

**Issue by hackneyed-one** [fabiangreffrath/woof#406]
Thank you so much for the change thresholds! I'm so sorry to ask but could the ammo please be blue if it is at what would be the max or more without the backpack? I mean 50+ for shells/rockets make it blue. As it is now its Green from 25 to 100.

I'm just looking for that bit of extra granularity to match PrBoom-Plus like this...

Shells/Rockets
0 = Grey
1 to 12 = Red
13 to 24 = Yellow 
25 to 49 = Green
50 to 100 = Blue

Thanks

**Comment by fabiangreffrath** [comment]
I'll add a check for ammo percentage being >100%, which is only possible when dividing by maxammo/2, i.e. when the backpack leaves the thresholds intact. 

I guess that's what this dubious third choice for this option is for in Pr+.

**Comment by hackneyed-one** [comment]
Thanks!

Yeah PrBoom-Plus's other option "Full Ammo Only" will turn the numbers blue when, and only when the ammo is at current max capacity. So, blue at 50 without a backpack or blue at 100 with a backpack. I don't see much point in it because again it leaves 25 to potentially 100 as green only. Sure it's nice to know when you are full but I'd rather know at a glance when I'm above or below half with a backpack.
