### ISSUE TITLE
[feature request] free look / mouse look

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#408]
This is an often requested feature. I guess the implementation could get ported over directly from Crispy Doom (watch out e.g. for the `yslopes[]` array and `MLOOKUNIT`). However, the change will be quite invasive, at least more so than e.g. widescreen rendering. It will require additional key bindings for look up / down and mouse look. 

We will *not* implement direct vertical aiming, though. 

This feature will require a sky texture stretching method (maybe something more sophisticated than the mere vertical stretching found in Crispy) as a prerequisite and itself serves as a prerequisite for weapon recoil pitch (another regularly requested feature).

**Comment by fabiangreffrath** [comment]
I wonder if we really need all the key bindings for "look up" + "look down" + "center look". I'd prefer a "mouselook" toggle that would center the view when disabled. What do you think?

**Comment by rfomin** [comment]
> I wonder if we really need all the key bindings for "look up" + "look down" + "center look". I'd prefer a single "mouselook" toggle that would center the view when disabled. What do you think?

I think we only need "mouselook" toggle and button.

**Comment by fabiangreffrath** [comment]
Done. Now what about sky stretching? I am not even sure if this is still the best solution or if we should implement something different.
