### ISSUE TITLE
[feature request] crosshair

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#409]
This is another regular feature request. If we don't implement the projected crosshair from Crispy (we won't), this could be a rather straightforward porting over. It's still up for decision which patch to use for the actual rendering or if we should offer a selection of patches at all. In Boom/MBF we have another (smaller) HUD font to choose from. 

This pulls in quite a handful of additional config keys and will require additional care not to trigger INTERCEPT overflow in Vanilla complevel. 

This requires translucent and color translated patch drawing functions as a prerequisite.

**Comment by rfomin** [comment]
Can we please not use the letters of the font, it looks bad. I still have an unfinished branch:
![doom01](https://user-images.githubusercontent.com/5077629/148637988-4265c9d5-e716-4dc1-a4de-66dd28234ae4.png)



> This requires translucent and color translated patch drawing functions as a prerequisite.

Does it seem to work as it is? Not sure.

**Comment by fabiangreffrath** [comment]
> Can we please not use the letters of the font, it looks bad. I still have an unfinished branch:

This looks indeed good! I think we could even draw the four lines directly into the renderer in a post-processing step. 
https://wiki.libsdl.org/SDL_RenderDrawLine

> Does it seem to work as it is? Not sure.

Sorry, I'm afraid I don't understand this question.

**Comment by rfomin** [comment]
> > Does it seem to work as it is? Not sure.
> 
> Sorry, I'm afraid I don't understand this question.

I just use `V_DrawPatch` and it works. So we don't need additional coding?

**Comment by fabiangreffrath** [comment]
Only if we want to make the crosshair translucent.

**Comment by kraflab** [comment]
Some time ago I added a variety of extra crosshair graphics to dsda-doom, feel free to copy them over if you decide to go that route.

**Comment by rfomin** [comment]
Can we somehow draw a patch without aspect ratio correction? I'm used to modern games with a crystal clear UI that is on a separate plane from the render. Non-square pixels on the crosshair look bad.

**Comment by fabiangreffrath** [comment]
Aspect ratio correction is a property of the renderer, by means of `SDL_RenderSetLogicalSize()`, so I am afraid that everything that goes through that renderer will get stretched.

**Comment by rfomin** [comment]
`SDL_RenderSetLogicalSize()` greatly simplifies things for us. What if we do the scaling ourselves?

**Comment by fabiangreffrath** [comment]
I think this is going too far for the benefit of an unstretched crosshair patch.

**Comment by rfomin** [comment]
I've tried `SDL_RenderDrawLineF` (with subpixel precision, SDL convert coords to float anyway), not good:
![doom01](https://user-images.githubusercontent.com/5077629/148645883-93da828a-f657-4d1b-95e5-409446ba7f4c.png)

**Comment by rfomin** [comment]
```c
   int w, h;
   SDL_RenderGetLogicalSize(renderer, &w, &h);
   float fw, fh;
   fw = (float)w/2; fh = (float)h/2;
   SDL_SetRenderDrawColor(renderer, 255, 255, 255, SDL_ALPHA_OPAQUE);
   SDL_RenderDrawLineF(renderer, fw - 7, fh, fw - 3, fh);
   SDL_RenderDrawLineF(renderer, fw + 7, fh, fw + 3, fh);
   SDL_RenderDrawLineF(renderer, fw, fh - 7, fw, fh - 3);
   SDL_RenderDrawLineF(renderer, fw, fh + 7, fw, fh + 3);
```

**Comment by fabiangreffrath** [comment]
Not bad, why aren't you satisfied with this.

**Comment by rfomin** [comment]
I guess it looks better on screenshot than in motion. Lines with non-square pixels right in the center of the screen look annoying. We could implement this and see if people are satisfied. I don't use crosshair in Doom anyway.

**Comment by fabiangreffrath** [comment]
Honestly, for the sake of simplicity, I'd rather prefer in-game patch drawing then.

**Comment by fabiangreffrath** [comment]
> Some time ago I added a variety of extra crosshair graphics to dsda-doom, feel free to copy them over if you decide to go that route.

Thanks for the offer! I like the shapes of the crosshairs, but we should decide which default color to go for. Pr+'s ones are read, whereas @rfomin seems to prefer white. Alternatively, we could offer a choice of default color which we could translate to from red.

**Comment by fabiangreffrath** [comment]
> Some time ago I added a variety of extra crosshair graphics to dsda-doom, feel free to copy them over if you decide to go that route.

May I assume GPL license for the assets, just as the rest of the code?

**Comment by kraflab** [comment]
> > Some time ago I added a variety of extra crosshair graphics to dsda-doom, feel free to copy them over if you decide to go that route.
> 
> May I assume GPL license for the assets, just as the rest of the code?

Sure
