### ISSUE TITLE
Weird Desync in Vanilla Multiplayer Demo

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#411]
Found on [TWANGO1](https://www.doomworld.com/idgames/levels/doom2/deathmatch/s-u/twango1) in the third demo. It completely desyncs.

**Comment by fabiangreffrath** [comment]
Is this with the 8.1 release or with a dev build?

**Comment by rfomin** [comment]
Desync in both. I'm testing it right now.

**Comment by rfomin** [comment]
It seems the problem is in `G_DeathMatchSpawnPlayer` function.
