### ISSUE TITLE
M_PADSEN Lump Replacements not showing

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#415]
I created a lmp for the gamepad sensitivity slider label in the options menu (labelled M_PADSEN), and it doesn't show in-game.

**Comment by rfomin** [comment]
Do you build the latest master? Current Woof 8.1.0 doesn't support it.

**Comment by OpenRift412** [comment]
> 

I haven't yet, no.

**Comment by fabiangreffrath** [comment]
You will need to create graphics for M_HORSEN and M_VERSEN as well, since these aren't embedded into the executable anymore.

**Comment by fabiangreffrath** [comment]
Just checked: If all three graphics are available, the Sensitivity menu is rendered as expected.

**Comment by OpenRift412** [comment]
> You will need to create graphics for M_HORSEN and M_VERSEN as well, since these aren't embedded into the executable anymore.

Right, that's what I had when I installed it.
