### ISSUE TITLE
MIDI doesn't pause in paused mode

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#417]
Hey so, something I've noticed is that when the game is in paused mode (with the Pause key, not the menu), instead of the MIDI being paused as well, it instead just mutes and keeps playing silently.

**Comment by rfomin** [comment]
> Hey so, something I've noticed is that when the game is in paused mode (with the Pause key, not the menu), instead of the MIDI being paused as well, it instead just mutes and keeps playing silently.

This has been changed recently. This will be fixed in the next version.

**Comment by fabiangreffrath** [comment]
Well, then this can be closed.
