### ISSUE TITLE
IDBEHOLD0 style cheat to disable all powerups at once

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#423]
I'd like to port over Crispy's IDBEHOLD0 cheat, which disables all powerups at once, but apparently MBF does not allow for non-alpha characters in cheat codes:
https://github.com/fabiangreffrath/woof/blob/344bb64a6369753c9be6c81878a8757ed893377a/Source/m_cheat.c#L775-L777

**Comment by rfomin** [comment]
I want to port RESURRECT (or IDDQD after death) and BUDDHA. BTW, what do you think about the console in Woof? :smile:

**Comment by fabiangreffrath** [comment]
If RESURRECT is not much more than IDDQD after death (i.e. what it currently is in PrBoom+ and Crispy), then I prefer the latter. BUDDHA may be funny as well. Regarding console in Woof, I don't think a console has ever made sense in any Doom source port - or do you have any specific use case in mind that I haven't stumbled upon yet?

**Comment by fabiangreffrath** [comment]
BTW, this line checks for a cheat code whose shift register `sr` solves the equation `(32767 & sr)-19891 == 0` and prints a cryptic message about being a "team member". Has anybody ever figured out which cheat code that is?

https://github.com/fabiangreffrath/woof/blob/344bb64a6369753c9be6c81878a8757ed893377a/Source/m_cheat.c#L788

**Comment by rfomin** [comment]
> Regarding console in Woof, I don't think a console has ever made sense in any Doom source port - or do you have any specific use case in mind that I haven't stumbled upon yet?

Basically for entering cheats. In addition, this is an excuse to dump 90% of the menu into it.

> cryptic cheat

Heh, probably some kind of easter egg.

**Comment by fabiangreffrath** [comment]
> Basically for entering cheats. In addition, this is an excuse to dump 90% of the menu into it.

The menu isn't *that* bad. A good menu entry pretty much explains itself, whereas console commands need to be documented elsewhere. Also, I don't need to *see* a cheat when I enter it.

Furthermore, may I quote from the project synapsis:

> [...] this source port should look very familiar to the original MBF.

😉 

> Heh, probably some kind of easter egg.

Yes, right, but I haven't yet figured it out. 😒

**Comment by kraflab** [comment]
> I'd like to port over Crispy's IDBEHOLD0 cheat, which disables all powerups at once, but apparently MBF does not allow for non-alpha characters in cheat codes:

I ran into this some time ago and "fixed" it in dsda-doom here: https://github.com/kraflab/dsda-doom/commit/b1b9d7ae5f2174f5114c02cbc7e443c10c617909#diff-41456c599f4ddf5bb74ba9a89750ac0db230eda7783f44526078b502dc358da9

:^)

BTW about consoles, the main motivations for this in dsda-doom are to eventually allow for the use of scripts and for recording generic actions into dsda-doom's extended demo format. Some day... 😉

**Comment by fabiangreffrath** [comment]
> I ran into this some time ago and "fixed" it in dsda-doom here: 

I think we follow very different approaches whenever we face such burdens. You seem to end up reimplementing stuff from scratch, whereas I try to make my changes as minimal as possible. 😉 

> BTW about consoles, the main motivations for this in dsda-doom are to eventually allow for the use of scripts and for recording generic actions into dsda-doom's extended demo format. Some day... 😉

I still fail to see a valid use case for any console in any Doom source port. They are either used for visibly entering cheats or for hiding options which could have been placed in the menu with a descriptive line.

**Comment by fabiangreffrath** [comment]
In the same manner, I'd like to allow IDCLEV00 to restart the current map - but now that we have UMAPINFO support, MAP00 or E0M0 may even be valid maps to warp to.

**Comment by kraflab** [comment]
I didn't reimplement cheat handling actually, I just deleted the boom / mbf handler (plus some refactoring I suppose). Prboom+ had both the old one and the new one, and as far as I could tell the new one was just a worse version (including the limitation you mentioned here).

The dsda-doom console has commands like setting the current position and buffer inputs. For instance you can set yourself to always execute a strafe value of 2 repetitively to execute a setup or trick. Those operations aren't really suited to being in a menu. Of course woof has different needs 🙂
