### ISSUE TITLE
"umapdef.lmp" in autoload incompatibility with UMAPINFO

### ISSUE THREAD

**Issue by Raddatoons** [fabiangreffrath/woof#431]
This is an awfully specific bug, but I wanted to bring it to your attention in case it might help.

I set up a custom file of SEWERS.WAD (🤢) with the original Xbox super secret exit path patched into E1M1, and enabled this through a UMAPINFO lump. This UMAPINFO also enables the Ultimate MIDI Pack's E1M10 track to play within the map correctly.
I also chose to run both of Romero's E1M4b and E1M8b wads alongside it, as well as UMIDIP.  It ran flawlessly.

But when I disabled the MIDI pack, something odd happened. Upon taking the super secret exit, the intermission screen said I completed E1M4b, then sent me directly to E1M2, instead of saying I completed E1M1 and sending me to E1M10 as expected.

It worked perfectly with the MIDI pack, implying that one of the various MAPINFO lumps included was solving the problem before I even knew it existed. After some tinkering, it turned out that trying to fix the problem using those files wasn't going to work out like I'd hoped.

I did eventually find the solution, but it feels like a really bizarre incompatibility to have.
The autoload files for E1M4b and E1M8b that come with Woof! are titled `umapdef.lmp`. But changing their file names to `umapinfo.lmp` suddenly makes them work together flawlessly with my SEWERS.WAD file. I had thought these two file types were perfectly compatible, but it seems like something in UMIDIP's UMAPINFO lump was forcing them to work together despite the somehow conflicting nature of the two formats.

I still don't understand it completely, but I wanted to make sure you were at least aware of it. I'm also curious why you chose to name them as `umapdef.lmp` instead of `umapinfo.lmp` in the first place. Is there a different bug that might arise if you labeled them as such?

I've attached a copy of my SEWERS.WAD if you want to experiment for yourself, maybe you'll find something I couldn't. Thanks for looking into this for me.
[UMAPINFOSEWERS.zip](https://github.com/fabiangreffrath/woof/files/7948266/UMAPINFOSEWERS.zip)
[Credits in case you wanna remake this entirely:
Patched SEWERS.WAD by ClassicDOOM.com
Modified E1M1 from condoom1.pk3 by Ded10c
UMAPINFO and WILV09 lumps by me]

**Comment by fabiangreffrath** [comment]
@rfomin If you could find some time, could you have a look, please?
