### ISSUE TITLE
autoload bugs with .bat files

### ISSUE THREAD

**Issue by Raddatoons** [fabiangreffrath/woof#437]
I recently decided to make a bunch of shortcuts to my commercial Doom WADs through Woof!, and discovered that for a couple of them the command parameters were too long to fit in the shortcut target space.  (Yes, I'm a subfolder madman, and loading the IWADs and PWADs filled up too many characters.)  To get around this, I created some batch files to give me unlimited room to load the necessary WADs.  I made one .bat file for NRFTL, and one for Chex Quest 2.

When I normally run my games, I have their related widescreen patches in their respective autoload folders.  When opening Chex Quest 2 through ZDL, it autoloads the widescreen patches (one for the status bar, one for the screens) and the chex.deh file perfectly.  However, when I ran the batch file, the widescreen autoloads failed, and it displayed the original 4:3 graphics.  I compared the batch file command directly against the ZDL launch command, and I couldn't find any differences.  Regardless, I had to manually add the normally autoloaded files into the batch file command.

I also made a batch file for NRFTL, so I went to test that one as well to see if it also had autoloading problems.  I discovered that the problem is actually _inconsistent_, as for this batch file, which just loaded NERVE.WAD alongside DOOM II, the widescreen patches worked completely fine.  However, when I made the decision to add the NRFTL MIDI Pack to the batch file, suddenly the widescreen patch failed to autoload.  However, the _status bar_ widescreen autoload still worked, perhaps because it was autoloaded to the IWAD instead of the PWAD?  Either way, it confused me to no end.

This bug could be any number of things, it could be my horrifically long file paths, it could be the number of PWADs being loaded, it could just be a bug with specific WAD files or a problem with batch files in general.  And the autoloads still work completely fine through ZDL, which further confuses me.  This is something that will need a lot of testing beyond my two little examples, but I wanted to at least make you aware of the issue for the future.

If needed I can try to provide all of my ridiculous filepaths and WAD loadings for exact testing.

**Comment by fabiangreffrath** [comment]
I can only guess what could be the cause of this. The autoload files are loaded from the `autoload/` subdirectory relative to the executable's directory - i.e. the directory where `woof.exe` resides. Now, if you start `woof.exe` from a `.bat` file, it may be possible that the `.bat` file takes the role of the executable and the autoload search path is set relative to its location. I am not sure about this, though.

So, does it help if you move the `.bat` files into the same directory as `woof.exe`?

I imagine that ZDL launches `woof.exe` with some kind of `execve()` or similar. I am not sure if the same can be achieved with a `.bat` file, but could you try to prepend `start` to the call to `woof.exe` in the `.bat` file?

**Comment by Raddatoons** [comment]
Testing with Chex Quest 2, moving the `.bat` file to the Woof! directory nor prepending `start` to the `.bat` file seemed to help.

However, I DID figure out the solution in the end!
It's not a problem with not running the `.bat` file near the source port, it's a problem with not running the `.bat` file near the WAD files themselves.  Putting the `.bat` file in the same folder as the WAD files I want to load and then marking the added files as
`-file "chex2.wad"`
instead of typing the full file path makes the autoload work correctly with the `.bat` file.

So what I'm going to do to fix the issue on my end is copy `chex.wad` and `chex2.wad` into a new folder, and edit my `.bat` file to refer to the files directly in the folder with it.  I don't know if the autoload issue happens with IWADs, but I figure it's better safe than sorry.  Doing the same thing with `NERVE.WAD` and the MIDI Pack also works, so I figure this is the way I should do it with all future `.bat` files.

Thanks for the advice, hopefully this is useful information for you!

**Comment by fabiangreffrath** [comment]
Hm, if relative file paths are important, maybe this is an issue of forward vs backward slashes. Do you use forward or backward slashes in your `.bat` files?

**Comment by Raddatoons** [comment]
I was using forward slashes.  I changed them all to backwards slashes and suddenly autoloads work fine again for the original batch files.

**Comment by Raddatoons** [comment]
After running into a different shortcut-related bug with Crispy Doom that once again was fixed by swapping the slashes around, I've concluded that ZDL is simply dummy-proofed to autocorrect all forward slashes in file paths to backwards slashes to allow for easy accessibility to people who don't know the difference (like me a lot of the time), yet never actually tells this to the user upfront.

I'll definitely remember to prioritize back slashes more often now, thanks for all the help though!
