### ISSUE TITLE
Not launching with Fluidsynth

### ISSUE THREAD

**Issue by leveste** [fabiangreffrath/woof#441]
Having issues running Woof on Manjaro Linux(KDE).

I first installed the source port from the AUR with yay. It launched, but there was no music, so I figured I'd change the MIDI player(worked with other source ports). I tried Fluidsynth and when I tried to launch Woof again, I got the output bellow

```
IWAD found: /home/leveste/Games/DOOM_Wads/PLUTONIA.WAD
Final DOOM: The Plutonia Experiment version
                   DOOM 2: Plutonia Experiment v2.03                           
Built on Feb  6 2022
M_LoadDefaults: Load system defaults.
V_Init: allocate screens.
W_Init: Init WADfiles.
 adding /home/leveste/Games/DOOM_Wads/PLUTONIA.WAD

M_Init: Init miscellaneous info.
R_Init: Init DOOM refresh daemon - [ ........................ ]
R_InitData
R_InitPlanes
R_InitLightTables
R_InitSkyMap
R_InitTranslationsTables

P_Init: Init Playloop state.
I_Init: Setting up machine state.
I_InitJoystick: Failed to open game controller.
I_InitSound: Configured audio device with 2048 samples/slice.
Precaching all sound effects...done.
I_InitMusic: Using SDL_mixer.
ALSA lib pcm_dsnoop.c:601:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_a52.c:1001:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
fluidsynth: error: fluid_sfloader_load(): Failed to open '/usr/share/sounds/sf3/default-GM.sf3': File does not exist.
fluidsynth: error: Unable to open file '/usr/share/sounds/sf3/default-GM.sf3'
fluidsynth: error: ipatch_file_open() failed with error: 'No such file or directory'
fluidsynth: error: Failed to load SoundFont "/usr/share/sounds/sf3/default-GM.sf3"
Error loading FluidSynth soundfont: /usr/share/sounds/sf3/default-GM.sf3
```

I tried uninstalling the AUR version and building from source(like in the README instructions), but I get the same output

I tried running DSDA-Doom with Fluidsynth and it also failed to load it, so I'm pretty sure the issue's on my side. Key difference is that, instead of crashing on launch, DSDA-Doom just tried(and succeded) launching with the next available player(in my case OPL2), while Woof just refuses to launch altogether, so I can't change the setting normally.

Is there a config file it's referencing? And, if so, how is it called and which line should I look for?

And, finally, could we get an implementation like in DSDA-Doom where it at least tries the other MIDI players first instead of not launching at all?

**Comment by fabiangreffrath** [comment]
Yes, we need to fall back to Native/SDL if Fluidsynth fails to initialize.

**Comment by leveste** [comment]
That's good to know. In the meantime, where should I change the setting back to the original. Since the issue remains no matter how much I re-install it, I'm guessing there's a config file that doesn't get affected.

**Comment by rfomin** [comment]
Can we somehow install soundfont on Linux? I deliberately call `I_Error` if the sound font is not found to inform the user on Windows.

**Comment by fabiangreffrath** [comment]
> That's good to know. In the meantime, where should I change the setting back to the original. Since the issue remains no matter how much I re-install it, I'm guessing there's a config file that doesn't get affected.

Set `midi_player` to `0` in `woof.cfg`.

**Comment by leveste** [comment]
Thanks! That worked. I'm kinda embarrased how long it took me to find it.

`.local/share/woof/woof.cfg`

I'll close the issue then, since we got a solution(music with OPL works, btw).

**Comment by fabiangreffrath** [comment]
> Can we somehow install soundfont on Linux? I deliberately call `I_Error` if the soundfont is not found to inform the user on Windows.

I fact, it gets installed to whereever `DESTINATION` points to. We should change that similar to how the `autoload/` directory gets installed. That's the first thing to fix.

> I'll close the issue then, since we got a solution(music with OPL works, btw).

I don't consider this issue as resolved, just because you managed to find the config file and manually reset the corresponding config key to the default setting. As a lesson from this, we need to print out the used config file, just as Chocolate Doom and PrBoom+ do - that's the second thing to fix.

Third, if the fluidsynth backend fails to initialize *for whatever reason*, we need to be able to get out of this config trap. It will be impossible to start the game in order to select a different music backend, because the one currently selected fails to start...

**Comment by fabiangreffrath** [comment]
b755013f62e5e4d81e31460b81af0ccef22df324
