### ISSUE TITLE
input_novert bound to key, disables cheats

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#445]
This is more a question about an inconvenience than an actual bug. If I bind the "horizontal mouse" toggle to e.g. the 'V' key, then I cannot type the IDCLEV cheat anymore. This is, because the key is already "eaten" in `M_Responder()`. Does anything speak against moving the check for this to `G_Responder()` or letting the check return `false`? How do other source ports handle this key clashing?

**Comment by kraflab** [comment]
All these toggles in dsda-doom don't eat the key, see https://github.com/kraflab/dsda-doom/blob/3b16be2faa1d6cb4023140b6c80c8fc532e49b1e/prboom2/src/m_menu.c#L4388

I think it's similar in prboom+.

**Comment by fabiangreffrath** [comment]
Ah, I see! That'd be pendant to not not returning at all from the toggle, not even `return false`.

**Comment by fabiangreffrath** [comment]
I guess I'd be best to comment out the `return true` line from the `autorun` and the `novert` toggles. What do you say @rfomin ?
