### ISSUE TITLE
SIGIL E5M8 Boss Death flags active

### ISSUE THREAD

**Issue by Raddatoons** [fabiangreffrath/woof#455]
I was recently playing `SIGIL_v1_21.wad` in Woof! 8.1.0 on HNTR, but when I reached the final level, the game unexpectedly cut to the end when I defeated the Spiderdemon boss.  I think it was designed for any source port's non-vanilla (>4) episodes to have boss flags inactive by default for their respective final levels, but I believe those flags have been enabled on accident.  Using `SIGIL_COMPAT_v1_21.wad` does not have this issue as it has specific DEHACKED flags to disable the Spiderdemon's boss death flags on E3M8.

I have not tested this on HMP or UV, where a Cyberdemon will also spawn, to see how it affects the boss flags.

I have observed this bug in multiple source ports, the main ones being Woof!, Crispy Doom, and PrBoom+.  I wasn't sure if it was a shared piece of code between these source ports causing the issue or if they each have unique issues, but I am intending to make unique bug reports for each one.

**Comment by fabiangreffrath** [comment]
Indeed, we are still missing a umapdev.lmp for sigil.wad, or SIGIL_v1_21.wad that is. @rfomin do you think you could provide one?
