### ISSUE TITLE
No Rest for the Living has Doom 2 map names in automap(and D2 title screen if using BFG edition)

### ISSUE THREAD

**Issue by leveste** [fabiangreffrath/woof#459]
Recently played NRFTL. I played with the community midi pack, which had no issues, but I noticed that the automap shows the names of the original Doom 2 maps(Entryway, Underhalls etc.) instead of the NRFTL ones. It's fine on the level stats screen. I tried it without the midi pack as well and it's the same.

I played on the version from the BFG Edition, since I already had it in my WADs folder from before the Unity ports came to PC, but I downloaded the add-on version and it had the same issue.

Interestingly, with the BFG edition, the NRFTL title screen only shows if I'm also running the MIDI pack(otherwise it defaults to the DOOM 2 screen). The Add-on version, otoh, doesn't have this issue and loads the correct title screen.

Otherwise, there haven't been any issues with running the WAD

**Comment by fabiangreffrath** [comment]
Dup of #431 ?

**Comment by rfomin** [comment]
> Dup of #431 ?

Yes, I think so.

**Comment by leveste** [comment]
> Dup of #431 ?



Honestly, not sure. My only issue was the Automap showing the names of DOOM 2 levels, instead of the NRFTL ones.

The correct title screen showing only if I use the MIDI pack only happens with the version of the WAD from DOOM 3 BFG Edition. I downloaded the Add-on version from the Unity port and running that one gave me the correct title screen even if I didn't have the MIDI pack on.

**Comment by fabiangreffrath** [comment]
@leveste Do you have any chance to test a development snapshot?

**Comment by leveste** [comment]
If you mean if I have time to test, sure. Do I compile the repo or are you sending a binary you compiled yourself? Cause, if it's the latter, I need to mention I'm on Linux(Manjaro KDE, to be exact).

**Comment by fabiangreffrath** [comment]
Then you'd better compile the repo yourself. There are detailled instruction in the README. Please check stdout if the corresponding files from `autoload/nerve.wad` are properly loaded.

**Comment by leveste** [comment]
So I compiled the repo(as of this comment, [this](4d92be7d915cf1226618d969cc0b3f1b2e9981a3) is the latest commit). Here's the output from the terminal for the BFG Edition version of the WAD:

```
./woof -iwad ~/Games/DOOM_Wads/DOOM2.WAD -file ~/Games/DOOM_Wads/NERVE.WAD                                                                                      
IWAD found: /home/leveste/Games/DOOM_Wads/DOOM2.WAD
DOOM II version
                         DOOM 2: Hell on Earth v2.03                           
Built on Feb 22 2022
M_LoadDefaults: Load system defaults.
 default file: /home/leveste/.local/share/woof/woof.cfg
V_Init: allocate screens.
W_Init: Init WADfiles.
 adding /home/leveste/Games/DOOM_Wads/DOOM2.WAD
 adding /home/leveste/Games/DOOM_Wads/NERVE.WAD

M_Init: Init miscellaneous info.
R_Init: Init DOOM refresh daemon - [ ........................ ]
R_InitData
R_InitPlanes
R_InitLightTables
R_InitSkyMap
R_InitTranslationsTables

P_Init: Init Playloop state.
I_Init: Setting up machine state.
I_InitJoystick: Failed to open game controller.
I_InitSound: Configured audio device with 2048 samples/slice.
Precaching all sound effects...done.
I_InitMusic: Using SDL_mixer.
OPL_Init: Using driver 'SDL'.
NET_Init: Init network subsystem.
D_CheckNetGame: Checking network game status.
startskill 3  deathmatch: 0  startmap: 1  startepisode: 1
player 1 of 1 (1 nodes)
S_Init: Setting up sound.
S_Init: default sfx volume 6
HU_Init: Setting up heads up display.
ST_Init: Init status bar.
P_SetupLevel: map01 (NERVE.WAD), Doom nodes
 Skill 3, Total 0:00:00
 Demo Version 221
```
And here's the output for the Add-on version from the Unity ports:
```
./woof -iwad ~/Games/DOOM_Wads/DOOM2.WAD -file ~/Games/DOOM_Wads/PWADS/NERVE.wad                                                                         
IWAD found: /home/leveste/Games/DOOM_Wads/DOOM2.WAD
DOOM II version
                         DOOM 2: Hell on Earth v2.03                           
Built on Feb 22 2022
M_LoadDefaults: Load system defaults.
 default file: /home/leveste/.local/share/woof/woof.cfg
V_Init: allocate screens.
W_Init: Init WADfiles.
 adding /home/leveste/Games/DOOM_Wads/DOOM2.WAD
 adding /home/leveste/Games/DOOM_Wads/PWADS/NERVE.wad

M_Init: Init miscellaneous info.
R_Init: Init DOOM refresh daemon - [ ........................ ]
R_InitData
R_InitPlanes
R_InitLightTables
R_InitSkyMap
R_InitTranslationsTables

P_Init: Init Playloop state.
I_Init: Setting up machine state.
I_InitJoystick: Failed to open game controller.
I_InitSound: Configured audio device with 2048 samples/slice.
Precaching all sound effects...done.
I_InitMusic: Using SDL_mixer.
OPL_Init: Using driver 'SDL'.
NET_Init: Init network subsystem.
D_CheckNetGame: Checking network game status.
startskill 3  deathmatch: 0  startmap: 1  startepisode: 1
player 1 of 1 (1 nodes)
S_Init: Setting up sound.
S_Init: default sfx volume 6
HU_Init: Setting up heads up display.
ST_Init: Init status bar.
P_SetupLevel: map01 (NERVE.wad), Doom nodes
 Skill 3, Total 0:00:00
 Demo Version 221
```


Same as before, the map name when opening the automap is the original DOOM 2 one and the BFG Edition version of the wad has the DOOM 2 title screen, while the Add-on version has the correct one.

**Comment by fabiangreffrath** [comment]
Please do this and try again:

```
rm -rf build/Source/autoload/
ln -s ../../autoload build/Source/
```

**Comment by fabiangreffrath** [comment]
@rfomin The same happens in MSYS2 if you start `woof.exe` from the `build/Source` directory. Somehow, Woof needs to get "installed" for the autoload feature to work, i.e. the autoload subdirectory must be either in the same directory as the executable or in a system-wide directory on Linux. Do you have any idea how we could copy the autoload directory into `build/Source` during building?

**Comment by rfomin** [comment]
We can add post-build command like here: https://github.com/fabiangreffrath/woof/blob/4d92be7d915cf1226618d969cc0b3f1b2e9981a3/Source/CMakeLists.txt#L212

**Comment by leveste** [comment]
> Please do this and try again:
> 
> ```
> rm -rf build/Source/autoload/
> ln -s ../../autoload build/Source/
> ```
> 
> Edit: from the top-level source directory, that is.

Still the same. Also, when I went to remove autoload, it wasn't present in the directory, so I went straight to the link command.

**Comment by fabiangreffrath** [comment]
@leveste Please do the following

```
rm -rf build
git pull
```

and try again.

**Comment by leveste** [comment]
Still the same. The `autoload` directory copied itself to `build/Source`, but the map names still show incorrectly. Same with the title screen for the BFG version.

**Comment by fabiangreffrath** [comment]
Ah, okay! On Linux, ´D_DoomPrefDir()` does not return the executable's directory, but the result of `SDL_GetPrefPath()`.

**Comment by fabiangreffrath** [comment]
@leveste Now it should work!

**Comment by leveste** [comment]
Getting error:

```
[  1%] Building C object opl/CMakeFiles/opl.dir/opl.c.o
[  2%] Building C object opl/CMakeFiles/opl.dir/opl_queue.c.o
[  2%] Building C object opl/CMakeFiles/opl.dir/opl_sdl.c.o
[  3%] Building C object opl/CMakeFiles/opl.dir/opl3.c.o
[  4%] Linking C static library libopl.a
[  4%] Built target opl
[  5%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_button.c.o
[  5%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_desktop.c.o
[  6%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_gui.c.o
[  7%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_io.c.o
[  8%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_label.c.o
[  9%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_separator.c.o
[ 10%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_strut.c.o
[ 10%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_table.c.o
[ 11%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_widget.c.o
[ 12%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_window_action.c.o
[ 13%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_window.c.o
[ 14%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_sdl.c.o
[ 15%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_utf8.c.o
[ 15%] Linking C static library libtextscreen.a
[ 15%] Built target textscreen
[ 16%] Building C object Source/CMakeFiles/woof.dir/am_map.c.o
[ 17%] Building C object Source/CMakeFiles/woof.dir/d_deh.c.o
[ 18%] Building C object Source/CMakeFiles/woof.dir/d_items.c.o
[ 20%] Building C object Source/CMakeFiles/woof.dir/d_iwad.c.o
[ 21%] Building C object Source/CMakeFiles/woof.dir/d_main.c.o
/home/leveste/Apps/woof/Source/d_main.c:687:12: error: initialization of ‘const char * (*)(void)’ from incompatible pointer type ‘char * (*)(void)’ [-Werror=incompatible-pointer-types]
  687 |     {NULL, D_DoomExeDir},
      |            ^~~~~~~~~~~~
/home/leveste/Apps/woof/Source/d_main.c:687:12: note: (near initialization for ‘autoload_basedirs[2].func’)
cc1: some warnings being treated as errors
make[2]: *** [Source/CMakeFiles/woof.dir/build.make:132: Source/CMakeFiles/woof.dir/d_main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:287: Source/CMakeFiles/woof.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

```

This was with a clean install.

**Comment by fabiangreffrath** [comment]
Sorry, I introduced a little bug. `git pull` and try again?

**Comment by leveste** [comment]
It compiled, but the original issue still persists. I don't see anything different in the output, but I'll paste it just in case. The one bellow is from the BFGE version(I tried both):

```
IWAD found: /home/leveste/Games/DOOM_Wads/DOOM2.WAD
DOOM II version
                         DOOM 2: Hell on Earth v2.03                           
Built on Feb 22 2022
M_LoadDefaults: Load system defaults.
 default file: /home/leveste/.local/share/woof/woof.cfg
V_Init: allocate screens.
W_Init: Init WADfiles.
 adding /home/leveste/Games/DOOM_Wads/DOOM2.WAD
 adding /home/leveste/Games/DOOM_Wads/NERVE.WAD

Loading DEH file ./autoload/doom-all/bloodcolor.deh
M_Init: Init miscellaneous info.
R_Init: Init DOOM refresh daemon - [ ........................ ]
R_InitData
R_InitPlanes
R_InitLightTables
R_InitSkyMap
R_InitTranslationsTables

P_Init: Init Playloop state.
I_Init: Setting up machine state.
I_InitJoystick: Failed to open game controller.
I_InitSound: Configured audio device with 2048 samples/slice.
Precaching all sound effects...done.
I_InitMusic: Using SDL_mixer.
OPL_Init: Using driver 'SDL'.
NET_Init: Init network subsystem.
D_CheckNetGame: Checking network game status.
startskill 3  deathmatch: 0  startmap: 1  startepisode: 1
player 1 of 1 (1 nodes)
S_Init: Setting up sound.
S_Init: default sfx volume 6
HU_Init: Setting up heads up display.
ST_Init: Init status bar.
P_SetupLevel: map01 (NERVE.WAD), Doom nodes
 Skill 3, Total 0:00:00
 Demo Version 221

```

**Comment by rfomin** [comment]
Maybe autoload is really case-sensitive in Linux?

**Comment by fabiangreffrath** [comment]
> Loading DEH file ./autoload/doom-all/bloodcolor.deh

This is quite an improvement!

**Comment by fabiangreffrath** [comment]
> Maybe autoload is really case-sensitive in Linux?

Indeed it is! In `GetAutoloadDir()`. I'll fix that!

**Comment by leveste** [comment]
> Maybe autoload is really case-sensitive in Linux?

Linux is indeed case-sensitive. Unlike Windows, you can have two files with identical names without any conflict as long as one letter is a different case.

**Comment by fabiangreffrath** [comment]
@leveste Your turn. 😉

**Comment by fabiangreffrath** [comment]
I have all my WAD files saved with lower case file names on Linux. 😆

**Comment by leveste** [comment]
I have them the way they're downloaded, so for PWADs it's up to the map maker(or, in the case of the add-on version, up to me, cause Bethesda just gives a number to the wad).

Anyway, it works now. The correct names show up. Only other thing is that the BFGE version still comes up with the Doom 2 title screen(again, the add-on version shows up the NRFTL title screen), but I'll leave it to you if you want to do anything further or just flag that one as unsoported. Issue's resolved as far I'm concerned :)

**Comment by fabiangreffrath** [comment]
> Anyway, it works now. 

Phew, thanks!

> The correct names show up. Only other thing is that the BFGE version still comes up with the Doom 2 title screen(again, the add-on version shows up the NRFTL title screen), but I'll leave it to you if you want to do anything further or just flag that one as unsoported. Issue's resolved as far I'm concerned :)

In fact, the BFGE Doom2 IWAD does contain a TITLEPIC lump in contrast to the Doom 1 IWAD. The rule is that if there is a TITLEPIC lump, this will be used, else PWADs couldn't provide their own TITLEPIC lumps anymore if the IWAD provides a DMENUPIC lump and that gets precedence.

**Comment by leveste** [comment]
I see. In that case, I think it's safe to close this issue.

**Comment by fabiangreffrath** [comment]
OK, I have fixed the DMENUPIC vs TITLEPIC issue as well: If (a) we don't have TITLEPIC or (b) we have TITLEPIC and also have DMENUPIC and TITLEPIC is from the IWAD, we use DMENUPIC.
