### ISSUE TITLE
Unix manpage

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#460]
This project needs a Unix manpage to document at least the most important command line parameters.

**Comment by rfomin** [comment]
Is there a cross-platform way to do this? It would be nice to have `--help` on Windows.

**Comment by fabiangreffrath** [comment]
There is `getopt()` and `argp()` and I think the latter even has built-in support for a `--help` command. However, using one of these would mean to adapt *all* command line options that we currently parse spread over all source files. Not sure if it's worth the effort.
