### ISSUE TITLE
Libraries not provided when built

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#462]
At least with my building method, I noticed that the built executable is not accompanied by the necessary libraries as before. 

I will make it clear that I know nothing about building so I'll just quickly sum up how I perform the building, in case it's an issue specific to that:

- Download and unzip `woof-master`
- In MSYS2:
  - `cd` to `woof-master`
  - Run `cmake -G "MinGW Makefiles" -B build`
  - `cd` to the newly generated `build` folder
  - Run `mingw32-make.exe`

After that, the contents of `woof-master/build/Source` are:

- `autoload` folder
- `woof.exe`
- And the probably irrelevant:
  - `CMakeLists` folder
  - `cmake_install.cmake`
  - `Makefile`

This building procedure _did_ work up until this release. I'm truly sorry if this is just me messing up, but I couldn't really know.

**Comment by fabiangreffrath** [comment]
You seem to mix up the concepts of building and installing (or maybe we did in the past and fixed that now): Building just creates the executable. 

You may want to call the install rule like this:
```
make install/strip DESTDIR=/tmp/whatever
```
with `DESTDIR` pionting to wherever you would like your package to end up.

**Comment by MrAlaux** [comment]
Seems like I got it working now, surprisingly without asking any more questions.

I'm still confused regarding why `mingw32-make` all by itself would provide the libraries back then and not anymore, but as I said, my experience is pretty much null, and the procedure is working now anyways, so it remains as just a matter of curiosity.

Thank you!

**Comment by fabiangreffrath** [comment]
Glad you got it working! To provide some background: We changed the way library dependencies were handled in environments that already provide these libraries themselves. Before, we would download all SDL libraries and even ZLib no matter what - now we only do this for MSVC and when cross-compiling from Linux to Windows. When the libraries are not downloaded, e.g. in MSYS2, the depending libraries are determined at install time and installed alongside the executable. But that latter step is strictly not part of the "build" process.

**Comment by fabiangreffrath** [comment]
As a final comment on this: You may want to revert this commit and replace the `NOT MSYS` part with something else:
https://github.com/fabiangreffrath/woof/commit/8629c1072bb1d3bbf791bd20d0c97e39385931f1
