### ISSUE TITLE
[Feature] Automatic Complevel based on PWAD's demo lump format

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#477]
I'm not entirely sure how doable this is, but I think this could be a killer feature to have for Woof. If I recall correctly, Woof (and similar ports) automatically sets a complevel during demo playback so that it plays back properly, so what's to say that couldn't also be applied when loading into a live game?

**Comment by rfomin** [comment]
The problem with this approach is that many PWADs don't have demos or have demos in wrong complevel, including many of the most popular ones (Goin Down, Eviternity - complevel 17, Dimension of the Boomed
 - complevel 11).

**Comment by fabiangreffrath** [comment]
Indeed, this wouldn't make things necessarily easier. As @rfomin (good to see you back!) already pointed out, e.g. Eviternity ships demos in PrBoom+'s own format. And even if we would just count them as MBF-format demos, there would be just one more place to set the demo format in addition to General menu and command line (and demo headers on playback, of course).

**Comment by fabiangreffrath** [comment]
I guess it's clear that we won't change complevel based on guessing from the format of embedded demo lumps. Also, we already have the menu switch, the command line switch, the COMPLVL lump and the actual demo header to determine which complevel to use.
