### ISSUE TITLE
emulate INTERCEPTS overflow for demo_version 109

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#493]
There are quite some Vanilla glitches that we do not emulate yet, most notably probably the INTERCEPTS overrun (but there are others as well like the donut overrun or the playingame overrun). In fact this is used as a mapping trick and required to finish e.g. Not Even Remotely Fair - Episode 1, MAP31: https://www.youtube.com/watch?v=FTq0-FvBSlE&t=3387s

Some more background on this glitch is provided here:
https://www.youtube.com/watch?v=-IYfwCWZeD0

**Comment by rfomin** [comment]
Interestingly, PrBoom+ disabled this emulation by default, and I didn't find a demo with it in the DSDA archive. Anyway, I would like to implement this.

**Comment by fabiangreffrath** [comment]
>  Anyway, I would like to implement this.

Alright, please go for it. 🚀

**Comment by fabiangreffrath** [comment]
This might be relevant: https://github.com/kraflab/dsda-doom/commit/fac8020a5e992ecc8c3f49125bc1913f97637256

**Comment by cyberdemon2004** [comment]
> ~This might be relevant: [kraflab/dsda-doom@fac8020](https://github.com/kraflab/dsda-doom/commit/fac8020a5e992ecc8c3f49125bc1913f97637256)~
> 
> Edit: turns out it's not

Can I please ask you a question ?

**Comment by cyberdemon2004** [comment]
> There are quite some Vanilla glitches that we do not emulate yet, most notably probably the INTERCEPTS overrun (but there are others as well like the donut overrun or the playingame overrun). In fact this is used as a mapping trick and required to finish e.g. Not Even Remotely Fair - Episode 1, MAP31: https://www.youtube.com/watch?v=FTq0-FvBSlE&t=3387s
> 
> Some more background on this glitch is provided here: https://www.youtube.com/watch?v=-IYfwCWZeD0

Can I please ask you a question ?

**Comment by fabiangreffrath** [comment]
> Can I please ask you a question ?

Well, I'd say you already did right now. 😁 

Sure, what's your question.

**Comment by cyberdemon2004** [comment]
> > Can I please ask you a question ?
> 
> Well, I'd say you already did right now. 😁
> 
> Sure, what's your question.

In Prboom plus, in emulation settings, when we turn *try to emulate intercepts overflow to NO,* will it permenantly remove all ghosts glitch even if we play a wad on complevel 2 ?

**Comment by rfomin** [comment]
> In Prboom plus, in emulation settings, when we turn _try to emulate intercepts overflow to NO,_ will it permenantly remove all ghosts glitch even if we play a wad on complevel 2 ?

Yes, it will remove it. For test you can try http://classicdoom.com/odddemos.htm#manorbug demo.

**Comment by cyberdemon2004** [comment]
> > In Prboom plus, in emulation settings, when we turn _try to emulate intercepts overflow to NO,_ will it permenantly remove all ghosts glitch even if we play a wad on complevel 2 ?
> 
> Yes, it will remove it. For test you can try http://classicdoom.com/odddemos.htm#manorbug demo.

Will it *entirely* remove INTERCEPTS limit ?

**Comment by rfomin** [comment]
> Will it _entirely_ remove INTERCEPTS limit ?

Yes, I think so, based on this function: https://github.com/Doom-Utils/historic-ports/blob/3ae2d25740b9d4ea896f0fde0c73f6b112135ce5/p_maputl.c#L426 But I'm not sure.

**Comment by fabiangreffrath** [comment]
Hard to believe that PrBoom+ will let you get away without emulating the INTERCEPTS overflow glitch when recording a complevel 2-4 demo.

**Comment by kraflab** [comment]
> Hard to believe that PrBoom+ will let you get away without emulating the INTERCEPTS overflow glitch when recording a complevel 2-4 demo.

In fact, demos that rely on an intercepts overflow aren't even legal for speedrunning.

**Comment by cyberdemon2004** [comment]
> Hard to believe that PrBoom+ will let you get away without emulating the INTERCEPTS overflow glitch when recording a complevel 2-4 demo.

Are you sure that the setting set to no, will entirely remove the intercepts limit ?

**Comment by cyberdemon2004** [comment]
> Hard to believe that PrBoom+ will let you get away without emulating the INTERCEPTS overflow glitch when recording a complevel 2-4 demo.

If the setting is set to no, will it entirely remove the intercepts limit ? I just wanted to confirm from you, because you are the maintainer of this source port.

**Comment by fabiangreffrath** [comment]
I'd rather say I am the only one left who has (1) commit rights to the main repository and (2) not completely lost interest in this port. Still, I don't know every line of code in it.

Anyway, why don't you just try it out. Examples have been given and there is even a test map available here called intercepts.wad:

https://github.com/fabiangreffrath/test-wads

Please don't let others do your research...

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/2fd4678a2ba609306fd590a0137792f7a1ea6df5

**Comment by fabiangreffrath** [comment]
> In fact, demos that rely on an intercepts overflow aren't even legal for speedrunning.

So, if an intercepts overflow occurs in a complevel 2 demo, but the emulation has been disabled, would you accept this demo, although it would desync in every other port that enables the glitch?

**Comment by fabiangreffrath** [comment]
> If the setting is set to no, will it entirely remove the intercepts limit ? I just wanted to confirm from you, because you are the maintainer of this source port.

While at it, the answer is "yes". The glitch is entirely disabled, but the following is printed to stderr:

```
INTERCEPT overflow has been detected. The option responsible for emulation of this overflow is switched off hence desync or crash can occur soon or during playback with the vanilla engine in case you're recording demo.
You can change PrBoom behaviour for this overflow through in-game menu.
```

**Comment by cyberdemon2004** [comment]
> 

Ok. Thank you so much. 
It doesn't crash on my computer.

**Comment by kraflab** [comment]
> So, if an intercepts overflow occurs in a complevel 2 demo, but the emulation has been disabled, would you accept this demo, although it would desync in every other port that enables the glitch?

That's correct. The same would go for a demo that breaks any other limits (hence cl2 being "limit-removing" compatibility). There are plenty of demos like this on dsda.

**Comment by fabiangreffrath** [comment]
Hm, so, maybe a third page for the Compatibility menu is due. 🤔

**Comment by rfomin** [comment]
> Hm, so, maybe a third page for the Compatibility menu is due.

I think that most users will expect Crispy's behavior in this aspect. Personally, I don't like this glitch, but if people even make maps around it, maybe it's okay.

**Comment by cyberdemon2004** [comment]
> > Hm, so, maybe a third page for the Compatibility menu is due.
> 
> I think that most users will expect Crispy's behavior in this aspect. Personally, I don't like this glitch, but if people even make maps around it, maybe it's okay.

Yes, that glitch is just bullshit. I hate it a lot.

**Comment by fabiangreffrath** [comment]
> I think that most users will expect Crispy's behavior in this aspect. Personally, I don't like this glitch, but if people even make maps around it, maybe it's okay.

What Ryan said got me thinking. Just as complevel 11 isn't *exactly* MBF, what if we consider complevel Vanilla as actually limit-removing Vanilla.

Although this isn't strictly a subjective decision (as in "I don't like this glitch, we shouldn't emulate it"), we should probably leave a choice to the user and provide sensible defaults.

**Comment by cyberdemon2004** [comment]
> > I think that most users will expect Crispy's behavior in this aspect. Personally, I don't like this glitch, but if people even make maps around it, maybe it's okay.
> 
> What Ryan said got me thinking. Just as complevel 11 isn't _exactly_ MBF, what if we consider complevel Vanilla as actually limit-removing Vanilla.
> 
> Although this isn't strictly a subjective decision (as in "I don't like this glitch, we shouldn't emulate it"), we should probably leave a choice to the user and provide sensible defaults.

What you said is 100% true and BTW, why don't you provide a choice or a setting in Crispy Doom source port to emulate the intercepts overflow to *Yes* or *No.*

**Comment by rfomin** [comment]
I think there are two approaches: PrBoom+, which has huge menus with all possible options, and Crispy, which tries to make it more elegant and easier to use. I think Woof should follow Crispy on this one.

**Comment by fabiangreffrath** [comment]
> What you said is 100% true and BTW, why don't you provide a choice or a setting in Crispy Doom source port to emulate the intercepts overflow to _Yes_ or _No._

Because Crispy is not about complevels, it is strictly Vanilla and will simply not crash anymore when limits are exceeded.

> I think there are two approaches: PrBoom+, which has huge menus with all possible options, and Crispy, which tries to make it more elegant and easier to use. I think Woof should follow Crispy on this one.

Definitely yes. Anyway, I'll submit a PR soon and then we can discuss in detail.

**Comment by cyberdemon2004** [comment]
> > What you said is 100% true and BTW, why don't you provide a choice or a setting in Crispy Doom source port to emulate the intercepts overflow to _Yes_ or _No._
> 
> Because Crispy is not about complevels, it is strictly Vanilla and will simply not crash anymore when limits are exceeded.

Ok. Fine. But please don't remove that *intercept overflow setting* from Prboom plus.
> 
> > I think there are two approaches: PrBoom+, which has huge menus with all possible options, and Crispy, which tries to make it more elegant and easier to use. I think Woof should follow Crispy on this one.
> 
> Definitely yes. Anyway, I'll submit a PR soon and then we can discuss in detail.

**Comment by fabiangreffrath** [comment]
BTW, intercepts overflow emulation is *enabled* by default in PrBoom+:
https://github.com/coelckers/prboom-plus/blob/784a17d73818cffa4ec3114cef99bcc990d157f4/prboom2/src/m_misc.c#L1198

**Comment by rfomin** [comment]
> BTW, intercepts overflow emulation is _enabled_ by default in PrBoom+: https://github.com/coelckers/prboom-plus/blob/784a17d73818cffa4ec3114cef99bcc990d157f4/prboom2/src/m_misc.c#L1198

Yes, my bad, it's disabled in my config. I didn't know about the speedrunner rule and assumed it was disabled by default.

**Comment by fabiangreffrath** [comment]
Me neither, and I am glad we have a choice now.

**Comment by cyberdemon2004** [comment]
> > BTW, intercepts overflow emulation is _enabled_ by default in PrBoom+: https://github.com/coelckers/prboom-plus/blob/784a17d73818cffa4ec3114cef99bcc990d157f4/prboom2/src/m_misc.c#L1198
> 
> Yes, my bad, it's disabled in my config. I didn't know about the speedrunner rule and assumed it was disabled by default.

Yeah, its disabled even in my config. 😊😊👍🤘🏻
