### ISSUE TITLE
[Suggestion] Relpace FindIWADFile and CheckIWAD

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#498]
I suggest replacing `FindIWADFile` and `CheckIWAD` with the Crispy/Choco counterparts from `d_iwad.c`. These functions are required for the multiplayer launcher but are very difficult to read/maintain and buggy. This is my Windows output for the wrong -iwad option:
```
Looking in .
Looking in .
Looking in C:\Users\User
Looking in \doom2
Looking in \plutonia
Looking in \tnt
Looking in \doom_se
Looking in \doom
Looking in \dooms
Looking in \doomsw
Looking in C:\Users\User
IWAD not found
```
Obviously there is a bug in `FindIWADFile`, but it's much easier to write a new function than to modify it. These functions should be trivial.

**Comment by mikeday0** [comment]
On a related topic, it would definitely be appreciated if you ported over the choco/crispy case-insensitive iwad filename matching. Seems like Woof has that for pwads but not iwads.

**Comment by fabiangreffrath** [comment]
I think this would come along with the changes that @rfomin is going to suggest/submit?

In general, while I was very reluctant in the early stages (and sometimes still am), I think the project is now mature and stable enough that I could live with bigger code changes / deviations from the MBF code base like this.

**Comment by fabiangreffrath** [comment]
> On a related topic, it would definitely be appreciated if you ported over the choco/crispy case-insensitive iwad filename matching. Seems like Woof has that for pwads but not iwads.

Please report any such inconveniences, thanks!
