### ISSUE TITLE
fails to identify renamed DOOM2.WAD as Doom 2

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#512]
I have an "alternative" DOOM2.WAD (actually minIWAD) that's called D2.WAD and that I use for testing purposes. However, after the recent changes to IWAD discovery, Woof fails to recognize it as a valid "commercial" gamemode IWAD. Surprisingly, Crispy still gets this right, so there is probably something missing.

**Comment by fabiangreffrath** [comment]
This code is missing:
https://github.com/fabiangreffrath/crispy-doom/blob/ae222fb9bccf7fc06c738139ace4934a45e813bf/src/doom/d_main.c#L900

**Comment by rfomin** [comment]
In Woof we load all PWADs and IWAD combined here: https://github.com/fabiangreffrath/woof/blob/d95f990fc1be810056c55fa1c8ac71514f2ffdee/Source/d_main.c#L1976
So it's not very convenient to check here. We can restore the old `CheckIWAD` but rewrite it for readability.

**Comment by fabiangreffrath** [comment]
We could load and check the contents of the file only if `gmode` is still undetermined at the end of the loop in `CheckIWAD()`.

**Comment by fabiangreffrath** [comment]
> So it's not very convenient to check here. We can restore the old `CheckIWAD` but rewrite it for readability.

Would you like to do this or should I?

**Comment by rfomin** [comment]
> > So it's not very convenient to check here. We can restore the old `CheckIWAD` but rewrite it for readability.
> 
> Would you like to do this or should I?

As you wish, I'm a little busy right now.

**Comment by NightFright2k19** [comment]
Out of curiosity, what does this "mini IWAD" look like? doom2.wad without the maps, so it only works if you load pwads with it?

**Comment by fabiangreffrath** [comment]
> Out of curiosity, what does this "mini IWAD" look like? doom2.wad without the maps, so it only works if you load pwads with it?

This is it:
https://github.com/fragglet/miniwad
