### ISSUE TITLE
[Bug] Episode ending in UMAPINFO

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#517]
Using latest Woof Github snapshot (x64).

Not sure if I am doing something wrong here or not, but when trying to end a custom episode early via UMAPINFO, it doesn't matter which option I am using, I always get an ep.1 ending screen saying "The End".

I tried placing a umapinfo.lmp into the doom.2wad autoload folder with this code:
```
MAP MAP01
{
	episode = "Attack"
	levelname = "Attack"
	levelpic = "CWILV00"
	skytexture = "SKY1"
	music = "D_RUNNIN"
	partime = 30
	endcast = true
}
```
Besides the fact the episode name stays empty, after ending the first map, you get this "The End" screen, regardless whether you use endcast, endgame, endpic or whatever. 

I tried with these instead of endcast = true:
endgame = true
endpic = "CREDIT"

**Comment by rfomin** [comment]
You should add intermission text.
```
map MAP01
{
	intertext = "some text"
	endcast = true
}
```

**Comment by NightFright2k19** [comment]
Hmm, alright. But if I do it like this:
```
map MAP01
{
	intertext = ""
	endcast = true
}
```
the only thing that changes is that it doesn't show "The End". I still wouldn't get any cast call, end pic display or whatever. I am almost sure that used to work better in earlier versions of Woof unless I remember badly.

**Comment by rfomin** [comment]
Just tested with latest master:

https://user-images.githubusercontent.com/5077629/163350064-57109a09-2d5a-49a4-a6f4-df0e0463d564.mp4

**Comment by NightFright2k19** [comment]
OK, then apparently there will be that intermission background first, regardless what you do and you have to do a mouseclick first before the actual ending appears. Good to know.

**Comment by fabiangreffrath** [comment]
Does it behave the same in current prboom-plus master?

**Comment by NightFright2k19** [comment]
Yes, it's the same.

**Comment by fabiangreffrath** [comment]
Then it's good. In this case, consistency is more important than plausibility. 😉
