### ISSUE TITLE
[Bug] UMAPINFO: endgame=true crashes Doom II

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#521]
Tested with: Latest Github master (Apr 14, 2022)

When using endgame=true in UMAPINFO while playing Doom 2, Woof! crashes to desktop with this message:
`W_GetNumForName: HELP2 not found!`
(HELP2 does not exist in doom2.wad, plutonia.wad or tnt.wad, there is only the HELP lump.)

UMAPINFO code:
```
MAP MAP01
{
	intertext = ""
	interbackdrop = "CREDIT"
	endgame = true
}
```

To reproduce:
- Place attached umapinfo.lmp into autoload\doom2.wad: [umapinfo.txt](https://github.com/fabiangreffrath/woof/files/8513543/umapinfo.txt)
- Launch Doom 2, start a new game
- Reach the end of MAP01
- CREDIT screen will appear first, then when pressing LMB, crash will occur

**Comment by rfomin** [comment]
It works if you set `endpic`
```
MAP MAP01
{
	intertext = ""
	interbackdrop = "CREDIT"
	endpic = "CREDIT"
}
```
`endgame` shows the default episode ending, which is not set for Doom 2.

**Comment by NightFright2k19** [comment]
I am aware of it. However, according to [wiki](https://doomwiki.org/wiki/UMAPINFO), engame = true is supposed to do this:

"Ends the game after this level, showing the default post-game screen for the current episode. Skips the 'entering level' screen."

My assumption was that either of the following entries can be used to end the game:
endgame
endpic
endbunny
endcast

While endbunny is clearly meant for Doom 1 only, I would assume all the others should work in Doom 2 as well. I think for Doom 2, endgame should default to HELP, not HELP2.

**Comment by rfomin** [comment]
> A crash to desktop could still be avoided for this rather minor issue, so redirecting to HELP for non-Doom 1 iwads might be something worth considering.

Technically it's not a crash, just an error message with exit. Okay, but I think it's better to show the CREDIT lump.

**Comment by NightFright2k19** [comment]
Pointing both interbackdrop and endpic to the CREDIT lump is definitely the better solution and that's what I am actually going for. I found this while trying the other options in order to see what the result would be.

**Comment by NightFright2k19** [comment]
Thanks for the pull request. That'll do it.
