### ISSUE TITLE
[bug] ARMS numbers don't display properly

### ISSUE THREAD

**Issue by dmslr** [fabiangreffrath/woof#539]
![doom00](https://user-images.githubusercontent.com/101458306/166465891-bfb5b62e-8712-4219-aab5-2b9c5c7a11ee.png)
The ARMS numbers should appear normally like the ammo numbers. I tested Augher Zenith and it showed the numbers properly in PrBoom but not in Woof. Sorry, I don't have PrBoom's screenshot for comparison right now.

There are plenty of wads affected by this bug.

**Comment by rfomin** [comment]
Screenshot from DSDA-Doom:
![doom02](https://user-images.githubusercontent.com/5077629/166469335-57b8a191-b035-41be-9289-3af427ad0c38.png)
Hmm, could you clarify what the problem is?

**Comment by rfomin** [comment]
@fabiangreffrath this patch fixes it for me with no visible flaws:
```diff
--- a/Source/st_lib.c
+++ b/Source/st_lib.c
@@ -302,8 +302,8 @@ void STlib_updateMultIcon
       if (y - ST_Y < 0)
         I_Error("updateMultIcon: y - ST_Y < 0");
 
-      if (!st_crispyhud)
-      V_CopyRect(x + WIDESCREENDELTA, y-ST_Y, BG, w, h, x + WIDESCREENDELTA, y, FG);
+      //if (!st_crispyhud)
+      //V_CopyRect(x + WIDESCREENDELTA, y-ST_Y, BG, w, h, x + WIDESCREENDELTA, y, FG);
     }
     if (*mi->inum != -1)  // killough 2/16/98: redraw only if != -1
       V_DrawPatch(mi->x, mi->y, FG, mi->p[*mi->inum]);
```
Is there something wrong with this `V_CopyRect`?

**Comment by fabiangreffrath** [comment]
Hm, if there was something generally wrong with that code, that would apply to all WADs, not only Augher Zenith. Before I introduced the Crispy HUD, the line in question was called unconditionally, so I guess it's unrealted to that feature.
