### ISSUE TITLE
Replace non-free embedded lumps 

### ISSUE THREAD

**Issue by fragglet** [fabiangreffrath/woof#54]
MBF included a bunch of embedded lumps which are definitely not free.

As a brief summary:

* Lumps using the Doom font: M_AUTO, M_CHAT, M_COMPAT, M_ENEM, M_GENERL, M_HORSEN, M_KEYBND, M_MESS, M_NMARE, M_SETUP, M_STAT, M_VERSEN, M_WEAP. The Freedoom versions would probably work as reasonable stand-ins.
* The dog sprites are from Wolfenstein 3D: DOGS*. ZDoom has a [free dog sprite set](https://forum.zdoom.org/viewtopic.php?f=59&t=58035) now that is CC licensed.
* Dog sound effects - unsure the provenance of these. Probably there are some public domain sounds out there that can be used.
* DSGETPOW, STBAR, STCFN096, STTMINUS, WIMINUS. I think these were not present in the Doom 1.1 IWAD and MBF included them as a pedantic compatibility measure so that you could play with any IWAD. Maybe it's not worth bothering to keep that compatibility?
* PLS1* and PLS2* - beta sprites. Move to betagrph.wad and embed some from Freedoom?

**Comment by fabiangreffrath** [comment]
> MBF included a bunch of embedded lumps which are definitely not free.

Thanks for bringing this up!

I knew about the embedded non-free stuff but somehow pushed this out of my mind. In hindsight, they were the reason why I started my own Doom source port project from Chocolate Doom instead of WinMBF.

>     * Lumps using the Doom font: M_AUTO, M_CHAT, M_COMPAT, M_ENEM, M_GENERL, M_HORSEN, M_KEYBND, M_MESS, M_NMARE, M_SETUP, M_STAT, M_VERSEN, M_WEAP. The Freedoom versions would probably work as reasonable stand-ins.

I'll probably remove them altogether and let the Options menu render in the HU font.

>     * The dog sprites are from Wolfenstein 3D: DOGS*. ZDoom has a [free dog sprite set](https://forum.zdoom.org/viewtopic.php?f=59&t=58035) now that is CC licensed.

These are neat replacements! I'll try to digitize them and replace the internal sprites.

>     * Dog sound effects - unsure the provenance of these. Probably there are some public domain sounds out there that can be used.

Do we have dog sounds in Freedoom?

>     * DSGETPOW, STBAR, STCFN096, STTMINUS, WIMINUS. I think these were not present in the Doom 1.1 IWAD and MBF included them as a pedantic compatibility measure so that you could play with any IWAD. Maybe it's not worth bothering to keep that compatibility?

I think I'll remove them altogether.

>     * PLS1* and PLS2* - beta sprites. Move to betagrph.wad and embed some from Freedoom?

I'll probably replace these with the regular plasma ball sprites from Freedoom,

**Comment by fabiangreffrath** [comment]
Cleaned up in the https://github.com/fabiangreffrath/woof/tree/nonfree branch except for the dogs sprites and sounds and the beta sprites.

**Comment by fabiangreffrath** [comment]
Fun fact: The embedded sprites `pls1a0` and `pls1c0`, `pls1b0` and `pls1d0`, `pls1e0` and `pls1f0` are pairwise identical!

**Comment by fabiangreffrath** [comment]
I'll probably replace the sprites with pendants from FreeDoom like this:
PLS1A0, PLS1C0 -> APLSA0
PLS1B0, PLS1D0 -> APLSB0
PLS1E0, PLS1F0 -> APBXC0
PLS1G0 -> APBXD0

PLS2A0 -> PLSSA0
PLS2B0 -> PLSSB0
PLS2C0 -> PLSEA0
PLS2D0 -> PLSEC0
PLS2E0 -> PLSED0
