### ISSUE TITLE
[Feature/Bug] UMAPINFO endpic behavior with secret levels

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#541]
[I thought this had been addressed before](https://github.com/fabiangreffrath/woof/pull/520), but apparently there are still issues in very latest Woof dev snapshots:

In ["Flashback to Hell"](https://www.doomworld.com/idgames/levels/doom2/Ports/d-f/fth666), you go to MAP31 automatically when ending MAP15 (only has secret exit). In MAP31, you have the choice between the regular exit and a secret one.

I wanted to make it so that the game ends when taking the normal exit in MAP31 and continue if you find the secret exit. **It also will not work if you add `nextsecret = "MAP32"` to the MAP31 definitions.**

UMAPINFO code used:
```
MAP MAP31
{
	endpic = "CREDIT"
	intertext = "", "", "", "", "", "", "", "Thank you for playing Flashback to Hell!"
}

MAP MAP32
{
	endpic = "CREDIT"
	interbackdrop = "CREDIT"
	intertext = "", "", "", "", "", "", "", "Thank you for playing Flashback to Hell!"
}
```
Expected outcome: 
The endpic part in MAP31 should only take effect if you take the normal exit.

Actual outcome:
The game ends either way, i.e. you won't be able to get to the secret level. Only difference is that the "You found the super secret level" text is shown when taking the secret exit, but then the game ends.

Suggested solution:
Always continue the game when entering the secret exit (since it can be assumed there's always something after that). Unless this is a limitation of UMAPINFO which currently can't be changed without adjusting the standard itself.

**Comment by fabiangreffrath** [comment]
Does it work as intended with the latest PrBoom+ master?

**Comment by NightFright2k19** [comment]
No. When omitting endpic, actually both exits lead to the secret level, which is even weirder. When it's in place, both exits end the game.

**Comment by fabiangreffrath** [comment]
Probably because this line doesn't check for `secretexit`:
https://github.com/fabiangreffrath/woof/blob/c27abe130028e909c100934a9e684f0217b5da8c/Source/g_game.c#L1101

**Comment by NightFright2k19** [comment]
Works as expected now. Thumbs up!
