### ISSUE TITLE
[Feature] Same sound limiter

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#546]
DSDA-Doom has a feature that could also be useful for this project: Due to an optional limiter of identical sounds, situations where your eardrums are raped by a cacophony of simultaneously played sounds are avoided.

This can happen when waking up many identical enemies at once or in areas with excessive usage of moving pistons with mechanical sounds. I had a level recently that got so loud because of that I had to almost turn volume down to 0. A sound limiter could work wonders here.

**Comment by fabiangreffrath** [comment]
There is still a glitch in the current implementation that I'd rather like to see fixed before porting this over: 

https://www.doomworld.com/forum/topic/118074-dsda-doom-source-port-v0243/?page=37&tab=comments#comment-2451596

**Comment by fabiangreffrath** [comment]
I'd like to get away with a simple on/off switch for this, so I am looking for the most reasonable defaults for the `limit` and `window` settings. I guess this would be a good start:

```c
dsda_parallel_sfx_limit = 8
dsda_parallel_sfx_window = 1
```

Also, I'd like to call it something like "Prevent Sound Overdrives".

What do you think @kraflab?

**Comment by kraflab** [comment]
I'm not sure there's an obvious default for the count because it depends on the user's ear preferences 😄

You could ask on the discord for what number people like. I think Daerik experimented with this quite a bit.

**Comment by fabiangreffrath** [comment]
I'd also like to hear @jackrjli's opinion on this.

**Comment by jackrjli** [comment]
I'd set the window higher than 1 because a large crowd of monsters doesn't all wake up on the same tic when alerted. I haven't experimented too much with different values, but personally I use 4 and 4.

**Comment by fabiangreffrath** [comment]
> You could ask on the discord for what number people like. I think Daerik experimented with this quite a bit.

I asked in the dsda-doom channel, but couldn't find Daerik there. 🤷

**Comment by fabiangreffrath** [comment]
@jackrjli Could you check if these settings work for you as well? 

```
sound channels: 16
limit: 2
window: 4
```

**Comment by jackrjli** [comment]
> @jackrjli Could you check if these settings work for you as well?
> 
> ```
> sound channels: 16
> limit: 2
> window: 4
> ```

Those settings work pretty well for me.
