### ISSUE TITLE
add SPECHITS cheat from Crispy

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#552]
I'd like to port over my favorite cheat code from Crispy Doom, "SPECHITS", which triggers all possible linedef and boss death specials available on a map all at once. Will require a bit more than a straight port because of general linedefs and UMAPINFO support in Woof.

**Comment by rfomin** [comment]
My favorite cheat from Crispy is "GOOBERS", but I guess it's not relevant here. :wink:
