### ISSUE TITLE
Weapon Recoil pitch not in sync with weapon rate of fire

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/woof#556]
### Background

I nicked the template from Crispy cause it's a good one.
Also commented about this on Doomworld, thought I'd put in an issue on Github as well.

Version of Woof: built locally from [e3d9f90](https://github.com/fabiangreffrath/woof/commit/e3d9f90e491bc96b9a25179e27e3b8d7a91daf18)

Operating System and version: Windows 10 (32-bit)

Any loaded WADs and mods (please include full command line): N/a

### Bug description

Observed behavior: if weapon recoil pitch is turned on, some weapons (the effect is noticeable especially when using the rocket launcher or the BFG) don't align/ sync their recoil effect with their actual rate of fire, resulting in the rocket launcher recoiling constantly, while firing once for every ~5 recoils.
Don't have the time right now, but maybe I can record the issue and upload it somewhere to better illustrate. Still, I think it's pretty noticeable.

Expected behavior: compare with Crispy Doom, which doesn't have this issue.

**Comment by fabiangreffrath** [comment]
I think the call in `P_SpawnPlayerMissile()` is too much:

```patch
--- a/Source/p_mobj.c
+++ b/Source/p_mobj.c
@@ -1449,8 +1449,6 @@ mobj_t* P_SpawnPlayerMissile(mobj_t* source,mobjtype_t type)
   // [FG] suppress interpolation of player missiles for the first tic
   th->interp = -1;
 
-  A_Recoil(source->player);
-
   // mbf21: return missile if it's ok
   return P_CheckMissileSpawn(th) ? th : NULL;
 }
```

**Comment by fabiangreffrath** [comment]
I've kept it and solved the issue differently. I want the recoil to happen when the missile leaves the weapon, and not when the atatcking state is entered.
