### ISSUE TITLE
Uncapped Framerate

### ISSUE THREAD

**Issue by AlexMax** [fabiangreffrath/woof#57]
Would you like this feature for this port?

**Comment by fabiangreffrath** [comment]
Thank you very much for the suggestion, but I am afraid I have to decline - at least for now. My current subjective for this port is to bring "the MBF experience" to modern systems. I try to remain as faithful as possible while fixing as much as necessary. This is a very thin line already.

However, advanced features like uncapped framerate are currently out of scope. I need to iron the stability and usability issues out first. Nevertheless, if you feel like it, feel free to open a pull request. :wink:

**Comment by fabiangreffrath** [comment]
I'd rather close this now, as this really isn't a feature goal for this port. But thank you anyway!

**Comment by fabiangreffrath** [comment]
@AlexMax If you feel too bored and still have interest in this, I'd like to see what you come up with. I cannot promise that I will apply your approach but I can promise that I will review it thoroughly. Deal?

**Comment by AlexMax** [comment]
I appreciate the thought, however I have gotten sucked back into Odamex, so my attention is currently elsewhere.

However, if I did, my approach would be that I would essentially just transplant the code I wrote for Crispy into this port to the best of my ability.  I think that anybody who was looking for `crispy_uncapped` in Crispy Doom could probably do the same thing.

**Comment by fabiangreffrath** [comment]
I see, thanks! No problem and good luck with your projects. 😉
