### ISSUE TITLE
[Feature/ Suggestion] Misc. features from Crispy Doom (colorized messages/ separate translucency)

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/woof#573]
Here's two relatively minor things that I like about Crispy Doom and would also fit nicely here.
The first is colorized messages (e.g.: when picking up the blue key, the "blue" word from the pickup message is colored in blue).
I think this fits great, especially with the other message options.
The second one is only partially related to Crispy Doom: separate translucency. 
There are some WADs that integrate translucent textures into their combat design, but projectile translucency (or item/ sprite translucency) looks off to me, so a toggle between translucent textures (walls, flats), items & projectiles or both would be nice.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/47d7d229402ae8699826f47dfeef78c8b31538b0
https://github.com/fabiangreffrath/woof/commit/6e545bea62294d4b9375d853927b4fdfe53a3248
