### ISSUE TITLE
fix occasional random crashes (probably related to the sound system)

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#58]
the currently sound implementation in `Source/i_sound.c` is cryptic to me and I suspect it to be the cause for some of the apparently random occasional crashes. It may be best to port over the relevant parts (i.e. not libsamplerate, for example) of `src/i_sdlsound.c` from Chocolate Doom.

**Comment by fabiangreffrath** [comment]
Let's wait until this is resolved:
https://github.com/chocolate-doom/chocolate-doom/pull/1246

**Comment by fabiangreffrath** [comment]
Let's first see if the sound system is *really* the culprit for the occasional andom crashes...

**Comment by JNechaevsky** [comment]
How often crashes are happening? Any possible ways to reproduce it (is `-timedemo` will work as an possible automation)? And of course, what `gdb` saying?

**Comment by fabiangreffrath** [comment]
It's hard to tell. Crashes may appear twice in a row and then none for the next hour or so. It *should* be possible to reproduce one within a time demo, at least as long as all frames are drawn and all sounds are played. Unfortunately, I have never caught any of them in GDB, else I would be a lot wiser...

**Comment by fabiangreffrath** [comment]
The culprit is definitely in this line in `i_sound.c:I_SDLUpdateSound()`:
```
         // Get the raw data from the channel. 
         // Sounds are now prefiltered.
         sample = *(channelinfo[chan].data);
```

It must be a racing condition with `stopchan()`. because `channelinfo[chan].data` is `NULL` at the time if the crash, although this exact case is checked for just two lines earlier.

Commenting out this block of code gets rid of the crashes, but as i understand the code, will also break stereo separation during sound updates.
