### ISSUE TITLE
mouse wheel behaviour in automap

### ISSUE THREAD

**Issue by liPillON** [fabiangreffrath/woof#580]
Hi! I'm experiencing a weird behaviour of the automap zooming feature.

**Test Setup**
1) download a Woof build for Windows (I've tested both the latest 9.0.0 win32 release and [this](https://github.com/fabiangreffrath/woof/actions/runs/2448035814) win64 devbuild)
2) unzip the build to a dedicated folder and copy any supported iwad to the same folder (I've used [DOOM2.WAD](https://doomwiki.org/wiki/DOOM2.WAD#Latest_versions_of_Doom_II))
3) launch woof.exe and go to the "setup > key bindings > automap" menu page
4) bind the zoom in/out functions to the mouse wheel as in the attached image

![woof-settings-ui-compare](https://user-images.githubusercontent.com/48625273/172602876-8ffc9077-b590-4c59-9656-64436d0f78a6.png)

**Expected Behaviour**
this is what I get in a similar test case performed on dsda-doom or gzdoom
this is also what generally happens in windows applications that implement CTRL+MWHEEL page/document zooming

- when pressing the "I" key, the automap will be ENLARGED
- when pressing the "O" key, the automap will be REDUCED
- when scrolling the mouse wheel UP, the automap will be ENLARGED
- when scrolling the mouse wheel DOWN, the automap will be REDUCED

**Observed Behaviour**
- when pressing the "I" key, the automap is being ENLARGED
- when pressing the "O" key, the automap is being REDUCED
- when scrolling the mouse wheel UP, the automap is being REDUCED
- when scrolling the mouse wheel DOWN, the automap is being ENLARGED

It seems that the mouse wheel input is not interpreted correctly

**Configuration Files**
Here they are: [woof-issue-automap-mwheel.zip](https://github.com/fabiangreffrath/woof/files/8860894/woof-issue-automap-mwheel.zip)

**Comment by fabiangreffrath** [comment]
Indeed, seems like `M2_ZOOMIN` and `M2_ZOOMOUT` play switched roles in this part of the code:

https://github.com/fabiangreffrath/woof/blob/7de70f2e8bfdb746eb071de338639493100400b8/Source/am_map.c#L777-L790
