### ISSUE TITLE
woof-setup.exe requires admin privileges

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#584]
Could we use the manifest file to tell stupid Windows that `woof-setup.exe` is not going to change anything relevant on the system, *although* it has "setup" in its name? 🤦

**Comment by fabiangreffrath** [comment]
```
$ ./build/Source/woof-setup.exe
-bash: ./build/Source/woof-setup.exe: Permission denied
```

**Comment by fabiangreffrath** [comment]
Seems the setup executable is still importing the wrong (i.e. the game executable's) manifest.

**Comment by rfomin** [comment]
I fixed it in master: https://github.com/fabiangreffrath/woof/commit/1e9de7b2f9f206522b8be327766bf3025c87a3db

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/1e9de7b2f9f206522b8be327766bf3025c87a3db
