### ISSUE TITLE
PSP port is possible? and/or on libretro? 😃 (Other platforms?)

### ISSUE THREAD

**Issue by DartPower** [fabiangreffrath/woof#588]
PSP port is possible? and/or on libretro? 😃 

About libretro some interesting info here
https://www.libretro.com/index.php/mission/
https://docs.libretro.com/development/cores/developing-cores/
https://www.libretro.com/index.php/powered-by-libretro/
https://docs.libretro.com/development/cores/opengl-cores/
https://github.com/libretro/libretro-prboom

Some info about PSP and sample repos:
https://github.com/pspdev
https://github.com/mwpenny/chocolate-doom-psp
https://github.com/derek57/psp-doom
https://github.com/z2442/PSPDoom

How about this idea(s)? 😅 
Or... maybe in future?

**Comment by fabiangreffrath** [comment]
If anyone wants to come up with a clean patch to support running on the PSP, they'd be welcome. I don't even own such a device.

Regarding libretro, AFAIUI all libretro cores are being developed and maintained as forks of the respective projects they are based upon. I don't see very much that this project could contribute to this.

**Comment by DartPower** [comment]
Okay. Thanks a lot for answer.
And. How about other platforms? Like consoles as homebrew, Android and/or other OS (e.g. SerenityOS, DJGPP (DOS)) for example?

**Comment by fabiangreffrath** [comment]
Same answer. If anyone wants to port this project to any other platform, they are welcome. Us developers use Linux, and Windows with MSVC and MinGW, so that's what we can work on ourselves.

**Comment by DartPower** [comment]
Okay thanks

**Comment by rfomin** [comment]
Personally, I'm interested in making a DOS port someday, but it won't be soon.
