### ISSUE TITLE
flexible arrangement of boom extended hud widgets 

### ISSUE THREAD

**Issue by liPillON** [fabiangreffrath/woof#593]
Since we're on a roll.. ;)

Would you consider the implementation of the attached hud layout feasible?
It's a custom prbhud lump I've made for DSDA, but I'm not implying that we need prbhud support in Woof. 
I just wish to replicate its features.

Thank you again for the time/energy you dedicate to this project.

![dsdahud-hud1-idkfa png 7dee8a2fa765e90a0dab23e5a6ae7e9c](https://user-images.githubusercontent.com/48625273/172884290-f59bcc0f-35a1-4adf-835d-ad5c2de8ef56.png)

**Comment by liPillON** [comment]
fair enough

I was just hoping for a couple of settings that would let users decide in which portion of the screen will be placed each hud element 

while we're talking about huds: what about adding labels to the crispy hud, just like International Doom does?

**Comment by fabiangreffrath** [comment]
> while we're talking about huds: what about adding labels to the crispy hud, just like International Doom does?

This would require embedding additional graphics based on the original IWAD assets and is thus out of question for this port.

**Comment by liPillON** [comment]
OK then

I'd keep the issue open in case anyone would want to chime in.
Feel free to close it whenever you want, though

Thank you!

**Comment by fabiangreffrath** [comment]
I'd like to tackle this issue next, i.e. introduce a new optional lump which contains coordinates for the HUD widgets in "compact" and "distributed" mode (mostly based on PrBoom+'s `-prbhud-` lump format). This is not that complicated by itself, but we currently have some sophisticated code to move around the HUD widgets if the "normal font" widgets (e.g. map title, map coordinates, separate K/I/S widgets) are visible and vice versa. The question is how to proceed with these, but this probably has time until the first draft is finished.

**Comment by rfomin** [comment]
> mostly based on PrBoom+'s `-prbhud-` lump format

How about the DSDA-Doom format? Although I don't know what the difference is.

**Comment by fabiangreffrath** [comment]
The prbhud format is simple, and I like that: It has different blocks, one for each HUD. Each block has a heading line with a counter (we would start to support 0 and 1, for compact and distributed). The following lines contain the widgets by name and their x and y coodinates.

The dsdahud format is a bit different.  The heading lines contain the name of the game and a variant that's either "ex", "off" or "full" (need to look up in the specs what that means). The following lines contain the widgets by their names (which do not match the names in code) and their x and y coordinates, but also an additional alignment keyword.

I'm not sure how much it adds over the simple prbhud format, but I like a syntax that I can immediately understand without having to refer to the specs. 😉 

https://github.com/coelckers/prboom-plus/blob/master/prboom2/data/lumps/-prbhud-.lmp
https://github.com/kraflab/dsda-doom/blob/master/prboom2/data/lumps/dsdahud.lmp

**Comment by liPillON** [comment]
a while after I've opened this issue @MrAlaux implemented something similar in Nugget Doom:
https://github.com/MrAlaux/Nugget-Doom/commits/master/docs/nughud.txt

**Comment by fabiangreffrath** [comment]
Yes, but that's somehow very specific to Nugget Doom, contains more than 100 key words and allows for mixing of HUD and Status Bar elements, etc. Not exactly my design goal...

**Comment by fabiangreffrath** [comment]
> move around the HUD widgets if the "normal font" widgets (e.g. map title, map coordinates, separate K/I/S widgets) are visible 

Strictly speaking, the separate K/I/S and level time widgets are redundant now that we have the corresponding compact widgets available even when the status bar is drawn. @rfomin You once suggested to remove them, maybe this would be the right occasion?

**Comment by rfomin** [comment]
> You once suggested to remove them, maybe this would be the right occasion?

Yes, sure.

**Comment by fabiangreffrath** [comment]
Alright. Remaining question is how to proceed with the coordinates widgets (which were already in MBF) and the FPS widget (which is the X coordinate widget reused).

**Comment by rfomin** [comment]
I think we should convert both the coordinate and FPS widget to the new style. And also, maybe, add the ability to choose a font for widgets?

**Comment by fabiangreffrath** [comment]
> I think we should convert both the coordinate and FPS widget to the new style. 

Yes! I think coordinates should be compacted into one line in the lower right corner (sorry, Lee Killough!). PFS counter should be separate in the upper right corner. 

> And also, maybe, add the ability to choose a font for widgets?

Indeed, I have also thought about this. I like how the K/I/S line looks in Crispy!

**Comment by fabiangreffrath** [comment]
I have spent the last ~2 weeks re-implementing the HUD widgets drawing routines in Woof, including a parser for a `WOOFHUD` lump format that contains coordinates for the widgets in compact and distributed mode - but I am still not satisfied with it. There are still too many exceptions and necessary recalculations for widescreen, status bar, automap with our without overlay, etc.

What I am aiming for is an entirely semantic positioning:

A widget defines its desired position, e.g. "bottom left", and then it gets drawn there. What the exact coordinates are depends on the boundary conditions, e.g. "bottom" has a different meaning when the status bar is drawn than when it's not. The next widget that wants to get drawn "bottom left" will be drawn one line above, etc. A problem that occurs is that positioning then depends on the order in which the widgets are drawn.

Another problem that still persists is horizontal positioning. Some widgets have a fixed maximum width that is reached with the IDKFA cheat, i.e. the ammo/armor/health/weapon/keys widgets. The others (i.e. monsec/coords/fps widgets) can have any width, so the exact x coordinate for e.g. "top right" is unknown until the widget is rendered. Things get even more complicated if we allow to choose between the small and normal HUD font.

**Comment by rfomin** [comment]
> I have spent the last ~2 weeks re-implementing the HUD widgets drawing routines in Woof...

Looks good! I have to admit that I haven't done anything in these weeks, hopefully I'll have more time next month.

> A problem that occurs is that positioning then depends on the order in which the widgets are drawn.

I think the position should depend on the order in which the widgets are defined in the `WOOFHUD` lump.

> Another problem that still persists is horizontal positioning...

As an alternative, I suggest simply setting the coordinates assuming 320x200 screen size. We have restricted internal resolution anyway.

**Comment by fabiangreffrath** [comment]
> Looks good!

I don't think so. Overlay mode is still a mess, for example. ☹️ 

> I think the position should depend on the order in which the widgets are defined in the `WOOFHUD` lump.

It's not that easy, unfortunately. In the automap we show the level title in the bottom left, so widgets in this corner need to get rearranged. If overlay mode is on, we show the level title and the whole mass of widgets. We show player messages in the top left corner, but there is also the multiple message lines feature which needs to be considered. On the intermission screen we show the level time in the top left corner, etc. There are so many exceptions from the rule...

> As an alternative, I suggest simply setting the coordinates assuming 320x200 screen size. We have restricted internal resolution anyway.

The problem arises if we want strictly right-aligned widgets as in @liPillON's screen shot. We can playce widgets on the right of the screen now, no problem, but they are still left-aligned but with an offset. For right alignment we need to determine the maximum pixel width of the widget, but this depends on the used font, and for some widgets it is strictly unknown. 😭 

For a start, things would be *a lot* easier if we just would draw the map title line in automap overlay mode. 🤔

**Comment by rfomin** [comment]
I mean that user will simply set coordinates for widgets and we don't care about alignments/overlays etc. In other words remove all dynamic positioning entirely.

**Comment by rfomin** [comment]
Another idea is to introduce modes in `WOOFHUD` so the user can separately set different coordinates for widgets in "fullsceen", "stbar", "overlay" and "automap" modes.

**Comment by fabiangreffrath** [comment]
> I mean that user will simply set coordinates for widgets and we don't care about alignments/offsets/overlays etc. In other words remove all dynamic positioning entirely.

Okay, so once the user passes a `WOOFHUD` lump we will use the coordinates set there no matter what? I think I like the idea. 🤔 

Should we keep the concept of two modes (`hud_distributed`) and two widgets groups (`hud_active > 1`)? I think it won't hurt.

**Comment by rfomin** [comment]
> Okay, so once the user passes a `WOOFHUD` lump we will use the coordinates set there no matter what? I think I like the idea.

Yes, but I'm assuming we still need left and right alignment to calculate the widescreen offset.
I suggest implementing 5 hud modes - `fullscreen`, `stbar`, `overlay_fullscreen`, `overlay_stbar`, `automap` so that the user can set the coordinates for each widget in any  mode. Something like `widget_name x, y, left|right [, font] [, color]`
```
overlay_fullscreen
map_title 0, 180, left, bold, gold
fps_widget 280, 10, right
```
But perhaps it's too complicated.

> Should we keep the concept of two modes (`hud_distributed`) and two widgets groups (`hud_active > 1`)? I think it won't hurt.

This is only for the `fullscreen` hud mode, right? I think we should keep it for continuity with Boom/MBF.

**Comment by liPillON** [comment]
hey, checking on this after quite some time and really loving the work you're doing!

just to clarify: you plan to just let users customize the extended hud widgets' positioning, or will this end up enabling the use of -let's say- lumps such as STIMA0, BON2B0 and STTNUM* like what's possible in PrBoom? (e.g: resultinin something like [this](https://i.postimg.cc/bJ31hSmb/moderngfx-stats.jpg))

**Comment by liPillON** [comment]
sorry for always coming up with silly requests, buuut...
any plan to let users hide/disable the health/armor/ammo progress bars?

**Comment by fabiangreffrath** [comment]
No, sorry, at the moment this is really just about rearrangement of the existing widgets - and I am literally breaking my brain about it. We may consider further widgets or modifications in the future, but this will have to settle first. :wink:

**Comment by liPillON** [comment]
yeah I completely understand!

**Comment by fabiangreffrath** [comment]
Alright, so now I have a working implementation ready in PR #890. To get the HUD that you suggested in your original post, please save the following in a file called `woofhud.lmp` and load it with the `-file` parameter (or put it into your `autoload/doom-all` directory):
```
hud 1
weapon bottomright
ammo bottomright
keys bottomleft
health bottomleft
armor bottomleft
monsec topright
sttime topright
coords topleft
fps topleft
```

**Comment by fabiangreffrath** [comment]
![woof0003](https://user-images.githubusercontent.com/6449237/217183285-5b7b8340-37ca-4cd1-b8c7-76df01fb91b8.png)

**Comment by liPillON** [comment]
Sweet! Looking good, thank you!


I've noticed this lump has no effect if "hud_distributed" is set to "0" 
If this is intended, maybe that setting should be exposed in the hud/crosshair/extended hud setup menu? Maybe calling it "enable custom hud support"?
The existence and the meaning of the "hud_distributed" setting might not be that obvious to new users, especially since is a config-file-only variable.

Also what the "use small font" does could be made more clear with different wording, I think.. Something along the lines of "use boom fixed-size font"?
For people coming from g/zdoom "Small Font" could be misleading since IIRC "SmallFont" is used there to identify the stock message font (STCFNxxx) 


Sorry to be particularly nitpicking, don't take this as ungrateful criticism.
On the contrary, I wish you, Roman and other contributors all the best for this port and, in that spirit, I'm suggesting what I think would make this feature really shine when it will be ready for prime time.

Keep up the hard work!

**Comment by fabiangreffrath** [comment]
> Sweet! I've just tested it: looking good, thank you!

😎 
 
> I've noticed this lump has no effect when "hud_distributed" is set to "0" If this is intended, 

Yes, that's because the lump only changes "hud 1", i.e. the distributed one. If you want to change to compact HUD as well, you'll have to add a new paragraph beginning with "hud 0". There are no other HUD ssupported than "hud 0" and "hud 1", currently.

> Also: what the "use small font" option does could be made more clear with different wording, I 

Sure, I am all thankful for suggestions like this! Though, I think the "fixed-size" term may be a bit too technical sounding here. How about "Use Boom font for HUD widgets" or "Use Boom HUD font for widgets", since we are referring to the Boom HUD already one item item above?

> Sorry to be particularly nitpicking, don't take this as ungrateful criticism. On the contrary, I 

That's understood! I am thankful for your suggestions and I don't expect my implementation to be straight perfect for others just because I clicked the "ready for review" button. 😉

**Comment by liPillON** [comment]
Hello again!
Since this landed in master recently, I've tried it using the latest autobuild.
I now have 2 issues with how the HUD and the LevelName string interact when the Automap is in overlay mode:
1) the levelname always claims the bottom left corner for itself, resulting in the HUD widgets being pushed upwards when activating the automap. Is this intended?
2) the levelname is the only remaining string using the message font (since the stats/time widgets are now always rendered by the hud subsystem). Could it be changed so that it complies with the "use small font" setting?

Thank you!

**Comment by fabiangreffrath** [comment]
> 1. the levelname always claims the bottom left corner for itself, resulting in the HUD widgets being pushed upwards when activating the automap. Is this intended?

Yes, because this is the original position of the level name widget inherited from Vanilla Doom.

> 2. the levelname is the only remaining string using the message font (since the stats/time widgets are now always rendered by the hud subsystem). Could it be changed so that it complies with the "use small font" setting?

I added an option to draw *all* widgets in the message font, but @rfomin already suggested to extend this to a special "on automap" behavior. I'll look into it.

**Comment by liPillON** [comment]
> Yes, because this is the original position of the level name widget inherited from Vanilla Doom.
I understand, but since neither the fullscreen hud nor the automap overlay are Vanilla Doom features.. Shouldn't this let you have some freedom?
From the top of my head: 
- the level name string could be put behind and option (no/yes/automap) just like the stats and time widgets
- the level name string could be added to the widgets managed using the WOOFHUD lump

> While at it, I could use some help properly naming that menu item.
I haven't read Roman's suggestion, would this be implemented as a third option for the already existing menu item?

**Comment by fabiangreffrath** [comment]
> * the level name string could be added to the widgets affected by the WOOFHUD lump

This will be the most sensible approach.

> I haven't read Roman's suggestion, would this be implemented as a third option for the already existing menu item?

Nope, this will be like "Use standard HUD font for widgets" with options "no"/"on automap"/"always".

**Comment by liPillON** [comment]
And it would replace this entry, right?
![woof0000](https://user-images.githubusercontent.com/48625273/218464062-25040dd1-e7b2-446a-aed2-6ffa1e6e68ca.png)


> "Use standard HUD font for widgets (no/on automap/always)"
I'm not a native-english-speaker myself, so your current proposal might be hard to read just for me.. But I just can't understand if with this you are referring to the stock message font or to the boom fixed-width font

I guess that either one of the following could be better:
- Use stock Boom HUD font for widgets
- Use standard Doom font for widgets

Each option's outcome would need to be changed accordingly, of course.

The reasoning behind this would be:
- the "hud widgets" expression seems redundant (unlike every other on-screen UI, I don't consider the StatusBar as a widget) so you might as well drop that "hud" 
- the "Stock" adjective would underline the fact that your referring to port-provided font, originating from its Boom roots
- the "Standard" adjective would be a reference to the message font being the one users are more familiar with (and the one modders usually replace in their pwads)

**Comment by fabiangreffrath** [comment]
> * Use standard Doom font for widgets

I think I'll got with this one. Thank you very much!

**Comment by fabiangreffrath** [comment]
What I am still aiming for until I am really satisfied with the current implementation:
* Only rebuild the widget strings if they have really changed. However, I don't think this is really possible, unfortunately. The `w_ammo` string, for example, will have to keep track of the player's current weapon, the current ammo and the maxammo values. Additionally, it will have to get redrawn if the widget font settings have changed or if one of the settings affecting only the coloring of the ammo widget have changed. There's more exceptions than rules...
* Move most of the alignment code into the `HU_Ticker()` function. The current imlementation solves this in quite an elegant way: There are some conditions checked under which the widget strings are built. Only if the widget string has been built in the ticker, the widget becomes visible in the drawer and can be aligned in FIFO order. However, this also means that widget coordinates are redundantly recalculated in the drawer function, although they remain constant until the next ticker call.

**Comment by liPillON** [comment]
just tried the latest build, the UI has gained a really good set of features!

(question: the map title widget is always drawn using the "standard doom" font, even when hud_widget_font is set to zero.. oversight, bug or feature? ;) )


(I'm also attaching the WOOFHUD lump I'm using - usually combined with the dark overlay automap)
[HUD-Woof.zip](https://github.com/fabiangreffrath/woof/files/10740912/HUD-Woof.zip)

**Comment by liPillON** [comment]
maybe [here](https://github.com/fabiangreffrath/woof/commit/c3377d49d7aed63bfb8be53b5dce1de948d55bf4#diff-67532b3043b66e4348b4f6652d5767385fefb36aab675469992f7f28f5e49896R588) hud_font2 should be used instead of hud_font?

**Comment by fabiangreffrath** [comment]
I'm not sure I'd survive the view of an entire map title line being printed with the small HUD font.

**Comment by liPillON** [comment]
hehe ok ok fine 😄

**Comment by fabiangreffrath** [comment]
> hehe ok ok fine 😄

Also, I don't consider the map title line as a "widget", just as I don't consider the player messages line or the "secret revealed" line as "widgets".

**Comment by fabiangreffrath** [comment]
I consider this issue as fixed now.

https://github.com/fabiangreffrath/woof/commit/914a4ccf1296e753b706164ab6e411eebadd9c38
https://github.com/fabiangreffrath/woof/commit/d75ef3c308b7964b09ae8b513571cfa7718a8207

**Comment by fabiangreffrath** [comment]
@liPillON Could you post your `woofhud.lmp` file that implements your custom HUD here? I'd like to include it as an example in the `doc/` directory.

**Comment by fabiangreffrath** [comment]
> Sure, here it is: [WOOFHUD.ZIP](https://github.com/fabiangreffrath/woof/files/11020642/WOOFHUD.ZIP)
> 
> This is the current version, directly from my autoload folder: it changes hud0, hud1 and hud2. In the archive you'll find screenshots for all three.

Thank you very much for this! I'll add this to the documentation. 



> Since we're here.. I'm not that familiar with boom/mbf codebase: could you direct me towards the lumps used for the HUD's progress bars and those used for the HUD's font? Are they available as files in the repository?

Nope, unfortunately not. They are only avaliable as embedded lumps in the form of arrays in `src/info.c`.

**Comment by liPillON** [comment]
They're also available in the EE repository:
https://github.com/team-eternity/eternity/tree/master/base/doom/res/graphics

**Comment by liPillON** [comment]
So with this new resources at hand, I went and made a few tweaks to some of those lumps.
I wasn't hoping that Woof would let me replace them, but it works!


I've fixed the misaligned shadows in some of the DIG* lumps and I've edited the STBR* lumps to remove something that always slightly annoyed me - let's see if you can [spot the differences](https://user-images.githubusercontent.com/48625273/226473798-c112de1e-3f06-4c86-b54c-d56b9c587032.png) ;)


These were small annoyances that I previously fixed in my "boom hud for gzdoom" project ([shameless plug](https://github.com/liPillON/gzhud_boom)).


So [here it is](https://github.com/fabiangreffrath/woof/files/11023328/WOOFHUD.ZIP), the final revision of my WOOFHUD edit. 
Now embedded in WAD, alongside all the other hud lumps mentioned above.

**Comment by fabiangreffrath** [comment]
I consider this an overall improvement to the hud font. Thanks for sharing this!
