### ISSUE TITLE
[Suggestion] Use docgen from Chocolate Doom

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#601]
What do you think of the docgen integration from Chocolate Doom? We already have comments in this format in the netcode. We will have to bring Python 3 back into the build system.

**Comment by fabiangreffrath** [comment]
On the one hand, I always found this approach a bit over-engineered. And considering that we have invested quite some effort to simplify the build system in this release cycle, this may even appear as a step back. On the other hand, we get manual page generation and even bash completion scripts for free once this is implemented.

Let's say, I'd like to keep this strictly optional. That is, I'd like to include generated content in the code, so it's not necessary to regenerate everything during each build.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/8a7ed2ac6b34a021cb2ccbc9e2ee02cbc2aa79c4
