### ISSUE TITLE
Scrolling walls don't work in Vanilla complevel

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#611]
Tested on Doom 2 Map30 with the following command line:
`woof.exe -iwad doom2.wad -warp 30 -complevel X`
X being set to 2, 3 and 4.

In none of those complevels did the scrolling texture actually scroll. From Boom onwards it seems to be working fine. I tried with a newly generated .cfg in case my settings were somehow causing it, but the issue persisted.

**Comment by rfomin** [comment]
Found the bad commit with `git bisect`: 46d5c05cd27b90a3a64bf6e979c68a49346d9a2e
