### ISSUE TITLE
[Suggestion] when the player is dead the game loads from the last save instead from the start

### ISSUE THREAD

**Issue by dmslr** [fabiangreffrath/woof#618]
This would be useful for those who play with saves (they wouldn't have to load the last save manually; just press any key and you're ready to continue the run). I don't see any reason why the game should start from the beginning for those who have saved their run.

Let's say, I play Sunder and keep dying a lot. The real stress begins when I keep spamming "main menu > load game > my save" in every 20 seconds. I'm aware there's a load key but it doesn't help much. Pressing any key to load the save would be nice.

**Comment by kraflab** [comment]
In case you're curious how this is implemented in dsda-doom: https://github.com/kraflab/dsda-doom/blob/master/prboom2/src/dsda/death.c (I suggest also adding the "do nothing" option if you go with it, that can be quite convenient for people that don't want to accidentally reset anything).

**Comment by fabiangreffrath** [comment]
This would make a useful combination with autosave at level start.

**Comment by fabiangreffrath** [comment]
@kraflab In DSDA, if you have selected "load game" and have neither saved nor loaded a savegame before dying, then nothing happens, right?

**Comment by fabiangreffrath** [comment]
Also, what happens during demo recording/playback or in network games?

**Comment by rfomin** [comment]
It's default action during demo recording/playback:
https://github.com/kraflab/dsda-doom/blob/7f8f4e9ba74b4fbb2c44456bece7136c7f5ed034/prboom2/src/dsda/death.c#L41-L42
There is no network game in DSDA-Doom.
I'm planning to implement this feature, just got distracted by the bugs.

**Comment by fabiangreffrath** [comment]
Ah, okay, thanks! I was looking at the exact same code file, but got distracted by the sheer number of indirections.

**Comment by kraflab** [comment]
It looks up the last save slot used. If none has been used, it does nothing.
