### ISSUE TITLE
Brightmap Feature parity

### ISSUE THREAD

**Issue by sneakernets** [fabiangreffrath/woof#625]
I have a question relating to Brightmaps: Will Crispy Doom, woof! and International Doom all have the same brightmap systems? And, will that system be configurable for existing PWADS?

**Comment by fabiangreffrath** [comment]
> I have a question relating to Brightmaps: Will Crispy Doom, woof! and International Doom all have the same brightmap systems? 

Yes, at least Crispy and Woof! share the exact same brightmap implementations. I think Inter Doom has also switched to my implementation meanwhile, but has added some more advanced features on top, like e.g. flickering lights. But, under the hood, they all use the same data. (@JNechaevsky right?)

> And, will that system be configurable for existing PWADS?

No, it is currently impossible to modify or extend the brightmap definitions. They are all hard-coded into the engine.

**Comment by JNechaevsky** [comment]
> Yes, at least Crispy and Woof! share the exact same brightmap implementations. I think Inter Doom has also switched to my implementation meanwhile, but has added some more advanced features on top, like e.g. flickering lights. But, under the hood, they all use the same data. (@JNechaevsky right?)

Absolutely right, this is your implementation. Flickering/glowing does not require any extra sprites or states, and does not require a lot of extra CPU power - their animation is calculated tic based, not frame rate based. Looks cool in terms of attention to details but may be not very friendly with new graphics, of course.

**Comment by rfomin** [comment]
What if we come up with new lump for this. It could be text config like this:
```
PATCH = brightmap
```
With `brightmap` as binary lump. For example:
```
"COMPSTA1" = notgray
```

**Comment by fabiangreffrath** [comment]
Hm, a good idea indeed! However, being based on patch names this could get tricky if a texture is composed of more than one such patch. And there must be a way to reset a patch to "no brightmap".

**Comment by JNechaevsky** [comment]
Maybe we then should switch mobj brightmaps to per-mobj_state bias from per-sprite_name bias? Same I've did in Heretic & Hexen. This should give the way more flexibility for applying.

**Comment by khades** [comment]
might is be better idea to have a standard for brightmaps, so they could be implemented for third party wads?

**Comment by fabiangreffrath** [comment]
We now support the BRGHTMPS lump (with some extensions) from Doom Retro, so I think it's safe to say that brightmap feature parity has been achieved.

https://github.com/fabiangreffrath/woof/commit/88a94d21f07caad386e83061b69c46542acc6849
