### ISSUE TITLE
I_SignalHandler: Exit on Illegal storage access (Signal 11) error upon starting level

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/woof#636]
![Capture](https://user-images.githubusercontent.com/82729328/176862112-84bd6e53-0a6a-4a6f-ac3e-e9f8352cbb4c.PNG)

### Background

Version of Woof: built from https://github.com/fabiangreffrath/woof/commit/78a24f99d025c08a149d021b6afaff8f556c2cff

Operating System and version: Windows 10 (32-Bit)

Any loaded WADs and mods (please include full command line): happens regardless of WADs loaded

### Bug description

Observed behavior: 

- This happens regardless of whether I try to start a new game, load a save, reload level (using bound key) or skip the level (using bound key).

- It happens randomly, but it is always the same error message.

- this happened on complevel vanilla and boom, with either doom.wad or doom2.wad as the loaded IWAD

**Comment by fabiangreffrath** [comment]
Could you try if this fixes the issue for you?
https://github.com/fabiangreffrath/woof/pull/635
