### ISSUE TITLE
compat: Vanilla and Boom demo recording (and multiplayer) compatibility 

### ISSUE THREAD

**Issue by Danfun64** [fabiangreffrath/woof#64]
While this is based off an MBF fork, it would be nice if you added a "-complevel 9" setting (or equivalent) so Boom compatible demos could be recorded (with all of the MBF features implemented into PrBoom-Plus's "-complevel 9" turned on).

A second feature request I have is working multiplayer support. Since PrBoom-Plus's netplay is busted, PrBoom 2.5 is slowly becoming even more obsolete, MBF 2.04 isn't supported in PrBoom-Plus, and Boom 2.02 and MBF 2.03 (with or without fixes) requires DOS for multiplayer, it would be nice to have a modern port of Boom/MBF which allows the recording of multiplayer demos for "-complevel 9" and "-complevel 11" (both with and without the 3 key bug fixed)

**Comment by fabiangreffrath** [comment]
Why would you want to record Boom demos? What's "better" about Boom demos than MBF demos?

Netplay would sure be nice, granted. To be honest, I haven't even checked if it works at all.

**Comment by fabiangreffrath** [comment]
> (both with and without the 3 key bug fixed)

PS: You are probably over-estimating the importance of this bug, but I have already added a compatibility switch for this.

**Comment by Danfun64** [comment]
"What's "better" about Boom demos than MBF demos?"

I was under the impression that Boom demos were far more standard for speedruns and stuff. I mean, they do (usually) say "Boom-compatible" and not "MBF-compatible" for wads, even if the target is PrBoom-Plus -complevel 9

**Comment by fabiangreffrath** [comment]
This will open a can of worms/bugs. First, there are multiple versions of Boom to emulate (2.01/2.02), then there is Boom's flawed compatibility mode - and there is also MBF's own flawed Boom compatibility mode. Not sure how much effort it is worth to properly emulate all of these to support a non-native demo format that is already supported by other ports - most notably PrBoom+, when you could just pick the port's own demo format.

Sorry to tell you, but this will most probably not become the same demo recording/playback machine that Prboom+ is.

**Comment by Danfun64** [comment]
"there are multiple versions of Boom to emulate (2.01/2.02), then there is Boom's flawed compatibility mode - and there is also MBF's own flawed Boom compatibility mode. "

I wasn't asking you to emulate _all_ of that. Just 2.02/-complevel 9. That's the only one you listed that really matters.

I wasn't asking you to make this port as comprehensive for demos as PrBoom-Plus... just something that can record multiplayer demos playable on PrBoom-Plus using -complevel 9.

If that still doesn't interest you regarding this port, I understand.

**Comment by fabiangreffrath** [comment]
The problem is not so much lack of interest. The problem is that if you are targetting demo compatibility, you'll better get it right in the first try. The community is unforgiving. :wink: 

Demo playback is one issue, this can be fixed - and I did so for Vanilla demos already (excluding emulated overflows, that is). But demo recording is a different kind of beast, and I am lacking the time and resources to trial-and-error this into a state that will be ready for release.

**Comment by Danfun64** [comment]
Are you saying you wouldn't recommend this port for demo recording even -complevel 11 stuff (which is more or less this port's main goal)?

**Comment by fabiangreffrath** [comment]
Yes, if course you can record MBF demos with this port. It's still pure MBF under the hood. But everything else needs to be emulated.

**Comment by Danfun64** [comment]
what do you mean, "everything else"?

**Comment by fabiangreffrath** [comment]
Vanilla and Boom are everything else from MBF's point of view regarding demo recording.

**Comment by Danfun64** [comment]
I see. I thought you meant x86 emulation of the type that Chocolate Doom (and derivatives) and PrBoom-Plus do.

**Comment by fabiangreffrath** [comment]
It turns out that MBF's emulation of Boom 2.02 is pretty flawed which leads to several demos desyncing during playback. I hope it's obvious that all these flaws need to be fixed before it makes sense to take demo recording in Boom 2.02 format into account.

**Comment by Notarget137** [comment]
There are also possible vanilla demo desyncs since MBF and Boom and general doesn't have a proper implementation of A_CheckReload function.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/2c6ec477510293a6e492e15aa54cce9c455e9003
