### ISSUE TITLE
HUD extenders for widescreen resolutions

### ISSUE THREAD

**Issue by dmslr** [fabiangreffrath/woof#651]
Any chance Woof could have [this feature from EDGE classic](https://www.doomworld.com/forum/post/2515544)?
I believe it's a universally accepted fact that GRNROCK is ugly and ruins the look of custom status bars. The solution they found for EDGE classic looks beautiful.

**Comment by fabiangreffrath** [comment]
Very nice, indeed! But this doesn't look like solid colors but some tinted background pattern. Where does this come from?

**Comment by rfomin** [comment]
> But this doesn't look like solid colors but some tinted background pattern. Where does this come from?

Looks like tinted standard STBAR texture.

**Comment by fabiangreffrath** [comment]
But how does it work? They fill up the gaps around custom status bars with tinted textures of the IWAD status bar?

**Comment by rfomin** [comment]
> They fill up the gaps around custom status bars with tinted textures of the IWAD status bar?

Probably, but I haven't looked at the code.

**Comment by fabiangreffrath** [comment]
Looks like they have `stbarl` and `stbarr` graphics lumps in `edge-defs.wad`:

![stbarl](https://user-images.githubusercontent.com/6449237/178226870-2da24847-bb18-4bcf-b7f9-de965c54d399.png)
![stbarr](https://user-images.githubusercontent.com/6449237/178226877-cb388b72-6b8f-4b1a-8a67-d925472e1f40.png)

**Comment by dmslr** [comment]
I'm glad you approved this! I hope implementing it won't need much effort.

**Comment by fabiangreffrath** [comment]
Sorry, but this doesn't mean we are going to do the same. Inclusion of some random probably-IWAD-derived assets in Woof is an absolute no-go.

**Comment by rfomin** [comment]
> Inclusion of some random probably-IWAD-derived assets in Woof is an absolute no-go.

But maybe we can find some good free texture (from Freedoom?)

> Even if the sides filled with a plain color, it looks decent.

I've tried a solid color before and it didn't look good. But I'm not an artist.

**Comment by dmslr** [comment]
> I've tried a solid color before and it didn't look good. But I'm not an artist.

It didn't? The screenshot from ancient aliens looks good. Maybe you've tried other wads when it didn't look good?

**Comment by rfomin** [comment]
> How about this?

Good enough for me.

**Comment by dmslr** [comment]
For me too.

**Comment by fabiangreffrath** [comment]
Cool, thanks! I'll work on a cleaner implementation then.
