### ISSUE TITLE
[Feature] Add more display options from PrBoom+

### ISSUE THREAD

**Issue by dististik** [fabiangreffrath/woof#657]
A few more display options to make the switch over from PrBoom+ would be very nice for someone like me to have. In specific, the option to disable palette changes for pain/bonus/powerups and disable the wipe screen effect are what are lacking from Woof! that are preventing me from making the full switch over.

That said I understand if this is outside of the scope of this project, just thought it was worth bringing up!

**Comment by fabiangreffrath** [comment]
Alright, we had Accessibility features somewhere on the list anyway. 😉
