### ISSUE TITLE
Misplaced level stats text on Boom HUD

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#669]
By enabling "Hide Level Stats" (of course, with the setting being disabled beforehand), by toggling Widescreen, or by entering and exiting a setup menu, the text is placed in the top left corner on the "original" screen, i.e. ignoring widescreen:

![image](https://user-images.githubusercontent.com/73968015/179672853-b211c3fb-f7ee-4d25-8358-e597c447c7fb.png)

Cycling between other distributions of the HUD fixes the issue. It doesn't seem to happen when starting a new game right after launching the program.

**Comment by fabiangreffrath** [comment]
Seems like we have to take changes in the value of `WIDESCREENDELTA` into account in `HU_MoveHud()`.

**Comment by fabiangreffrath** [comment]
Does this little change fix the issue?
```patch
--- a/src/hu_stuff.c
+++ b/src/hu_stuff.c
@@ -864,7 +864,7 @@ void HU_MoveHud(void)
       w_armor.x =   hud_distributed? HU_ARMORX_D  : HU_ARMORX;
       w_armor.y =   hud_distributed? HU_ARMORY_D  : HU_ARMORY;
     }
-  ohud_distributed = hud_distributed;
+  ohud_distributed = hud_distributed & (WIDESCREENDELTA << 8);
 }

 static int HU_top(int i, int idx1, int top1)

```

**Comment by MrAlaux** [comment]
I can try it in about 12 hours.
In the meanwhile I wonder, does fixing the X position of the text somehow fix its Y position too? Just to clarify, I don't think the STS text should be so high up, not with that specific HUD layout at least.

**Comment by fabiangreffrath** [comment]
The `HU_MoveHud()` function fixes the widget's x and y positions.

**Comment by fabiangreffrath** [comment]
@rfomin Well, that's pragmatic. 😉 Do we have to do the same with `w_sttime`?

**Comment by fabiangreffrath** [comment]
Alright, let's fix it like this. I'm still at work right now.

**Comment by rfomin** [comment]
It seems this bug is side effect of this commit: 108467e3c87b55a11aac2582a2b97f2ad325a94a
Maybe there is another way to fix this?

**Comment by fabiangreffrath** [comment]
I think we can even revert https://github.com/fabiangreffrath/woof/commit/108467e3c87b55a11aac2582a2b97f2ad325a94a after I fixed https://github.com/fabiangreffrath/woof/commit/d8a068c97b3e98b918d31360ad84c5b22f43c249
