### ISSUE TITLE
Couple of launching errors.

### ISSUE THREAD

**Issue by ice44** [fabiangreffrath/woof#68]
Congrats on 1.0.0! Had a few snags. Had to download zlib1.dll file to get it to launch. and W_GetNumForName: STTMINUS not found!,

**Comment by fabiangreffrath** [comment]
Hi,

I am sorry for the zlib1.dll thing, this somehow sneaked itself out of the release zip.

Regarding STTMINUS, this lump should be available in every IWAD since Doom 1.2, so could you please check which version you have?

**Comment by ice44** [comment]
@fabiangreffrath I was using the 1.2 version of Doom, it was working without error in the earlier version.
