### ISSUE TITLE
D_AddZipFile does not look for archives in %DOOMWADPATH%

### ISSUE THREAD

**Issue by liPillON** [fabiangreffrath/woof#686]
Hi team!
I'm using Woof 10.1.0 x64 under Windows 10.

I usually launch the game by using a batch launcher of my own making that:
1. sets DOOMWADDIR to the path containing the IWAD (i.e. ".\MAIN")
2. adds to DOOMWADPATH the paths for each folder where my PWADs are (i.e. ".\MAPs";".\MODs", etc)
3. lists the content of the ".\MAPs" folder and let me choose a megawad to play
4. lists the content of the ".\MODs" folder and let me choose a pwad to apply
5. runs "woof.com" by passing only the filenames to the -iwad and -file parameters

Under these conditions, both the following command lines are working as intended:
- woof.com -iwad ".\MAIN\DOOM.WAD" -file ".\MAPs\neis.wad" ".\BlackOps.wad"
- woof.com -iwad DOOM.WAD -file neis.wad BlackOps.wad

I've noticed today, however, that this breaks when trying to load a zip archive instead of a plain wad. 
This is the resulting terminal output in Windows:
```
D:\games\IDTECH\Woof-10.1.0-win64>woof.com -iwad DOOM2.WAD -file ar.zip WPN-BlackOps.wad MNS-Smoothed.wad
IWAD found: .\MAIN\DOOM2.WAD
DOOM II version
                         DOOM 2: Hell on Earth v2.03
Built on Jul 18 2022
D_AddZipFile: Failed to open ar.zip


D:\games\IDTECH\Woof-10.1.0-win64>
```

**Comment by rfomin** [comment]
> Does it work if you pass the full path to `ar.zip`?

Yes, I don't call `D_TryFindWADByName` for `.zip` files.

**Comment by liPillON** [comment]
wow you've already submitted a fix.. sweet!
