### ISSUE TITLE
hard dependency on SDL2_Image for PNG screenshots

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#69]
I guess the `dlopen()` trick doesn't really meet its audience and people just don't want (or understand) to copy DLL files around. As both PCX and BMP formats are really archaic nowadays we need PNG screenshots unconditionally. Therefore I will change the code to make them the default. 

@AlexMax I guess we need a new `cmake/findSDL2_Image.cmake` snippet for this. Would you take care of that?

**Comment by AlexMax** [comment]
I can certainly do this.  However, might I suggest an alternative that might be easier from a dependency point of view?

https://github.com/nothings/stb/blob/master/stb_image_write.h

stb_image is a reasonably common alternative to SDL_image.  The repository has over 11k stars on github, and is used in many other programs and libraries, including libraries like SFML.  It is made available under either the MIT license or the public domain/unlicense.  However, the most important bit is that it is a single-file dependency that can be included in-tree and requires no build-system magic.

Given the fact that SDL_image currently sees very little use in the project, it seems prudent to at least consider stb_image as an alternative for writing screenshots.  If not, I'm happy to get SDL_image working, but I thought I might as well bring up the alternative.

**Comment by fabiangreffrath** [comment]
Thank you very much for suggesting stb_image, this is appreciated. Usually, I am very fond of single-header libraries, but in this specific case, I'd rather prefer to use SDL_Image.

The reasons are: I am using SDL for everything else already, so using SDL_Image for screenshots feel like a one-stop solution. I can simply pass an `SDL_Surface` and a file name to `IMG_SavePNG()` and be done without and don't have to care about the surface's color space or row pitch. And finally, I contributed SDL_Images libpng-based PNG export functionality myself [1], so I think I should naturally use it. :grin: 

[1] https://hg.libsdl.org/SDL_image/rev/4076ac7cf0a1

**Comment by JNechaevsky** [comment]
Gentlemen, FYI, SDL 2.0.11 is coming: https://www.libsdl.org/tmp/download-2.0.php. 
Changelog here: https://www.libsdl.org/tmp/SDL/WhatsNew.txt
