### ISSUE TITLE
WheelUp/Down Rebinds not Functioning

### ISSUE THREAD

**Issue by Frostwolfo** [fabiangreffrath/woof#699]
When rebinding either WheelUp or WheelDown to anything under the Action, Weapon, or Chatting categories (except for prev and next), the wheel doesn't perform any function during gameplay.

**Comment by fabiangreffrath** [comment]
@rfomin any idea?

**Comment by rfomin** [comment]
The problem is that the wheel up/down sends `ev_mouseb_down` and `ev_mouseb_up` events on the same tick, so you can't "hold" it like other buttons. I guess we can send the `ev_mouseb_up` event on the next tick in `G_Responder`.
