### ISSUE TITLE
An error occurs when try to Multiplayer

### ISSUE THREAD

**Issue by skyrain128** [fabiangreffrath/woof#715]
![화면 캡처 2022-09-04 150913](https://user-images.githubusercontent.com/50762042/188300025-4208ff74-3ca5-42e5-b38c-f34bfedb125b.png)
This error occurs when I try to Multiplayer in setup program.

**Comment by rfomin** [comment]
That was fixed in https://github.com/fabiangreffrath/woof/commit/ec69d27549dc0fe754007aa5f035708b27f673ff right after 10.2.0 release. You can try download current autobuild, see artifacts here: https://github.com/fabiangreffrath/woof/actions/runs/2984186551
