### ISSUE TITLE
No such option '@C:\Users\...\AppData\Local\Temp\woof.rsp'.

### ISSUE THREAD

**Issue by thatanti360** [fabiangreffrath/woof#716]
Trying to create or join a multiplayer game in Woof results in this error.

**Comment by rfomin** [comment]
That was fixed in https://github.com/fabiangreffrath/woof/commit/ec69d27549dc0fe754007aa5f035708b27f673ff
@fabiangreffrath maybe we should make a small bug fix release because the multiplayer launcher doesn't work in 10.2.0

**Comment by fabiangreffrath** [comment]
Yes, I'm fine with releasing the current state as 10.2.1.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/ec69d27549dc0fe754007aa5f035708b27f673ff
