### ISSUE TITLE
REKKR: Sunken Land - Colored Blood issue

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/woof#717]
I've been replaying through REKKR with the following command line:
-complevel vanilla -iwad rekkrsl.wad
(rekkrsl.deh is autoloaded, and so are widescreen assets for REKKR).

No matter if bloodcolor.deh (not sure if needed anymore) is loaded or not, if the colored blood option is on, the caco/ baron replacements bleed blue and green respectively.
I assume this might have something to do with [dc93bd6](https://github.com/fabiangreffrath/woof/commit/dc93bd6b5469ac044ba8b526ced1c00cd6b4c921) , but I'm not sure.

**Comment by fabiangreffrath** [comment]
Do you still have the `autoload/doom-all/bloodcolor.deh` file in your Woof directory? It is not supposed to be there anymore. This, and I think we might need a copy of `autoload/rekkrsa.wad/bloodcolor.deh` for `rekksl.wad`.

**Comment by fabiangreffrath** [comment]
> -complevel vanilla -iwad rekkrsl.wad

Wait a minute! Doomwiki states that `rekkrsl.wad` doesn't work as an IWAD and requires an Ultimate Doom IWAD instead. So, how does that work for you?

**Comment by rzhxiii** [comment]
I don't know how, I just tried it and it works.
Here's the full command line: woof.exe -complevel vanilla -iwad rekkrsl.wad -save .\savedir\rekkr
There are no files that might change the color of the blood in these folders (also checked the Doom 2, rekkr.wad and rekkrsa.wad folders).
There are no monsters in REKKR that bleed other colors apart from red.
And here are some screenshots:
![rekkrsl](https://user-images.githubusercontent.com/82729328/188658058-e0cc7920-54e7-4cf1-a4a6-ca0a1e94882a.PNG)
![doomall](https://user-images.githubusercontent.com/82729328/188658072-e0372e3e-7cdd-42d2-b62e-4a63e1a1b6c2.PNG)
![doom](https://user-images.githubusercontent.com/82729328/188658087-317c7d90-a9e1-4b52-a780-14741f02adf7.PNG)

**Comment by rzhxiii** [comment]
Maybe Woof for some reason registers this WAD as The Ultimate Doom already? I had a custom palette autoloaded in the doom-all folder earlier and it affected Rekkr too, despite the command line remaining the same.
As a result, the E4 sky, which is normally a light purple, ended up looking brown.

**Comment by fabiangreffrath** [comment]
Indeed, if Woof cannot recognize the IWAD by its file name at first, it scans through the file for some characteristic lumps. And by the presence of both E1M1 and E4M1 it concludes that this must be an Ultimate Doom compatible IWAD. So, it choses gamemode to be "retail" and gamemission to be "doom", and thus it autoloads all the PWADs from the "doom-all" directory -- which it wouldn't have done if it had recognized `rekkrsl.wad` as a "pack_rekkr" IWAD by its filename. #718 should take care of that.
