### ISSUE TITLE
snapshots for savegames

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#734]
Hi all,

I am currently drafting on the idea of adding snapshots to savegames, i.e. basically saving a screenshot of the game scene at the moment the game is saved. These snapshots are meant to be displayed next to the currently highlighted savegame in the Load Game / Save Game dialogs. 

It is quite obvious that they cannot get displayed in their actual size, else they would overlay the entire screen and make everything else unrecognizable. Thus I'll have to reduce the respective image size *at least* by factor 2, if not even factor 4 or 5 - I mean, have a look at the Load Game menu and imagine how much horizontal space will be left if we move the savegame entries and the skull completely to the left or right. I'd like to get away *without* reducing the length of the savegame description fields.

It would be cool, of course, if the size of the displayed image would get increased automagically in widescreen mode, which means I would have to save the snapshots at least with `ORIGWIDTH x ORIGHEIGHT´ size (which would add about 64kB to each savegame). Speaking of widescreen mode, I am going to save only the inner part of the scene that matches non-wide rendering, so all snapshots share the same dimensions.

What do you think?

**Comment by rfomin** [comment]
We can compress screenshots as PNG.
I think it's an interesting feature, but it won't be very legible at 320x200. Maybe it's worth supporting this feature only in hires mode?

**Comment by fabiangreffrath** [comment]
> We can compress screenshots as PNG. 

We would need paletted PNGs in order to show them in-game. Not a problem, but something to keep in mind.

> I think it's an interesting feature, but it won't be very legible at 320x200. Maybe it's worth supporting this feature only in hires mode?

I think we could let the users figure out that they can see more detailed savegame snapshots in hires mode. 😉

**Comment by mikeday0** [comment]
Couldn't you render the screenshots at a higher resolution overtop the game screen? In other words make the screenshot its own distinct `SDL_Texture` object. Might be out of line with the Woof! aesthetic though.

**Comment by fabiangreffrath** [comment]
Hm, but then I'd still have to scale them down in order for the savegame descriptions to remain legible. And if the screenshots are still too crisp then, I'm afraid the whole arrangement will look too artifical and out of place then. :shrug:

**Comment by mikeday0** [comment]
My point being that you could decouple the screenshot resolution/crispness from the game framebuffer resolution. Hence the screenshot would look the same regardless of the user's choice of rendering resolution.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/c815ac2102292d50fd2260976145a02784e2de3c
