### ISSUE TITLE
Partime missing from intermission screen with PWADs

### ISSUE THREAD

**Issue by Raddatoons** [fabiangreffrath/woof#747]
Hi, I was making a pseudo-WADsmoosh style complete pack for DOOM II using UMAPINFO, and I was working on adding the partimes for the NRFTL levels when I decided to testrun the WAD.  However, I discovered that partimes weren't showing up at all upon beating a level, only the level and total times.

Turning off all of my loaded PWADs in ZDL brought the partimes back, but I also remembered that I had some sprite edits in my autoload folder.  Those clearly weren't messing with the partime.  My other WADs however completely wiped the partime off the screen, even the .MID the Way id Did MIDI pack, which doesn't even have any MAPINFO-style lump to speak of.  I do remember glancing at a stray post on a Doomworld forum asking about something similar, but I don't remember where I saw it and I couldn't find anything already in the GitHub issues, so I'm doubling down on it here.

I'm running the newest version of Woof!, 10.3.0.  Testing on other source ports, PrBoom+ does have the same issue of hiding partimes with PWADs, while the Eternity Engine, Crispy Doom and GZDoom keep the partimes visible.  Perhaps it's a shared piece of code between PrBoom+ and Woof! causing the issue?

(On an unrelated note: I can't find where Woof! saves its screenshots, so I'm using Windows' built in screen snipping tool for these screenshots.  Shouldn't affect anything, I just didn't know where else to ask about this. '^-^)

`-iwad "D:/Games/Program Files/DOOM/WAD Files/IWADs/DOOM2.WAD" -save "D:/Games/Program Files/DOOM/Save Files/Woof!/DOOM II" -complevel vanilla`
Autoloaded files: `D2SPFX19.WAD`, `D2DEHFIX.DEH`, `doom2_ws.wad`
![image](https://user-images.githubusercontent.com/86673970/192126783-9e9a046c-42a0-43cf-b3f9-db908eae9273.png)

`-iwad "D:/Games/Program Files/DOOM/WAD Files/IWADs/DOOM2.WAD" -file "D:/Games/Program Files/DOOM/WAD Files/PWADs/DOOM II/midtwid2.wad" -save "D:/Games/Program Files/DOOM/Save Files/Woof!/DOOM II" -complevel vanilla`
Autoloaded files: `D2SPFX19.WAD`, `D2DEHFIX.DEH`, `doom2_ws.wad`
![image](https://user-images.githubusercontent.com/86673970/192126864-500ada30-cad1-495c-8e8c-613533cb8199.png)

**Comment by fabiangreffrath** [comment]
The par time value determines how long we have to wait for its counter to increase on the intermission screen. This, it directly affects demo sync and we shouldn't change it. However, we should change if it gets displayed at all. The easiest fix would probably be to set `deh_parts = true` here in the `next` case:
https://github.com/fabiangreffrath/woof/blob/9f6d273ee3006112ad6cc33866bd14127da2adb2/src/g_game.c#L1295

**Comment by Raddatoons** [comment]
Admittedly I hadn't considered demo compatibility when I was making my "complete addon" WAD, especially as the NRFTL levels are on maps 54-63, but this is also why I did not include it in my examples showcased above.  The MIDI pack alone still causes the bug, and shouldn't affect demo compatibility at all because it's just a music replacement.

**Comment by fabiangreffrath** [comment]
This is my idea so far.

I am not so sure about the `um_pars = false` part in `G_DoCompleted()`, though. For `deh_pars` the logic is that if a par time is defined for at least one map, then all the par times are considered set for all maps. For UMAPINFO, though, I think it's a bit different, because par times are only set if a "next map" is defined - and this check happens on a per-map base.

```patch
--- a/src/g_game.c
+++ b/src/g_game.c
@@ -1235,6 +1235,8 @@ static void G_WriteLevelStat(void)
 // G_DoCompleted
 //

+boolean um_pars = false;
+
 static void G_DoCompleted(void)
 {
   int i;
@@ -1265,6 +1267,7 @@ static void G_DoCompleted(void)

   wminfo.lastmapinfo = gamemapinfo;
   wminfo.nextmapinfo = NULL;
+  um_pars = false;
   if (gamemapinfo)
   {
     const char *next = NULL;
@@ -1293,6 +1296,7 @@ static void G_DoCompleted(void)
       }
       wminfo.didsecret = players[consoleplayer].didsecret;
       wminfo.partime = gamemapinfo->partime * TICRATE;
+      um_pars = true;
       goto frommapinfo;        // skip past the default setup.
     }
   }
diff --git a/src/wi_stuff.c b/src/wi_stuff.c
index cb9d85e..3f3e046 100644
--- a/src/wi_stuff.c
+++ b/src/wi_stuff.c
@@ -42,6 +42,7 @@

 // Ty 03/17/98: flag that new par times have been loaded in d_deh
 extern boolean deh_pars;
+extern boolean um_pars;

 //
 // Data needed to add patches to full screen intermission pics.
@@ -1801,6 +1802,7 @@ static void WI_drawStats(void)
 {
   // line height
   int lh;
+  int maplump = W_CheckNumForName(MAPNAME(wbs->epsd + 1, wbs->last + 1));

   lh = (3*SHORT(num[0]->height))/2;

@@ -1828,8 +1830,8 @@ static void WI_drawStats(void)
   // killough 2/22/98: skip drawing par times on pwads
   // Ty 03/17/98: unless pars changed with deh patch

-  if (!modifiedgame || deh_pars)
-    if (wbs->epsd < 3)
+  if (W_IsIWADLump(maplump) || deh_pars || um_pars)
+    if (wbs->epsd < 3 || um_pars)
       {
        V_DrawPatch(ORIGWIDTH/2 + SP_TIMEX, SP_TIMEY, FB, par);
        WI_drawTime(ORIGWIDTH - SP_TIMEX, SP_TIMEY, cnt_par, true);
```

**Comment by rfomin** [comment]
> Patch

Looks good. I tested it, seems to work.

We still don't show `partime` if `endgame = true`.
Little test wad: [partime.zip](https://github.com/fabiangreffrath/woof/files/9644306/partime.zip)

**Comment by fabiangreffrath** [comment]
> Looks good. I tested, it seems to work.

Thanks for checking!

> We still don't show `partime` if `endgame = true`. 

Yes, right, this isn't decided yet. Also, do we assume all par times to be set by UMAPINFO once we have seen a "next map" for a map, or do we decide on a per-map base (as my current patch implements)? I strongly suggest the latter.

**Comment by rfomin** [comment]
> I strongly suggest the latter.

I agree.

**Comment by fabiangreffrath** [comment]
> We still don't show `partime` if `endgame = true`.

One problem when introducing a tally screen between the last map of an episode and the end screen is that a demo playback won't show the end screen if no key event has been recorded to quit the tally screen. I had to introduce this fix in Crispy (the bug report is linked in the decription):
https://github.com/fabiangreffrath/crispy-doom/commit/b9077f230c6467eae70ac9fee6f782c0cddef823

**Comment by Raddatoons** [comment]
> @Raddatoons In the savegame directory if you pass the -save parameter.

Cool, thanks so much for looking into this.
