### ISSUE TITLE
[Feature] Support mouse wheel left/right buttons

### ISSUE THREAD

**Issue by rrPKrr** [fabiangreffrath/woof#755]
Hey!

I have a g502 hero which has wheel left/right buttons on it. Seems like that's all you need to do to add support for those buttons:
https://github.com/fabiangreffrath/woof/commit/651684de4d993ba5297acbab02fe37102f7e1822

**Comment by fabiangreffrath** [comment]
Cool, thanks! Would you file a PR for this, please?

**Comment by rrPKrr** [comment]
https://github.com/fabiangreffrath/woof/pull/756
