### ISSUE TITLE
Multiple aspect ratio support

### ISSUE THREAD

**Issue by Jambus95** [fabiangreffrath/woof#762]
Hey there! I was wondering. Would it be possible to add an option to switch type of aspect ratio like in Crispy Doom? It's one thing I really like about it and PrBoom+, but I noticed that this option is missing in Woof. I tend to play regular widescreen on my ultrawide monitor since it's much comfier to play like that. Just wondering if it would be possible!

Thank you in advance for any reply. :)

**Comment by fabiangreffrath** [comment]
I wouldn't want to expose this in the menu, but I could imagine "hidden" values for the widescreen config key, that need to get explicitly set in the config file.

**Comment by Jambus95** [comment]
Even an option like that would work wonders, definitely!
