### ISSUE TITLE
Toggles are not disabled when typing on chat

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#767]
As the title says: toggles (like "Autorun" or "Mouselook") can still be triggered if their corresponding key is pressed while typing in the multiplayer chat.

EDIT: Maybe checking for `!chat_on` [here](https://github.com/fabiangreffrath/woof/blob/master/src/m_menu.c#L5285) might prevent this?

**Comment by fabiangreffrath** [comment]
> EDIT: Maybe checking for `!chat_on` [here](https://github.com/fabiangreffrath/woof/blob/master/src/m_menu.c#L5285) might prevent this?

Indeed, this sounds like a good idea. Could you please file a PR for this (and adjust the other checks for `chat_on` accordingly)?

**Comment by MrAlaux** [comment]
> (and adjust the other checks for chat_on accordingly)

I have to ask, what does this mean? What exactly do I have to change elsewhere?

**Comment by fabiangreffrath** [comment]
There are at last three checks for `chat_on` on the code block that you suggest to only execute if `chat_on` is false.

**Comment by MrAlaux** [comment]
Sorry, but I seem to be kinda troubled to file a PR myself; I already have a fork of this repo and it seems like I can't have any more, and it was too late when I realized that I should've made a PR in said fork to try and merge the changes into Woof. Even then, it would've probably tried to merge everything else from my fork.
