### ISSUE TITLE
UMAPINFO episodes do not show

### ISSUE THREAD

**Issue by DoodlesYT** [fabiangreffrath/woof#775]
(tested with valiant and eviternity) the episodes set by UMAPINFO do not display when playing a wad that supports it.

**Comment by fabiangreffrath** [comment]
Could you try these? They're known to work: 
https://www.doomworld.com/forum/topic/122892-umapinfo-appreciation-thread/?tab=comments#comment-2340153

**Comment by DoodlesYT** [comment]
it works! thanks for the help!
