### ISSUE TITLE
"Restart level/demo" text doesn't fit in non-widescreen

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#781]
In the Key Bindings setup menu, page 4:
![image](https://user-images.githubusercontent.com/73968015/198247525-db259d16-464a-4df9-b523-85db5d14fbfa.png)
I'm aware it's just a matter of changing the text, but I can't guess what you'd like to change it to.

**Comment by fabiangreffrath** [comment]
Does "Restart" -> "Reload" fix the issue? Else, we need to increase the `KB_X` value, I am afraid.

**Comment by rfomin** [comment]
It fits, barely:
![woof0001](https://user-images.githubusercontent.com/5077629/198265770-1ff38662-fc6e-47b6-a515-2f36476cdc9f.png)

**Comment by kraflab** [comment]
Level -> map if you want to make more room :^)

**Comment by fabiangreffrath** [comment]
Good idea! But then also "Next Map" one line above, please.
