### ISSUE TITLE
Level Brightness setting does not take Smooth Diminishing Lighting into account

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#783]
As a result of this, the brightness increase provided by each level of Level Brightness is halved when using Smooth Diminishing Lighting.

Example:

Level Brightness = 4, Smooth Diminishing Lighting OFF
![imagen](https://user-images.githubusercontent.com/73968015/198816703-323b92b1-bf0c-48fe-ad7a-8806f5ebd84b.png)

Same Level Brightness, Smooth Diminishing Lighting ON
![imagen](https://user-images.githubusercontent.com/73968015/198816717-bb3562fc-56d1-4c74-ab1a-4459465b07e6.png)

**Comment by rfomin** [comment]
@fabiangreffrath So this is the fix?
```diff
diff --git a/src/r_main.c b/src/r_main.c
index 0adb92c..ec7ac8e 100644
--- a/src/r_main.c
+++ b/src/r_main.c
@@ -654,7 +654,9 @@ void R_SetupFrame (player_t *player)
   pitch = player->lookdir / MLOOKUNIT + player->recoilpitch;
   }
   extralight = player->extralight;
-  extralight += STRICTMODE(extra_level_brightness); // level brightness feature
+
+  if (!strictmode) // level brightness feature
+    extralight += (smoothlight ? extra_level_brightness * 2 : extra_level_brightness);
     
   if (pitch > LOOKDIRMAX)
     pitch = LOOKDIRMAX;
```

**Comment by fabiangreffrath** [comment]
You could just add `LIGHTBRIGHT`?

**Comment by rfomin** [comment]
> You could just add `LIGHTBRIGHT * extra_level_brightness`?

Yes, thank you. Fixed in https://github.com/fabiangreffrath/woof/commit/010b85eca31ec896c2a7b8c5137caad54cff0529

**Comment by fabiangreffrath** [comment]
👍
