### ISSUE TITLE
Saving while fast forwarding a demo causes a segfault

### ISSUE THREAD

**Issue by Doommsatic** [fabiangreffrath/woof#787]
I ran a git bisect and https://github.com/fabiangreffrath/woof/commit/26f676e6d3107cd51733510646190668af1bd709 seems to be the first commit where this happens

**Comment by fabiangreffrath** [comment]
Where exactly does it crash and why?

**Comment by rfomin** [comment]
It crash in `M_WriteSnapshot()` function because `M_TakeSnapshot()` is not called if `fastdemo == true` https://github.com/fabiangreffrath/woof/blob/049ff059db0d9cc72567cff45e46936828fe3e4d/src/d_main.c#L287

**Comment by fabiangreffrath** [comment]
Then savegames taken while fast-forwarding won't get a snapshot. 🤷 We just need to add a safety guard to check if `current_snapshot == NULL`, right?
