### ISSUE TITLE
[Feature] Wadname-based savegame dirs

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#793]
Right now, Woof stores savegames in its root directory. If someone is switching between several addons within a short period of time, it's possible to accidentally overwrite savegames meant for a different PWAD. Therefore, it would be better if there was a way to keep them separate in a more fool-proof way, but also simply in order to maintain some order in the game root directory.

In other ports such as GZDoom, wadname-based savegame directories are created to avoid such situations. It's actually pretty much like the autoload folder works right now, just for savegames.

Suggested realization:
- Introduction of a CVAR to set up directory for savegames (may default to either root dir or e.g. %root%\savegames)
- Port automatically creates subdirs inside of the specified savegame dir with names based on active IWAD/PWAD (e.g. "doom.wad" for Doom 1 or "requiem.wad" for Doom 2 PWAD "Requiem")
- Only savegames from those subdirs are used, depending on which wad is loaded

Things to consider:
- Port needs to recognize if a wad actually contains maps. Savegame dirs should only be created for those, not mere gameplay mods.
- Needs to work with PWADs for Doom 1+2 as well (obviously).

**Comment by fabiangreffrath** [comment]
I am not opposed to this idea, but there are some things to consider.

Take e.g. "requiem.wad", there is a patch for this available to fix some issues with MAP21. So, will savegames get stored into the "req21fix.wad" directory for this one map or will they also get stored into the "requiem.wad" directory as the for the other maps?

**Comment by kraflab** [comment]
Gameplay mods do need to be considered. Dehacked can introduce hundreds of new entities and cause them to spawn in a level without editing the level itself. You wouldn't be able to properly load a save that uses xaser's mbf21 weapon set for instance if you don't have the mod loaded. Depending on what states are replaced and what woof does if it tries to load something that doesn't exist, you could have crashes immediately or delayed. Maybe you could link those non-map-wads to the save files implicitly and load the mod when you load the save. I don't really know what the expected behaviour should be.

**Comment by NightFright2k19** [comment]
Interesting points you are bringing up there. TBH I don't know right now how other ports are handling this.

**Comment by NightFright2k19** [comment]
I have asked in the ZDoom forums about how GZDoom handles this.

Graf Zahl wrote:
"The whole thing only checks IWADs. All PWADs for the same IWAD still get saved to the same folder, unless you explicitly override the destination with -savedir or the save_dir CVAR (the latter is not recommended as it completely disables the system, but needs to be kept for compatibility)"

I guess they took the easy way out to avoid the system to get too complicated.

**Comment by kraflab** [comment]
The way dsda-doom does this is it generates a directory `iwad/pwad1/pwad2/...` and stores the saves there, inside a root data directory that sits in the exe directory (there are things in there besides save files). The concatenated wad list ignores autoload files, so the idea is "these are meaningful files chosen for this session".

**Comment by NightFright2k19** [comment]
Well, we wouldn't need it for anything besides save files. But other than that, the concept seems good to me at first glance.

**Comment by fabiangreffrath** [comment]
It would be a lot easier if we just did per-IWAD savegame directories.

**Comment by NightFright2k19** [comment]
That would basically mean just four different directories, for Doom 1+2, Plutonia and TNT (unless I forgot some)? I mean, most PWADs are for D2 these days, but well... it'd be something.

**Comment by fabiangreffrath** [comment]
Chex, Hacx and (flavors of) Rekkr. 🤷

**Comment by NightFright2k19** [comment]
Ah right, those. Well, it's a sorting mechanism like that, even if it's basic. For me would be OK.

**Comment by fabiangreffrath** [comment]
We would still need a migration path from the current scheme, though.

**Comment by jeffdoggett** [comment]
It's should be noted that some games have a DeHackEd patch that changes the filename.  For instance HacX

Text 13 13
doomsav%c.dsghacxsav%c.dsg
