### ISSUE TITLE
Rock background fails to draw on Screen Size 3 in 21:9 widescreen

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#794]
These images should explain it better:
![woof0000](https://user-images.githubusercontent.com/73968015/200987439-8583e6b0-a66d-4e08-a98b-0c517ef16521.png)
![woof0002](https://user-images.githubusercontent.com/73968015/200987548-967e258b-8217-4daf-aa14-53e4a17abaa3.png)

It only seems to happen with that specific Aspect Ratio and Screen Size combination.

**Comment by fabiangreffrath** [comment]
What a strange bug! Will have to investigate...

**Comment by fabiangreffrath** [comment]
Does this help?

```patch
diff --git a/src/d_main.c b/src/d_main.c
index 54233bc..0650c5d 100644
--- a/src/d_main.c
+++ b/src/d_main.c
@@ -297,7 +297,7 @@ void D_Display (void)
     }

   // see if the border needs to be updated to the screen
-  if (gamestate == GS_LEVEL && (!automapactive || automapoverlay) && scaledviewwidth != 320)
+  if (gamestate == GS_LEVEL && (!automapactive || automapoverlay) && scaledviewwidth != SCREENWIDTH)
     {
       if (menuactive || menuactivestate || !viewactivestate)
         borderdrawcount = 3;
diff --git a/src/r_draw.c b/src/r_draw.c
index eea89bd..f9119e4 100644
--- a/src/r_draw.c
+++ b/src/r_draw.c
@@ -909,7 +909,7 @@ void R_DrawBorder (int x, int y, int w, int h, int s)

 void R_FillBackScreen (void)
 {
-  if (scaledviewwidth == 320)
+  if (scaledviewwidth == SCREENWIDTH)
     return;

   // killough 11/98: use the function in m_menu.c
```

**Comment by MrAlaux** [comment]
Sorry, I won't be able to test it myself up until ~14 hours from now.

**Comment by fabiangreffrath** [comment]
> Sorry, I won't be able to test it myself up until ~14 hours from now.

Alright, let's see who gets home first. 😁

**Comment by liPillON** [comment]
I would argue that any screen size below 7 is not needed anymore..
Does someone actually use it nowadays?

**Comment by fabiangreffrath** [comment]
> I would argue that any screen size below 7 is not needed anymore.. Does someone actually use it nowadays?

It's more effort to remove the code than to keep it. 😉
