### ISSUE TITLE
[Feature] SSG in Doom 1

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#799]
Crispy Doom allows using the Super Shotgun in Doom 1 if Doom 2 is loaded as a PWAD or you just load the SSG assets (sprites and sounds) as a small custom mod. Using it ingame is done via a custom cheat (TNTWEAP9), I guess to avoid adding it by accident when using IDKFA.

Would this be something you guys might consider adding in Woof as well? It's for those lil' cheaters out there.

**Comment by fabiangreffrath** [comment]
Sure, we could do that. :wink:

**Comment by NightFright2k19** [comment]
Be praised!
