### ISSUE TITLE
Remove pointless cheat codes

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#800]
It seems the port has collected some rather pointless cheat codes, or at least some with questionable usefulness, throughout its history. 

Some chat codes modify one single aspect of the game mechanics, working against map authors intentions:

* ice, push, nuke

Some cheat codes have a corresponding menu toggle which achieves the same:

* tran, smart

Or a command line switch:

* fast

Some more obscure ones only apply for beta emulation:

* aim, eek, amo, tst, nc

And some others are simply duplicates of other obscure cheats:

* mbfran

Let's discuss here which ones to keep.

**Comment by NightFright2k19** [comment]
If I am brutally honest... Pretty much all of these are new to me. Are they doing anything special?

**Comment by MrAlaux** [comment]
The ones specific to Beta emulation seem somewhat justified to me, as they're faithful to the original Press Beta, _but_ having to suddenly use different cheats is certainly confusing. `fast` is convenient if I want to avoid having to do the command-line dance. The rest of them seem like debugging aids, if anything, and I personally would get rid of them.

Let's wait and see what other people think.

**Comment by kraflab** [comment]
Some of these may be useful to authors although they don't seem useful to someone playing the game. Toggling ice for instance could be useful for testing. I'd get rid of the beta stuff personally.

**Comment by fabiangreffrath** [comment]
Hm, on the other hand I wouldn't want to remove even obscure cheat codes that are somehow "typical" or "characteristic" for Boom/MBF. Maybe I should just do what we always do and see how PrBoom+ does it. 😁

**Comment by fabiangreffrath** [comment]
Unclear what's "pointless".
