### ISSUE TITLE
Rotate Automap bug?

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#804]
With Follow Mode off and Rotate Mode on, the automap will rotate as normal ONLY if Overlay Mode is disabled, and it won't rotate anymore if it is enabled. As implied by the title, I'm not sure if this is actually a bug.

**Comment by NightFright2k19** [comment]
I think that's actually intended. There were complaints about this before IIRC.

**Comment by fabiangreffrath** [comment]
So, would you prefer the automap to *never* rotate if follow mode is off, regardless of overlay mode? Or would you like the automap to *always* rotate?

**Comment by MrAlaux** [comment]
> So, would you prefer the automap to _never_ rotate if follow mode is off, regardless of overlay mode? Or would you like the automap to _always_ rotate?

Personally, I believe it'd be annoying if the automap rotated when not following the player, since the arrow would jump around the screen and wouldn't be as easy to follow. However, the key to toggle automap rotation is right there, ready to be used at any time, so users can do whatever they'd like. Ultimately, I believe that what should be done is keep behavior consistent across overlay modes, which is not the case and is the reason why I opened this issue.

**Comment by fabiangreffrath** [comment]
> Personally, I believe it'd be annoying if the automap rotated when not following the player, since the arrow would jump around the screen and wouldn't be as easy to follow. 

Yes, so I think I will make "rotate on + follow off + overlay on = do not rotate" the new behaviour even for "overlay off".

> However, the key to toggle automap rotation is right there, ready to be used at any time, so users can do whatever they'd like.

Not quite, because disabling rotate mode would also reset the map orientation.

> I believe that what should be done is keep behavior consistent across overlay modes, which is not the case currently and is the reason why I opened this issue.

Yes, I fully agree here. That's wky I asked. 😉

**Comment by MrAlaux** [comment]
> > However, the key to toggle automap rotation is right there, ready to be used at any time, so users can do whatever they'd like.
> 
> Not quite, because disabling rotate mode would also reset the map orientation.

Indeed, that would still make the arrow suddenly jump around from one point to another, but it wouldn't be constant unlike with rotation always enabled.

> I think I will make "rotate on + follow off + overlay on = do not rotate" the new behaviour even for "overlay off".

Sounds like the key to toggle rotation would serve no purpose in that case. It would personally bug me to have it not do anything when it definitely could, but then again, I don't think many people would want to keep rotation enabled when not following the player.
