### ISSUE TITLE
Skull graphic is misplaced in F1 help screen for -complevel 2.

### ISSUE THREAD

**Issue by Terraformer9x** [fabiangreffrath/woof#826]
I know that this may come off as an incredibly minuscule nitpick, but I couldn't help pointing out an odd inconsistency I noticed in the help screens involving the skull in the corner.

In the F1 help screen, the skull at the bottom right corner is supposed to be just above the text. Here's the screen taken in Chocolate Doom.
![help_chocolate](https://user-images.githubusercontent.com/83795041/205618591-84da10ca-59eb-4f65-8f19-093e9c6f0269.png)

However in Woof, the skull is lower than it's supposed to be. It's actually using the skull position that found in the Doom 1 help screens.
![help_woof](https://user-images.githubusercontent.com/83795041/205618850-1000fa96-30ba-45f4-9a06-05c3a222488a.png)

This only occurs in Doom 2 / -complevel 2. In Final Doom / -complevel 4, the skull is in the correct position on the help screen.

**Comment by fabiangreffrath** [comment]
Hm, I don't understand this. There is some adjustment done for the skull key position on the "Read This" page, but it applies to `gamemode == commercial` which should be true for both Doom 2 and Final Doom. 🤔 

https://github.com/fabiangreffrath/woof/blob/84aa5955d0b5c0233fa71e5ff90e7fb6556b76f9/src/m_menu.c#L6906
