### ISSUE TITLE
Suggestion: Support multiple keys in one slot a la Crispy

### ISSUE THREAD

**Issue by mikeday0** [fabiangreffrath/woof#839]
WAD: Knee-Deep in Knee-Deep in ZDoom
Command-line: `woof -iwad doom2.wad -complevel vanilla -file KDiKDi_A.wad KDiKDi_B.wad`

This wad replaces the skull keys with orange, silver and green key cards and does some offset trickery so that you can display two keys in one slot on the status bar. 

Here's what it looks like on Crispy when you have the yellow key and then pick up the green:
![DOOM0001](https://user-images.githubusercontent.com/43701387/206884493-646936e4-b105-40f7-b51f-a6b7ab5d2727.png)
![DOOM0002](https://user-images.githubusercontent.com/43701387/206884497-8107b7ff-c7c8-44e9-a166-b45d850282c2.png)

Note how the yellow key moves up and to the left, and the green key gets drawn in the lower right. (If you reverse the order of pickup, the green key will initially be drawn in the center of the box and then moved down and to the right.)

Woof does not correctly support this behavior:
![woof0007](https://user-images.githubusercontent.com/43701387/206884535-b733189e-23f8-4727-8715-056602993106.png)
![woof0008](https://user-images.githubusercontent.com/43701387/206884539-371641d1-acf1-44dd-850c-6529934a6468.png)

**Comment by mikeday0** [comment]
I just realized that Crispy has special handling for this situation and that's why it's able to draw multiple keys in one slot like that. Any reason it couldn't be ported to Woof?

**Comment by mikeday0** [comment]
Nevermind, I'm dumb. Woof! supports this already, you just have to change the Setup > Status Bar / HUD > Single Key Display option to "no".

**Comment by fabiangreffrath** [comment]
Although this specific use case is now fixed by allowing to parse (certain entries of) the OPTIONS lump even in non-MBF complevels, I am still considering if we shouldn't just disable "Single Key Display" by default.

**Comment by rfomin** [comment]
> if we shouldn't just disable "Single Key Display" by default.

No objections 😄
