### ISSUE TITLE
unify gamma tables

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#847]
Currently, we provide two ways to apply gamma correction:

1) Using the original gamma tables, which only lighten up the scene.
2) Using a formula to provide darker gamma levels and intermediate ones for the lighter levels.

As it is now, you can apply gamma using only one of both methods. We keep the first one, because some members of the speed-running cmmunity got so much used to the original values that they depend on them being applied to the scene for pixel-perfect positioning for jumps and glides.

The idea is to keep the original gamma tables (1) for lighting up the scene, calculate 4 intermediate levels from them and use the formula (2) to calculate the darker gamma levels.

Concept patch:

```patch
--- a/src/i_video.c
+++ b/src/i_video.c
@@ -1074,13 +1074,24 @@ static byte gamma2table[18][256];

 static void I_InitGamma2Table(void)
 {
-  int i, j;
+  int i, j, k;

-  for (i = 0; i < 18; ++i)
+  for (i = 0; i < 9; ++i)
     for (j = 0; j < 256; ++j)
     {
       gamma2table[i][j] = (byte)(pow(j / 255.0, 1.0 / gammalevels[i]) * 255.0 + 0.5);
     }
+
+  // [crispy] 5 original gamma levels
+  for (i = 9, k = 0; i < 18 && k < 5; i += 2, k++)
+    memcpy(gamma2table[i], gammatable[k], 256);
+
+  // [crispy] 4 intermediate gamma levels
+  for (i = 10, k = 0; i < 18 && k < 4; i += 2, k++)
+    for (j = 0; j < 256; ++j)
+    {
+      gamma2table[i][j] = (gammatable[k][j] + gammatable[k + 1][j]) / 2;
+    }
 }

 int gamma2;
```

**Comment by rfomin** [comment]
This patch is already working well for me 👍
