### ISSUE TITLE
W_GetNumForName: WIMINUS not found on Doom 1.2

### ISSUE THREAD

**Issue by Maidentree** [fabiangreffrath/woof#86]
The maps work fine, but when I hit the use key on the exit switch; it throws up a W_GetNumForName: WIMINUS not found error on the v1.2 version of DOOM.WAD.

**Comment by fabiangreffrath** [comment]
Thanks for the report. I believed that the v1.2 IWAD was only missing the STTMINUS lump, but apparently it is also missing WIMINUS. I'll fix that.

However, why would one still want to play with the v1.2 IWAD nowadays?

**Comment by Maidentree** [comment]
oh, I forgot to say, thanks but also, I don't remember why I had reported this specific issue, but I'm still glad it got fixed (sorry if this is like 3 years later, I just had to say thank you)

**Comment by fabiangreffrath** [comment]
You are very welcome. 😉
