### ISSUE TITLE
less verbosity / more meaningful information

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#860]
We have inherited a lot of debug messages from the DOS era that are printed at engine start-up, but that don't have any useful meaning anymore today.

For a normal start-up , I'd like the engine to print:
 * Its own name and version.
 * The path of its config file.
 * The path of the IWAD it has found.
 * The game mode / mission it has detected.
 * The name / path of each WAD file or DEH patch that it has loaded.
 * Hardware initialization parameters (e.g. during sound init).
 * Progress indicators for data preparation (e.g. sfx caching, texture generation).

What else?

**Comment by rfomin** [comment]
Hmm I like to keep classic Doom startup. I even want to add "DOOM Operating System" and all that stuff 😄

**Comment by fabiangreffrath** [comment]
Oh, wow! 😮

**Comment by fabiangreffrath** [comment]
So, how do we proceed here? I'd like to get away from the current random state of messages that are printed at engine start-up and I think there are two possible directions:

First, we could trim down the messages and only show relevant information. Pretty much what I outlined on my OP.
Second, we could go for full emulation of Doom's start-up screen (or Boom's or MBF's depending on default complevel?).

Whatever we decide, I'd like to get rid of the current none-of-both solution that we inherited from WinMBF.

**Comment by rfomin** [comment]
Actually the current output is pretty much the same as vanilla DOS MBF (screenshot from DosBox):
![mbf_014](https://user-images.githubusercontent.com/5077629/212065256-73913ca0-54d3-4c70-8d27-a870ad8ee89f.png)

I think we need `libtextscreen` to truly emulate the original Doom start screen.

> First, we could trim down the messages and only show relevant information. Pretty much what I outlined on my OP.

Ok, but what to remove? I think we should keep `R_Init: Init DOOM refresh daemon - [...` 😆

**Comment by fabiangreffrath** [comment]
But... hm, I somehow remembered a more graphical start-up like Vanilla. Obviously I was wrong.

Well, arguably lines like `V_Init: allocate screens` or the many `R_Init*` lines do not provide any useful information. Anyway, we could still argue that we are very closely resembling actual MBF.exe start-up messages.

Close this issue?

**Comment by rfomin** [comment]
I agree with `V_Init: allocate screens`, and I've already removed most of the `R_Init*` lines here: https://github.com/fabiangreffrath/woof/pull/662/commits/aa09c97d4b976f76e5b27e8adb14af633c852b7b#diff-0012ac8152ee6fa1745d91838559e54249cddef7857b3dceb884f70b2e4ca949

> Close this issue?

We can clear more things. I agree with everything but I want to keep the most memorable lines like `R_Init: Init DOOM refresh daemon`.

**Comment by fabiangreffrath** [comment]
Okay, fine with me.

What bugs me most is that (1) the port doesn't even print its own name, (2) it prints the wrong version number and (3) the game mode/mission information is redundantly provided twice.

**Comment by rfomin** [comment]
> (1), (2) and (3)

Sure, no objection.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/32e7b145fc4c5617a3dfaeb06e9c21990514e726
