### ISSUE TITLE
Mouse Support for Menus

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#861]
Would it be out of the scope to have the ability to navigate the menus with the mouse? I think it would be a nice addition to have that makes the port feel that much more fluid.

**Comment by rfomin** [comment]
Good idea, but only if it works in the style of Unity port and not a vanilla Doom exe. I'll try to experiment with it.

**Comment by OpenRift412** [comment]
> Good idea, but only if it works in the style of Unity port and not a vanilla Doom exe. I'll try to experiment with it.

That's what I meant, I don't mean like the weird mouse menu scrolling that games had around when Doom came out lol.

**Comment by fabiangreffrath** [comment]
So, we are talking about moving between menu entries with the mouse wheel and LMB = enter and RMB = back?

**Comment by rfomin** [comment]
> So, we are talking about moving between menu entries with the mouse wheel and LMB = enter and RMB = back?

No, about real clicks on menu items with the cursor. It's possible, but requires some work.

**Comment by fabiangreffrath** [comment]
Oh, wow!

**Comment by rfomin** [comment]
Done in https://github.com/fabiangreffrath/woof/commit/1503cfed67833f76b75186933a81900475c20e23
