### ISSUE TITLE
woof loads doom2.wad even when doom.wad is in the directory of the program

### ISSUE THREAD

**Issue by Swim-Swim-Hungry** [fabiangreffrath/woof#866]
make woof load the closest iwad to the executable

**Comment by fabiangreffrath** [comment]
IWADs are searched for in a certain order and `doom2.wad` comes first. I think it's the same in about any other source port. If you want to explicitly select a certain IWAD, use the `-iwad` parameter. 

https://github.com/fabiangreffrath/woof/blob/73dc94480cbadf6e90d94e858b32282e49b08650/src/d_iwad.c#L27-L43
