### ISSUE TITLE
Directory-based Addons Menu

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#871]
I'd been thinking about the idea of a sort of integrated method for loading WAD for Doom in a more streamlined and user-friendly way, when I remembered this something that Nightdive's Blood: Fresh Supply does with loading custom addons.

What I'm proposing here is having an addons subdirectory for Woof, in which you would put a folder containing WADs, DEHs, Response Files, etc. for your corresponding mod. In-game, there would be an "Addons" option in the Options menu. Selecting this would show a list of all the folder names listed in your addons directory, and selecting one of the listings would restart Woof, loading all the addon files in the respective folder.

Would this work within the scope of this port?

**Comment by OpenRift412** [comment]
> To me, that sounds like a feature best incorporated into a launcher rather than a particular port. Or maybe it even already is a thing.

Sure, but having a launcher isn't a very elegant solution. Like it works fine but it's not anywhere as user-friendly as having it contained within the main app. I think it would be a good addition for new players.

**Comment by kraflab** [comment]
What you're suggesting is to embed a launcher inside the port and then close and reopen it. That's the polar opposite of elegant. Stand-alone launchers are also significantly more friendly for new players especially. The thing with a launcher is that it does the launching for you, which takes away a lot of the confusing parts of playing doom.

**Comment by OpenRift412** [comment]
> What you're suggesting is to embed a launcher inside the port and then close and reopen it. That's the polar opposite of elegant. Stand-alone launchers are also significantly more friendly for new players especially. The thing with a launcher is that it does the launching for you, which takes away a lot of the confusing parts of playing doom.

I want you to take a look at how Blood: Fresh Supply does their addons menu to see what I mean. Hell, even what the Unity Port does it to a degree. Everything's all in one place, you don't have to bother with this whole mess of settings with an external tool. It's just a clean list of the addons you have installed. You don't have to go through an ugly launcher.

![image](https://user-images.githubusercontent.com/29780788/212205973-a3235d19-6837-450e-bfd1-f78609ae1446.png)

To be clear, when I say "restart" in this context, I mean it reloads the title sequence with the new WAD, not completely restarting the application.

**Comment by rfomin** [comment]
> You don't have to go through an ugly launcher.

I like Unity's port addons menu and was thinking of adding a launcher based on libtextscreen or ImGui. But maybe modern beautiful standalone launcher with idgames integration is better idea, https://github.com/nstlaurent/DoomLauncher is close.

**Comment by fabiangreffrath** [comment]
I agree with the concerns expressed here that it's not the port's duty to *organize* your add-ons. You could bundle them in ZIP files and load them as one package on the commend line, but adding a file browser to the menu to load entire directory content at once is pretty sure outside our scope. Thanks for the suggestion anyway!

**Comment by fabiangreffrath** [comment]
Also, the Unity port supports only a hard-coded fixed set of addons (just like Crispy supports nerve.wad and masterlevels.wad, arguably), so this is hardly comparable as prior work.
