### ISSUE TITLE
[Feature] IDBEHOLD powerup cheats as toggles

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#875]
Some IDBEHOLD powerup cheats are only temporary (R/I/V/L). It would be neat to turn these into toggles, pretty much like others such as the automap cheat, meaning that e.g. a radsuit cheat would last until you type the code a second time. 

It works like that in PrBoom+ and is a consequent change to make all cheats work the same way (e.g. like IDCLIP, IDDQD etc). Besides that, since these are cheats, one might want to use them as long as they like, not needing to reactivate them when the timer runs out.

As a compromise, this could be a menu option, labelled s.th. like "Powerup cheats as toggles".

**Comment by MrAlaux** [comment]
I might be missing something, but isn't there a setting in the Doom Compatibility menu that does exactly this?

**Comment by fabiangreffrath** [comment]
Yep, right, there is already a toggle for this in the compatibility menu.

**Comment by NightFright2k19** [comment]
Alright, didn't see that. Thanks for the clearification!
