### ISSUE TITLE
[Bug/Feature] UMAPINFO: intertext = clear on MAP30

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#876]
[As stated in this ticket for PrBoom+](https://github.com/coelckers/prboom-plus/issues/536#issuecomment-1402253538), we need some fix for UMAPINFO behavior in MAP30 (and possibly its Doom 1 counterparts, i.e. ExM8) when using code like this:

```
MAP MAP30
{
  intertext = clear
}
```

What this is supposed to do is: Show level stats, skip the text for the intermission at the end of the game and jump right to the endcast, but instead it shows the level stats, then jumps straight to MAP01 (no intermission text or endcast). Any attempts with _endcast_ or _endpic_ remain unsuccessful. With _nointermission = true_, you are able to kind of get there, but then the level stats are skipped.

**Comment by rfomin** [comment]
This is a known issue and cannot be fixed in a demo-compatible way. Perhaps in the future, with a new version of UMAPINFO or a new complevel.

**Comment by NightFright2k19** [comment]
Alright. I'll leave my code as it is right now, then, hoping for a port-sided fix.
