### ISSUE TITLE
Demo desync in -complevel 9

### ISSUE THREAD

**Issue by fraansg** [fabiangreffrath/woof#883]
Hi!

I come to report a demo desync issue that occurs in -complevel 9. I playbacked the demo on other ports, and the problem doesn't take place on dsda-doom (v0.25.6), prboom+um (v2.6.2) nor prboom-plus (v2.5.1.5), but yes on woof (v10.5.1).

This is the file with which the issue occurred (desync take place in map09):
https://dsdarchive.com/files/demos/aaliens/48481/aad2alluvmax-40053.zip

My command line to launch the demo in that map was as follows:
`woof -iwad doom2.wad -file aaliens.wad -complevel 9 -warp 09 -playdemo aad2alluvmax-40053.lmp`

The issue take place with the original aaliens.wad and with aaliens_v1_1.wad in woof (in the other source ports I only checked the v1.1 version of that pwad).

I also leave the link to the pwad: https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/aaliens

Before I say goodbye, I will take the opportunity to thank you for all the work you do in this source port. Thanks!

**Comment by rfomin** [comment]
You probably have a umapinfo.lmp file in your autoload folder. Check the `autoload/aaliens.wad` path or try running it with the `-nomapinfo` command line option.

I can't reproduce it, we regularly test this demo and most of the DSDA archive.

**Comment by fraansg** [comment]
Thanks!
Effectively, I had the umapinfo lump in the autoload folder, the reproduction with -nomapinfo solve the problem.

**Comment by fabiangreffrath** [comment]
Thanks for the fast resolution to both of you!
