### ISSUE TITLE
switch to "linear" resampling for SDL >= 2.28

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#884]

**Comment by fabiangreffrath** [comment]
We could also add a run time check for SDL version around the hint. Or just change the hint to "linear" now - and if SDL doesn't know this, it will fall back to the default resampling method anyway.

**Comment by rfomin** [comment]
> Or just change the hint to "linear" now

Yes, I think we should do so. Also we should not release until SDL 2.28 is available (March?), the default resampling method is slower and sounds different from the previous release.
