### ISSUE TITLE
mouse movement not working when mouse held for strafing

### ISSUE THREAD

**Issue by ribbiks** [fabiangreffrath/woof#891]
Greetings, noticed an issue after updating to macOS 13 that mouse movement (i.e. turning inputs) no longer work if a mouse button is held down for strafing (I tried mouse1-5, same for all of them). e.g. you can't hold mouse2 and move mouse to strafe, player just sits there immobile.

Was tested on a fresh install of latest woof, unmodified cfg. For comparison dsda-doom works as expected so I don't think the issue is entirely on my end.

**Comment by ribbiks** [comment]
as an addendum, this is not an issue in an older version of woof that I have lying around from march 2022. I can try a few recent commits to see if I can pin down at which point it broke.

**Comment by rfomin** [comment]
We have added a new mouse sensitivity setting "horizontal: strafe" (default 0), change it to mouse strafe.
@fabiangreffrath maybe we should change the default value?

**Comment by ribbiks** [comment]
ahah. I feel silly for not checking the mouse menu for new options but I've had experiences before with prb+ eating mouse inputs so my first thought was that it was something mac-specific. Indeed probably makes sense for the default value be nonzero though.

thanks!
