### ISSUE TITLE
game audio is being lowpassed?

### ISSUE THREAD

**Issue by ribbiks** [fabiangreffrath/woof#892]
It seems like all game audio is being put through a lowpass filter, which sounds strange and rather bad. Here's a spectrogram comparison of some gameplay audio from woof circa march 2022 (on the left) vs. latest woof (on the right):

![Screenshot 2023-02-02 at 2 08 52 PM](https://user-images.githubusercontent.com/74789959/216439095-edd22bd6-ebf9-41a6-a8bc-fb01e4f7d68a.png)

I'd upload mp3s but github doesn't seem to allow that.

Is there some config option that changed somewhere maybe?

**Comment by fabiangreffrath** [comment]
Yes this will change again back to the better in the near future. Some background is provided in the thread starting here:

https://www.doomworld.com/forum/topic/112333-this-is-woof-1051-dec-28-2022-updated-winmbf/?page=56&tab=comments#comment-2593676

**Comment by mikeday0** [comment]
Linear resampling produces aliasing artifacts which you can see in the spectrum here:
![image](https://user-images.githubusercontent.com/43701387/216615419-520aafce-626f-4a2d-b8bc-67eac3198c93.png)

These are perceived as a high-frequency shimmer on top of the original sound. It is a form of distortion. (Comparable in effect to turning up sharpness or enabling edge enhancement on your TV.) The spectrum on the right is more "correct" from a signal fidelity standpoint. That is, it's showing a resampling process (sinc resampling) that's not adding extra noise or artifacts that weren't present in the original signal. That said, I think most people prefer the sound of linear resampling for the Doom sounds.

**Comment by fabiangreffrath** [comment]
Yes, because that's the sound most people are used to in the age of source ports. Even though sinc-resampling may be considered as more "correct", it simply doesn't match what people are used to hear - and expect to hear. Every decision from this is perceived as "wrong", and I understand this.

**Comment by fabiangreffrath** [comment]
BTW, @ribbiks which software did you use to generate these graphs?

**Comment by mikeday0** [comment]
> Yes, because that's the sound most people are used to in the age of source ports. Even though sinc-resampling may be considered as more "correct", it simply doesn't match what people are used to hear - and expect to hear. Every decision from this is perceived as "wrong", and I understand this.

You are spot-on, no disagreement here. Just providing some background info for any curious minds who might be reading.

**Comment by ribbiks** [comment]
> BTW, @ribbiks which software did you use to generate these graphs?

I used Audacity (specifically: analyze --> plot spectrum)

**Comment by fabiangreffrath** [comment]
SDL_Mixer is a thing of the past now.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/1a278d6105c8df9007f47cda61b6c02a2afc66b6
