### ISSUE TITLE
Stutter in weapon switch animation with bobbing disabled on Doom 4 Vanilla

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#893]
_Tested in the 10.5.1 release._

Consider the following scenario: playing D4V with bobbing disabled, you switch from the Fists to the Pistol. For a brief moment, when the actual switch to the Pistol is performed, the sprite is drawn at what would be its final position (i.e. when it is done raising), then it snaps downwards again and resumes the raise animation as usual.

Note that most of D4V's weapons - including the Pistol - use coordinate set (`misc1` and `misc2`) both when lowering and raising to achieve quick weapon switching. Knowing this, I believe that a fix for the issue would be to add `&& !psp->state->misc1` at [this line](https://github.com/fabiangreffrath/woof/blob/master/src/p_pspr.c#L1094).

**Comment by fabiangreffrath** [comment]
> Knowing this, I believe that a fix for the issue would be to add `&& !psp->state->misc1` at [this line](https://github.com/fabiangreffrath/woof/blob/master/src/p_pspr.c#L1094).

Yes, pretty sure that's the fix. Thanks!
