### ISSUE TITLE
"Gray %" menu item still available when using red numbers

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#897]
The setup menu item to toggle `sts_pct_always_gray` remains interactable even if `sts_always_red` is enabled, in which case the former variable has no effect.

**Comment by fabiangreffrath** [comment]
Indeed. Seems to be a bug inherited from MBF: the `sts_pct_always_gray` config keys only has effect if `sts_always_red` is disabled. 

https://github.com/fabiangreffrath/woof/blob/e76c6561d22be8b6cac105df73c6663463692066/src/st_lib.c#L216-L226

**Comment by MrAlaux** [comment]
If it's any relevant, I'd go for the possibility of toggling gray percents regardless of red numbers, instead of disabling the menu item when red numbers are enabled.

**Comment by fabiangreffrath** [comment]
Yep, that's what I'm going to do. 👍
