### ISSUE TITLE
audio: midiproc process for Windows

### ISSUE THREAD

**Issue by tpoppins** [fabiangreffrath/woof#90]
Win 7 x64 Pro SP1, Woof 1.2.2.

I'm sure you're well familiar with the symptoms. 
Crispy has crispy-midiproc.exe, what about Woof?

Great port otherwise, no need for Crispy Boom now, eh?

**Comment by fabiangreffrath** [comment]
I'd be okay if someone submitted this as a PR, but I don't feel any incentive to implement this myself.
