### ISSUE TITLE
W_GetNumForName: STBAR not found!

### ISSUE THREAD

**Issue by Maidentree** [fabiangreffrath/woof#901]
yeah sorry if this is like, another one of those "it errors when I try to run this ancient version of the DOOM.WAD" issues,
(i'd figure I'd report this issue while you're still possibly taking in compatibility issue reports)

but yeah, Doom v1.1 (and also Doom v1.0 (which was shareware only)'s DOOM.WAD doesn't load at all, it just throws a 
"W_GetNumForName: STBAR not found!" error, unlike Doom v1.2's DOOM.WAD (where the issue with pressing the exit button in a level sprung up an error, which did get fixed) (although I'm not sure how this one would be tackled since the image that STBAR is, was two (STMBARL and STMBARR) prior to v1.2)

(again, it's really nice that there are some source ports that don't mind running older versions of the Doom and Doom II wad files, but you're right about "However, why would one want to play with the DOOM v1.2 wad nowadays?", (well, me not being able to answer that question, sorry about that) I'm not sure why I asked that one, and just out of curiosity, I tested running v1.1 in MBF in DOSBox, and it launched, but it was weird seeing the nightmare skill level being available in a version before the nightmare skill level was even introduced)

**Comment by fraansg** [comment]
MBF solved the problem of the missing lumps in early iwads versions with the inclusion of predefined lumps in the same executable. Some of these are missing in Woof because they were removed due to being non-free (#59).

Even adding the STBAR lump, the M_NMARE lump would still be missing to turn the iwad playable, as well the DSGETPOW lump to get sound when collecting powerups @fabiangreffrath

**Comment by fabiangreffrath** [comment]
Thank you for the additional hints @fraansg !

**Comment by fabiangreffrath** [comment]
> Even adding the STBAR lump, 

We would have to support the split left/right status bar, which shouldn't be much of a problem.

> the M_NMARE lump would still be missing to turn the iwad playable, 

Is it preferred to have the skill selection menu printed with the HUD font but have the Nightmare skill available? Or should we just cut the Nightmare skill off the skill selection menu?

> as well the DSGETPOW lump to get sound when collecting powerups @fabiangreffrath

This is also easy to add a workaround.

**Comment by rfomin** [comment]
Should we support Doom v1.2 in Woof? This will not be demo compatible.

**Comment by fabiangreffrath** [comment]
This is only about getting the IWADs to load without crashes. We are not talking about game engine emulation for versions earlier than 1.9 (yet).
