### ISSUE TITLE
Default handlings and umapinfo

### ISSUE THREAD

**Issue by fraansg** [fabiangreffrath/woof#904]
The same issue reported in PrBoom-Plus almost a year ago [UMAPINFO: Questionable default handling of exiting the secret levels](https://github.com/coelckers/prboom-plus/issues/498) is present in Woof (doesn't crash, but is unable to continue to the "expected" map). Regardless of the convenience or not of the given handling, I think it goes against the specification.

**Comment by fabiangreffrath** [comment]
This will be clarified alongside https://github.com/coelckers/prboom-plus/issues/498
