### ISSUE TITLE
How to get helper dogs?

### ISSUE THREAD

**Issue by dfgdgdgfd** [fabiangreffrath/woof#908]
-dogs from mbf doesn't work.

**Comment by rfomin** [comment]
`woof -dogs 2` works for me. What complevel do you have? Check "default compatibility" in Options -> General -> Last Page, it should be MBF or MBF21. Or run the game with `-complevel mbf`.

**Comment by fabiangreffrath** [comment]
Just checked: `-dogs 1` works with `-complevel 11` but not with `-complevel 2` or `-complevel 9`.

Furthermore, `-dogs` alone does not work at all, although it should:
```
No parameter for '-dogs'.
```
In that case, it should fall back to use the `default_dogs` config variable.

Maybe we should give `-dogs` the same treatment as `-beta` and fail with an explicit error message if the corresponding complevel does not match.

**Comment by fabiangreffrath** [comment]
```patch
--- a/src/g_game.c
+++ b/src/g_game.c
@@ -3113,6 +3113,9 @@ void G_ReloadDefaults(boolean keep_demover)
   if (beta_emulation && demo_version != 203)
     I_Error("G_ReloadDefaults: Beta emulation requires complevel MBF.");
 
+  if ((M_CheckParm ("-dog") || M_CheckParm ("-dogs")) && demo_version < 203)
+    I_Error("G_ReloadDefaults: Helper dogs require complevel MBF or MBF21.");
+
   if (demo_version < 203)
   {
     monster_infighting = 1;
```
