### ISSUE TITLE
242 drawn heights, ceils and floors disappeared

### ISSUE THREAD

**Issue by simc2** [fabiangreffrath/woof#91]
Hi, it seems that linetype 242 floors and ceilings got broken in Woof 2.0.0. 
The false floors and ceilings are not rendered; the sectors are now always drawn 
by their original heigths and not by the subsectors. They did work in 1.2.2. 

![24](https://user-images.githubusercontent.com/27227020/86982159-4200f880-c191-11ea-93f6-89296d256461.jpg)

For example boomedit.wad:
https://www.doomworld.com/idgames/themes/TeamTNT/boom/boomedit

**Comment by fabiangreffrath** [comment]
Oh. Does it make a difference if you have uncapped frame rate enabled or not?

**Comment by simc2** [comment]
Uncapped frame rate had no difference. Thanks for the fix.
