### ISSUE TITLE
Unused sectors and zero-length linedefs cause Singal 11 exit

### ISSUE THREAD

**Issue by dististik** [fabiangreffrath/woof#917]
Found in the PWAD [1killtng.wad](https://www.doomworld.com/idgames/levels/doom2/megawads/1killtng) map13 on all complevels. Woof throws the error:

> I_SignalHandler: Exit on Illegal storage access (Signal 11)

When loaded in DSDA-Doom -complevel 2 it throws this error:

> P_LoadSideDefs2: sidedef 1315 has out-of-range sector num 65535
P_LoadSideDefs2: sidedef 1705 has out-of-range sector num 65535
P_LoadSideDefs2: sidedef 1833 has out-of-range sector num 65535
P_LoadSideDefs2: sidedef 2391 has out-of-range sector num 65535
P_LoadSideDefs2: sidedef 2454 has out-of-range sector num 65535
P_LoadSegs: linedef 2223 for seg 3761 references a non-existent sidedef 65535

And when opened in Ultimate Doom Builder it throws these warnings:

> Linedef 1891 is zero-length. Linedef has been removed.
Linedef 2234 is zero-length. Linedef has been removed.
Sector 517 was unused and has been removed.
Sector 516 was unused and has been removed.
Sector 515 was unused and has been removed.
Sector 509 was unused and has been removed.
Sector 489 was unused and has been removed.
Sector 487 was unused and has been removed.
Sector 483 was unused and has been removed.
Sector 481 was unused and has been removed.
Sector 479 was unused and has been removed.
Sector 477 was unused and has been removed.
Sector 470 was unused and has been removed.
Sector 469 was unused and has been removed.
Sector 455 was unused and has been removed.

However, the map loads fine in Chocolate.

**Comment by dististik** [comment]
Oh my goodness I am very sorry it does not load in Chocolate fine I just accidentally opened the version of the map I fixed when testing and immediately realized after submitting the issue. Huge apologies.

**Comment by fabiangreffrath** [comment]
No problem, thanks for the report! Woof shouldn't crash with a segmentation fault no matter what mapping error occurs, so I reopen this to fix the crash and properly exit with an error message.
