### ISSUE TITLE
[Feature] Muting "Unknown Thing Type" warnings

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#919]
There are some rare PWADs out there like "Herian 2" which were made with ZDoom in mind, but would also work in other Boom compatible ports with a few minor limitations.

When running "Herian 2" with Woof, you would get "_Unknown Thing Type at (coordinates)_" warnings after loading each map since they contain ambience sound markers which are unsupported by the port. PrBoom+ behaves better, not showing these warnings in the first place.

If there is no official way to mute those warnings, it would be nice to have an option to turn them off. (I am aware these can be useful for debugging, which is why I am not requesting to simply remove them.)

**Comment by fabiangreffrath** [comment]
Wait a minute, do these warnings appear as in-game player messages?

**Comment by rfomin** [comment]
> Wait a minute, do these warnings appear as in-game player messages?

Yes, I think we should simply remove it: https://github.com/fabiangreffrath/woof/blob/81b2f888222e5d3f6c9da01fc583ca614ff46641/src/p_mobj.c#L1243

**Comment by fabiangreffrath** [comment]
Yes.

**Comment by rfomin** [comment]
Done in https://github.com/fabiangreffrath/woof/commit/1997a14c1f7f6963b0f1e3b608d700b3b64dfdc4

**Comment by NightFright2k19** [comment]
Outstanding! Thanks a lot!
