### ISSUE TITLE
add Crispy's any-to-red/green/blue color translation tables

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#920]
for status bar numbers and probably the menu (but not anything affecting in- game rendering)

**Comment by fabiangreffrath** [comment]
Must not forget to check for PWAD-provided translation tables and always prefer them.

**Comment by liPillON** [comment]
I'll leave this here, in case you guys missed it:
https://www.doomworld.com/forum/post/2613723

**Comment by fabiangreffrath** [comment]
Thank you! I am on it.

This is a left-over semantic mismatch of Boom's CR_RED translation which actually meant "no translation", the CR_NONE translation which means "no translation" now and its usage in HUD widgets which currently means "back to the widget's original translation" - which is wrong in this case.

**Comment by liPillON** [comment]
hmm 

I've checked my recent posts in the woof thread and found only these:
- new feature: framerate cap option, from crispy
- enhancement(?): draw the overlay automap over the entire screen, when screensize>7

should I open a github issue for each?
