### ISSUE TITLE
[Feature] bind cheats to keys

### ISSUE THREAD

**Issue by Vulldozer** [fabiangreffrath/woof#922]
I'd love to be able to bind specific keys to activate a cheat in the keybindings menu as typing any cheat that starts with "id" causes me to move to the right after clicking D

**Comment by fabiangreffrath** [comment]
yo dawg I heard you like cheating so I put single key cheating in my port so you can cheat while you cheat 🤣

**Comment by Vulldozer** [comment]
Lol 🤣

I'd be really thankful if you consider adding it, I need to constantly toggle idclip on and off when working on my map and when typing IDCLIP I sometimes fall of platforms after hitting D

**Comment by fabiangreffrath** [comment]
@rfomin Do you think it will work if we let users edit the cheat strings in the (e.g. keybinding) menu and if the string for the "noclip" cheat code is changed from "IDCLIP" to "D" then simply pressing the `D` key will toggle the cheat?

**Comment by kraflab** [comment]
What about wads that change the codes in dehacked? You also wouldn't be able to bind mouse or controller buttons or certain keys (shift, enter, etc).

**Comment by rfomin** [comment]
I think people want this menu (screenshot from DSDA-Doom):
![doom00](https://user-images.githubusercontent.com/5077629/221834148-dffc5555-0e23-441d-9d2e-3bbf44c168ec.png)
Not gonna lie, it's pretty convenient.

**Comment by Vulldozer** [comment]
> I think people want this menu (screenshot from DSDA-Doom):
Yes this is pretty much what I hope for, I can use dsda-doom in the meantime but I'd love to see it in woof as well.
