### ISSUE TITLE
Viddump support.

### ISSUE THREAD

**Issue by ClassicSSGEnjoyer** [fabiangreffrath/woof#927]
Since, you know that DSDA Doom and its father PrB+ (🤣), both support the -viddump parameter, I think, it would be cool if even this port support -viddump as it will be definately an enhancement in the port and the demo recorders won't need to install any other port just for viddumping the demos to videos.

So, I think it would be cool if this port also supports -viddump.

Also, I was just kidding by saying that PrB+ is father of DSDA Doom lol

**Comment by kraflab** [comment]
I would recommend against this. I would remove vidddump from dsda-doom if I could, but this is an essential component as it's the go-to for creating renderings of demos. There's a lot of extra complexity in the port to support it. It makes perfect sense to me to have an extra demo-to-video tool, and dsda-doom can be configured to look like wood for viddump if it's a preference there. Better to save woof the intrusion.

**Comment by fabiangreffrath** [comment]
Actually, I was working on a branch that adds this to Chocolate Doom some 8 years ago. However, the approach was rather ad-hoc and I couldn't find a solution to add sound/music to the resulting video, so I gave up on this.

https://github.com/chocolate-doom/chocolate-doom/commit/ae2b806364c06e26331067b3850fce14affacb74

**Comment by fabiangreffrath** [comment]
Yep, this doesn't sound like fun. I doubt that anyone will ever again want to code this into a general purpose port that serves as more then a demo-to-video recording machine.

**Comment by rfomin** [comment]
As far as I understand, this OpenAL extension can be used for non-realtime audio rendering: https://openal-soft.org/openal-extensions/SOFT_loopback.txt
I haven't experimented with it yet.

**Comment by ClassicSSGEnjoyer** [comment]
All right. No problem if you don't wanna fix this. But hey @kraflab, dude, I was just kidding that PrB+ is father of DSDA. Don't take my words seriously please.

**Comment by ClassicSSGEnjoyer** [comment]
I will close this issue. Take care guys.

**Comment by ClassicSSGEnjoyer** [comment]
Also, the original monster sound effects of Id's Original Code i.e 1.1 aren't seem to be supported in DSDA Doom, but are supported in Woof source port. Those effects are very pleasing and funny to my ears. I would like if you i.e @kraflab put those funny sound effects in DSDA Doom source port.
