### ISSUE TITLE
show ENDOOM screen / setup window with "nearest" scaling method

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#929]
Repeatedly requested on Doomworld: To prevent a blurry appearance of the ENDOOM screen (or the setup tool), scale the screen by "nearest" method. Probably depending on font size?

**Comment by fabiangreffrath** [comment]
Like this probably?
```patch
--- a/textscreen/txt_sdl.c
+++ b/textscreen/txt_sdl.c
@@ -478,7 +478,7 @@ void TXT_UpdateScreenArea(int x, int y, int w, int h)
 
     SDL_UnlockSurface(screenbuffer);
 
-    SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "linear");
+    SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, (font == &large_font) ? "linear" : "nearest");
 
     // TODO: This is currently creating a new texture every time we render
     // the screen; find a more efficient way to do it.
```

**Comment by fabiangreffrath** [comment]
Well, no, this will produce severe artifacts in the setup window.

**Comment by rfomin** [comment]
The idea was to try "smooth pixel scaling" for textscreen windows. I doubt it will look good, there is no way to scale bitmap fonts to non-integer multiples. The alternative is to switch to TTF.

**Comment by Swim-Swim-Hungry** [comment]
I FUCKING HATE THE BLURRY ENDOOM SCREEN!!!

**Comment by Swim-Swim-Hungry** [comment]
But may I suggest a windowed ENDOOM like in Chocolate or Crispy Doom?

**Comment by fabiangreffrath** [comment]
Maybe we should use nearest scaling for the ENDOOM screen, but linear for the Setup tool.

**Comment by fabiangreffrath** [comment]
We could still allow resizing of the Setup window, but simply not apply aspect ratio correction anymore.

**Comment by ceski-1** [comment]
> But I want to try something, maybe downsampling and a "sharp" shader.

This is the solution. Sharp-bilinear. It's right there in RetroArch and it looks fine.

**Comment by ceski-1** [comment]
Every window should be consistent too (game, setup, endoom).

**Comment by rfomin** [comment]
> We could still allow resizing of the Setup window, but simply not apply aspect ratio correction anymore.

Currently we don't apply aspect ratio correction to textscreen, it looks even worse with it.

> This is the solution. Sharp-bilinear. It's right there in RetroArch and it looks fine.

RetroArch's shader system is perhaps too complex. I'm thinking about DOSBox-staging or DOSBox-X.

**Comment by ceski-1** [comment]
> RetroArch's shader system is perhaps too complex. I'm thinking about DOSBox-staging or DOSBox-X.

Right, no need to go into a full shader system, but sharp-bilinear is simple and very good.

**Comment by fabiangreffrath** [comment]
Hm, honestly I'd rather use what we already got from SDL.

**Comment by fabiangreffrath** [comment]
There is also `SDL_HINT_RENDER_SCALE_QUALITY "best"`, at least on Windows. Did we ever check this?

**Comment by fabiangreffrath** [comment]
> But may I suggest a windowed ENDOOM like in Chocolate or Crispy Doom?

We came from there. Also, what would that change in terms of scaling quality?

**Comment by fabiangreffrath** [comment]
How about we restrict scaling to integer multiples?

**Comment by rfomin** [comment]
> How about we restrict scaling to integer multiples?

This is roughly the old Choco system. I think we'll come back to it if all else fails 😄

**Comment by liPillON** [comment]
compare and contrast with how things were before the PR:
- setup: ![definitely an improvement](https://user-images.githubusercontent.com/48625273/225864628-31f54f0a-669e-476f-8208-fd2804ec58c6.png)
- windowed endoom: ![blurrier, slight pixel distortion](https://user-images.githubusercontent.com/48625273/225864634-f10d7c00-9d3f-4285-9f41-5677fe24ecbe.png)
- fullscreen endoom: ![crispier, stronger pixel distortion](https://user-images.githubusercontent.com/48625273/225864632-fc345b93-8713-4cbf-8d2b-fa5480ce044f.png)
