### ISSUE TITLE
Boom linetype 242 and height changes

### ISSUE THREAD

**Issue by simc2** [fabiangreffrath/woof#93]
Woof 2.1.0
Windows x64

It appears that Boom line type 242 fake floors and ceilings retain their initial heights from the level start if the control sector that sets up the drawn heights changes it's floor and ceiling heights.

A test wad for Doom2 map01:
[242heightchange.zip](https://github.com/fabiangreffrath/woof/files/5139494/242heightchange.zip)

**Comment by fabiangreffrath** [comment]
Sorry, I don't quite understand. You mean the moving lava pillar in the back of the map, right? What exactly is the water pool on the left supposed to look like?

**Comment by fabiangreffrath** [comment]
Alright, got it:
```
--- a/Source/r_bsp.c
+++ b/Source/r_bsp.c
@@ -657,6 +657,11 @@ static void R_Subsector(int num)
   //      when you're standing inside the sector.
   R_MaybeInterpolateSector(frontsector);

+  if (frontsector->heightsec != -1)
+  {
+    R_MaybeInterpolateSector(&sectors[frontsector->heightsec]);
+  }
+
   // killough 3/8/98, 4/4/98: Deep water / fake ceiling effect
   frontsector = R_FakeFlat(frontsector, &tempsec, &floorlightlevel,
                            &ceilinglightlevel, false);   // killough 4/11/98

```
