### ISSUE TITLE
[feature] framerate cap settings (from crispy)

### ISSUE THREAD

**Issue by liPillON** [fabiangreffrath/woof#935]
first mentioned in doomworld's thread

these are the PRs that prompted me to request the feature
https://github.com/fabiangreffrath/crispy-doom/pull/970
https://github.com/fabiangreffrath/crispy-doom/pull/988

**Comment by fabiangreffrath** [comment]
Any takers? @mikeday0? :wink:

**Comment by mikeday0** [comment]
Sure, I’ll have a go at it.
