### ISSUE TITLE
[feature] Skip Level Finished Screen

### ISSUE THREAD

**Issue by Chonkblonk** [fabiangreffrath/woof#938]
UMAPINFO has an argument which lets you make a map skip showing the score screen upon ending, BUT, this only works for levels where the game ends, not between regular levels.

What I'm looking to do is to put a text crawl before the first level of an episode, and you could do this with an empty dummy level which exits itself, but it will inevitably take you to the score screen anyway, which isn't exactly clean looking.

Is it out of line to add the ability for Woof to do this for levels which aren't ending the game? Or would you rather stay consistent with other ports? I asked Kraf if this was something which could be tweaked with UMAPINFO as a format, but it seems he's got no plans for anything of the like any time soon, and he'd rather the standard stay consistent, as I understood.

I'm not sure if this would introduce any problems, but possibly for multiple level demo recordings it could maybe cause a desync if input is expected for the score screen and now that screen isn't there when played up in another port which skips the screen. Maybe the .exe deliberately doesn't skip score screens when playing up a demo?

It's a small cosmetic thing, so it's not exactly a big deal to have an awkward transition, but maybe you can think of something, or maybe you know something I've missed.

**Comment by fabiangreffrath** [comment]
> Is it out of line to add the ability for Woof to do this for levels which aren't ending the game? Or would you rather stay consistent with other ports? I asked Kraf if this was something which could be tweaked with UMAPINFO as a format, but it seems he's got no plans for anything of the like any time soon, and he'd rather the standard stay consistent, as I understood.

Exact same reply here, sorry. We neither are going to risk demo desync under any circumstances.

**Comment by Chonkblonk** [comment]
I figured as such, I assume it wouldn't help to prevent the added skipping behavior when recording and playing demos, then? It wouldn't be important there, and I think there's a few bonus features which Woof has which are handled that way.
Optionally, if a pre-level text crawl/image display could be used, which just the same is skipped if recording or playing demos?

Otherwise, I guess I'll just deal with it, I'm already putting in some minor visual flair in a patch for running with GzDoom, so maybe that will allow the smoother transition, until some day UMAPINFO maybe adds a few new options.
