### ISSUE TITLE
video: widescreen support

### ISSUE THREAD

**Issue by rctGuy101** [fabiangreffrath/woof#94]
Just an idea.

**Comment by pwseo** [comment]
Probably [not the most pressing issue](https://www.doomworld.com/forum/topic/112333-this-is-woof-231-sep-30-2020-updated-winmbf/?page=7&tab=comments#comment-2153957) on Fabian's list.
While I'm not opposed to this feature, I realize what we're asking from Fabian is really a Crispy MBF (which would be awesome). Maybe in the future :p

**Comment by OpenRift412** [comment]
Honestly, I kind of a agree with this. @pwseo  As for being a Crispy MBF, widescreen would fit in perfectly, as that's something Crispy has had implemented recently.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/25ac96403b2149fe8df5f93b5da2b6ed2ebf0827
