### ISSUE TITLE
Suggesting an idea.

### ISSUE THREAD

**Issue by ClassicSSGEnjoyer** [fabiangreffrath/woof#941]
Hello, I just wanted to suggest an idea:

In PrBoom +, Emulation Settings, there are total of 6 emulation overflows.
Intercepts, Spechits, Reject, MissedBackSide, is also supported by Woof!. In its next milestone Woof! 10.6, you are also going to add Donut overflow.

My suggestion was to even add Player-in-game overflow from PrBoom plus. I think, by adding that overflow emulation would maybe help to sync some more obscure Vanilla/Limit Removing demos in Woof ? 🤔.

**Comment by kraflab** [comment]
Do you have example demos that are out of sync? I'm not aware of any desyncing demos.

**Comment by ClassicSSGEnjoyer** [comment]
Lol no.

**Comment by ClassicSSGEnjoyer** [comment]
> Do you have example demos that are out of sync? I'm not aware of any desyncing demos.

Lol no.

But:

Warn on playeringame Overflow :

Provide an on-screen message if an overflow occurs due to a rare multiplayer issue seen in demos such as **vex6d.wad\bug_wald.lmp, vex6d.wad\bug_toke.lmp, etc.**

Try to emulate it :

Attempt to emulate Doom2.exe's behaviour in the case of a playeringame Overflow. Note that this will result in the creation of a zombie player.

I got this information from the link below:

https://github.com/coelckers/prboom-plus/blob/master/prboom2/doc/prboom-plus-usage.txt

**Comment by fabiangreffrath** [comment]
It's already caught, but we don't have a switch for it:

https://github.com/fabiangreffrath/woof/commit/c70f5a5309c1dd0f2baeb2720c8a4a962993d78f

**Comment by ClassicSSGEnjoyer** [comment]
Alright good ;)
