### ISSUE TITLE
implement DSDA kill counter

### ISSUE THREAD

**Issue by ghost** [fabiangreffrath/woof#949]
Hello.

Woof has a seperate additional column for the resurrected monsters. That is a bit annoying because in maps which have more than like 400 enemies, its a bit difficult to keep a track of like, how many monsters we killed till this point, how many are remaining.

The problem is the monsters resurrected by Archviles is added in a seperate column. Like for e.g
416/358 + 58 : 116% like this.

In DSDA Doom, you can see pretty easily, because there is no seperate column for resurrected monsters, so, its much more easy to keep a track of the alive monsters and total enemies killed.

So, would you optionally include the setting to remove the seperate column and include DSDA's logic of Stats ?

**Comment by fabiangreffrath** [comment]
I don't have plans to remove the display of extrakills or make them optional.

**Comment by ClassicSSGEnjoyer** [comment]
> I don't have plans to remove the display of extrakills or make them optional. 
> 
> @rfomin ?

I was 99% sure you wont fix it, but I had 1% hope so I asked you to fix it optionally.

But, yeah, sorry for annoying you, by making such childish issues..

**Comment by rfomin** [comment]
> I don't have plans to remove the display of extrakills or make them optional.

I think DSDA-Doom just doesn't increase the kill counter if an extra monster is killed. Maybe we should do the same, it's easier.

**Comment by fabiangreffrath** [comment]
I would be missing that information.

**Comment by leveste** [comment]
Hi, sorry to comment in a closed issue(I only found it cause I was looking for a similar thing).

I just want to clarify that in DSDA-Doom, it's the **total kill count** that doesn't increase, while the current kill count decreases for each resurrect.

E.g. 10/50 kills -> Archvile resurrects one -> 9/50 kills

Personally, I find this method a bit more intuitive(for me at least). If nothing else, it would be nice to have the option to pick between the two.

**Comment by fabiangreffrath** [comment]
So, we keep on counting monsters that are (1) resurrected in Nightmare mode, (2) resurrected by an Archvile, (3) spawned by an IOS as `extrakills`, but instead of explicitly adding them to the `totalkills` on the status line, we substract them from the player's `kills`, right? In multiplayer, which player's stats are they substracted from - the one who killed them?

**Comment by rfomin** [comment]
> In multiplayer, which player's stats are they substracted from - the one who killed them?

In PrBoom+/DSDA-Doom, extrakills are stored per player, but we store them all in one `extrakills' variable.

**Comment by fabiangreffrath** [comment]
We can fix this part, though we would have to maintain savegame compatibility. So, do monster mobjs track which player killed them?

**Comment by rfomin** [comment]
> So, do monster mobjs track which player killed them?

There is a `lastenemy` field, I guess.

**Comment by fabiangreffrath** [comment]
Is this what people refer to as "Smart Totals"? I am a bit puzzled...

**Comment by rfomin** [comment]
> Is this what people refer to as "Smart Totals"?

The difference is what the level end screen shows, we always show "Dumb Totals" here. I think "Extended HUD" is always "Smart".

**Comment by fabiangreffrath** [comment]
Confusing.

**Comment by fabiangreffrath** [comment]
I will need help with this.

**Comment by rfomin** [comment]
> I will need help with this.

I think we should copy PrBoom+/DSDA-Doom here. The Crispy system is inconvenient.

**Comment by fabiangreffrath** [comment]
@kraflab Did the way "smart totals" are calculated change between prboom-plus and dsda-doom?

**Comment by kraflab** [comment]
Dsda-doom uses totals based on uv max category requirements. I don't remember what prboom+ did exactly but it was different.

**Comment by fabiangreffrath** [comment]
Dsda-doom removed its per-player kills counting in the stats line for multiplayer games, e.g. 
https://github.com/kraflab/dsda-doom/commit/1ff006d4e4c91e85852594e974ab04341c935883

Should we do the same?

**Comment by fabiangreffrath** [comment]
> Dsda-doom uses totals based on uv max category requirements. I don't remember what prboom+ did exactly but it was different.

I could identify at least two major differences: First, PrBoom+ does not have the concept of `max_kill_requirement`. Instead, achieved kills are *always* compared against `totalkills`. Second, PrBoom+ adds to `player->resurectedkillcount` (which is its own misspelled pendant to `player->maxkilldiscount`) for each monster with flag `MF_RESSURECTED`, which in turn is applied in `A_SpawnFly()`, `A_VileChase()` and `P_NightmareRespawn()`, i.e. whenever a monsters is spawned or respawned on the map.

Also, there is no spacial-casing for Nightmare!/respawn runs. In the DSDA way of counting, I found it funny to see that in respawn mode the max kill requirement for a map is considered achieved if the `totalkills` number of monsters is killed, without checking for them respawning. So, in the end, you could always kill the same monster `totalkills` timed and gain max kills achievement. :grin:
