### ISSUE TITLE
Somewhat untidy config file

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#951]
For example: the config items for [High Resolution](https://github.com/fabiangreffrath/woof/blob/master/src/m_misc.c#L154-L158) and [V-Sync](https://github.com/fabiangreffrath/woof/blob/master/src/m_misc.c#L167-L172); [Aspect Ratio Correction](https://github.com/fabiangreffrath/woof/blob/master/src/m_misc.c#L2260-L2265); [Uncapped Framerate and FPS Limit](https://github.com/fabiangreffrath/woof/blob/master/src/m_misc.c#L2419-L2433); and [Widescreen](https://github.com/fabiangreffrath/woof/blob/master/src/m_misc.c#L2450-L2456) are notably separate from each other, when I'd expect them to be closer together as they're more-or-less related.

While that's the most notable case in my opinion, I'm certain it's not the only one. The current arrangement of items could very well have some reasoning behind it, but I haven't been able to identify any, making it seem untidy to me.

If you do agree with me on that the list isn't very tidy, what I'm suggesting is the obvious: to go through the whole list of config items at some point and rearrange it to have related items closer together. Their current arrangement in the various in-game setup menus could be a good starting point. I repeat, though: maybe it's just me not being able to figure out the logic.

**Comment by fabiangreffrath** [comment]
I guess you are right. The order of config items in `m_misc.c` and thus in the config file is pretty random and confusing.

**Comment by rfomin** [comment]
Yes, to be honest, I did not think about order and grouping when I added new items to the config.

**Comment by kraflab** [comment]
I was thinking about this problem in the scope of dsda-doom as well. The plan I had was to add a config_category_t and assign each config entry to a category, and the category would have its name / comment / whatever meta data to also be printed. Then the config file writer would go through all the categories and write their data to the file. Then the order of config entries isn't relevant and you can change sections just by updating the associated category. But the dsda-doom config management has completely diverged, so idk if that approach would make sense in woof.

**Comment by fabiangreffrath** [comment]
We already have something similar in the form of the `setupscreen` element of `struct default_t`. I could run some `qsort()` on all config keys before exporting the to config file, sorting by `setupscreen` first and alphabet second. 🤔

**Comment by kraflab** [comment]
Sounds great 👍
