### ISSUE TITLE
Choice-type (and Thermo-type?) setup menu items can change a variable without calling their function (if any)

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#952]
_Tested in the 10.5.1 release._

As an example, you can test this with the _Color By Target_ crosshair option: starting at **Off**, press Enter on it and set it to **Highlight**. You'll see how the _Highlight Color_ setting below becomes available. Now, press Enter on it again and move towards **Health**, but DO NOT confirm with Enter; instead, press Escape. The variable is changed, but the function associated to that setup menu item (`M_UpdateCrosshairItems()`) isn't called, therefore the _Highlight Color_ item below remains available. This has the potential to crash the game depending on what new items are added in the future.

In my opinion, pressing Escape should revert the item back to its initial state, i.e. before you pressed Enter on it.

**Comment by fabiangreffrath** [comment]
I think @rfomin has just fixed that last month, can you confirm?
https://github.com/fabiangreffrath/woof/commit/6b1c41718fc5707010ed33b5baa346d31216d093

**Comment by MrAlaux** [comment]
Well, while I can't build Woof myself, I _can_ download the artifacts from the Actions tab and test on those.

With the latest artifact, the problem in the specific example mentioned in my first comment appears to be fixed - in short, Choice-type items work properly. _However,_ pressing Escape after changing the value of a Thermo-type item does not reset it back to its original value, and I assume it wouldn't call its function either (can't test that as none of the current Thermo items have an associated function), so I guess that needs to be fixed.

**Comment by rfomin** [comment]
The Themo type applies changes immediately on every move, so I thought it would be fine without a reset. Or maybe then I just got confused by the `M_Responder()` code, I don't remember 😆

**Comment by fabiangreffrath** [comment]
> The Themo type applies changes immediately on every move, so I thought it would be fine without a reset. 

Yes, right. Imagine the screen size or music volume sliders would only apply their new values after confirmation. Can we close this?
