### ISSUE TITLE
[request] more control over "bobbing percentage"

### ISSUE THREAD

**Issue by liPillON** [fabiangreffrath/woof#987]
It would be nice to either:
- have 25% and 50% added to the available choices 
- let the user specify a 0-100 integer

What do you guys think?

**Comment by fabiangreffrath** [comment]
I have added the 75% bobbing option just because this is the canonical value for the classic Doom port shipped with the Doom 3 BFG Edition. I don't see a reason to add more values, to be honest.

**Comment by fabiangreffrath** [comment]
@rfomin ?

**Comment by rfomin** [comment]
> I have added the 75% bobbing option just because this is the canonical value for the classic Doom port shipped with the Doom 3 BFG Edition.

I did not know that. Does this apply to the Unity port as well? It looks like it has also reduced the bobbing.
I've tried 50% and below and it looks weird, so yes, I think 75% is optimal.

**Comment by fabiangreffrath** [comment]
Here it is:
https://github.com/id-Software/DOOM-3-BFG/blob/1caba1979589971b5ed44e315d9ead30b278d8b4/doomclassic/doom/p_user.cpp#L94

**Comment by liPillON** [comment]
your house, your rules!

thank you for indulging me anyway

**Comment by fabiangreffrath** [comment]
> thank you for indulging me anyway

Thanks for your suggestions!
