### ISSUE TITLE
[Request] Options to disable certain messages

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#990]
ZDoom and derivatives have a setting for "Minimum message level", meaning that certain kinds of messages can be hidden without outright disabling all messages.

I think that this could be a nice addition for Woof, albeit providing separate settings for each kind of message. By "kind" I mean categories like:

- Item pickup messages;
- Cheat messages;
- Toggle messages (like "Mouselook On/Off");
- Warning messages (like the "Unknown Thing" warning).

Those are the ones I remember off the top of my head.

Implementing this would surely mean looking through the code for all instances of messages and adding conditions to them. If you'd like to go ahead with it, I can try to implement it myself and make a PR for it.

**Comment by ak-988** [comment]
I would enjoy this too, mostly for disabling the auto run toggle message (similar to Eternity)

**Comment by fabiangreffrath** [comment]
Well, I am generally opposed to this kind of feature micro-management. However, if this is about disabling player messages *that we added*, then I understand.

I feel zero incentive to work on this myself, so please feel free to look into this. However, please understand that this will never get more than one menu item, so I suggest to sort messages by some kind of "priority" ranking.

**Comment by MrAlaux** [comment]
As implied by its name, ZDoom's setting does actually work by hiding messages with a "lower priority", specifically:

`Item pickup < Obituaries < Critical messages`

Obituaries obviously don't apply to Woof, and I'm not sure what "Critical messages" encompasses. What do you think should be the hierarchy of the categories I mentioned in the opening comment? Can you think of any other categories?

**Comment by MrAlaux** [comment]
> So, maybe the categories should be "game messages" and "technical messages"

So, the setting should allow to disable one category or the other (or none)? For disabling both we already have `show_messages`, unless your idea was to expand that variable with the functionality I'm proposing.

**Comment by fabiangreffrath** [comment]
I think we cannot expand the `show_messages` variable, because its value is drawn with the big font in the Options menu. My idea is a single menu switch called "show messages" (in the Quality Of Life section, probably) offering the choices "game messages", "game+chat messages" (if you insist) and "all messages". Roughly.

**Comment by MrAlaux** [comment]
I never mentioned **chat** messages, but rather **cheat** messages. Whatever the case, I think both fall within the "game messages" category. In that case, we'd only have two possible choices, so we could achieve the same functionality with a simple toggle to hide technical messages (i.e. `Hide technical messages: YES/NO`). What do you say?

**Comment by fabiangreffrath** [comment]
Oh my, sorry for consequently misreading what you have written!

Yes, as mentioned earlier, I'd be fine with a single menu switch to modify this behaviour - and yes, we have a Messages setup menu and we should use it. 😁

**Comment by fabiangreffrath** [comment]
Some shower thoughts: So, we distinguish between messages that say what's happening *in the game* and those that say *how the game* is played. If I were to implement this, I would concistently use `doomprintf()` and introduce an additional parameter for the message type. Then I would decide inside the function whether to construct the string or not depending on the config value.

**Comment by rfomin** [comment]
We don't have obituaries, so there is much less spam than GZDoom. I suggest two options - "minimum" and "full". In the "minimal" mode, we will disable item pick up messages.

**Comment by fabiangreffrath** [comment]
>  In the "minimal" mode, we will disable item pick up messages.

Oh, I have understood that the toggle messages were too much for some people.

**Comment by MrAlaux** [comment]
Well, in an attempt to merge both of your ideas, we could do something like the following:

`Hide Messages: None/Technical/Technical + Pickups`

"Technical" being, at least, toggle messages. Again, to hide all messages we would still resort to `show_messages`. What do you think?

**Comment by rfomin** [comment]
> Warning messages (like the "Unknown Thing" warning).

We have changed this message to a normal `printf()`. I don't think we have technical messages left.

So, we have a cheat, toggle and pick up messages. I think we can make two categories: toggle and pick up.

**Comment by MrAlaux** [comment]
> So, we have a cheat, toggle and pick up messages. I think we can make two categories: toggle and pick up.

Sounds good to me. The choices could also be `Toggles/Pickups/Both`. @fabiangreffrath?

**Comment by fabiangreffrath** [comment]
Sounds good to me.

**Comment by fabiangreffrath** [comment]
> We don't have obituaries

Do you still consider adding these?

**Comment by MrAlaux** [comment]
Just a tip, but maybe you should directly mention the user whom you're replying to in the future. I was unsure if it was me or someone else who had said that.

**Comment by rfomin** [comment]
> > We don't have obituaries
> 
> Do you still consider adding these?

Yes, although very few PWADs set it in DEH, I only know about Ancient Aliens and Doom In Spain Only. I've been a bit slow lately, sorry.
