### ISSUE TITLE
Toggling overlay modes resets Automap position when not following the player

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#992]
_Tested in the [latest master artifact (x86)](https://github.com/fabiangreffrath/woof/actions/runs/4686556360)._

As explained in the title: with Follow Mode off, if I move away from the player then change the overlay mode, the Automap will snap back to the player's position.

**Comment by rfomin** [comment]
https://github.com/fabiangreffrath/woof/commit/653482947fe71a7ec65be3fad4d2615f76a9cf74
