### ISSUE TITLE
Automatic loading of SIGIL.WAD, NERVE.WAD, and Master Levels similar to Crispy Doom

### ISSUE THREAD

**Issue by FreshRoyal** [fabiangreffrath/woof#996]
Crispy Doom's automatic loading of the mentioned expansions is a very nice QoL feature. It would be very appreciated, but it's understandable if it's not a priority.

**Comment by fabiangreffrath** [comment]
Supporting side-loading PWADs requires a lot of hard-coding inside the engine, e.g. map names, music, intermission texts, map transitions, etc. For Crispy Doom, I have decided to go that way, but for Woof we rely on modifying these features by means of UMAPINFO instead, which requires the PWADs in question to get explicitly loaded.
